souffle: souffle::DebugReport Class Reference
souffle::DebugReport Class Reference
Class representing a HTML report, consisting of a list of sections.
#include <DebugReport.h>
Public Member Functions
void addSection (const DebugReportSection &section)
void addSection (std::string id, std::string title, std::string code)
bool empty () const
void endSection (std::string currentSectionName, std::string currentSectionTitle)
void print (std::ostream &out) const
Outputs a complete HTML document to the given stream, consisting of an index of all of the sections of the report, followed by the content of each section.
void startSection ()
~DebugReport ()
Static Public Member Functions
static DebugReportSection getCodeSection (const std::string &id, std::string title, std::string code)
Generate a debug report section for code (preserving formatting), with the given id and title.
Private Attributes
std::stack< std::vector< DebugReportSection > > currentSubsections
std::vector< DebugReportSection > sections
Friends
std::ostream & operator<< (std::ostream &out, const DebugReport &report)
Detailed Description
Class representing a HTML report, consisting of a list of sections.
Definition at line 85 of file DebugReport.h.
Constructor & Destructor Documentation
~DebugReport()
souffle::DebugReport::~DebugReport () inline
Definition at line 87 of file DebugReport.h.
References souffle::Global::config().
                    {
         while (!currentSubsections.empty()) {
             endSection("forced-closed", "Forcing end of unknown section");
         }
         if (!empty()) {
             std::ofstream debugReportStream(Global::config().get("debug-report"));
             debugReportStream << *this;
         }
     }
Member Function Documentation
addSection() [1/2]
void souffle::DebugReport::addSection (const DebugReportSection & section) inline
Definition at line 100 of file DebugReport.h.
Referenced by souffle::RamTransformer::apply(), souffle::DebugReporter::generateDebugReport(), souffle::AstTranslationUnit::getAnalysis(), souffle::RamTranslationUnit::getAnalysis(), souffle::main(), and souffle::AstTranslator::translateUnit().
{
         if (!currentSubsections.empty()) {
             currentSubsections.top().emplace_back(section);
         } else {
             sections.emplace_back(section);
         }
     }
addSection() [2/2]
void souffle::DebugReport::addSection (std::string id, std::string title, std::string code) inline
Definition at line 108 of file DebugReport.h.
References i.
{
         std::stringstream codeHTML;
         std::string escapedCode = std::move(code);
         while (true) {
             size_t i = escapedCode.find("<");
             if (i == std::string::npos) {
                 break;
             }
             escapedCode.replace(i, 1, "&lt;");
         }
         codeHTML << "<pre>" << escapedCode << "</pre>\n";
         if (!currentSubsections.empty()) {
             currentSubsections.top().emplace_back(std::move(id), std::move(title), codeHTML.str());
         } else {
             sections.emplace_back(std::move(id), std::move(title), codeHTML.str());
         }
     }
empty()
bool souffle::DebugReport::empty () const inline
Definition at line 96 of file DebugReport.h.
{
         return sections.empty();
     }
endSection()
void souffle::DebugReport::endSection (std::string currentSectionName, std::string currentSectionTitle) inline
Definition at line 130 of file DebugReport.h.
References souffle::DebugReportSection::DebugReportSection(), souffle::DebugReportSection::subsections, and souffle::DebugReportSection::title.
Referenced by souffle::RamTransformer::apply(), souffle::main(), and souffle::DebugReporter::transform().
{
         auto subsections = currentSubsections.top();
         currentSubsections.pop();
         addSection(DebugReportSection(currentSectionName, currentSectionTitle, subsections, ""));
     }
getCodeSection()
static DebugReportSection souffle::DebugReport::getCodeSection (const std::string & id, std::string title, std::string code) static
Generate a debug report section for code (preserving formatting), with the given id and title.
print()
void souffle::DebugReport::print (std::ostream & out) const
Outputs a complete HTML document to the given stream, consisting of an index of all of the sections of the report, followed by the content of each section.
Definition at line 64 of file DebugReport.cpp.
References souffle::Global::config().
{
     out << "<!DOCTYPE html>\n";
     out << "<html lang='en-AU'>\n";
     out << "<head>\n";
     out << "<meta charset=\"UTF-8\">\n";
     out << "<title>Souffle Debug Report (" << Global::config().get("") << ")</title>\n";
     out << "<style>\n";
     out << "ul { list-style-type: none; }\n";
     out << "ul > li.leaf { display: inline-block; padding: 0em 1em; }\n";
     out << "ul > li.nonleaf { padding: 0em 1em; }\n";
     out << "* { font-family: sans-serif; }\n";
     out << "pre { white-space: pre-wrap; font-family: monospace; }\n";
     out << "a:link { text-decoration: none; color: blue; }\n";
     out << "a:visited { text-decoration: none; color: blue; }\n";
     out << "div.headerdiv { background-color:lightgrey; margin:10px; padding-left:10px; padding-right:10px; "
            "padding-top:3px; padding-bottom:3px; border-radius:5px }\n";
     out << ".headerdiv h1 { display:inline; }\n";
     out << ".headerdiv a { float:right; }\n";
     out << "</style>\n";
     out << "<script>\n";
     out << "function toggleVisibility(id) {\n";
     out << "  var element = document.getElementById(id);\n";
     out << "  if (element.style.display == 'none') {\n";
     out << "    element.style.display = 'block';\n";
     out << "  } else {\n";
     out << "    element.style.display = 'none';\n";
     out << "  }\n";
     out << "}\n";
     out << "</script>\n";
     out << "</head>\n";
     out << "<body>\n";
     out << "<div class='headerdiv'><h1>Souffle Debug Report (" << Global::config().get("")
         << ")</h1></div>\n";
     for (const DebugReportSection& section : sections) {
         section.printIndex(out);
     }
     for (const DebugReportSection& section : sections) {
         section.printContent(out);
     }
     out << "<a href='#'>(return to top)</a>\n";
     out << "</body>\n";
     out << "</html>\n";
 }
startSection()
void souffle::DebugReport::startSection () inline
Definition at line 126 of file DebugReport.h.
Referenced by souffle::RamTransformer::apply(), souffle::main(), and souffle::DebugReporter::transform().
{
         currentSubsections.emplace();
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const DebugReport & report) friend
Definition at line 148 of file DebugReport.h.
{
         report.print(out);
         return out;
     }
Field Documentation
currentSubsections
std::stack<std::vector<DebugReportSection> > souffle::DebugReport::currentSubsections private
Definition at line 155 of file DebugReport.h.
sections
std::vector<DebugReportSection> souffle::DebugReport::sections private
Definition at line 154 of file DebugReport.h.
The documentation for this class was generated from the following files:
DebugReport.h
DebugReport.cpp