souffle: souffle::AstFunctor Class Reference
souffle::AstFunctor Class Reference abstract
Functor class.
#include <AstArgument.h>
Public Member Functions
virtual TypeAttribute getArgType (const size_t arg) const =0
virtual TypeAttribute getReturnType () const =0
Public Member Functions inherited from souffle::AstTerm
void addArgument (std::unique_ptr< AstArgument > arg)
add argument to argument list
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< AstArgument * > getArguments () const
get arguments
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
Public Member Functions inherited from souffle::AstArgument
AstArgument * clone () const override=0
Create clone.
Public Member Functions inherited from souffle::AstNode
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
AstFunctor ()=default
AstFunctor (std::vector< std::unique_ptr< AstArgument >> operands)
Protected Member Functions inherited from souffle::AstTerm
AstTerm ()=default
AstTerm (std::vector< std::unique_ptr< AstArgument >> operands)
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
Protected Member Functions inherited from souffle::AstNode
virtual void print (std::ostream &os) const =0
Output to a given output stream.
Additional Inherited Members
Protected Attributes inherited from souffle::AstTerm
std::vector< std::unique_ptr< AstArgument > > args
Arguments.
Detailed Description
Functor class.
Definition at line 258 of file AstArgument.h.
Constructor & Destructor Documentation
AstFunctor() [1/2]
souffle::AstFunctor::AstFunctor () protected default
AstFunctor() [2/2]
souffle::AstFunctor::AstFunctor (std::vector< std::unique_ptr< AstArgument >> operands) inline explicit protected
Definition at line 265 of file AstArgument.h.
 : AstTerm(std::move(operands)) {}
Member Function Documentation
getArgType()
virtual TypeAttribute souffle::AstFunctor::getArgType (const size_t arg) const pure virtual
Implemented in souffle::AstUserDefinedFunctor, and souffle::AstIntrinsicFunctor.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
getReturnType()
virtual TypeAttribute souffle::AstFunctor::getReturnType () const pure virtual
Implemented in souffle::AstUserDefinedFunctor, and souffle::AstIntrinsicFunctor.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::AstSemanticChecker::checkProgram().
The documentation for this class was generated from the following file:
AstArgument.h