souffle: souffle::AstProgram Class Reference
souffle::AstProgram Class Reference
Intermediate representation of a datalog program that consists of relations, clauses and types.
#include <AstProgram.h>
Public Member Functions
void addClause (std::unique_ptr< AstClause > clause)
add a clause
void addRelation (std::unique_ptr< AstRelation > r)
void apply (const AstNodeMapper &map) override
Apply the mapper to all child nodes.
AstProgram * clone () const override
Create a clone (i.e.
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::vector< AstClause * > getClauses () const
get clauses
std::vector< AstComponentInit * > getComponentInstantiations () const
get component instantiation
std::vector< AstComponent * > getComponents () const
get components
std::vector< AstFunctorDeclaration * > getFunctorDeclarations () const
get functor declarations
std::vector< AstIO * > getIOs () const
get io directives
const std::vector< std::unique_ptr< AstPragma > > & getPragmaDirectives () const
get pragma directives
std::vector< AstRelation * > getRelations () const
get relations
std::vector< AstType * > getTypes () const
get types
bool removeClause (const AstClause *clause)
remove a clause
bool removeRelation (const AstQualifiedName &name)
remove relation
void setClauses (std::vector< std::unique_ptr< AstClause >> newClauses)
Public Member Functions inherited from souffle::AstNode
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
void addComponent (std::unique_ptr< AstComponent > c)
add component
void addFunctorDeclaration (std::unique_ptr< souffle::AstFunctorDeclaration > f)
add functor
void addInstantiation (std::unique_ptr< AstComponentInit > i)
add component instantiation
void addIO (std::unique_ptr< AstIO > directive)
add IO directive
void addPragma (std::unique_ptr< AstPragma > pragma)
add a pragma
void addType (std::unique_ptr< AstType > type)
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::vector< std::unique_ptr< AstClause > > clauses
Program clauses.
std::vector< std::unique_ptr< AstComponent > > components
Program components.
std::vector< std::unique_ptr< AstFunctorDeclaration > > functors
External Functors.
std::vector< std::unique_ptr< AstComponentInit > > instantiations
Component instantiations.
std::vector< std::unique_ptr< AstIO > > ios
IO statements.
std::vector< std::unique_ptr< AstPragma > > pragmaDirectives
Pragmas.
std::vector< std::unique_ptr< AstRelation > > relations
Program relations.
std::vector< std::unique_ptr< AstType > > types
Program types.
Friends
class ComponentInstantiationTransformer
class ParserDriver
Detailed Description
Intermediate representation of a datalog program that consists of relations, clauses and types.
Definition at line 49 of file AstProgram.h.
Member Function Documentation
addClause()
void souffle::AstProgram::addClause (std::unique_ptr< AstClause > clause) inline
add a clause
Definition at line 105 of file AstProgram.h.
References clauses.
Referenced by souffle::makeInfoRelation(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::normaliseInlinedHeads(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::separateDBs(), souffle::ResolveAliasesTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::MagicSetTransformer::transform(), and souffle::transformEqrelRelation().
{
         assert(clause != nullptr && "Undefined clause");
         assert(clause->getHead() != nullptr && "Undefined head of the clause");
         clauses.push_back(std::move(clause));
     }
addComponent()
void souffle::AstProgram::addComponent (std::unique_ptr< AstComponent > c) inline protected
add component
Definition at line 306 of file AstProgram.h.
References components.
{
         components.push_back(std::move(c));
     }
addFunctorDeclaration()
void souffle::AstProgram::addFunctorDeclaration (std::unique_ptr< souffle::AstFunctorDeclaration > f) inline protected
add functor
Definition at line 300 of file AstProgram.h.
References functors, and souffle::getFunctorDeclaration().
{
         assert(getFunctorDeclaration(*this, f->getName()) == nullptr && "Redefinition of functor!");
         functors.push_back(std::move(f));
     }
addInstantiation()
void souffle::AstProgram::addInstantiation (std::unique_ptr< AstComponentInit > i) inline protected
add component instantiation
Definition at line 311 of file AstProgram.h.
References instantiations.
{
         instantiations.push_back(std::move(i));
     }
addIO()
void souffle::AstProgram::addIO (std::unique_ptr< AstIO > directive) inline protected
add IO directive
Definition at line 288 of file AstProgram.h.
References ios.
{
         assert(directive && "NULL IO directive");
         ios.push_back(std::move(directive));
     }
addPragma()
void souffle::AstProgram::addPragma (std::unique_ptr< AstPragma > pragma) inline protected
add a pragma
Definition at line 294 of file AstProgram.h.
References pragmaDirectives.
{
         assert(pragma && "NULL IO directive");
         pragmaDirectives.push_back(std::move(pragma));
     }
addRelation()
void souffle::AstProgram::addRelation (std::unique_ptr< AstRelation > r) inline
Definition at line 82 of file AstProgram.h.
References souffle::getRelation(), and relations.
Referenced by souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::separateDBs(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
         assert(getRelation(*this, r->getQualifiedName()) == nullptr && "Redefinition of relation!");
         relations.push_back(std::move(r));
     }
addType()
void souffle::AstProgram::addType (std::unique_ptr< AstType > type) inline protected
Definition at line 282 of file AstProgram.h.
References souffle::getType(), and types.
{
         assert(getType(*this, type->getQualifiedName()) == nullptr && "Redefinition of type!");
         types.push_back(std::move(type));
     }
apply()
void souffle::AstProgram::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 164 of file AstProgram.h.
References clauses, components, functors, instantiations, ios, pragmaDirectives, relations, and types.
Referenced by souffle::nameInlinedUnderscores(), souffle::reduceSingletonRelations(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::NameUnnamedVariablesTransformer::transform(), souffle::RemoveRedundantSumsTransformer::transform(), souffle::RemoveTypecastsTransformer::transform(), souffle::PolymorphicObjectsTransformer::transform(), and souffle::AstUserDefinedFunctorsTransformer::transform().
{
         for (auto& cur : pragmaDirectives) {
             cur = map(std::move(cur));
         }
         for (auto& cur : components) {
             cur = map(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : functors) {
             cur = map(std::move(cur));
         }
         for (auto& cur : types) {
             cur = map(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = map(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = map(std::move(cur));
         }
         for (auto& cur : ios) {
             cur = map(std::move(cur));
         }
     }
clone()
AstProgram* souffle::AstProgram::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 132 of file AstProgram.h.
References clauses, components, functors, instantiations, ios, pragmaDirectives, relations, and types.
{
         auto res = new AstProgram();
         for (const auto& cur : pragmaDirectives) {
             res->pragmaDirectives.emplace_back(cur->clone());
         }
         for (const auto& cur : components) {
             res->components.emplace_back(cur->clone());
         }
         for (const auto& cur : instantiations) {
             res->instantiations.emplace_back(cur->clone());
         }
         for (const auto& cur : types) {
             res->types.emplace_back(cur->clone());
         }
         for (const auto& cur : functors) {
             res->functors.emplace_back(cur->clone());
         }
         for (const auto& cur : relations) {
             res->relations.emplace_back(cur->clone());
         }
         for (const auto& cur : clauses) {
             res->clauses.emplace_back(cur->clone());
         }
         for (const auto& cur : ios) {
             res->ios.emplace_back(cur->clone());
         }
         // done
         return res;
     }
equal()
bool souffle::AstProgram::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 248 of file AstProgram.h.
References clauses, components, souffle::equal_targets(), functors, instantiations, ios, pragmaDirectives, relations, and types.
{
         const auto& other = static_cast<const AstProgram&>(node);
         if (!equal_targets(pragmaDirectives, other.pragmaDirectives)) {
             return false;
         }
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(functors, other.functors)) {
             return false;
         }
         if (!equal_targets(types, other.types)) {
             return false;
         }
         if (!equal_targets(relations, other.relations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(ios, other.ios)) {
             return false;
         }
         return true;
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstProgram::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 191 of file AstProgram.h.
References clauses, components, functors, instantiations, ios, pragmaDirectives, relations, and types.
{
         std::vector<const AstNode*> res;
         for (const auto& cur : pragmaDirectives) {
             res.push_back(cur.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : functors) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : ios) {
             res.push_back(cur.get());
         }
         return res;
     }
getClauses()
std::vector<AstClause*> souffle::AstProgram::getClauses () const inline
get clauses
Definition at line 62 of file AstProgram.h.
References clauses, and souffle::toPtrVector().
Referenced by souffle::AstSemanticChecker::checkRules(), souffle::getClauses(), souffle::FoldAnonymousRecords::transform(), and souffle::ResolveAnonymousRecordsAliases::transform().
{
         return toPtrVector(clauses);
     }
getComponentInstantiations()
std::vector<AstComponentInit*> souffle::AstProgram::getComponentInstantiations () const inline
get component instantiation
Definition at line 128 of file AstProgram.h.
References instantiations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), and souffle::AstComponentChecker::checkComponents().
{
         return toPtrVector(instantiations);
     }
getComponents()
std::vector<AstComponent*> souffle::AstProgram::getComponents () const inline
get components
Definition at line 123 of file AstProgram.h.
References components, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstComponentChecker::checkComponents(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
getFunctorDeclarations()
std::vector<AstFunctorDeclaration*> souffle::AstProgram::getFunctorDeclarations () const inline
get functor declarations
Definition at line 67 of file AstProgram.h.
References functors, and souffle::toPtrVector().
Referenced by souffle::getFunctorDeclaration().
{
         return toPtrVector(functors);
     }
getIOs()
std::vector<AstIO*> souffle::AstProgram::getIOs () const inline
get io directives
Definition at line 72 of file AstProgram.h.
References ios, and souffle::toPtrVector().
Referenced by souffle::AstSemanticChecker::checkIO(), souffle::AstTranslator::getInputDirectives(), souffle::AstTranslator::getOutputDirectives(), and souffle::MagicSetTransformer::transform().
{
         return toPtrVector(ios);
     }
getPragmaDirectives()
const std::vector<std::unique_ptr<AstPragma> >& souffle::AstProgram::getPragmaDirectives () const inline
get pragma directives
Definition at line 77 of file AstProgram.h.
References pragmaDirectives.
{
         return pragmaDirectives;
     }
getRelations()
std::vector<AstRelation*> souffle::AstProgram::getRelations () const inline
get relations
Definition at line 57 of file AstProgram.h.
References relations, and souffle::toPtrVector().
Referenced by souffle::addBackwardDependencies(), souffle::addIgnoredRelations(), souffle::bindComposites(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkNamespaces(), souffle::AstSemanticChecker::checkRules(), souffle::getRelation(), souffle::nameInlinedUnderscores(), souffle::normaliseInlinedHeads(), souffle::reduceLocallyEquivalentClauses(), souffle::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::replaceUnderscores(), souffle::TypeAnalysis::run(), souffle::PrecedenceGraph::run(), souffle::RedundantRelations::run(), souffle::SCCGraph::run(), souffle::Adornment::run(), souffle::separateDBs(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::NameUnnamedVariablesTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), and souffle::NormaliseConstraintsTransformer::transform().
{
         return toPtrVector(relations);
     }
getTypes()
std::vector<AstType*> souffle::AstProgram::getTypes () const inline
get types
Definition at line 52 of file AstProgram.h.
References souffle::toPtrVector(), and types.
Referenced by souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticChecker::checkNamespaces(), souffle::AstSemanticChecker::checkRecursiveUnionTypes(), souffle::AstSemanticChecker::checkTypes(), souffle::AstTranslator::getRecordsTypes(), souffle::getType(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return toPtrVector(types);
     }
print()
void souffle::AstProgram::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 221 of file AstProgram.h.
References clauses, components, functors, instantiations, ios, souffle::join(), pragmaDirectives, relations, and types.
{
         if (!pragmaDirectives.empty()) {
             os << join(pragmaDirectives, "\n\n", print_deref<std::unique_ptr<AstPragma>>()) << "\n";
         }
         if (!components.empty()) {
             os << join(components, "\n", print_deref<std::unique_ptr<AstComponent>>()) << "\n";
         }
         if (!instantiations.empty()) {
             os << join(instantiations, "\n", print_deref<std::unique_ptr<AstComponentInit>>()) << "\n";
         }
         if (!types.empty()) {
             os << join(types, "\n", print_deref<std::unique_ptr<AstType>>()) << "\n";
         }
         if (!functors.empty()) {
             os << join(functors, "\n", print_deref<std::unique_ptr<AstFunctorDeclaration>>()) << "\n";
         }
         if (!relations.empty()) {
             os << join(relations, "\n", print_deref<std::unique_ptr<AstRelation>>()) << "\n";
         }
         if (!clauses.empty()) {
             os << join(clauses, "\n\n", print_deref<std::unique_ptr<AstClause>>()) << "\n";
         }
         if (!ios.empty()) {
             os << join(ios, "\n\n", print_deref<std::unique_ptr<AstIO>>()) << "\n";
         }
     }
removeClause()
bool souffle::AstProgram::removeClause (const AstClause * clause) inline
remove a clause
Definition at line 112 of file AstProgram.h.
References clauses.
Referenced by souffle::normaliseInlinedHeads(), souffle::reduceLocallyEquivalentClauses(), souffle::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::removeRelationClauses(), souffle::ResolveAliasesTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), and souffle::ReorderLiteralsTransformer::transform().
{
         for (auto it = clauses.begin(); it != clauses.end(); it++) {
             if (**it == *clause) {
                 clauses.erase(it);
                 return true;
             }
         }
         return false;
     }
removeRelation()
bool souffle::AstProgram::removeRelation (const AstQualifiedName & name) inline
remove relation
Definition at line 88 of file AstProgram.h.
References relations, and souffle::removeRelationClauses().
Referenced by souffle::reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveRedundantRelationsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
         for (auto it = relations.begin(); it != relations.end(); it++) {
             const auto& rel = *it;
             if (rel->getQualifiedName() == name) {
                 removeRelationClauses(*this, name);
                 relations.erase(it);
                 return true;
             }
         }
         return false;
     }
setClauses()
void souffle::AstProgram::setClauses (std::vector< std::unique_ptr< AstClause >> newClauses) inline
Definition at line 100 of file AstProgram.h.
References clauses.
Referenced by souffle::FoldAnonymousRecords::transform().
{
         clauses = std::move(newClauses);
     }
Friends And Related Function Documentation
ComponentInstantiationTransformer
friend class ComponentInstantiationTransformer friend
Definition at line 278 of file AstProgram.h.
ParserDriver
friend class ParserDriver friend
Definition at line 279 of file AstProgram.h.
Field Documentation
clauses
std::vector<std::unique_ptr<AstClause> > souffle::AstProgram::clauses protected
Program clauses.
Definition at line 325 of file AstProgram.h.
Referenced by addClause(), apply(), clone(), equal(), getChildNodes(), getClauses(), print(), removeClause(), setClauses(), and souffle::ComponentInstantiationTransformer::transform().
components
std::vector<std::unique_ptr<AstComponent> > souffle::AstProgram::components protected
Program components.
Definition at line 331 of file AstProgram.h.
Referenced by addComponent(), apply(), clone(), equal(), getChildNodes(), getComponents(), print(), and souffle::ComponentInstantiationTransformer::transform().
functors
std::vector<std::unique_ptr<AstFunctorDeclaration> > souffle::AstProgram::functors protected
External Functors.
Definition at line 322 of file AstProgram.h.
Referenced by addFunctorDeclaration(), apply(), clone(), equal(), getChildNodes(), getFunctorDeclarations(), and print().
instantiations
std::vector<std::unique_ptr<AstComponentInit> > souffle::AstProgram::instantiations protected
Component instantiations.
Definition at line 334 of file AstProgram.h.
Referenced by addInstantiation(), apply(), clone(), equal(), getChildNodes(), getComponentInstantiations(), print(), and souffle::ComponentInstantiationTransformer::transform().
ios
std::vector<std::unique_ptr<AstIO> > souffle::AstProgram::ios protected
IO statements.
Definition at line 328 of file AstProgram.h.
Referenced by addIO(), apply(), clone(), equal(), getChildNodes(), getIOs(), print(), and souffle::ComponentInstantiationTransformer::transform().
pragmaDirectives
std::vector<std::unique_ptr<AstPragma> > souffle::AstProgram::pragmaDirectives protected
Pragmas.
Definition at line 337 of file AstProgram.h.
Referenced by addPragma(), apply(), clone(), equal(), getChildNodes(), getPragmaDirectives(), and print().
relations
std::vector<std::unique_ptr<AstRelation> > souffle::AstProgram::relations protected
Program relations.
Definition at line 319 of file AstProgram.h.
Referenced by addRelation(), apply(), clone(), equal(), getChildNodes(), getRelations(), print(), removeRelation(), and souffle::ComponentInstantiationTransformer::transform().
types
std::vector<std::unique_ptr<AstType> > souffle::AstProgram::types protected
Program types.
Definition at line 316 of file AstProgram.h.
Referenced by addType(), apply(), clone(), equal(), getChildNodes(), getTypes(), print(), and souffle::ComponentInstantiationTransformer::transform().
The documentation for this class was generated from the following file:
AstProgram.h