souffle: souffle::RamAbstractAggregate Class Reference
souffle::RamAbstractAggregate Class Reference
Abstract class for aggregation.
#include <RamOperation.h>
Public Member Functions
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Get condition.
const RamExpression & getExpression () const
Get target expression.
AggregateOp getFunction () const
Get aggregation function.
RamAbstractAggregate (AggregateOp fun, std::unique_ptr< RamExpression > expr, std::unique_ptr< RamCondition > cond)
virtual ~RamAbstractAggregate ()=default
Protected Member Functions
bool equal (const RamNode &node) const
void print (std::ostream &os, int) const
Protected Attributes
std::unique_ptr< RamCondition > condition
Aggregation tuple condition.
std::unique_ptr< RamExpression > expression
Aggregation expression.
AggregateOp function
Aggregation function.
Detailed Description
Abstract class for aggregation.
A particular function (e.g. MIN) is applied given a that a condition holds
Definition at line 664 of file RamOperation.h.
Constructor & Destructor Documentation
RamAbstractAggregate()
souffle::RamAbstractAggregate::RamAbstractAggregate (AggregateOp fun, std::unique_ptr< RamExpression > expr, std::unique_ptr< RamCondition > cond) inline
Definition at line 666 of file RamOperation.h.
             : function(fun), expression(std::move(expr)), condition(std::move(cond)) {
         assert(condition != nullptr && "Condition is a null-pointer");
         assert(expression != nullptr && "Expression is a null-pointer");
     }
~RamAbstractAggregate()
virtual souffle::RamAbstractAggregate::~RamAbstractAggregate () virtual default
Member Function Documentation
equal()
bool souffle::RamAbstractAggregate::equal (const RamNode & node) const inline protected
Definition at line 727 of file RamOperation.h.
References souffle::equal_ptr(), and function.
Referenced by souffle::RamAggregate::equal(), and souffle::RamIndexAggregate::equal().
{
         const auto& other = dynamic_cast<const RamAbstractAggregate&>(node);
         return function == other.function && equal_ptr(expression, other.expression) &&
                equal_ptr(condition, other.condition);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamAbstractAggregate::getChildNodes () const inline
Definition at line 692 of file RamOperation.h.
Referenced by souffle::RamAggregate::getChildNodes(), and souffle::RamIndexAggregate::getChildNodes().
{
         return {expression.get(), condition.get()};
     }
getCondition()
const RamCondition& souffle::RamAbstractAggregate::getCondition () const inline
Get condition.
Definition at line 676 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::NodeGenerator::visitAggregate(), and souffle::NodeGenerator::visitIndexAggregate().
{
         assert(condition != nullptr && "Condition of aggregate is a null-pointer");
         return *condition;
     }
getExpression()
const RamExpression& souffle::RamAbstractAggregate::getExpression () const inline
Get target expression.
Definition at line 687 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::NodeGenerator::visitAggregate(), and souffle::NodeGenerator::visitIndexAggregate().
{
         assert(expression != nullptr && "Expression of aggregate is a null-pointer");
         return *expression;
     }
getFunction()
AggregateOp souffle::RamAbstractAggregate::getFunction () const inline
Get aggregation function.
Definition at line 682 of file RamOperation.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::MakeIndexTransformer::rewriteAggregate().
{
         return function;
     }
print()
void souffle::RamAbstractAggregate::print (std::ostream & os, int) const inline protected
Definition at line 697 of file RamOperation.h.
References souffle::COUNT, souffle::FMAX, souffle::FMIN, souffle::FSUM, souffle::MAX, souffle::MEAN, souffle::MIN, souffle::SUM, souffle::UMAX, souffle::UMIN, and souffle::USUM.
Referenced by souffle::RamAggregate::print(), and souffle::RamIndexAggregate::print().
{
         switch (function) {
             case AggregateOp::MIN:
             case AggregateOp::FMIN:
             case AggregateOp::UMIN:
                 os << "min ";
                 break;
             case AggregateOp::MAX:
             case AggregateOp::UMAX:
             case AggregateOp::FMAX:
                 os << "max ";
                 break;
             case AggregateOp::SUM:
             case AggregateOp::FSUM:
             case AggregateOp::USUM:
                 os << "sum ";
                 break;
             case AggregateOp::COUNT:
                 os << "count ";
                 break;
             case AggregateOp::MEAN:
                 os << "mean ";
                 break;
         }
         if (function != AggregateOp::COUNT) {
             os << *expression << " ";
         }
     }
Field Documentation
condition
std::unique_ptr<RamCondition> souffle::RamAbstractAggregate::condition protected
Aggregation tuple condition.
Definition at line 740 of file RamOperation.h.
expression
std::unique_ptr<RamExpression> souffle::RamAbstractAggregate::expression protected
Aggregation expression.
Definition at line 737 of file RamOperation.h.
function
AggregateOp souffle::RamAbstractAggregate::function protected
Aggregation function.
Definition at line 734 of file RamOperation.h.
Referenced by equal().
The documentation for this class was generated from the following file:
RamOperation.h