souffle: souffle::RemoveRedundantRelationsTransformer Class Reference
souffle::RemoveRedundantRelationsTransformer Class Reference
Transformation pass to remove relations which are redundant (do not contribute to output).
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to remove relations which are redundant (do not contribute to output).
Definition at line 186 of file AstTransforms.h.
Member Function Documentation
getName()
std::string souffle::RemoveRedundantRelationsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 188 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return "RemoveRedundantRelationsTransformer";
     }
transform()
bool souffle::RemoveRedundantRelationsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 502 of file AstTransforms.cpp.
References souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getProgram(), souffle::RedundantRelations::getRedundantRelations(), and souffle::AstProgram::removeRelation().
{
     bool changed = false;
     auto* redundantRelationsAnalysis = translationUnit.getAnalysis<RedundantRelations>();
     const std::set<const AstRelation*>& redundantRelations =
             redundantRelationsAnalysis->getRedundantRelations();
     if (!redundantRelations.empty()) {
         for (auto rel : redundantRelations) {
             translationUnit.getProgram()->removeRelation(rel->getQualifiedName());
             changed = true;
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp