souffle: souffle::WriteStream Class Reference
souffle::WriteStream Class Reference abstract
#include <WriteStream.h>
Public Member Functions
template<typename T >
void writeAll (const T &relation)
template<>
void writeNext (const RamDomain *tuple)
template<typename T >
void writeSize (const T &relation)
WriteStream (const std::map< std::string, std::string > &rwOperation, const SymbolTable &symbolTable, const RecordTable &recordTable)
virtual ~WriteStream ()=default
Protected Member Functions
void outputRecord (std::ostream &destination, const RamDomain value, const std::string &name)
template<typename Tuple >
void writeNext (const Tuple tuple)
virtual void writeNextTuple (const RamDomain *tuple)=0
virtual void writeNullary ()=0
virtual void writeSize (std::size_t)
Protected Attributes
size_t arity
const RecordTable & recordTable
const bool summary
const SymbolTable & symbolTable
std::vector< std::string > typeAttributes
Json types
Detailed Description
Definition at line 31 of file WriteStream.h.
Constructor & Destructor Documentation
WriteStream()
souffle::WriteStream::WriteStream (const std::map< std::string, std::string > & rwOperation, const SymbolTable & symbolTable, const RecordTable & recordTable) inline
Definition at line 33 of file WriteStream.h.
References arity, i, json11::Json::long_value(), json11::Json::parse(), json11::Json::string_value(), typeAttributes, and types.
             : symbolTable(symbolTable), recordTable(recordTable),
               summary(rwOperation.at("IO") == "stdoutprintsize") {
         const std::string& relationName{rwOperation.at("name")};
         std::string parseErrors;
         types = Json::parse(rwOperation.at("types"), parseErrors);
         assert(parseErrors.size() == 0 && "Internal JSON parsing failed.");
         arity = static_cast<size_t>(types[relationName]["arity"].long_value());
         for (size_t i = 0; i < arity; ++i) {
             std::string type = types[relationName]["types"][i].string_value();
             typeAttributes.push_back(std::move(type));
         }
     }
~WriteStream()
virtual souffle::WriteStream::~WriteStream () virtual default
Referenced by writeSize().
Member Function Documentation
outputRecord()
void souffle::WriteStream::outputRecord (std::ostream & destination, const RamDomain value, const std::string & name) inline protected
Definition at line 97 of file WriteStream.h.
References i, json11::Json::is_null(), json11::Json::long_value(), json11::Json::string_value(), souffle::RecordTable::unpack(), and souffle::SymbolTable::unsafeResolve().
Referenced by souffle::WriteStreamCSV::writeNextTupleElement().
{
         Json recordInfo = types["records"][name];
         // Check if record type information are present
         assert(!recordInfo.is_null() && "Missing record type information");
         // Check for nil
         if (value == 0) {
             destination << "nil";
             return;
         }
         const Json recordTypes = recordInfo["types"];
         const size_t recordArity = recordInfo["arity"].long_value();
         const RamDomain* tuplePtr = recordTable.unpack(value, recordArity);
         destination << "[";
         // print record's elements
         for (size_t i = 0; i < recordArity; ++i) {
             if (i > 0) {
                 destination << ", ";
             }
             const std::string& recordType = recordTypes[i].string_value();
             const RamDomain recordValue = tuplePtr[i];
             switch (recordType[0]) {
                 case 'i':
                     destination << recordValue;
                     break;
                 case 'f':
                     destination << ramBitCast<RamFloat>(recordValue);
                     break;
                 case 'u':
                     destination << ramBitCast<RamUnsigned>(recordValue);
                     break;
                 case 's':
                     destination << symbolTable.unsafeResolve(recordValue);
                     break;
                 case 'r':
                     outputRecord(destination, recordValue, recordType);
                     break;
                 default:
                     assert(false && "Unsupported type attribute.");
             }
         }
         destination << "]";
     }
writeAll()
template<typename T > void souffle::WriteStream::writeAll (const T & relation) inline
Definition at line 54 of file WriteStream.h.
References souffle::SymbolTable::acquireLock(), arity, summary, symbolTable, writeNext(), writeNullary(), and writeSize().
{
         if (summary) {
             return writeSize(relation.size());
         }
         auto lease = symbolTable.acquireLock();
         (void)lease;  // silence "unused variable" warning
         if (arity == 0) {
             if (relation.begin() != relation.end()) {
                 writeNullary();
             }
             return;
         }
         for (const auto& current : relation) {
             writeNext(current);
         }
     }
writeNext() [1/2]
template<typename Tuple > void souffle::WriteStream::writeNext (const Tuple tuple) inline protected
Definition at line 93 of file WriteStream.h.
References souffle::Tuple< Domain, _arity >::data, and writeNextTuple().
Referenced by writeAll().
{
         writeNextTuple(tuple.data);
     }
writeNext() [2/2]
template<> void souffle::WriteStream::writeNext (const RamDomain * tuple) inline
Definition at line 159 of file WriteStream.h.
References writeNextTuple().
{
     writeNextTuple(tuple);
 }
writeNextTuple()
virtual void souffle::WriteStream::writeNextTuple (const RamDomain * tuple) protected pure virtual
Implemented in souffle::WriteCoutPrintSize, souffle::WriteCoutCSV, souffle::WriteFileCSV, and souffle::WriteStreamSQLite.
Referenced by writeNext(), and souffle::WriteFileCSV::writeNextTuple().
writeNullary()
virtual void souffle::WriteStream::writeNullary () protected pure virtual
Implemented in souffle::WriteCoutPrintSize, souffle::WriteCoutCSV, souffle::WriteFileCSV, and souffle::WriteStreamSQLite.
Referenced by writeAll(), and souffle::WriteFileCSV::writeNextTuple().
writeSize() [1/2]
template<typename T > void souffle::WriteStream::writeSize (const T & relation) inline
Definition at line 71 of file WriteStream.h.
References ~WriteStream().
Referenced by writeAll().
{
         writeSize(relation.size());
     }
writeSize() [2/2]
virtual void souffle::WriteStream::writeSize (std::size_t) inline protected virtual
Reimplemented in souffle::WriteCoutPrintSize.
Definition at line 89 of file WriteStream.h.
{
         assert(false && "attempting to print size of a write operation");
     }
Field Documentation
arity
size_t souffle::WriteStream::arity protected
Definition at line 85 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::createRelationTable(), souffle::WriteStreamSQLite::createRelationView(), souffle::WriteStreamSQLite::prepareInsertStatement(), writeAll(), souffle::WriteStreamSQLite::writeNextTuple(), souffle::WriteStreamCSV::writeNextTupleCSV(), and WriteStream().
recordTable
const RecordTable& souffle::WriteStream::recordTable protected
Definition at line 79 of file WriteStream.h.
Referenced by souffle::WriteFileCSVFactory::getWriter(), souffle::WriteCoutCSVFactory::getWriter(), souffle::WriteSQLiteFactory::getWriter(), and souffle::WriteFileCSV::writeNextTuple().
summary
const bool souffle::WriteStream::summary protected
Definition at line 84 of file WriteStream.h.
Referenced by writeAll().
symbolTable
const SymbolTable& souffle::WriteStream::symbolTable protected
Definition at line 78 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::getSymbolTableID(), souffle::WriteStreamSQLite::getSymbolTableIDFromDB(), souffle::WriteFileCSVFactory::getWriter(), souffle::WriteCoutCSVFactory::getWriter(), souffle::WriteSQLiteFactory::getWriter(), writeAll(), souffle::WriteFileCSV::writeNextTuple(), and souffle::WriteStreamCSV::writeNextTupleElement().
typeAttributes
std::vector<std::string> souffle::WriteStream::typeAttributes protected
Definition at line 82 of file WriteStream.h.
Referenced by souffle::WriteStreamSQLite::createRelationView(), souffle::WriteStreamSQLite::writeNextTuple(), souffle::WriteStreamCSV::writeNextTupleCSV(), and WriteStream().
types
Json souffle::WriteStream::types protected
Definition at line 81 of file WriteStream.h.
Referenced by WriteStream().
The documentation for this class was generated from the following file:
WriteStream.h