souffle: souffle::RamParallelIndexChoice Class Reference
souffle::RamParallelIndexChoice Class Reference
Use an index to find a tuple in a relation such that a given condition holds in parallel.
#include <RamOperation.h>
Public Member Functions
RamParallelIndexChoice * clone () const override
Create a clone (i.e.
RamParallelIndexChoice (std::unique_ptr< RamRelationReference > r, int ident, std::unique_ptr< RamCondition > cond, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexChoice
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
RamIndexChoice (std::unique_ptr< RamRelationReference > r, int ident, std::unique_ptr< RamCondition > cond, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexOperation
std::vector< RamExpression * > getRangePattern () const
Get range pattern.
RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Public Member Functions inherited from souffle::RamAbstractChoice
void apply (const RamNodeMapper &map)
std::vector< const RamNode * > getChildNodes () const
const RamCondition & getCondition () const
Getter for the condition.
RamAbstractChoice (std::unique_ptr< RamCondition > cond)
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamIndexChoice
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
Protected Member Functions inherited from souffle::RamIndexOperation
void printIndex (std::ostream &os) const
Helper method for printing.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Member Functions inherited from souffle::RamAbstractChoice
bool equal (const RamNode &node) const
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamIndexOperation
std::vector< std::unique_ptr< RamExpression > > queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Protected Attributes inherited from souffle::RamAbstractChoice
std::unique_ptr< RamCondition > condition
Condition for which a tuple in the relation may hold.
Detailed Description
Use an index to find a tuple in a relation such that a given condition holds in parallel.
For example:
QUERY
 ...
  PARALLEL CHOICE A AS t1 ON INDEX t1.x=10 AND t1.y = 20
  WHERE (t1.x, t1.y) NOT IN A
    ...
Definition at line 626 of file RamOperation.h.
Constructor & Destructor Documentation
RamParallelIndexChoice()
souffle::RamParallelIndexChoice::RamParallelIndexChoice (std::unique_ptr< RamRelationReference > r, int ident, std::unique_ptr< RamCondition > cond, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 628 of file RamOperation.h.
             : RamIndexChoice(std::move(r), ident, std::move(cond), std::move(queryPattern), std::move(nested),
                       profileText) {}
Member Function Documentation
clone()
RamParallelIndexChoice* souffle::RamParallelIndexChoice::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamIndexChoice.
Definition at line 634 of file RamOperation.h.
References i.
{
         std::vector<std::unique_ptr<RamExpression>> resQueryPattern(queryPattern.size());
         for (size_t i = 0; i < queryPattern.size(); ++i) {
             resQueryPattern[i] = std::unique_ptr<RamExpression>(queryPattern[i]->clone());
         }
         auto* res = new RamParallelIndexChoice(std::unique_ptr<RamRelationReference>(relationRef->clone()),
                 getTupleId(), std::unique_ptr<RamCondition>(condition->clone()), std::move(resQueryPattern),
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
         return res;
     }
print()
void souffle::RamParallelIndexChoice::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamIndexChoice.
Definition at line 646 of file RamOperation.h.
References souffle::RamRelation::getName(), souffle::getRelation(), souffle::RamNestedOperation::print(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "PARALLEL CHOICE " << rel.getName() << " AS t" << getTupleId();
         printIndex(os);
         os << " WHERE " << getCondition();
         os << std::endl;
         RamIndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
RamOperation.h