souffle: souffle::NameUnnamedVariablesTransformer Class Reference
souffle::NameUnnamedVariablesTransformer Class Reference
Transformation pass to replace unnamed variables with singletons.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to replace unnamed variables with singletons.
E.g.: a() :- b(_). -> a() :- b(x).
Definition at line 303 of file AstTransforms.h.
Member Function Documentation
getName()
std::string souffle::NameUnnamedVariablesTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 305 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return "NameUnnamedVariablesTransformer";
     }
transform()
bool souffle::NameUnnamedVariablesTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 1043 of file AstTransforms.cpp.
References souffle::AstProgram::apply(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), and souffle::AstProgram::getRelations().
{
     bool changed = false;
     static constexpr const char* boundPrefix = "+underscore";
     struct nameVariables : public AstNodeMapper {
         mutable bool changed = false;
         mutable size_t count = 0;
         nameVariables() = default;
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (dynamic_cast<AstUnnamedVariable*>(node.get()) != nullptr) {
                 changed = true;
                 std::stringstream name;
                 name << boundPrefix << "_" << count++;
                 return std::make_unique<AstVariable>(name.str());
             }
             node->apply(*this);
             return node;
         }
     };
     AstProgram& program = *translationUnit.getProgram();
     for (AstRelation* rel : program.getRelations()) {
         for (AstClause* clause : getClauses(program, *rel)) {
             nameVariables update;
             clause->apply(update);
             changed |= update.changed;
         }
     }
     return changed;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp