souffle: souffle::AstSemanticChecker Class Reference
souffle::AstSemanticChecker Class Reference
#include <AstSemanticChecker.h>
Public Member Functions
std::string getName () const override
~AstSemanticChecker () override=default
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Static Private Member Functions
static void checkAggregator (ErrorReport &report, const AstProgram &program, const AstAggregator &aggregator)
static void checkArgument (ErrorReport &report, const AstProgram &program, const AstArgument &arg)
static void checkAtom (ErrorReport &report, const AstProgram &program, const AstAtom &atom)
static void checkClause (ErrorReport &report, const AstProgram &program, const AstClause &clause, const RecursiveClauses &recursiveClauses)
static void checkConstant (ErrorReport &report, const AstArgument &argument)
static void checkFact (ErrorReport &report, const AstProgram &program, const AstClause &fact)
static void checkInlining (ErrorReport &report, const AstProgram &program, const PrecedenceGraph &precedenceGraph, const IOType &ioTypes)
static void checkIO (ErrorReport &report, const AstProgram &program)
static void checkLiteral (ErrorReport &report, const AstProgram &program, const AstLiteral &literal)
static void checkNamespaces (ErrorReport &report, const AstProgram &program)
static void checkProgram (AstTranslationUnit &translationUnit)
static void checkRecordType (ErrorReport &report, const AstProgram &program, const TypeEnvironment &typeEnvironment, const AstRecordType &type)
static void checkRecursiveUnionTypes (ErrorReport &report, const AstProgram &program)
static void checkRelation (ErrorReport &report, const TypeEnvironment &typeEnv, const AstProgram &program, const AstRelation &relation, const RecursiveClauses &recursiveClauses, const IOType &ioTypes)
static void checkRelationDeclaration (ErrorReport &report, const TypeEnvironment &typeEnv, const AstProgram &program, const AstRelation &relation, const IOType &ioTypes)
static void checkRules (ErrorReport &report, const TypeEnvironment &typeEnv, const AstProgram &program, const RecursiveClauses &recursiveClauses, const IOType &ioTypes)
static void checkType (ErrorReport &report, const AstProgram &program, const TypeEnvironment &typeEnvironment, const AstType &type)
static void checkTypes (ErrorReport &report, const TypeEnvironmentAnalysis &typeEnvAnalysis, const AstProgram &program)
static void checkUnionType (ErrorReport &report, const AstProgram &program, const TypeEnvironment &typeEnvironment, const AstUnionType &type)
static void checkWitnessProblem (ErrorReport &report, const AstProgram &program)
static bool isDependent (const AstClause &agg1, const AstClause &agg2)
agg1, agg2 are clauses which contain no head, and consist of a single literal that contains an aggregate.
Detailed Description
Definition at line 43 of file AstSemanticChecker.h.
Constructor & Destructor Documentation
~AstSemanticChecker()
souffle::AstSemanticChecker::~AstSemanticChecker () override default
Member Function Documentation
checkAggregator()
void souffle::AstSemanticChecker::checkAggregator (ErrorReport & report, const AstProgram & program, const AstAggregator & aggregator) static private
Definition at line 509 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstClause::addToBody(), checkLiteral(), souffle::AstLiteral::clone(), souffle::AstAggregator::getBodyLiterals(), souffle::AstNode::getSrcLoc(), isDependent(), and souffle::visitDepthFirst().
Referenced by checkArgument(), and getName().
{
     const AstAggregator* inner = nullptr;
     // check for disallowed nested aggregates
     visitDepthFirst(aggregator, [&](const AstAggregator& innerAgg) {
         if (aggregator != innerAgg) {
             inner = &innerAgg;
         }
     });
     if (inner != nullptr) {
         report.addError("Unsupported nested aggregate", inner->getSrcLoc());
     }
     AstClause dummyClauseAggregator;
     visitDepthFirst(program, [&](const AstLiteral& parentLiteral) {
         visitDepthFirst(parentLiteral, [&](const AstAggregator& candidateAggregate) {
             if (candidateAggregate != aggregator) {
                 return;
             }
             // Get the literal containing the aggregator and put it into a dummy clause
             // so we can get information about groundedness
             dummyClauseAggregator.addToBody(std::unique_ptr<AstLiteral>(parentLiteral.clone()));
         });
     });
     visitDepthFirst(program, [&](const AstLiteral& parentLiteral) {
         visitDepthFirst(parentLiteral, [&](const AstAggregator& /* otherAggregate */) {
             // Create the other aggregate's dummy clause
             AstClause dummyClauseOther;
             dummyClauseOther.addToBody(std::unique_ptr<AstLiteral>(parentLiteral.clone()));
             // Check dependency between the aggregator and this one
             if (isDependent(dummyClauseAggregator, dummyClauseOther) &&
                     isDependent(dummyClauseOther, dummyClauseAggregator)) {
                 report.addError("Mutually dependent aggregate", aggregator.getSrcLoc());
             }
         });
     });
     for (AstLiteral* literal : aggregator.getBodyLiterals()) {
         checkLiteral(report, program, *literal);
     }
 }
checkArgument()
void souffle::AstSemanticChecker::checkArgument (ErrorReport & report, const AstProgram & program, const AstArgument & arg) static private
Definition at line 555 of file AstSemanticChecker.cpp.
References checkAggregator().
Referenced by checkAtom(), checkLiteral(), and getName().
{
     if (const auto* agg = dynamic_cast<const AstAggregator*>(&arg)) {
         checkAggregator(report, program, *agg);
     } else if (const auto* func = dynamic_cast<const AstFunctor*>(&arg)) {
         for (auto arg : func->getArguments()) {
             checkArgument(report, program, *arg);
         }
     }
 }
checkAtom()
void souffle::AstSemanticChecker::checkAtom (ErrorReport & report, const AstProgram & program, const AstAtom & atom) static private
Definition at line 382 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkArgument(), souffle::AstAtom::getArguments(), souffle::AstAtom::getArity(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), souffle::AstNode::getSrcLoc(), and souffle::toString().
Referenced by checkClause(), checkLiteral(), and getName().
{
     // check existence of relation
     auto* r = getRelation(program, atom.getQualifiedName());
     if (r == nullptr) {
         report.addError("Undefined relation " + toString(atom.getQualifiedName()), atom.getSrcLoc());
     }
     // check arity
     if ((r != nullptr) && r->getArity() != atom.getArity()) {
         report.addError(
                 "Mismatching arity of relation " + toString(atom.getQualifiedName()), atom.getSrcLoc());
     }
     for (const AstArgument* arg : atom.getArguments()) {
         checkArgument(report, program, *arg);
     }
 }
checkClause()
void souffle::AstSemanticChecker::checkClause (ErrorReport & report, const AstProgram & program, const AstClause & clause, const RecursiveClauses & recursiveClauses) static private
Definition at line 629 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ErrorReport::addWarning(), checkAtom(), checkFact(), checkLiteral(), souffle::contains(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getExecutionPlan(), souffle::AstClause::getHead(), souffle::AstVariable::getName(), souffle::AstExecutionPlan::getOrders(), souffle::AstNode::getSrcLoc(), souffle::hasUnnamedVariable(), i, souffle::isFact(), souffle::RecursiveClauses::recursive(), and souffle::visitDepthFirst().
Referenced by checkRules(), and getName().
{
     // check head atom
     checkAtom(report, program, *clause.getHead());
     // check for absence of underscores in head
     if (hasUnnamedVariable(clause.getHead())) {
         report.addError("Underscore in head of rule", clause.getHead()->getSrcLoc());
     }
     // check body literals
     for (AstLiteral* lit : clause.getBodyLiterals()) {
         checkLiteral(report, program, *lit);
     }
     // check facts
     if (isFact(clause)) {
         checkFact(report, program, clause);
     }
     // check for use-once variables
     std::map<std::string, int> var_count;
     std::map<std::string, const AstVariable*> var_pos;
     visitDepthFirst(clause, [&](const AstVariable& var) {
         var_count[var.getName()]++;
         var_pos[var.getName()] = &var;
     });
     // check for variables only occurring once
     for (const auto& cur : var_count) {
         int numAppearances = cur.second;
         const auto& varName = cur.first;
         const auto& varLocation = var_pos[varName]->getSrcLoc();
         if (varName[0] == '_') {
             assert(varName.size() > 1 && "named variable should not be a single underscore");
             if (numAppearances > 1) {
                 report.addWarning("Variable " + varName + " marked as singleton but occurs more than once",
                         varLocation);
             }
         } else if (numAppearances == 1) {
             report.addWarning("Variable " + varName + " only occurs once", varLocation);
         }
     }
     // check execution plan
     if (clause.getExecutionPlan() != nullptr) {
         auto numAtoms = getBodyLiterals<AstAtom>(clause).size();
         for (const auto& cur : clause.getExecutionPlan()->getOrders()) {
             bool isComplete = true;
             auto order = cur.second->getOrder();
             for (unsigned i = 1; i <= order.size(); i++) {
                 if (!contains(order, i)) {
                     isComplete = false;
                     break;
                 }
             }
             if (order.size() != numAtoms || !isComplete) {
                 report.addError("Invalid execution order in plan", cur.second->getSrcLoc());
             }
         }
     }
     // check auto-increment
     if (recursiveClauses.recursive(&clause)) {
         visitDepthFirst(clause, [&](const AstCounter& ctr) {
             report.addError("Auto-increment functor in a recursive rule", ctr.getSrcLoc());
         });
     }
 }
checkConstant()
void souffle::AstSemanticChecker::checkConstant (ErrorReport & report, const AstArgument & argument) static private
Definition at line 582 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstNode::getSrcLoc(), and souffle::isConstantArithExpr().
Referenced by checkFact(), and getName().
{
     if (const auto* var = dynamic_cast<const AstVariable*>(&argument)) {
         report.addError("Variable " + var->getName() + " in fact", var->getSrcLoc());
     } else if (dynamic_cast<const AstUnnamedVariable*>(&argument) != nullptr) {
         report.addError("Underscore in fact", argument.getSrcLoc());
     } else if (dynamic_cast<const AstIntrinsicFunctor*>(&argument) != nullptr) {
         if (!isConstantArithExpr(argument)) {
             report.addError("Function in fact", argument.getSrcLoc());
         }
     } else if (dynamic_cast<const AstUserDefinedFunctor*>(&argument) != nullptr) {
         report.addError("User-defined functor in fact", argument.getSrcLoc());
     } else if (auto* cast = dynamic_cast<const AstTypeCast*>(&argument)) {
         checkConstant(report, *cast->getValue());
     } else if (dynamic_cast<const AstCounter*>(&argument) != nullptr) {
         report.addError("Counter in fact", argument.getSrcLoc());
     } else if (dynamic_cast<const AstConstant*>(&argument) != nullptr) {
         // this one is fine - type checker will make sure of number and symbol constants
     } else if (auto* ri = dynamic_cast<const AstRecordInit*>(&argument)) {
         for (auto* arg : ri->getArguments()) {
             checkConstant(report, *arg);
         }
     } else {
         std::cout << "Unsupported Argument: " << typeid(argument).name() << "\n";
         assert(false && "Unknown case");
     }
 }
checkFact()
void souffle::AstSemanticChecker::checkFact (ErrorReport & report, const AstProgram & program, const AstClause & fact) static private
Definition at line 610 of file AstSemanticChecker.cpp.
References checkConstant(), souffle::AstAtom::getArguments(), souffle::AstClause::getHead(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), and souffle::isFact().
Referenced by checkClause(), and getName().
{
     assert(isFact(fact));
     AstAtom* head = fact.getHead();
     if (head == nullptr) {
         return;  // checked by clause
     }
     AstRelation* rel = getRelation(program, head->getQualifiedName());
     if (rel == nullptr) {
         return;  // checked by clause
     }
     // facts must only contain constants
     for (auto arg : head->getArguments()) {
         checkConstant(report, *arg);
     }
 }
checkInlining()
void souffle::AstSemanticChecker::checkInlining (ErrorReport & report, const AstProgram & program, const PrecedenceGraph & precedenceGraph, const IOType & ioTypes) static private
Definition at line 1219 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::findInlineCycle(), souffle::AstNegation::getAtom(), souffle::AstNode::getChildNodes(), souffle::getClauses(), souffle::AstRelation::getQualifiedName(), souffle::AstAtom::getQualifiedName(), souffle::getRelation(), souffle::AstProgram::getRelations(), souffle::AstNode::getSrcLoc(), i, souffle::INLINE, souffle::IOType::isIO(), relation, souffle::toString(), and souffle::visitDepthFirst().
Referenced by checkProgram(), and getName().
{
     auto isInline = [&](const AstRelation* rel) { return rel->hasQualifier(RelationQualifier::INLINE); };
     // Find all inlined relations
     AstRelationSet inlinedRelations;
     for (const auto& relation : program.getRelations()) {
         if (isInline(relation)) {
             inlinedRelations.insert(relation);
             if (ioTypes.isIO(relation)) {
                 report.addError(
                         "IO relation " + toString(relation->getQualifiedName()) + " cannot be inlined",
                         relation->getSrcLoc());
             }
         }
     }
     // Check 1:
     // Let G' be the subgraph of the precedence graph G containing only those nodes
     // which are marked with the inline directive.
     // If G' contains a cycle, then inlining cannot be performed.
     AstRelationSet unvisited;  // nodes that have not been visited yet
     AstRelationSet visiting;   // nodes that we are currently visiting
     AstRelationSet visited;    // nodes that have been completely explored
     // All nodes are initially unvisited
     for (const AstRelation* rel : inlinedRelations) {
         unvisited.insert(rel);
     }
     // Remember the parent node of each visited node to construct the found cycle
     std::map<const AstRelation*, const AstRelation*> origins;
     std::vector<AstQualifiedName> result =
             findInlineCycle(precedenceGraph, origins, nullptr, unvisited, visiting, visited);
     // If the result contains anything, then a cycle was found
     if (!result.empty()) {
         AstRelation* cycleOrigin = getRelation(program, result[result.size() - 1]);
         // Construct the string representation of the cycle
         std::stringstream cycle;
         cycle << "{" << cycleOrigin->getQualifiedName();
         // Print it backwards to preserve the initial cycle order
         for (int i = result.size() - 2; i >= 0; i--) {
             cycle << ", " << result[i];
         }
         cycle << "}";
         report.addError(
                 "Cannot inline cyclically dependent relations " + cycle.str(), cycleOrigin->getSrcLoc());
     }
     // Check 2:
     // Cannot use the counter argument ('$') in inlined relations
     // Check if an inlined literal ever takes in a $
     visitDepthFirst(program, [&](const AstAtom& atom) {
         AstRelation* associatedRelation = getRelation(program, atom.getQualifiedName());
         if (associatedRelation != nullptr && isInline(associatedRelation)) {
             visitDepthFirst(atom, [&](const AstArgument& arg) {
                 if (dynamic_cast<const AstCounter*>(&arg) != nullptr) {
                     report.addError(
                             "Cannot inline literal containing a counter argument '$'", arg.getSrcLoc());
                 }
             });
         }
     });
     // Check if an inlined clause ever contains a $
     for (const AstRelation* rel : inlinedRelations) {
         for (AstClause* clause : getClauses(program, *rel)) {
             visitDepthFirst(*clause, [&](const AstArgument& arg) {
                 if (dynamic_cast<const AstCounter*>(&arg) != nullptr) {
                     report.addError(
                             "Cannot inline clause containing a counter argument '$'", arg.getSrcLoc());
                 }
             });
         }
     }
     // Check 3:
     // Suppose the relation b is marked with the inline directive, but appears negated
     // in a clause. Then, if b introduces a new variable in its body, we cannot inline
     // the relation b.
     // Find all relations with the inline declarative that introduce new variables in their bodies
     AstRelationSet nonNegatableRelations;
     for (const AstRelation* rel : inlinedRelations) {
         bool foundNonNegatable = false;
         for (const AstClause* clause : getClauses(program, *rel)) {
             // Get the variables in the head
             std::set<std::string> headVariables;
             visitDepthFirst(
                     *clause->getHead(), [&](const AstVariable& var) { headVariables.insert(var.getName()); });
             // Get the variables in the body
             std::set<std::string> bodyVariables;
             visitDepthFirst(clause->getBodyLiterals(),
                     [&](const AstVariable& var) { bodyVariables.insert(var.getName()); });
             // Check if all body variables are in the head
             // Do this separately to the above so only one error is printed per variable
             for (const std::string& var : bodyVariables) {
                 if (headVariables.find(var) == headVariables.end()) {
                     nonNegatableRelations.insert(rel);
                     foundNonNegatable = true;
                     break;
                 }
             }
             if (foundNonNegatable) {
                 break;
             }
         }
     }
     // Check that these relations never appear negated
     visitDepthFirst(program, [&](const AstNegation& neg) {
         AstRelation* associatedRelation = getRelation(program, neg.getAtom()->getQualifiedName());
         if (associatedRelation != nullptr &&
                 nonNegatableRelations.find(associatedRelation) != nonNegatableRelations.end()) {
             report.addError(
                     "Cannot inline negated relation which may introduce new variables", neg.getSrcLoc());
         }
     });
     // Check 4:
     // Don't support inlining atoms within aggregators at this point.
     // Reasoning: Suppose we have an aggregator like `max X: a(X)`, where `a` is inlined to `a1` and `a2`.
     // Then, `max X: a(X)` will become `max( max X: a1(X),  max X: a2(X) )`. Suppose further that a(X) has
     // values X where it is true, while a2(X) does not. Then, the produced argument
     // `max( max X: a1(X),  max X: a2(X) )` will not return anything (as one of its arguments fails), while
     // `max X: a(X)` will.
     // Can work around this with emptiness checks (e.g. `!a1(_), ... ; !a2(_), ... ; ...`)
     // This corner case prevents generalising aggregator inlining with the current set up.
     visitDepthFirst(program, [&](const AstAggregator& aggr) {
         visitDepthFirst(aggr, [&](const AstAtom& subatom) {
             const AstRelation* rel = getRelation(program, subatom.getQualifiedName());
             if (rel != nullptr && isInline(rel)) {
                 report.addError("Cannot inline relations that appear in aggregator", subatom.getSrcLoc());
             }
         });
     });
     // Check 5:
     // Suppose a relation `a` is inlined, appears negated in a clause, and contains a
     // (possibly nested) unnamed variable in its arguments. Then, the atom can't be
     // inlined, as unnamed variables are named during inlining (since they may appear
     // multiple times in an inlined-clause's body) => ungroundedness!
     // Exception: It's fine if the unnamed variable appears in a nested aggregator, as
     // the entire aggregator will automatically be grounded.
     // TODO (azreika): special case where all rules defined for `a` use the
     // underscored-argument exactly once: can workaround by remapping the variable
     // back to an underscore - involves changes to the actual inlining algo, though
     // Returns the pair (isValid, lastSrcLoc) where:
     //  - isValid is true if and only if the node contains an invalid underscore, and
     //  - lastSrcLoc is the source location of the last visited node
     std::function<std::pair<bool, SrcLocation>(const AstNode*)> checkInvalidUnderscore =
             [&](const AstNode* node) {
                 if (dynamic_cast<const AstUnnamedVariable*>(node) != nullptr) {
                     // Found an invalid underscore
                     return std::make_pair(true, node->getSrcLoc());
                 } else if (dynamic_cast<const AstAggregator*>(node) != nullptr) {
                     // Don't care about underscores within aggregators
                     return std::make_pair(false, node->getSrcLoc());
                 }
                 // Check if any children nodes use invalid underscores
                 for (const AstNode* child : node->getChildNodes()) {
                     std::pair<bool, SrcLocation> childStatus = checkInvalidUnderscore(child);
                     if (childStatus.first) {
                         // Found an invalid underscore
                         return childStatus;
                     }
                 }
                 return std::make_pair(false, node->getSrcLoc());
             };
     // Perform the check
     visitDepthFirst(program, [&](const AstNegation& negation) {
         const AstAtom* associatedAtom = negation.getAtom();
         const AstRelation* associatedRelation = getRelation(program, associatedAtom->getQualifiedName());
         if (associatedRelation != nullptr && isInline(associatedRelation)) {
             std::pair<bool, SrcLocation> atomStatus = checkInvalidUnderscore(associatedAtom);
             if (atomStatus.first) {
                 report.addError(
                         "Cannot inline negated atom containing an unnamed variable unless the variable is "
                         "within an aggregator",
                         atomStatus.second);
             }
         }
     });
 }
checkIO()
void souffle::AstSemanticChecker::checkIO (ErrorReport & report, const AstProgram & program) static private
Definition at line 972 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstProgram::getIOs(), souffle::getRelation(), and souffle::toString().
Referenced by checkProgram(), and getName().
{
     auto checkIO = [&](const AstIO* directive) {
         auto* r = getRelation(program, directive->getQualifiedName());
         if (r == nullptr) {
             report.addError(
                     "Undefined relation " + toString(directive->getQualifiedName()), directive->getSrcLoc());
         }
     };
     for (const auto* directive : program.getIOs()) {
         checkIO(directive);
     }
 }
checkLiteral()
void souffle::AstSemanticChecker::checkLiteral (ErrorReport & report, const AstProgram & program, const AstLiteral & literal) static private
Definition at line 449 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkArgument(), checkAtom(), souffle::AstNode::getSrcLoc(), and souffle::hasUnnamedVariable().
Referenced by checkAggregator(), checkClause(), and getName().
{
     // check potential nested atom
     if (const auto* atom = dynamic_cast<const AstAtom*>(&literal)) {
         checkAtom(report, program, *atom);
     }
     if (const auto* neg = dynamic_cast<const AstNegation*>(&literal)) {
         checkAtom(report, program, *neg->getAtom());
     }
     if (const auto* constraint = dynamic_cast<const AstBinaryConstraint*>(&literal)) {
         checkArgument(report, program, *constraint->getLHS());
         checkArgument(report, program, *constraint->getRHS());
     }
     // check for invalid underscore utilization
     if (hasUnnamedVariable(&literal)) {
         if (dynamic_cast<const AstAtom*>(&literal) != nullptr) {
             // nothing to check since underscores are allowed
         } else if (dynamic_cast<const AstNegation*>(&literal) != nullptr) {
             // nothing to check since underscores are allowed
         } else if (dynamic_cast<const AstBinaryConstraint*>(&literal) != nullptr) {
             report.addError("Underscore in binary relation", literal.getSrcLoc());
         } else {
             std::cout << "Unsupported Literal type: " << typeid(literal).name() << "\n";
             assert(false && "Unsupported Argument Type!");
         }
     }
 }
checkNamespaces()
void souffle::AstSemanticChecker::checkNamespaces (ErrorReport & report, const AstProgram & program) static private
Definition at line 1425 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstProgram::getRelations(), souffle::AstProgram::getTypes(), and souffle::toString().
Referenced by checkProgram(), and getName().
{
     std::map<std::string, SrcLocation> names;
     // Find all names and report redeclarations as we go.
     for (const auto& type : program.getTypes()) {
         const std::string name = toString(type->getQualifiedName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on type " + name, type->getSrcLoc());
         } else {
             names[name] = type->getSrcLoc();
         }
     }
     for (const auto& rel : program.getRelations()) {
         const std::string name = toString(rel->getQualifiedName());
         if (names.count(name) != 0u) {
             report.addError("Name clash on relation " + name, rel->getSrcLoc());
         } else {
             names[name] = rel->getSrcLoc();
         }
     }
 }
checkProgram()
void souffle::AstSemanticChecker::checkProgram (AstTranslationUnit & translationUnit) static private
Definition at line 64 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addDiagnostic(), souffle::ErrorReport::addError(), souffle::any_of(), souffle::AstQualifiedName::append(), souffle::TypeSet::begin(), checkInlining(), checkIO(), checkNamespaces(), checkRules(), checkTypes(), checkWitnessProblem(), souffle::Global::config(), souffle::TypeSet::empty(), souffle::eqTypeTypeAttribute(), souffle::Diagnostic::ERROR, souffle::Float, souffle::AstNumericConstant::Float, souffle::AstTranslationUnit::getAnalysis(), souffle::AstFunctor::getArgType(), souffle::AstTerm::getArguments(), souffle::getBinaryConstraintTypes(), souffle::getClauses(), souffle::AstTranslationUnit::getErrorReport(), souffle::RecordType::getFields(), souffle::getGroundedTerms(), souffle::SCCGraph::getInternalRelations(), souffle::AstBinaryConstraint::getLHS(), souffle::AstVariable::getName(), souffle::AstBinaryConstraint::getOperator(), souffle::AstAggregator::getOperator(), souffle::AstTranslationUnit::getProgram(), souffle::AstRelation::getQualifiedName(), souffle::getRecords(), souffle::getRelation(), souffle::AstFunctor::getReturnType(), souffle::AstBinaryConstraint::getRHS(), souffle::SCCGraph::getSCC(), souffle::AstNode::getSrcLoc(), souffle::AstNumericConstant::getType(), souffle::AstTypeCast::getType(), souffle::getTypeAttributeAggregate(), souffle::TypeEnvironmentAnalysis::getTypeEnvironment(), souffle::TypeAnalysis::getTypes(), souffle::getVariables(), souffle::hasClauseWithAggregatedRelation(), souffle::hasClauseWithNegatedRelation(), souffle::hasFloatType(), souffle::hasSignedType(), souffle::hasUnsignedType(), i, souffle::AstNumericConstant::Int, souffle::isFact(), souffle::isOrderedBinaryConstraintOp(), souffle::isRecordType(), souffle::SCCGraph::isRecursive(), souffle::isSymbolType(), souffle::join(), souffle::ORD, souffle::Record, souffle::Signed, souffle::TypeSet::size(), souffle::splitString(), souffle::profile::ss, souffle::SUPPRESSED, souffle::Symbol, souffle::toString(), types, souffle::AstNumericConstant::Uint, souffle::Unsigned, and souffle::visitDepthFirst().
Referenced by getName(), and transform().
{
     const TypeEnvironmentAnalysis& typeEnvAnalysis = *translationUnit.getAnalysis<TypeEnvironmentAnalysis>();
     const TypeEnvironment& typeEnv = typeEnvAnalysis.getTypeEnvironment();
     const TypeAnalysis& typeAnalysis = *translationUnit.getAnalysis<TypeAnalysis>();
     const PrecedenceGraph& precedenceGraph = *translationUnit.getAnalysis<PrecedenceGraph>();
     const RecursiveClauses& recursiveClauses = *translationUnit.getAnalysis<RecursiveClauses>();
     const IOType& ioTypes = *translationUnit.getAnalysis<IOType>();
     const AstProgram& program = *translationUnit.getProgram();
     ErrorReport& report = translationUnit.getErrorReport();
     const SCCGraph& sccGraph = *translationUnit.getAnalysis<SCCGraph>();
     // suppress warnings for given relations
     if (Global::config().has("suppress-warnings")) {
         std::vector<std::string> suppressedRelations =
                 splitString(Global::config().get("suppress-warnings"), ',');
         if (std::find(suppressedRelations.begin(), suppressedRelations.end(), "*") !=
                 suppressedRelations.end()) {
             // mute all relations
             for (AstRelation* rel : program.getRelations()) {
                 rel->addQualifier(RelationQualifier::SUPPRESSED);
             }
         } else {
             // mute only the given relations (if they exist)
             for (auto& relname : suppressedRelations) {
                 const std::vector<std::string> comps = splitString(relname, '.');
                 if (!comps.empty()) {
                     // generate the relation identifier
                     AstQualifiedName relid(comps[0]);
                     for (size_t i = 1; i < comps.size(); i++) {
                         relid.append(comps[i]);
                     }
                     // update suppressed qualifier if the relation is found
                     if (AstRelation* rel = getRelation(program, relid)) {
                         rel->addQualifier(RelationQualifier::SUPPRESSED);
                     }
                 }
             }
         }
     }
     // -- conduct checks --
     // TODO: re-write to use visitors
     checkTypes(report, typeEnvAnalysis, program);
     checkRules(report, typeEnv, program, recursiveClauses, ioTypes);
     checkNamespaces(report, program);
     checkIO(report, program);
     checkWitnessProblem(report, program);
     checkInlining(report, program, precedenceGraph, ioTypes);
     // get the list of components to be checked
     std::vector<const AstNode*> nodes;
     for (const auto& rel : program.getRelations()) {
         for (const auto& cls : getClauses(program, *rel)) {
             nodes.push_back(cls);
         }
     }
     // -- check grounded variables and records --
     visitDepthFirst(nodes, [&](const AstClause& clause) {
         // only interested in rules
         if (isFact(clause)) {
             return;
         }
         // compute all grounded terms
         auto isGrounded = getGroundedTerms(clause);
         // all terms in head need to be grounded
         std::set<std::string> reportedVars;
         for (const AstVariable* cur : getVariables(clause)) {
             if (!isGrounded[cur] && reportedVars.insert(cur->getName()).second) {
                 report.addError("Ungrounded variable " + cur->getName(), cur->getSrcLoc());
             }
         }
         // all records need to be grounded
         for (const AstRecordInit* cur : getRecords(clause)) {
             if (!isGrounded[cur]) {
                 report.addError("Ungrounded record", cur->getSrcLoc());
             }
         }
     });
     // -- type checks --
     // - variables -
     visitDepthFirst(nodes, [&](const AstVariable& var) {
         if (typeAnalysis.getTypes(&var).empty()) {
             report.addError("Unable to deduce type for variable " + var.getName(), var.getSrcLoc());
         }
     });
     // - constants -
     // all string constants are used as symbols
     visitDepthFirst(nodes, [&](const AstStringConstant& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         if (!isSymbolType(types)) {
             report.addError("Symbol constant (type mismatch)", constant.getSrcLoc());
         }
     });
     // TODO (darth_tytus): Improve error messages.
     // At this stage each constant should have a type (assigned by a transformer)
     visitDepthFirst(nodes, [&](const AstNumericConstant& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         // No type could be assigned.
         if (!constant.getType().has_value()) {
             report.addError("Ambiguous constant (unable to deduce type)", constant.getSrcLoc());
             return;
         }
         switch (*constant.getType()) {
             case AstNumericConstant::Type::Int:
                 if (!hasSignedType(types)) {
                     report.addError("Number constant (type mismatch)", constant.getSrcLoc());
                 }
                 break;
             case AstNumericConstant::Type::Uint:
                 if (!hasUnsignedType(types)) {
                     report.addError("Unsigned constant (type mismatch)", constant.getSrcLoc());
                 }
                 break;
             case AstNumericConstant::Type::Float:
                 if (!hasFloatType(types)) {
                     report.addError("Float constant (type mismatch)", constant.getSrcLoc());
                 }
                 break;
         }
     });
     // all nil constants are used as records
     visitDepthFirst(nodes, [&](const AstNilConstant& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         if (!isRecordType(types)) {
             report.addError("Nil constant used as a non-record", constant.getSrcLoc());
         }
     });
     // record initializations have the same size as their types
     visitDepthFirst(nodes, [&](const AstRecordInit& constant) {
         TypeSet types = typeAnalysis.getTypes(&constant);
         if (!isRecordType(types) || types.size() != 1) {
             report.addError("Ambiguous record", constant.getSrcLoc());
             return;
         }
         // At this point we know that there is exactly one type in set, so we can take it.
         const RecordType* recordType = dynamic_cast<const RecordType*>(&(*types.begin()));
         if (recordType->getFields().size() != constant.getArguments().size()) {
             report.addError("Wrong number of arguments given to record", constant.getSrcLoc());
         }
     });
     // type casts name a valid type
     visitDepthFirst(nodes, [&](const AstTypeCast& cast) {
         if (!typeEnv.isType(cast.getType())) {
             report.addError("Type cast is to undeclared type " + toString(cast.getType()), cast.getSrcLoc());
         }
     });
     // - functors -
     visitDepthFirst(nodes, [&](const AstFunctor& fun) {
         // check type of result
         const TypeSet& resultType = typeAnalysis.getTypes(&fun);
         if (!eqTypeTypeAttribute(fun.getReturnType(), resultType)) {
             switch (fun.getReturnType()) {
                 case TypeAttribute::Signed:
                     report.addError("Non-numeric use for numeric functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Unsigned:
                     report.addError("Non-unsigned use for unsigned functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Float:
                     report.addError("Non-float use for float functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Symbol:
                     report.addError("Non-symbolic use for symbolic functor", fun.getSrcLoc());
                     break;
                 case TypeAttribute::Record:
                     assert(false && "Invalid return type");
             }
         }
         // Special case
         if (auto intrFun = dynamic_cast<const AstIntrinsicFunctor*>(&fun)) {
             if (intrFun->getFunction() == FunctorOp::ORD) {
                 return;
             }
         }
         size_t i = 0;
         for (auto arg : fun.getArguments()) {
             if (!eqTypeTypeAttribute(fun.getArgType(i), typeAnalysis.getTypes(arg))) {
                 switch (fun.getArgType(i)) {
                     case TypeAttribute::Signed:
                         report.addError("Non-numeric argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Symbol:
                         report.addError("Non-symbolic argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Unsigned:
                         report.addError("Non-unsigned argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Float:
                         report.addError("Non-float argument for functor", arg->getSrcLoc());
                         break;
                     case TypeAttribute::Record:
                         assert(false && "Invalid argument type");
                 }
             }
             ++i;
         }
     });
     // - binary relation -
     visitDepthFirst(nodes, [&](const AstBinaryConstraint& constraint) {
         auto op = constraint.getOperator();
         auto left = constraint.getLHS();
         auto right = constraint.getRHS();
         auto opRamTypes = getBinaryConstraintTypes(op);
         // Skip checks if either side is `Bottom` b/c it just adds noise.
         // The unable-to-deduce-type checker will point out the issue.
         if (typeAnalysis.getTypes(left).empty() || typeAnalysis.getTypes(right).empty()) return;
         // give them a slightly nicer error
         if (isOrderedBinaryConstraintOp(op) && typeAnalysis.getTypes(left) != typeAnalysis.getTypes(right)) {
             report.addError("Cannot compare different types", constraint.getSrcLoc());
         } else {
             auto checkTyAttr = [&](AstArgument const& side) {
                 auto opMatchesType = any_of(opRamTypes, [&](auto& ramType) {
                     return eqTypeTypeAttribute(ramType, typeAnalysis.getTypes(&side));
                 });
                 if (!opMatchesType) {
                     std::stringstream ss;
                     ss << "Constraint requires an operand of type "
                        << join(opRamTypes, " or ", [&](auto& out, auto& ramTy) {
                               switch (ramTy) {
                                   case TypeAttribute::Signed:
                                       out << "`number`";
                                       break;
                                   case TypeAttribute::Symbol:
                                       out << "`symbol`";
                                       break;
                                   case TypeAttribute::Unsigned:
                                       out << "`unsigned`";
                                       break;
                                   case TypeAttribute::Float:
                                       out << "`float`";
                                       break;
                                   case TypeAttribute::Record:
                                       out << "a record";
                                       break;
                               }
                           });
                     report.addError(ss.str(), side.getSrcLoc());
                 }
             };
             checkTyAttr(*left);
             checkTyAttr(*right);
         }
     });
     visitDepthFirst(nodes, [&](const AstAggregator& aggregator) {
         auto op = aggregator.getOperator();
         auto aggregatorType = typeAnalysis.getTypes(&aggregator);
         TypeAttribute opType = getTypeAttributeAggregate(op);
         // Check if operation type and return type agree.
         if (!eqTypeTypeAttribute(opType, aggregatorType)) {
             report.addError("Couldn't assign types to the aggregator", aggregator.getSrcLoc());
         }
     });
     // - stratification --
     // check for cyclic dependencies
     for (AstRelation* cur : program.getRelations()) {
         size_t scc = sccGraph.getSCC(cur);
         if (sccGraph.isRecursive(scc)) {
             for (const AstRelation* cyclicRelation : sccGraph.getInternalRelations(scc)) {
                 // Negations and aggregations need to be stratified
                 const AstLiteral* foundLiteral = nullptr;
                 bool hasNegation = hasClauseWithNegatedRelation(cyclicRelation, cur, &program, foundLiteral);
                 if (hasNegation ||
                         hasClauseWithAggregatedRelation(cyclicRelation, cur, &program, foundLiteral)) {
                     auto const& relSet = sccGraph.getInternalRelations(scc);
                     std::set<const AstRelation*, AstNameComparison> sortedRelSet(
                             relSet.begin(), relSet.end());
                     // Negations and aggregations need to be stratified
                     std::string relationsListStr = toString(join(sortedRelSet, ",",
                             [](std::ostream& out, const AstRelation* r) { out << r->getQualifiedName(); }));
                     std::vector<DiagnosticMessage> messages;
                     messages.push_back(DiagnosticMessage(
                             "Relation " + toString(cur->getQualifiedName()), cur->getSrcLoc()));
                     std::string negOrAgg = hasNegation ? "negation" : "aggregation";
                     messages.push_back(
                             DiagnosticMessage("has cyclic " + negOrAgg, foundLiteral->getSrcLoc()));
                     report.addDiagnostic(Diagnostic(Diagnostic::ERROR,
                             DiagnosticMessage("Unable to stratify relation(s) {" + relationsListStr + "}"),
                             messages));
                     break;
                 }
             }
         }
     }
 }
checkRecordType()
void souffle::AstSemanticChecker::checkRecordType (ErrorReport & report, const AstProgram & program, const TypeEnvironment & typeEnvironment, const AstRecordType & type) static private
Definition at line 789 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstRecordType::getFields(), souffle::AstType::getQualifiedName(), souffle::AstNode::getSrcLoc(), souffle::getType(), i, souffle::TypeEnvironment::isPredefinedType(), j, and souffle::toString().
Referenced by checkType(), and getName().
{
     // check proper definition of all field types
     for (const auto& field : type.getFields()) {
         if (!typeEnvironment.isPredefinedType(field.type) && (getType(program, field.type) == nullptr)) {
             report.addError(
                     "Undefined type " + toString(field.type) + " in definition of field " + field.name,
                     type.getSrcLoc());
         }
     }
     // check that field names are unique
     auto& fields = type.getFields();
     for (std::size_t i = 0; i < fields.size(); i++) {
         const std::string& cur_name = fields[i].name;
         for (std::size_t j = 0; j < i; j++) {
             if (fields[j].name == cur_name) {
                 report.addError("Doubly defined field name " + cur_name + " in definition of type " +
                                         toString(type.getQualifiedName()),
                         type.getSrcLoc());
             }
         }
     }
 }
checkRecursiveUnionTypes()
void souffle::AstSemanticChecker::checkRecursiveUnionTypes (ErrorReport & report, const AstProgram & program) static private
Definition at line 823 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstType::getQualifiedName(), souffle::AstNode::getSrcLoc(), souffle::AstProgram::getTypes(), souffle::AstUnionType::getTypes(), souffle::Graph< Vertex, Compare >::insert(), souffle::join(), souffle::Graph< Vertex, Compare >::successors(), souffle::toString(), types, souffle::Graph< Vertex, Compare >::vertices(), and souffle::visitDepthFirst().
Referenced by checkTypes(), and getName().
{
     /* Goal: throw an error when unions are cyclically defined */
     // create an edge from each union to its dependents
     Graph<AstQualifiedName> unionTypeGraph = Graph<AstQualifiedName>();
     visitDepthFirst(program, [&](const AstUnionType& ut) {
         for (auto subtype : ut.getTypes()) {
             unionTypeGraph.insert(ut.getQualifiedName(), subtype);
         }
     });
     // helper method to find cycle in the final graph
     std::set<AstQualifiedName> exploredNodes;
     std::function<bool(
             const Graph<AstQualifiedName>&, const AstQualifiedName&, std::vector<AstQualifiedName>&)>
             findCycle;
     // @param   graph union-type dependency graph
     // @param   root next node to explore
     // @param   currPath current path being explored through the graph
     // @return  true if a cycle exists, false otherwise
     findCycle = [&](const Graph<AstQualifiedName>& graph, AstQualifiedName root,
                         std::vector<AstQualifiedName>& currPath) {
         if (exploredNodes.find(root) != exploredNodes.end()) {
             // already checked paths through this node
             return false;
         }
         // exploring paths through this node
         currPath.push_back(root);
         bool cycleFound = false;
         for (auto next : graph.successors(root)) {
             auto pos = std::find(currPath.begin(), currPath.end(), next);
             if (pos != currPath.end()) {
                 // cycle found!
                 // add to the end to close the cycle
                 currPath.push_back(next);
                 cycleFound = true;
                 break;
             }
             // keep going down this path
             if (findCycle(graph, next, currPath)) {
                 cycleFound = true;
                 break;
             }
         }
         // done with this node
         exploredNodes.insert(root);
         if (cycleFound) {
             return true;
         } else {
             // no cycle found, bounce back
             currPath.pop_back();
             return false;
         }
     };
     // run the cycle check
     for (const auto& node : unionTypeGraph.vertices()) {
         std::vector<AstQualifiedName> path;
         if (findCycle(unionTypeGraph, node, path)) {
             // pop out the last node of the cycle
             AstQualifiedName cycleStart = path.back();
             path.pop_back();
             // last node is also the first node, so crop out irrelevant nodes from the start
             auto startPos = std::find(path.begin(), path.end(), cycleStart);
             assert(startPos != path.end() && "node should appear twice in cycle");
             path.erase(path.begin(), startPos);
             // get the associated type definition
             auto types = program.getTypes();
             const AstUnionType* typeDefinition = nullptr;
             for (const auto* cur : program.getTypes()) {
                 const auto* curUnion = dynamic_cast<const AstUnionType*>(cur);
                 if (curUnion == nullptr) {
                     // only care about union types
                     continue;
                 }
                 // typename must match
                 if (curUnion->getQualifiedName() == cycleStart) {
                     typeDefinition = curUnion;
                 }
             }
             assert(typeDefinition != nullptr && "typename should have union type definition");
             // add the error
             std::string typeListStr = toString(join(path, ","));
             report.addError(
                     "Cyclic definition of union type(s) {" + typeListStr + "}", typeDefinition->getSrcLoc());
         }
     }
 }
checkRelation()
void souffle::AstSemanticChecker::checkRelation (ErrorReport & report, const TypeEnvironment & typeEnv, const AstProgram & program, const AstRelation & relation, const RecursiveClauses & recursiveClauses, const IOType & ioTypes) static private
Definition at line 726 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::ErrorReport::addWarning(), checkRelationDeclaration(), souffle::EQREL, souffle::AstRelation::getArity(), souffle::AstRelation::getAttributes(), souffle::getClauses(), souffle::AstRelation::getQualifiedName(), souffle::AstRelation::getRepresentation(), souffle::AstNode::getSrcLoc(), souffle::AstRelation::hasQualifier(), souffle::IOType::isInput(), souffle::SUPPRESSED, and souffle::toString().
Referenced by checkRules(), and getName().
{
     if (relation.getRepresentation() == RelationRepresentation::EQREL) {
         if (relation.getArity() == 2) {
             const auto& attributes = relation.getAttributes();
             assert(attributes.size() == 2 && "mismatching attribute size and arity");
             if (attributes[0]->getTypeName() != attributes[1]->getTypeName()) {
                 report.addError("Domains of equivalence relation " + toString(relation.getQualifiedName()) +
                                         " are different",
                         relation.getSrcLoc());
             }
         } else {
             report.addError(
                     "Equivalence relation " + toString(relation.getQualifiedName()) + " is not binary",
                     relation.getSrcLoc());
         }
     }
     // start with declaration
     checkRelationDeclaration(report, typeEnv, program, relation, ioTypes);
     // check whether this relation is empty
     if (getClauses(program, relation).empty() && !ioTypes.isInput(&relation) &&
             !relation.hasQualifier(RelationQualifier::SUPPRESSED)) {
         report.addWarning("No rules/facts defined for relation " + toString(relation.getQualifiedName()),
                 relation.getSrcLoc());
     }
 }
checkRelationDeclaration()
void souffle::AstSemanticChecker::checkRelationDeclaration (ErrorReport & report, const TypeEnvironment & typeEnv, const AstProgram & program, const AstRelation & relation, const IOType & ioTypes) static private
Definition at line 699 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstRelation::getArity(), souffle::AstAttribute::getAttributeName(), souffle::AstRelation::getAttributes(), souffle::AstNode::getSrcLoc(), souffle::getType(), souffle::AstAttribute::getTypeName(), i, souffle::TypeEnvironment::isPredefinedType(), j, and souffle::toString().
Referenced by checkRelation(), and getName().
{
     const auto& attributes = relation.getAttributes();
     assert(attributes.size() == relation.getArity() && "mismatching attribute size and arity");
     for (size_t i = 0; i < relation.getArity(); i++) {
         AstAttribute* attr = attributes[i];
         AstQualifiedName typeName = attr->getTypeName();
         /* check whether type exists */
         if (!typeEnvironment.isPredefinedType(typeName) && (getType(program, typeName) == nullptr)) {
             report.addError("Undefined type in attribute " + attr->getAttributeName() + ":" +
                                     toString(attr->getTypeName()),
                     attr->getSrcLoc());
         }
         /* check whether name occurs more than once */
         for (size_t j = 0; j < i; j++) {
             if (attr->getAttributeName() == attributes[j]->getAttributeName()) {
                 report.addError("Doubly defined attribute name " + attr->getAttributeName() + ":" +
                                         toString(attr->getTypeName()),
                         attr->getSrcLoc());
             }
         }
     }
 }
checkRules()
void souffle::AstSemanticChecker::checkRules (ErrorReport & report, const TypeEnvironment & typeEnv, const AstProgram & program, const RecursiveClauses & recursiveClauses, const IOType & ioTypes) static private
Definition at line 756 of file AstSemanticChecker.cpp.
References checkClause(), checkRelation(), souffle::AstProgram::getClauses(), and souffle::AstProgram::getRelations().
Referenced by checkProgram(), and getName().
{
     for (const AstRelation* rel : program.getRelations()) {
         checkRelation(report, typeEnv, program, *rel, recursiveClauses, ioTypes);
     }
     for (const AstClause* clause : program.getClauses()) {
         checkClause(report, program, *clause, recursiveClauses);
     }
 }
checkType()
void souffle::AstSemanticChecker::checkType (ErrorReport & report, const AstProgram & program, const TypeEnvironment & typeEnvironment, const AstType & type) static private
Definition at line 814 of file AstSemanticChecker.cpp.
References checkRecordType(), and checkUnionType().
Referenced by checkTypes(), and getName().
{
     if (const auto* u = dynamic_cast<const AstUnionType*>(&type)) {
         checkUnionType(report, program, typeEnvironment, *u);
     } else if (const auto* r = dynamic_cast<const AstRecordType*>(&type)) {
         checkRecordType(report, program, typeEnvironment, *r);
     }
 }
checkTypes()
void souffle::AstSemanticChecker::checkTypes (ErrorReport & report, const TypeEnvironmentAnalysis & typeEnvAnalysis, const AstProgram & program) static private
Definition at line 921 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), checkRecursiveUnionTypes(), checkType(), souffle::Float, souffle::TypeEnvironmentAnalysis::getTypeEnvironment(), souffle::AstProgram::getTypes(), souffle::TypeEnvironmentAnalysis::getUnionType(), souffle::join(), souffle::Signed, souffle::Symbol, and souffle::Unsigned.
Referenced by checkProgram(), and getName().
{
     /* check each type individually */
     for (const auto& cur : program.getTypes()) {
         checkType(report, program, typeEnvAnalysis.getTypeEnvironment(), *cur);
     }
     /* check that union types do not mix different primitive types */
     for (const auto* type : program.getTypes()) {
         // We are only interested in unions here.
         if (dynamic_cast<const AstUnionType*>(type) == nullptr) {
             continue;
         }
         const auto& name = type->getQualifiedName();
         const std::set<TypeAttribute>& predefinedTypesInUnion = typeEnvAnalysis.getUnionType(name);
         // Report error (if size == 0, then the union is cyclic)
         if (predefinedTypesInUnion.size() > 1) {
             std::stringstream errorMessage;
             auto toPrimitiveTypeName = [](std::ostream& out, TypeAttribute type) {
                 switch (type) {
                     case TypeAttribute::Signed:
                         out << "number";
                         break;
                     case TypeAttribute::Unsigned:
                         out << "unsigned";
                         break;
                     case TypeAttribute::Float:
                         out << "float";
                         break;
                     case TypeAttribute::Symbol:
                         out << "symbol";
                         break;
                     default:
                         assert(false && "Invalid type");
                 }
             };
             errorMessage << "Union type " << name << " is defined over {"
                          << join(predefinedTypesInUnion, ", ", toPrimitiveTypeName) << "}"
                          << " (multiple primitive types in union)";
             report.addError(errorMessage.str(), type->getSrcLoc());
         }
     }
     /* check that union types are not defined recursively */
     checkRecursiveUnionTypes(report, program);
 }
checkUnionType()
void souffle::AstSemanticChecker::checkUnionType (ErrorReport & report, const AstProgram & program, const TypeEnvironment & typeEnvironment, const AstUnionType & type) static private
Definition at line 769 of file AstSemanticChecker.cpp.
References souffle::ErrorReport::addError(), souffle::AstType::getQualifiedName(), souffle::AstNode::getSrcLoc(), souffle::getType(), souffle::AstUnionType::getTypes(), souffle::TypeEnvironment::isPredefinedType(), souffle::sub(), and souffle::toString().
Referenced by checkType(), and getName().
{
     // check presence of all the element types and that all element types are based off a primitive
     for (const AstQualifiedName& sub : type.getTypes()) {
         if (!typeEnvironment.isPredefinedType(sub)) {
             const AstType* subt = getType(program, sub);
             if (subt == nullptr) {
                 report.addError("Undefined type " + toString(sub) + " in definition of union type " +
                                         toString(type.getQualifiedName()),
                         type.getSrcLoc());
             } else if ((dynamic_cast<const AstUnionType*>(subt) == nullptr) &&
                        (dynamic_cast<const AstSubsetType*>(subt) == nullptr)) {
                 report.addError("Union type " + toString(type.getQualifiedName()) +
                                         " contains the non-primitive type " + toString(sub),
                         type.getSrcLoc());
             }
         }
     }
 }
checkWitnessProblem()
void souffle::AstSemanticChecker::checkWitnessProblem (ErrorReport & report, const AstProgram & program) static private
Definition at line 1109 of file AstSemanticChecker.cpp.
References souffle::AstAtom::addArgument(), souffle::ErrorReport::addError(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::usesInvalidWitness(), and souffle::visitDepthFirst().
Referenced by checkProgram(), and getName().
{
     // Visit each clause to check if an invalid aggregator witness is used
     visitDepthFirst(program, [&](const AstClause& clause) {
         // Body literals of the clause to check
         std::vector<AstLiteral*> bodyLiterals = clause.getBodyLiterals();
         // Add in all head variables as new ungrounded body literals
         auto headVariables = std::make_unique<AstAtom>("*");
         visitDepthFirst(*clause.getHead(), [&](const AstVariable& var) {
             headVariables->addArgument(std::unique_ptr<AstVariable>(var.clone()));
         });
         auto* headNegation = new AstNegation(std::move(headVariables));
         bodyLiterals.push_back(headNegation);
         // Perform the check
         std::set<std::unique_ptr<AstArgument>> groundedArguments;
         std::vector<SrcLocation> invalidArguments = usesInvalidWitness(bodyLiterals, groundedArguments);
         for (SrcLocation invalidArgument : invalidArguments) {
             report.addError(
                     "Witness problem: argument grounded by an aggregator's inner scope is used ungrounded in "
                     "outer scope",
                     invalidArgument);
         }
         delete headNegation;
     });
 }
getName()
std::string souffle::AstSemanticChecker::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 47 of file AstSemanticChecker.h.
References checkAggregator(), checkArgument(), checkAtom(), checkClause(), checkConstant(), checkFact(), checkInlining(), checkIO(), checkLiteral(), checkNamespaces(), checkProgram(), checkRecordType(), checkRecursiveUnionTypes(), checkRelation(), checkRelationDeclaration(), checkRules(), checkType(), checkTypes(), checkUnionType(), checkWitnessProblem(), isDependent(), relation, and transform().
{
         return "AstSemanticChecker";
     }
isDependent()
bool souffle::AstSemanticChecker::isDependent (const AstClause & agg1, const AstClause & agg2) static private
agg1, agg2 are clauses which contain no head, and consist of a single literal that contains an aggregate.
agg1 is dependent on agg2 if agg1 contains a variable which is grounded by agg2, and not by agg1.
Definition at line 484 of file AstSemanticChecker.cpp.
References souffle::getGroundedTerms(), and souffle::visitDepthFirst().
Referenced by checkAggregator(), and getName().
{
     auto groundedInAgg1 = getGroundedTerms(agg1);
     auto groundedInAgg2 = getGroundedTerms(agg2);
     bool dependent = false;
     // For each variable X in the first aggregate
     visitDepthFirst(agg1, [&](const AstVariable& searchVar) {
         // Try to find the corresponding variable X in the second aggregate
         // by string comparison
         const AstVariable* matchingVarPtr = nullptr;
         visitDepthFirst(agg2, [&](const AstVariable& var) {
             if (var == searchVar) {
                 matchingVarPtr = &var;
                 return;
             }
         });
         // If the variable occurs in both clauses (a match was found)
         if (matchingVarPtr != nullptr) {
             if (!groundedInAgg1[&searchVar] && groundedInAgg2[matchingVarPtr]) {
                 dependent = true;
             }
         }
     });
     return dependent;
 }
transform()
bool souffle::AstSemanticChecker::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 59 of file AstSemanticChecker.cpp.
References checkProgram().
Referenced by getName(), and souffle::AstExecutionPlanChecker::getName().
{
     checkProgram(translationUnit);
     return false;
 }
The documentation for this class was generated from the following files:
AstSemanticChecker.h
AstSemanticChecker.cpp