souffle: souffle::RamParallelIndexScan Class Reference
souffle::RamParallelIndexScan Class Reference
Search for tuples of a relation matching a criteria.
#include <RamOperation.h>
Public Member Functions
RamParallelIndexScan * clone () const override
Create a clone (i.e.
RamParallelIndexScan (std::unique_ptr< RamRelationReference > rel, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexScan
RamIndexScan (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamIndexOperation
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamExpression * > getRangePattern () const
Get range pattern.
RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamIndexOperation
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void printIndex (std::ostream &os) const
Helper method for printing.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Protected Attributes inherited from souffle::RamIndexOperation
std::vector< std::unique_ptr< RamExpression > > queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Detailed Description
Search for tuples of a relation matching a criteria.
For example:
QUERY
 ...
   PARALLEL FOR t1 IN X ON INDEX t1.c = t0.0
     ...
Definition at line 390 of file RamOperation.h.
Constructor & Destructor Documentation
RamParallelIndexScan()
souffle::RamParallelIndexScan::RamParallelIndexScan (std::unique_ptr< RamRelationReference > rel, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 392 of file RamOperation.h.
             : RamIndexScan(std::move(rel), ident, std::move(queryPattern), std::move(nested), profileText) {}
Member Function Documentation
clone()
RamParallelIndexScan* souffle::RamParallelIndexScan::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Reimplemented from souffle::RamIndexScan.
Definition at line 397 of file RamOperation.h.
References i.
{
         std::vector<std::unique_ptr<RamExpression>> resQueryPattern(queryPattern.size());
         for (unsigned int i = 0; i < queryPattern.size(); ++i) {
             resQueryPattern[i] = std::unique_ptr<RamExpression>(queryPattern[i]->clone());
         }
         return new RamParallelIndexScan(std::unique_ptr<RamRelationReference>(relationRef->clone()),
                 getTupleId(), std::move(resQueryPattern),
                 std::unique_ptr<RamOperation>(getOperation().clone()), getProfileText());
     }
print()
void souffle::RamParallelIndexScan::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Reimplemented from souffle::RamIndexScan.
Definition at line 408 of file RamOperation.h.
References souffle::RamRelation::getName(), souffle::getRelation(), souffle::RamNestedOperation::print(), and souffle::times().
{
         const RamRelation& rel = getRelation();
         os << times(" ", tabpos);
         os << "PARALLEL FOR t" << getTupleId() << " IN ";
         os << rel.getName();
         printIndex(os);
         os << std::endl;
         RamIndexOperation::print(os, tabpos + 1);
     }
The documentation for this class was generated from the following file:
RamOperation.h