souffle: souffle::ReadStream Class Reference
souffle::ReadStream Class Reference abstract
#include <ReadStream.h>
Public Member Functions
template<typename T >
void readAll (T &relation)
virtual ~ReadStream ()=default
Protected Member Functions
void consumeChar (const std::string &str, char c, size_t &pos)
Read past given character, consuming any preceding whitespace.
void consumeWhiteSpace (const std::string &str, size_t &pos)
Advance position in the string until first non-whitespace character.
virtual std::unique_ptr< RamDomain[]> readNextTuple ()=0
RamDomain readRecord (const std::string &source, const std::string &recordTypeName, size_t pos=0, size_t *charactersRead=nullptr)
Read a record from a string.
ReadStream (const std::map< std::string, std::string > &rwOperation, SymbolTable &symbolTable, RecordTable &recordTable)
RamDomain readStringInRecord (const std::string &source, const size_t pos, size_t *charactersRead)
Protected Attributes
size_t arity
size_t auxiliaryArity
RecordTable & recordTable
SymbolTable & symbolTable
std::vector< std::string > typeAttributes
Json types
Detailed Description
Definition at line 31 of file ReadStream.h.
Constructor & Destructor Documentation
ReadStream()
souffle::ReadStream::ReadStream (const std::map< std::string, std::string > & rwOperation, SymbolTable & symbolTable, RecordTable & recordTable) inline protected
Definition at line 33 of file ReadStream.h.
References arity, auxiliaryArity, i, json11::Json::long_value(), json11::Json::parse(), json11::Json::string_value(), typeAttributes, and types.
             : symbolTable(symbolTable), recordTable(recordTable) {
         const std::string& relationName{rwOperation.at("name")};
         std::string parseErrors;
         types = Json::parse(rwOperation.at("types"), parseErrors);
         assert(parseErrors.size() == 0 && "Internal JSON parsing failed.");
         arity = static_cast<size_t>(types[relationName]["arity"].long_value());
         auxiliaryArity = static_cast<size_t>(types[relationName]["auxArity"].long_value());
         for (size_t i = 0; i < arity + auxiliaryArity; ++i) {
             std::string type = types[relationName]["types"][i].string_value();
             typeAttributes.push_back(std::move(type));
         }
     }
~ReadStream()
virtual souffle::ReadStream::~ReadStream () virtual default
Referenced by readAll().
Member Function Documentation
consumeChar()
void souffle::ReadStream::consumeChar (const std::string & str, char c, size_t & pos) inline protected
Read past given character, consuming any preceding whitespace.
Definition at line 157 of file ReadStream.h.
References consumeWhiteSpace().
Referenced by readRecord().
{
         consumeWhiteSpace(str, pos);
         if (pos >= str.length()) {
             throw std::invalid_argument("Unexpected end of input in record");
         }
         if (str[pos] != c) {
             std::stringstream error;
             error << "Expected: \'" << c << "\', got: " << str[pos];
             throw std::invalid_argument(error.str());
         }
         ++pos;
     }
consumeWhiteSpace()
void souffle::ReadStream::consumeWhiteSpace (const std::string & str, size_t & pos) inline protected
Advance position in the string until first non-whitespace character.
Definition at line 173 of file ReadStream.h.
Referenced by consumeChar(), and readRecord().
{
         while (pos < str.length() && std::isspace(static_cast<unsigned char>(str[pos]))) {
             ++pos;
         }
     }
readAll()
template<typename T > void souffle::ReadStream::readAll (T & relation) inline
Definition at line 55 of file ReadStream.h.
References souffle::SymbolTable::acquireLock(), readNextTuple(), symbolTable, and ~ReadStream().
{
         auto lease = symbolTable.acquireLock();
         (void)lease;
         while (const auto next = readNextTuple()) {
             const RamDomain* ramDomain = next.get();
             relation.insert(ramDomain);
         }
     }
readNextTuple()
virtual std::unique_ptr<RamDomain[]> souffle::ReadStream::readNextTuple () protected pure virtual
Implemented in souffle::ReadFileCSV, souffle::ReadStreamCSV, and souffle::ReadStreamSQLite.
Referenced by readAll().
readRecord()
RamDomain souffle::ReadStream::readRecord (const std::string & source, const std::string & recordTypeName, size_t pos = 0, size_t * charactersRead = nullptr) inline protected
Read a record from a string.
Parameters
source - string containing a record
recordTypeName - record type. pos - start parsing from this position.
consumed - if not nullptr: number of characters read.
Definition at line 76 of file ReadStream.h.
References consumeChar(), consumeWhiteSpace(), i, json11::Json::is_null(), json11::Json::long_value(), souffle::RecordTable::pack(), souffle::ramBitCast(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), souffle::RamUnsignedFromString(), readStringInRecord(), recordTable, json11::Json::string_value(), and types.
Referenced by souffle::ReadStreamCSV::readNextTuple().
{
         const size_t initial_position = pos;
         Json recordInfo = types["records"][recordTypeName];
         // Check if record type information are present
         if (recordInfo.is_null()) {
             throw std::invalid_argument("Missing record type information: " + recordTypeName);
         }
         // Handle nil case
         consumeWhiteSpace(source, pos);
         if (source.substr(pos, 3) == "nil") {
             if (charactersRead != nullptr) {
                 *charactersRead = 3;
             }
             return 0;
         }
         const Json recordTypes = recordInfo["types"];
         const size_t recordArity = recordInfo["arity"].long_value();
         std::vector<RamDomain> recordValues(recordArity);
         consumeChar(source, '[', pos);
         for (size_t i = 0; i < recordArity; ++i) {
             const std::string& recordType = recordTypes[i].string_value();
             size_t consumed = 0;
             if (i > 0) {
                 consumeChar(source, ',', pos);
             }
             consumeWhiteSpace(source, pos);
             switch (recordType[0]) {
                 case 's':
                     recordValues[i] = readStringInRecord(source, pos, &consumed);
                     break;
                 case 'i':
                     recordValues[i] = RamSignedFromString(source.substr(pos), &consumed);
                     break;
                 case 'u':
                     recordValues[i] = ramBitCast(RamUnsignedFromString(source.substr(pos), &consumed));
                     break;
                 case 'f':
                     recordValues[i] = ramBitCast(RamFloatFromString(source.substr(pos), &consumed));
                     break;
                 case 'r':
                     recordValues[i] = readRecord(source, recordType, pos, &consumed);
                     break;
                 default:
                     assert(false && "Invalid type attribute");
             }
             pos += consumed;
         }
         consumeChar(source, ']', pos);
         if (charactersRead != nullptr) {
             *charactersRead = pos - initial_position;
         }
         return recordTable.pack(recordValues.data(), recordValues.size());
     }
readStringInRecord()
RamDomain souffle::ReadStream::readStringInRecord (const std::string & source, const size_t pos, size_t * charactersRead) inline protected
Definition at line 141 of file ReadStream.h.
References str, symbolTable, and souffle::SymbolTable::unsafeLookup().
Referenced by readRecord().
{
         size_t endOfSymbol = source.find_first_of(",]", pos);
         if (endOfSymbol == std::string::npos) {
             throw std::invalid_argument("Unexpected end of input in record");
         }
         *charactersRead = endOfSymbol - pos;
         std::string str = source.substr(pos, *charactersRead);
         return symbolTable.unsafeLookup(str);
     }
Field Documentation
arity
size_t souffle::ReadStream::arity protected
Definition at line 186 of file ReadStream.h.
Referenced by souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), ReadStream(), and souffle::ReadStreamCSV::ReadStreamCSV().
auxiliaryArity
size_t souffle::ReadStream::auxiliaryArity protected
Definition at line 187 of file ReadStream.h.
Referenced by souffle::ReadStreamSQLite::readNextTuple(), and ReadStream().
recordTable
RecordTable& souffle::ReadStream::recordTable protected
Definition at line 184 of file ReadStream.h.
Referenced by souffle::ReadSQLiteFactory::getReader(), souffle::ReadCinCSVFactory::getReader(), souffle::ReadFileCSVFactory::getReader(), and readRecord().
symbolTable
SymbolTable& souffle::ReadStream::symbolTable protected
Definition at line 183 of file ReadStream.h.
Referenced by souffle::ReadSQLiteFactory::getReader(), souffle::ReadCinCSVFactory::getReader(), souffle::ReadFileCSVFactory::getReader(), readAll(), souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), and readStringInRecord().
typeAttributes
std::vector<std::string> souffle::ReadStream::typeAttributes protected
Definition at line 182 of file ReadStream.h.
Referenced by souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), and ReadStream().
types
Json souffle::ReadStream::types protected
Definition at line 179 of file ReadStream.h.
Referenced by readRecord(), and ReadStream().
The documentation for this class was generated from the following file:
ReadStream.h