souffle: souffle::AstIO Class Reference
souffle::AstIO Class Reference
I/O operation has a type (input/output/printsize), qualified relation name, and I/O directives.
#include <AstIO.h>
Public Types
enum AstIOType { UndefinedIO, InputIO, OutputIO, PrintsizeIO }
Public Member Functions
void addDirective (const std::string &key, const std::string &value)
add new I/O directive
AstIO (const AstIO &io)
AstIO ()=default
AstIO * clone () const override
Create a clone (i.e.
const std::string & getDirective (const std::string &key) const
get value of I/O directive
const std::map< std::string, std::string > & getDirectives () const
get I/O-directive map
const AstQualifiedName & getQualifiedName () const
get relation name
AstIOType getType () const
get I/O type
bool hasDirective (const std::string &key) const
check for I/O directive
void setQualifiedName (const AstQualifiedName &name)
set relation name
void setType (AstIOType type)
set I/O type
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::map< std::string, std::string > directives
I/O directives.
AstQualifiedName name
relation name of I/O operation
AstIOType type = UndefinedIO
type of I/O operation
Detailed Description
I/O operation has a type (input/output/printsize), qualified relation name, and I/O directives.
Definition at line 31 of file AstIO.h.
Member Enumeration Documentation
AstIOType
enum souffle::AstIO::AstIOType
Enumerator
UndefinedIO
InputIO
OutputIO
PrintsizeIO
Definition at line 33 of file AstIO.h.
 { UndefinedIO, InputIO, OutputIO, PrintsizeIO };
Constructor & Destructor Documentation
AstIO() [1/2]
souffle::AstIO::AstIO (const AstIO & io) inline
Definition at line 35 of file AstIO.h.
References AstIO(), souffle::AstNode::getSrcLoc(), and souffle::AstNode::setSrcLoc().
                            : type(io.type), name(io.name), directives(io.directives) {
         this->setSrcLoc(io.getSrcLoc());
     }
AstIO() [2/2]
souffle::AstIO::AstIO () default
Referenced by AstIO(), and clone().
Member Function Documentation
addDirective()
void souffle::AstIO::addDirective (const std::string & key, const std::string & value) inline
add new I/O directive
Definition at line 66 of file AstIO.h.
References directives.
{
         directives[key] = value;
     }
clone()
AstIO* souffle::AstIO::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 80 of file AstIO.h.
References AstIO(), directives, souffle::AstNode::getSrcLoc(), name, and type.
{
         auto res = new AstIO();
         res->type = type;
         res->name = name;
         res->directives = directives;
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstIO::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 115 of file AstIO.h.
References directives, name, and type.
{
         const auto& other = static_cast<const AstIO&>(node);
         return other.type == type && other.name == name && other.directives == directives;
     }
getDirective()
const std::string& souffle::AstIO::getDirective (const std::string & key) const inline
get value of I/O directive
Definition at line 61 of file AstIO.h.
References directives.
{
         return directives.at(key);
     }
getDirectives()
const std::map<std::string, std::string>& souffle::AstIO::getDirectives () const inline
get I/O-directive map
Definition at line 76 of file AstIO.h.
References directives.
{
         return directives;
     }
getQualifiedName()
const AstQualifiedName& souffle::AstIO::getQualifiedName () const inline
get relation name
Definition at line 51 of file AstIO.h.
References name.
Referenced by souffle::IOType::run().
{
         return name;
     }
getType()
AstIOType souffle::AstIO::getType () const inline
get I/O type
Definition at line 41 of file AstIO.h.
References type.
Referenced by souffle::IOType::run().
{
         return type;
     }
hasDirective()
bool souffle::AstIO::hasDirective (const std::string & key) const inline
check for I/O directive
Definition at line 71 of file AstIO.h.
References directives.
{
         return directives.find(key) != directives.end();
     }
print()
void souffle::AstIO::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 90 of file AstIO.h.
References directives, InputIO, souffle::join(), name, OutputIO, PrintsizeIO, type, and UndefinedIO.
{
         switch (type) {
             case UndefinedIO:
                 os << ".undefined ";
                 break;
             case InputIO:
                 os << ".input ";
                 break;
             case OutputIO:
                 os << ".output ";
                 break;
             case PrintsizeIO:
                 os << ".printsize ";
                 break;
             default:
                 assert("Unknown I/O operation type");
         }
         os << name;
         if (!directives.empty()) {
             os << "(" << join(directives, ",", [](std::ostream& out, const auto& arg) {
                 out << arg.first << "=\"" << arg.second << "\"";
             }) << ")";
         }
     }
setQualifiedName()
void souffle::AstIO::setQualifiedName (const AstQualifiedName & name) inline
set relation name
Definition at line 56 of file AstIO.h.
References name.
{
         this->name = name;
     }
setType()
void souffle::AstIO::setType (AstIOType type) inline
set I/O type
Definition at line 46 of file AstIO.h.
References type.
{
         this->type = type;
     }
Field Documentation
directives
std::map<std::string, std::string> souffle::AstIO::directives protected
I/O directives.
Definition at line 127 of file AstIO.h.
Referenced by addDirective(), clone(), equal(), getDirective(), getDirectives(), hasDirective(), and print().
name
AstQualifiedName souffle::AstIO::name protected
relation name of I/O operation
Definition at line 124 of file AstIO.h.
Referenced by clone(), equal(), getQualifiedName(), print(), and setQualifiedName().
type
AstIOType souffle::AstIO::type = UndefinedIO protected
type of I/O operation
Definition at line 121 of file AstIO.h.
Referenced by clone(), equal(), getType(), print(), and setType().
The documentation for this class was generated from the following file:
AstIO.h