souffle: souffle::PolymorphicObjectsTransformer Class Reference
souffle::PolymorphicObjectsTransformer Class Reference
Transformation pass to determine instances of polymorphic object objects = Functors (plus, minus...) ∪ binary constraints (>, ≥ ...) ∪ aggregation ∪ numeric constants.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
Detailed Description
Transformation pass to determine instances of polymorphic object objects = Functors (plus, minus...) ∪ binary constraints (>, ≥ ...) ∪ aggregation ∪ numeric constants.
Definition at line 565 of file AstTransforms.h.
Member Function Documentation
getName()
std::string souffle::PolymorphicObjectsTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 567 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return "PolymorphicObjectsTransformer";
     }
transform()
bool souffle::PolymorphicObjectsTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 1253 of file AstTransforms.cpp.
References souffle::all_of(), souffle::AstProgram::apply(), souffle::convertOverloadedAggregator(), souffle::convertOverloadedConstraint(), souffle::convertOverloadedFunctor(), souffle::Float, souffle::AstNumericConstant::Float, souffle::AstTranslationUnit::getAnalysis(), souffle::AstTranslationUnit::getErrorReport(), souffle::AstTranslationUnit::getProgram(), souffle::TypeAnalysis::getTypes(), souffle::hasFloatType(), souffle::hasSignedType(), souffle::hasUnsignedType(), souffle::AstNumericConstant::Int, souffle::isFloatType(), souffle::isOverloaded(), souffle::isOverloadedAggregator(), souffle::isOverloadedFunctor(), souffle::isSymbolType(), souffle::isUnsignedType(), souffle::Symbol, types, souffle::AstNumericConstant::Uint, and souffle::Unsigned.
{
     struct TypeRewriter : public AstNodeMapper {
         mutable bool changed{false};
         const TypeAnalysis& typeAnalysis;
         ErrorReport& report;
         TypeRewriter(const TypeAnalysis& typeAnalysis, ErrorReport& report)
                 : typeAnalysis(typeAnalysis), report(report) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // Utility lambdas to determine if all args are of the same type.
             auto isFloat = [&](const AstArgument* argument) {
                 return isFloatType(typeAnalysis.getTypes(argument));
             };
             auto isUnsigned = [&](const AstArgument* argument) {
                 return isUnsignedType(typeAnalysis.getTypes(argument));
             };
             auto isSymbol = [&](const AstArgument* argument) {
                 return isSymbolType(typeAnalysis.getTypes(argument));
             };
             // rewrite sub-expressions first
             node->apply(*this);
             // It's possible that at this stage we get an undeclared clause.
             // In this case types can't be assigned to it, and the procedure getTypes can fail
             try {
                 // Handle numeric constant
                 if (auto* numericConstant = dynamic_cast<AstNumericConstant*>(node.get())) {
                     // Check if there is no value yet.
                     if (!numericConstant->getType().has_value()) {
                         TypeSet types = typeAnalysis.getTypes(numericConstant);
                         if (hasSignedType(types)) {
                             numericConstant->setType(AstNumericConstant::Type::Int);
                             changed = true;
                         } else if (hasUnsignedType(types)) {
                             numericConstant->setType(AstNumericConstant::Type::Uint);
                             changed = true;
                         } else if (hasFloatType(types)) {
                             numericConstant->setType(AstNumericConstant::Type::Float);
                             changed = true;
                         }
                     }
                 }
                 // Handle functor
                 if (auto* functor = dynamic_cast<AstIntrinsicFunctor*>(node.get())) {
                     if (isOverloadedFunctor(functor->getFunction())) {
                         auto attemptOverload = [&](TypeAttribute ty, auto& fn) {
                             // All args must be of the same type.
                             if (!all_of(functor->getArguments(), fn)) return false;
                             functor->setFunction(convertOverloadedFunctor(functor->getFunction(), ty));
                             return true;
                         };
                         if (attemptOverload(TypeAttribute::Float, isFloat) ||
                                 attemptOverload(TypeAttribute::Unsigned, isUnsigned) ||
                                 attemptOverload(TypeAttribute::Symbol, isSymbol)) {
                             changed = true;
                         }
                     }
                 }
                 // Handle binary constraint
                 if (auto* binaryConstraint = dynamic_cast<AstBinaryConstraint*>(node.get())) {
                     if (isOverloaded(binaryConstraint->getOperator())) {
                         // Get arguments
                         auto* leftArg = binaryConstraint->getLHS();
                         auto* rightArg = binaryConstraint->getRHS();
                         // Both args must be of the same type
                         if (isFloat(leftArg) && isFloat(rightArg)) {
                             BinaryConstraintOp convertedConstraint = convertOverloadedConstraint(
                                     binaryConstraint->getOperator(), TypeAttribute::Float);
                             binaryConstraint->setOperator(convertedConstraint);
                             changed = true;
                         } else if (isUnsigned(leftArg) && isUnsigned(rightArg)) {
                             BinaryConstraintOp convertedConstraint = convertOverloadedConstraint(
                                     binaryConstraint->getOperator(), TypeAttribute::Unsigned);
                             binaryConstraint->setOperator(convertedConstraint);
                             changed = true;
                         } else if (isSymbol(leftArg) && isSymbol(rightArg)) {
                             BinaryConstraintOp convertedConstraint = convertOverloadedConstraint(
                                     binaryConstraint->getOperator(), TypeAttribute::Symbol);
                             binaryConstraint->setOperator(convertedConstraint);
                             changed = true;
                         }
                     }
                 }
                 if (auto* aggregator = dynamic_cast<AstAggregator*>(node.get())) {
                     if (isOverloadedAggregator(aggregator->getOperator())) {
                         auto* targetExpression = aggregator->getTargetExpression();
                         if (isFloat(targetExpression)) {
                             AggregateOp convertedOperator = convertOverloadedAggregator(
                                     aggregator->getOperator(), TypeAttribute::Float);
                             aggregator->setOperator(convertedOperator);
                             changed = true;
                         } else if (isUnsigned(targetExpression)) {
                             AggregateOp convertedOperator = convertOverloadedAggregator(
                                     aggregator->getOperator(), TypeAttribute::Unsigned);
                             aggregator->setOperator(convertedOperator);
                             changed = true;
                         }
                     }
                 }
             } catch (std::out_of_range&) {
                 // No types to convert in undeclared clauses
             }
             return node;
         }
     };
     const TypeAnalysis& typeAnalysis = *translationUnit.getAnalysis<TypeAnalysis>();
     TypeRewriter update(typeAnalysis, translationUnit.getErrorReport());
     translationUnit.getProgram()->apply(update);
     return update.changed;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
AstTransforms.cpp