souffle: souffle::AstTranslator::ClauseTranslator Class Reference
souffle::AstTranslator::ClauseTranslator Class Reference
translate AST clause to RAM code
Public Member Functions
ClauseTranslator (AstTranslator &translator)
std::unique_ptr< RamStatement > translateClause (const AstClause &clause, const AstClause &originalClause, const int version=0)
generate RAM code for a clause
Protected Member Functions
virtual std::unique_ptr< RamCondition > createCondition (const AstClause &originalClause)
virtual std::unique_ptr< RamOperation > createOperation (const AstClause &clause)
std::unique_ptr< RamOperation > filterByConstraints (size_t level, const std::vector< AstArgument *> &args, std::unique_ptr< RamOperation > op, bool constrainByFunctors=true)
translate RAM code for a constant value
Protected Attributes
const AuxiliaryArity * auxArityAnalysis
int level = 0
AstTranslator & translator
ValueIndex valueIndex
Private Types
using arg_list = std::vector< AstArgument * >
Private Member Functions
void createValueIndex (const AstClause &clause)
index values in rule
arg_list * getArgList (const AstNode *curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> &nodeArgs) const
std::unique_ptr< AstClause > getReorderedClause (const AstClause &clause, const int version) const
void indexValues (const AstNode *curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> &nodeArgs, std::map< const arg_list *, int > &arg_level, RamRelationReference *relation)
Private Attributes
std::vector< const AstAggregator * > aggregators
std::vector< const AstNode * > op_nesting
Detailed Description
translate AST clause to RAM code
Definition at line 337 of file AstTranslator.h.
Member Typedef Documentation
arg_list
using souffle::AstTranslator::ClauseTranslator::arg_list = std::vector<AstArgument*> private
Definition at line 339 of file AstTranslator.h.
Constructor & Destructor Documentation
ClauseTranslator()
souffle::AstTranslator::ClauseTranslator::ClauseTranslator (AstTranslator & translator) inline
Definition at line 376 of file AstTranslator.h.
                 : translator(translator), auxArityAnalysis(translator.auxArityAnalysis) {}
Member Function Documentation
createCondition()
std::unique_ptr< RamCondition > souffle::AstTranslator::ClauseTranslator::createCondition (const AstClause & originalClause) protected virtual
Reimplemented in souffle::AstTranslator::ProvenanceClauseTranslator.
Definition at line 656 of file AstTranslator.cpp.
References souffle::AstClause::getHead().
{
     const auto head = originalClause.getHead();
     // add stopping criteria for nullary relations
     // (if it contains already the null tuple, don't re-compute)
     if (head->getArity() == 0) {
         return std::make_unique<RamEmptinessCheck>(translator.translateRelation(head));
     }
     return nullptr;
 }
createOperation()
std::unique_ptr< RamOperation > souffle::AstTranslator::ClauseTranslator::createOperation (const AstClause & clause) protected virtual
Reimplemented in souffle::AstTranslator::ProvenanceClauseTranslator.
Definition at line 575 of file AstTranslator.cpp.
References souffle::Global::config(), souffle::AstAtom::getArity(), souffle::AstClause::getHead(), i, and souffle::visitDepthFirst().
{
     const auto head = clause.getHead();
     std::vector<std::unique_ptr<RamExpression>> values;
     for (AstArgument* arg : head->getArguments()) {
         values.push_back(translator.translateValue(arg, valueIndex));
     }
     std::unique_ptr<RamOperation> project =
             std::make_unique<RamProject>(translator.translateRelation(head), std::move(values));
     if (head->getArity() == 0) {
         project = std::make_unique<RamFilter>(
                 std::make_unique<RamEmptinessCheck>(translator.translateRelation(head)), std::move(project));
     }
     // check existence for original tuple if we have provenance
     // only if we don't compile
     if (Global::config().has("provenance") &&
             ((!Global::config().has("compile") && !Global::config().has("dl-program") &&
                     !Global::config().has("generate")))) {
         size_t auxiliaryArity = translator.getEvaluationArity(head);
         auto arity = head->getArity() - auxiliaryArity;
         std::vector<std::unique_ptr<RamExpression>> values;
         bool isVolatile = true;
         auto args = head->getArguments();
         // add args for original tuple
         for (size_t i = 0; i < arity; i++) {
             auto arg = args[i];
             // don't add counters
             visitDepthFirst(*arg, [&](const AstCounter&) { isVolatile = false; });
             values.push_back(translator.translateValue(arg, valueIndex));
         }
         for (size_t i = 0; i < auxiliaryArity; i++) {
             values.push_back(std::make_unique<RamUndefValue>());
         }
         if (isVolatile) {
             return std::make_unique<RamFilter>(
                     std::make_unique<RamNegation>(std::make_unique<RamExistenceCheck>(
                             translator.translateRelation(head), std::move(values))),
                     std::move(project));
         }
     }
     // build up insertion call
     return project;  // start with innermost
 }
createValueIndex()
void souffle::AstTranslator::ClauseTranslator::createValueIndex (const AstClause & clause) private
index values in rule
Definition at line 534 of file AstTranslator.cpp.
References souffle::any_of(), souffle::AstAtom::getArguments(), souffle::AstAggregator::getBodyLiterals(), and souffle::visitDepthFirstPostOrder().
{
     for (const auto* atom : getBodyLiterals<AstAtom>(clause)) {
         // std::map<const arg_list*, int> arg_level;
         std::map<const AstNode*, std::unique_ptr<arg_list>> nodeArgs;
         std::map<const arg_list*, int> arg_level;
         nodeArgs[atom] = std::make_unique<arg_list>(atom->getArguments());
         // the atom is obtained at the current level
         // increment nesting level for the atom
         arg_level[nodeArgs[atom].get()] = level++;
         op_nesting.push_back(atom);
         indexValues(atom, nodeArgs, arg_level, translator.translateRelation(atom).get());
     }
     // add aggregation functions
     visitDepthFirstPostOrder(clause, [&](const AstAggregator& cur) {
         // add each aggregator expression only once
         if (any_of(aggregators, [&](const AstAggregator* agg) { return *agg == cur; })) {
             return;
         }
         int aggLoc = level++;
         valueIndex.setAggregatorLocation(cur, Location({aggLoc, 0}));
         // bind aggregator variables to locations
         assert(nullptr != dynamic_cast<const AstAtom*>(cur.getBodyLiterals()[0]));
         const AstAtom& atom = static_cast<const AstAtom&>(*cur.getBodyLiterals()[0]);
         size_t pos = 0;
         for (auto arg : atom.getArguments()) {
             if (const auto* var = dynamic_cast<const AstVariable*>(arg)) {
                 valueIndex.addVarReference(*var, aggLoc, (int)pos, translator.translateRelation(&atom));
             }
             ++pos;
         };
         // and remember aggregator
         aggregators.push_back(&cur);
     });
 }
filterByConstraints()
std::unique_ptr< RamOperation > souffle::AstTranslator::ClauseTranslator::filterByConstraints (size_t level, const std::vector< AstArgument *> & args, std::unique_ptr< RamOperation > op, bool constrainByFunctors = true) protected
translate RAM code for a constant value
Definition at line 673 of file AstTranslator.cpp.
References souffle::EQ, souffle::FEQ, souffle::Float, souffle::AstNumericConstant::Float, and rhs.
{
     size_t pos = 0;
     auto mkFilter = [&](bool isFloatArg, std::unique_ptr<RamExpression> rhs) {
         return std::make_unique<RamFilter>(
                 std::make_unique<RamConstraint>(isFloatArg ? BinaryConstraintOp::FEQ : BinaryConstraintOp::EQ,
                         std::make_unique<RamTupleElement>(level, pos), std::move(rhs)),
                 std::move(op));
     };
     for (auto* a : args) {
         if (auto* c = dynamic_cast<const AstConstant*>(a)) {
             auto* const c_num = dynamic_cast<const AstNumericConstant*>(c);
             assert((!c_num || c_num->getType()) && "numeric constant wasn't bound to a type");
             op = mkFilter(c_num && *c_num->getType() == AstNumericConstant::Type::Float,
                     translator.translateConstant(*c));
         } else if (auto* func = dynamic_cast<const AstFunctor*>(a)) {
             if (constrainByFunctors) {
                 op = mkFilter(func->getReturnType() == TypeAttribute::Float,
                         translator.translateValue(func, valueIndex));
             }
         }
         ++pos;
     }
     return op;
 }
getArgList()
AstTranslator::ClauseTranslator::arg_list * souffle::AstTranslator::ClauseTranslator::getArgList (const AstNode * curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> & nodeArgs) const private
Definition at line 486 of file AstTranslator.cpp.
{
     if (nodeArgs.count(curNode) == 0u) {
         if (auto rec = dynamic_cast<const AstRecordInit*>(curNode)) {
             nodeArgs[curNode] = std::make_unique<arg_list>(rec->getArguments());
         } else if (auto atom = dynamic_cast<const AstAtom*>(curNode)) {
             nodeArgs[curNode] = std::make_unique<arg_list>(atom->getArguments());
         } else {
             assert(false && "node type doesn't have arguments!");
         }
     }
     return nodeArgs[curNode].get();
 }
getReorderedClause()
std::unique_ptr< AstClause > souffle::AstTranslator::ClauseTranslator::getReorderedClause (const AstClause & clause, const int version) const private
Definition at line 453 of file AstTranslator.cpp.
References souffle::AstClause::clone(), souffle::AstClause::getExecutionPlan(), souffle::AstExecutionPlan::getOrders(), i, and souffle::reorderAtoms().
{
     const auto plan = clause.getExecutionPlan();
     // check whether there is an imposed order constraint
     if (plan == nullptr) {
         return nullptr;
     }
     auto orders = plan->getOrders();
     if (orders.find(version) == orders.end()) {
         return nullptr;
     }
     // get the imposed order
     const auto& order = orders[version];
     // create a copy and fix order
     std::unique_ptr<AstClause> reorderedClause(clause.clone());
     // Change order to start at zero
     std::vector<unsigned int> newOrder(order->getOrder().size());
     std::transform(order->getOrder().begin(), order->getOrder().end(), newOrder.begin(),
             [](unsigned int i) -> unsigned int { return i - 1; });
     // re-order atoms
     reorderedClause.reset(reorderAtoms(reorderedClause.get(), newOrder));
     // clear other order and fix plan
     reorderedClause->clearExecutionPlan();
     return reorderedClause;
 }
indexValues()
void souffle::AstTranslator::ClauseTranslator::indexValues (const AstNode * curNode, std::map< const AstNode *, std::unique_ptr< arg_list >> & nodeArgs, std::map< const arg_list *, int > & arg_level, RamRelationReference * relation) private
Definition at line 500 of file AstTranslator.cpp.
References souffle::RamRelationReference::clone().
{
     arg_list* cur = getArgList(curNode, nodeArgs);
     for (size_t pos = 0; pos < cur->size(); ++pos) {
         // get argument
         auto& arg = (*cur)[pos];
         // check for variable references
         if (auto var = dynamic_cast<const AstVariable*>(arg)) {
             if (pos < relation->get()->getArity()) {
                 valueIndex.addVarReference(
                         *var, arg_level[cur], pos, std::unique_ptr<RamRelationReference>(relation->clone()));
             } else {
                 valueIndex.addVarReference(*var, arg_level[cur], pos);
             }
         }
         // check for nested records
         if (auto rec = dynamic_cast<const AstRecordInit*>(arg)) {
             // introduce new nesting level for unpack
             op_nesting.push_back(rec);
             arg_level[getArgList(rec, nodeArgs)] = level++;
             // register location of record
             valueIndex.setRecordDefinition(*rec, arg_level[cur], pos);
             // resolve nested components
             indexValues(rec, nodeArgs, arg_level, relation);
         }
     }
 }
translateClause()
std::unique_ptr< RamStatement > souffle::AstTranslator::ClauseTranslator::translateClause (const AstClause & clause, const AstClause & originalClause, const int version = 0)
generate RAM code for a clause
Definition at line 704 of file AstTranslator.cpp.
References souffle::Global::config(), souffle::EQ, souffle::AstAtom::getArguments(), souffle::AstAtom::getArity(), souffle::AstClause::getBodyLiterals(), souffle::AstAggregator::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstAggregator::getOperator(), souffle::AstAtom::getQualifiedName(), souffle::AstAggregator::getTargetExpression(), souffle::AstTranslator::Location::identifier, souffle::isFact(), souffle::isRamUndefValue(), souffle::isRule(), souffle::AstTranslator::makeRamTupleElement(), souffle::profile::ss, souffle::stringify(), and souffle::toString().
Referenced by souffle::AstTranslator::makeSubproofSubroutine(), souffle::AstTranslator::translateNonRecursiveRelation(), and souffle::AstTranslator::translateRecursiveRelation().
{
     if (auto reorderedClause = getReorderedClause(clause, version)) {
         // translate reordered clause
         return translateClause(*reorderedClause, originalClause, version);
     }
     // get extract some details
     const AstAtom* head = clause.getHead();
     // handle facts
     if (isFact(clause)) {
         // translate arguments
         std::vector<std::unique_ptr<RamExpression>> values;
         for (auto& arg : head->getArguments()) {
             values.push_back(translator.translateValue(arg, ValueIndex()));
         }
         // create a fact statement
         return std::make_unique<RamQuery>(
                 std::make_unique<RamProject>(translator.translateRelation(head), std::move(values)));
     }
     // the rest should be rules
     assert(isRule(clause));
     createValueIndex(clause);
     // -- create RAM statement --
     std::unique_ptr<RamOperation> op = createOperation(clause);
     /* add equivalence constraints imposed by variable binding */
     for (const auto& cur : valueIndex.getVariableReferences()) {
         // the first appearance
         const Location& first = *cur.second.begin();
         // all other appearances
         for (const Location& loc : cur.second) {
             if (first != loc && !valueIndex.isAggregator(loc.identifier)) {
                 // FIXME: equiv' for float types (`FEQ`)
                 op = std::make_unique<RamFilter>(
                         std::make_unique<RamConstraint>(
                                 BinaryConstraintOp::EQ, makeRamTupleElement(first), makeRamTupleElement(loc)),
                         std::move(op));
             }
         }
     }
     /* add conditions caused by atoms, negations, and binary relations */
     for (const auto& lit : clause.getBodyLiterals()) {
         if (auto condition = translator.translateConstraint(lit, valueIndex)) {
             op = std::make_unique<RamFilter>(std::move(condition), std::move(op));
         }
     }
     // add aggregator conditions
     size_t curLevel = op_nesting.size() - 1;
     for (auto it = op_nesting.rbegin(); it != op_nesting.rend(); ++it, --curLevel) {
         const AstNode* cur = *it;
         if (const auto* atom = dynamic_cast<const AstAtom*>(cur)) {
             // add constraints
             size_t pos = 0;
             for (auto arg : atom->getArguments()) {
                 if (auto* agg = dynamic_cast<AstAggregator*>(arg)) {
                     auto loc = valueIndex.getAggregatorLocation(*agg);
                     // FIXME: equiv' for float types (`FEQ`)
                     op = std::make_unique<RamFilter>(std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                                              std::make_unique<RamTupleElement>(curLevel, pos),
                                                              makeRamTupleElement(loc)),
                             std::move(op));
                 }
                 ++pos;
             }
         }
     }
     // add aggregator levels
     --level;
     for (auto it = aggregators.rbegin(); it != aggregators.rend(); ++it, --level) {
         const AstAggregator* cur = *it;
         // condition for aggregate and helper function to add terms
         std::unique_ptr<RamCondition> aggCondition;
         auto addAggCondition = [&](std::unique_ptr<RamCondition>& arg) {
             if (aggCondition == nullptr) {
                 aggCondition = std::move(arg);
             } else {
                 aggCondition = std::make_unique<RamConjunction>(std::move(aggCondition), std::move(arg));
             }
         };
         // translate constraints of sub-clause
         for (const auto& lit : cur->getBodyLiterals()) {
             if (auto newCondition = translator.translateConstraint(lit, valueIndex)) {
                 addAggCondition(newCondition);
             }
         }
         // get the first predicate of the sub-clause
         // NB: at most one atom is permitted in a sub-clause
         const AstAtom* atom = nullptr;
         for (const auto& lit : cur->getBodyLiterals()) {
             if (atom == nullptr) {
                 atom = dynamic_cast<const AstAtom*>(lit);
             } else {
                 assert(dynamic_cast<const AstAtom*>(lit) != nullptr &&
                         "Unsupported complex aggregation body encountered!");
             }
         }
         // translate arguments's of atom (if exists) to conditions
         if (atom != nullptr) {
             size_t pos = 0;
             for (auto arg : atom->getArguments()) {
                 // variable bindings are issued differently since we don't want self
                 // referential variable bindings
                 if (const auto* var = dynamic_cast<const AstVariable*>(arg)) {
                     for (const Location& loc :
                             valueIndex.getVariableReferences().find(var->getName())->second) {
                         if (level != loc.identifier || (int)pos != loc.element) {
                             // FIXME: equiv' for float types (`FEQ`)
                             std::unique_ptr<RamCondition> newCondition = std::make_unique<RamConstraint>(
                                     BinaryConstraintOp::EQ, makeRamTupleElement(loc),
                                     std::make_unique<RamTupleElement>(level, pos));
                             addAggCondition(newCondition);
                             break;
                         }
                     }
                 } else if (arg != nullptr) {
                     std::unique_ptr<RamExpression> value = translator.translateValue(arg, valueIndex);
                     if (value != nullptr && !isRamUndefValue(value.get())) {
                         // FIXME: equiv' for float types (`FEQ`)
                         std::unique_ptr<RamCondition> newCondition =
                                 std::make_unique<RamConstraint>(BinaryConstraintOp::EQ,
                                         std::make_unique<RamTupleElement>(level, pos), std::move(value));
                         addAggCondition(newCondition);
                     }
                 }
                 ++pos;
             }
         }
         // translate aggregate expression
         std::unique_ptr<RamExpression> expr =
                 translator.translateValue(cur->getTargetExpression(), valueIndex);
         if (expr == nullptr) {
             expr = std::make_unique<RamUndefValue>();
         }
         if (aggCondition == nullptr) {
             aggCondition = std::make_unique<RamTrue>();
         }
         // add Ram-Aggregation layer
         std::unique_ptr<RamAggregate> aggregate =
                 std::make_unique<RamAggregate>(std::move(op), cur->getOperator(),
                         translator.translateRelation(atom), std::move(expr), std::move(aggCondition), level);
         op = std::move(aggregate);
     }
     // build operation bottom-up
     while (!op_nesting.empty()) {
         // get next operator
         const AstNode* cur = op_nesting.back();
         op_nesting.pop_back();
         // get current nesting level
         auto level = op_nesting.size();
         if (const auto* atom = dynamic_cast<const AstAtom*>(cur)) {
             // add constraints
             // TODO: do we wish to enable constraints by header functor? record inits do so...
             op = filterByConstraints(level, atom->getArguments(), std::move(op), false);
             // check whether all arguments are unnamed variables
             bool isAllArgsUnnamed = true;
             for (auto* argument : atom->getArguments()) {
                 if (dynamic_cast<AstUnnamedVariable*>(argument) == nullptr) {
                     isAllArgsUnnamed = false;
                 }
             }
             // add check for emptiness for an atom
             op = std::make_unique<RamFilter>(
                     std::make_unique<RamNegation>(
                             std::make_unique<RamEmptinessCheck>(translator.translateRelation(atom))),
                     std::move(op));
             // add a scan level
             if (atom->getArity() != 0 && !isAllArgsUnnamed) {
                 if (head->getArity() == 0) {
                     op = std::make_unique<RamBreak>(
                             std::make_unique<RamNegation>(
                                     std::make_unique<RamEmptinessCheck>(translator.translateRelation(head))),
                             std::move(op));
                 }
                 if (Global::config().has("profile")) {
                     std::stringstream ss;
                     ss << head->getQualifiedName();
                     ss.str("");
                     ss << "@frequency-atom" << ';';
                     ss << originalClause.getHead()->getQualifiedName() << ';';
                     ss << version << ';';
                     ss << stringify(toString(clause)) << ';';
                     ss << stringify(toString(*atom)) << ';';
                     ss << stringify(toString(originalClause)) << ';';
                     ss << level << ';';
                     op = std::make_unique<RamScan>(
                             translator.translateRelation(atom), level, std::move(op), ss.str());
                 } else {
                     op = std::make_unique<RamScan>(translator.translateRelation(atom), level, std::move(op));
                 }
             }
             // TODO: support constants in nested records!
         } else if (const auto* rec = dynamic_cast<const AstRecordInit*>(cur)) {
             // add constant constraints
             op = filterByConstraints(level, rec->getArguments(), std::move(op));
             // add an unpack level
             const Location& loc = valueIndex.getDefinitionPoint(*rec);
             op = std::make_unique<RamUnpackRecord>(
                     std::move(op), level, makeRamTupleElement(loc), rec->getArguments().size());
         } else {
             assert(false && "Unsupported AST node for creation of scan-level!");
         }
     }
     /* generate the final RAM Insert statement */
     std::unique_ptr<RamCondition> cond = createCondition(originalClause);
     if (cond != nullptr) {
         return std::make_unique<RamQuery>(std::make_unique<RamFilter>(std::move(cond), std::move(op)));
     } else {
         return std::make_unique<RamQuery>(std::move(op));
     }
 }
Field Documentation
aggregators
std::vector<const AstAggregator*> souffle::AstTranslator::ClauseTranslator::aggregators private
Definition at line 341 of file AstTranslator.h.
auxArityAnalysis
const AuxiliaryArity* souffle::AstTranslator::ClauseTranslator::auxArityAnalysis protected
Definition at line 373 of file AstTranslator.h.
level
int souffle::AstTranslator::ClauseTranslator::level = 0 protected
Definition at line 364 of file AstTranslator.h.
op_nesting
std::vector<const AstNode*> souffle::AstTranslator::ClauseTranslator::op_nesting private
Definition at line 344 of file AstTranslator.h.
translator
AstTranslator& souffle::AstTranslator::ClauseTranslator::translator protected
Definition at line 358 of file AstTranslator.h.
valueIndex
ValueIndex souffle::AstTranslator::ClauseTranslator::valueIndex protected
Definition at line 361 of file AstTranslator.h.
The documentation for this class was generated from the following files:
AstTranslator.h
AstTranslator.cpp