souffle: souffle::SouffleProgram Class Reference
souffle::SouffleProgram Class Reference abstract
Abstract base class for generated Datalog programs.
#include <SouffleInterface.h>
Data Structures
struct tuple_insert
Helper function for the wrapper function Relation::insert() and Relation::contains().
struct tuple_insert< Tuple, 1 >
Helper function for the wrapper function Relation::insert() and Relation::contains() for the first element of the tuple.
Public Member Functions
template<typename... Args>
bool contains (const std::tuple< Args... > &t, Relation *relation)
Contains function with std::tuple as input (wrapper)
virtual void dumpInputs (std::ostream &out=std::cout)=0
Output all the input relations in stdout, without generating any files.
virtual void dumpOutputs (std::ostream &out=std::cout)=0
Output all the output relations in stdout, without generating any files.
virtual void executeSubroutine (std::string, const std::vector< RamDomain > &, std::vector< RamDomain > &)
Execute a subroutine.
std::vector< Relation * > getAllRelations () const
Getter of allRelations, which this vector structure contains all relations.
std::vector< Relation * > getInputRelations () const
Getter of inputRelations, which this vector structure contains all input relations.
std::vector< Relation * > getInternalRelations () const
Getter of internalRelations, which this vector structure contains all relations that are neither an input relation or an output relation.
std::size_t getNumThreads ()
Get the number of threads to be used.
std::vector< Relation * > getOutputRelations () const
Getter of outputRelations, which this vector structure contains all output relations.
Relation * getRelation (const std::string &name) const
Get Relation by its name from relationMap, if relation not found, return a nullptr.
std::string getRelationName (const std::string &name) const
Return the name of the target relation from relationMap.
std::size_t getRelationSize (const std::string &name) const
Return the size of the target relation from relationMap.
virtual SymbolTable & getSymbolTable ()=0
Get the symbol table of the program.
template<typename... Args>
void insert (const std::tuple< Args... > &t, Relation *relation)
Insert function with std::tuple as input (wrapper)
virtual void loadAll (std::string inputDirectory=".")=0
Read all input relations from the given directory.
virtual void printAll (std::string outputDirectory=".")=0
Store all output relations individually in .CSV file in the given directory, with the relation name as the file name of the .CSV file.
void purgeInputRelations ()
Remove all the tuples from the inputRelations, calling the purge method of each.
void purgeInternalRelations ()
Remove all the tuples from the internalRelations, calling the purge method of each.
void purgeOutputRelations ()
Remove all the tuples from the outputRelations, calling the purge method of each.
virtual void run ()
Execute the souffle program, without any loads or stores.
virtual void runAll (std::string inputDirectory=".", std::string outputDirectory=".")=0
Execute program, loading inputs and storing outputs as required.
void setNumThreads (std::size_t numThreadsValue)
Set the number of threads to be used.
virtual ~SouffleProgram ()=default
Destructor.
Protected Member Functions
void addRelation (const std::string &name, Relation *rel, bool isInput, bool isOutput)
Add the relation to relationMap (with its name) and allRelations, depends on the properties of the relation, if the relation is an input relation, it will be added to inputRelations, else if the relation is an output relation, it will be added to outputRelations, otherwise will add to internalRelations.
Private Attributes
std::vector< Relation * > allRelations
allRelations store all the relation in a vector.
std::vector< Relation * > inputRelations
inputRelations stores all the input relation in a vector.
std::vector< Relation * > internalRelations
internalRelation stores all the relation in a vector that are neither an input or an output.
std::size_t numThreads = 1
std::vector< Relation * > outputRelations
outputRelations stores all the output relation in a vector.
std::map< std::string, Relation * > relationMap
Define a relation map for external access, when getRelation(name) is called, the relation with the given name will be returned from this map, relationMap stores all the relations in a map with its name as the key and relation as the value.
Detailed Description
Abstract base class for generated Datalog programs.
Definition at line 653 of file SouffleInterface.h.
Constructor & Destructor Documentation
~SouffleProgram()
virtual souffle::SouffleProgram::~SouffleProgram () virtual default
Destructor.
Destructor of SouffleProgram.
Member Function Documentation
addRelation()
void souffle::SouffleProgram::addRelation (const std::string & name, Relation * rel, bool isInput, bool isOutput) inline protected
Add the relation to relationMap (with its name) and allRelations, depends on the properties of the relation, if the relation is an input relation, it will be added to inputRelations, else if the relation is an output relation, it will be added to outputRelations, otherwise will add to internalRelations.
(a relation could be both input and output at the same time.)
Parameters
name the name of the relation (std::string)
rel a pointer to the relation (std::string)
isInput a bool argument, true if the relation is a input relation, else false (bool)
isOnput a bool argument, true if the relation is a ouput relation, else false (bool)
Definition at line 696 of file SouffleInterface.h.
{
         relationMap[name] = rel;
         allRelations.push_back(rel);
         if (isInput) {
             inputRelations.push_back(rel);
         }
         if (isOutput) {
             outputRelations.push_back(rel);
         }
         if (!isInput && !isOutput) {
             internalRelations.push_back(rel);
         }
     }
contains()
template<typename... Args> bool souffle::SouffleProgram::contains (const std::tuple< Args... > & t, Relation * relation) inline
Contains function with std::tuple as input (wrapper)
Parameters
t The existence searching tuple (std::tuple)
relation The relation that perform contains operation (Relation*)
Returns
A boolean value, return true if the tuple found, otherwise return false
See also
Relation::contains()
Definition at line 942 of file SouffleInterface.h.
References souffle::Relation::contains().
{
         tuple t1(relation);
         tuple_insert<decltype(t), sizeof...(Args)>::add(t, t1);
         return relation->contains(t1);
     }
dumpInputs()
virtual void souffle::SouffleProgram::dumpInputs (std::ostream & out = std::cout) pure virtual
Output all the input relations in stdout, without generating any files.
(for debug purposes).
Implemented in souffle::InterpreterProgInterface.
Referenced by SWIGSouffleProgram::dumpInputs().
dumpOutputs()
virtual void souffle::SouffleProgram::dumpOutputs (std::ostream & out = std::cout) pure virtual
Output all the output relations in stdout, without generating any files.
(for debug purposes).
Implemented in souffle::InterpreterProgInterface.
Referenced by SWIGSouffleProgram::dumpOutputs().
executeSubroutine()
virtual void souffle::SouffleProgram::executeSubroutine (std::string , const std::vector< RamDomain > & , std::vector< RamDomain > &) inline virtual
Execute a subroutine.
Parameters
name Name of a subroutine (std:string)
arg Arguments of the subroutine (std::vector<RamDomain>&)
ret Return values of the subroutine (std::vector<RamDomain>&)
Reimplemented in souffle::InterpreterProgInterface.
Definition at line 856 of file SouffleInterface.h.
References souffle::Relation::getSymbolTable().
Referenced by souffle::ExplainProvenanceImpl::explain(), and souffle::ExplainProvenanceImpl::explainNegation().
                                      {}
getAllRelations()
std::vector<Relation*> souffle::SouffleProgram::getAllRelations () const inline
Getter of allRelations, which this vector structure contains all relations.
Returns
allRelations (std::vector)
See also
allRelations
Definition at line 846 of file SouffleInterface.h.
Referenced by souffle::ExplainProvenanceImpl::setup().
{
         return allRelations;
     }
getInputRelations()
std::vector<Relation*> souffle::SouffleProgram::getInputRelations () const inline
Getter of inputRelations, which this vector structure contains all input relations.
Returns
intputRelations (std::vector)
See also
inputRelations
Definition at line 825 of file SouffleInterface.h.
{
         return inputRelations;
     }
getInternalRelations()
std::vector<Relation*> souffle::SouffleProgram::getInternalRelations () const inline
Getter of internalRelations, which this vector structure contains all relations that are neither an input relation or an output relation.
Returns
internalRelations (std::vector)
See also
internalRelations
Definition at line 836 of file SouffleInterface.h.
{
         return internalRelations;
     }
getNumThreads()
std::size_t souffle::SouffleProgram::getNumThreads () inline
Get the number of threads to be used.
Definition at line 770 of file SouffleInterface.h.
{
         return numThreads;
     }
getOutputRelations()
std::vector<Relation*> souffle::SouffleProgram::getOutputRelations () const inline
Getter of outputRelations, which this vector structure contains all output relations.
Returns
outputRelations (std::vector)
See also
outputRelations
Definition at line 815 of file SouffleInterface.h.
{
         return outputRelations;
     }
getRelation()
Relation* souffle::SouffleProgram::getRelation (const std::string & name) const inline
Get Relation by its name from relationMap, if relation not found, return a nullptr.
Parameters
name The name of the target relation (const std::string)
Returns
The pointer of the target relation, or null pointer if the relation not found (Relation*)
Definition at line 780 of file SouffleInterface.h.
Referenced by souffle::ExplainProvenance::argsToNums(), souffle::ExplainProvenance::decodeArguments(), souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainSubproof(), souffle::ExplainProvenanceImpl::findTuple(), souffle::ExplainProvenanceImpl::measureRelation(), and souffle::ExplainProvenanceImpl::queryProcess().
{
         auto it = relationMap.find(name);
         if (it != relationMap.end()) {
             return (*it).second;
         } else {
             return nullptr;
         }
     };
getRelationName()
std::string souffle::SouffleProgram::getRelationName (const std::string & name) const inline
Return the name of the target relation from relationMap.
Parameters
name The name of the target relation (const std::string)
Returns
The name of the target relation (std::string)
Definition at line 805 of file SouffleInterface.h.
References souffle::getRelation().
{
         return getRelation(name)->getName();
     }
getRelationSize()
std::size_t souffle::SouffleProgram::getRelationSize (const std::string & name) const inline
Return the size of the target relation from relationMap.
Parameters
name The name of the target relation (const std::string)
Returns
The size of the target relation (std::size_t)
Definition at line 795 of file SouffleInterface.h.
References souffle::getRelation().
{
         return getRelation(name)->size();
     }
getSymbolTable()
virtual SymbolTable& souffle::SouffleProgram::getSymbolTable () pure virtual
Get the symbol table of the program.
Implemented in souffle::InterpreterProgInterface.
Referenced by souffle::ExplainProvenanceImpl::findQuerySolution(), and souffle::ExplainProvenanceImpl::queryProcess().
insert()
template<typename... Args> void souffle::SouffleProgram::insert (const std::tuple< Args... > & t, Relation * relation) inline
Insert function with std::tuple as input (wrapper)
Parameters
t The insert tuple (std::tuple)
relation The relation that perform insert operation (Relation*)
See also
Relation::insert()
Definition at line 927 of file SouffleInterface.h.
References souffle::Relation::insert().
{
         tuple t1(relation);
         tuple_insert<decltype(t), sizeof...(Args)>::add(t, t1);
         relation->insert(t1);
     }
loadAll()
virtual void souffle::SouffleProgram::loadAll (std::string inputDirectory = ".") pure virtual
Read all input relations from the given directory.
If no directory is given, the default is to use the current working directory. The implementation of this function occurs in the C++ code generated by Souffle. To view the generated C++ code, run Souffle with the -g option.
Implemented in souffle::InterpreterProgInterface.
Referenced by SWIGSouffleProgram::loadAll().
printAll()
virtual void souffle::SouffleProgram::printAll (std::string outputDirectory = ".") pure virtual
Store all output relations individually in .CSV file in the given directory, with the relation name as the file name of the .CSV file.
If no directory is given, the default is to use the current working directory. The implementation of this function occurs in the C++ code generated by Souffle. To view the generated C++ code, run Souffle with the -g option.
Implemented in souffle::InterpreterProgInterface.
Referenced by SWIGSouffleProgram::printAll().
purgeInputRelations()
void souffle::SouffleProgram::purgeInputRelations () inline
Remove all the tuples from the inputRelations, calling the purge method of each.
See also
Relation::purge()
Definition at line 880 of file SouffleInterface.h.
References relation.
{
         for (Relation* relation : inputRelations) {
             relation->purge();
         }
     }
purgeInternalRelations()
void souffle::SouffleProgram::purgeInternalRelations () inline
Remove all the tuples from the internalRelations, calling the purge method of each.
See also
Relation::purge()
Definition at line 891 of file SouffleInterface.h.
References relation.
{
         for (Relation* relation : internalRelations) {
             relation->purge();
         }
     }
purgeOutputRelations()
void souffle::SouffleProgram::purgeOutputRelations () inline
Remove all the tuples from the outputRelations, calling the purge method of each.
See also
Relation::purge()
Definition at line 869 of file SouffleInterface.h.
References relation.
{
         for (Relation* relation : outputRelations) {
             relation->purge();
         }
     }
run()
virtual void souffle::SouffleProgram::run () inline virtual
Execute the souffle program, without any loads or stores.
Reimplemented in souffle::InterpreterProgInterface.
Definition at line 721 of file SouffleInterface.h.
Referenced by SWIGSouffleProgram::run().
 {}
runAll()
virtual void souffle::SouffleProgram::runAll (std::string inputDirectory = ".", std::string outputDirectory = ".") pure virtual
Execute program, loading inputs and storing outputs as required.
Read all input relations and store all output relations from the given directory. First argument is the input directory, second argument is the output directory, if no directory is given, the default is to use the current working directory. The implementation of this function occurs in the C++ code generated by Souffle. To view the generated C++ code, run Souffle with the -g option.
Implemented in souffle::InterpreterProgInterface.
Referenced by SWIGSouffleProgram::runAll().
setNumThreads()
void souffle::SouffleProgram::setNumThreads (std::size_t numThreadsValue) inline
Set the number of threads to be used.
Definition at line 763 of file SouffleInterface.h.
{
         this->numThreads = numThreadsValue;
     }
Field Documentation
allRelations
std::vector<Relation*> souffle::SouffleProgram::allRelations private
allRelations store all the relation in a vector.
Definition at line 681 of file SouffleInterface.h.
inputRelations
std::vector<Relation*> souffle::SouffleProgram::inputRelations private
inputRelations stores all the input relation in a vector.
Definition at line 666 of file SouffleInterface.h.
internalRelations
std::vector<Relation*> souffle::SouffleProgram::internalRelations private
internalRelation stores all the relation in a vector that are neither an input or an output.
Definition at line 676 of file SouffleInterface.h.
numThreads
std::size_t souffle::SouffleProgram::numThreads = 1 private
Definition at line 682 of file SouffleInterface.h.
outputRelations
std::vector<Relation*> souffle::SouffleProgram::outputRelations private
outputRelations stores all the output relation in a vector.
Definition at line 671 of file SouffleInterface.h.
relationMap
std::map<std::string, Relation*> souffle::SouffleProgram::relationMap private
Define a relation map for external access, when getRelation(name) is called, the relation with the given name will be returned from this map, relationMap stores all the relations in a map with its name as the key and relation as the value.
Definition at line 661 of file SouffleInterface.h.
The documentation for this class was generated from the following file:
SouffleInterface.h