souffle: souffle::DebugReporter Class Reference
souffle::DebugReporter Class Reference
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
#include <DebugReporter.h>
Public Member Functions
DebugReporter (std::unique_ptr< AstTransformer > wrappedTransformer)
void disableTransformers (const std::set< std::string > &transforms) override
std::string getName () const override
void setDebugReport () override
void setVerbosity (bool verbose) override
Public Member Functions inherited from souffle::MetaTransformer
bool applySubtransformer (AstTranslationUnit &translationUnit, AstTransformer *transformer)
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Static Public Member Functions
template<typename A , typename B >
static std::string generateDiff (const A &prev, const B &curr)
Generate a full-content diff between two sources.
Private Member Functions
void generateDebugReport (AstTranslationUnit &tu, const std::string &preTransformDatalog)
bool transform (AstTranslationUnit &translationUnit) override
Private Attributes
std::unique_ptr< AstTransformer > wrappedTransformer
Additional Inherited Members
Protected Attributes inherited from souffle::MetaTransformer
bool verbose = false
Detailed Description
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
Definition at line 36 of file DebugReporter.h.
Constructor & Destructor Documentation
DebugReporter()
souffle::DebugReporter::DebugReporter (std::unique_ptr< AstTransformer > wrappedTransformer) inline
Definition at line 38 of file DebugReporter.h.
             : wrappedTransformer(std::move(wrappedTransformer)) {}
Member Function Documentation
disableTransformers()
void souffle::DebugReporter::disableTransformers (const std::set< std::string > & transforms) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 50 of file DebugReporter.h.
References wrappedTransformer.
{
         if (auto* mt = dynamic_cast<MetaTransformer*>(wrappedTransformer.get())) {
             mt->disableTransformers(transforms);
         } else if (transforms.find(wrappedTransformer->getName()) != transforms.end()) {
             wrappedTransformer = std::unique_ptr<AstTransformer>(new NullTransformer());
         }
     }
generateDebugReport()
void souffle::DebugReporter::generateDebugReport (AstTranslationUnit & tu, const std::string & preTransformDatalog) private
Definition at line 64 of file DebugReporter.cpp.
References souffle::DebugReport::addSection(), generateDiff(), souffle::AstTranslationUnit::getDebugReport(), souffle::AstTranslationUnit::getProgram(), and souffle::profile::ss.
Referenced by transform().
{
     auto show = [](auto* printablePtr) {
         std::stringstream ss;
         if (printablePtr != nullptr) {
             ss << *printablePtr;
         }
         return ss.str();
     };
     std::string datalogSpec = show(tu.getProgram());
     tu.getDebugReport().addSection("dl", "Datalog",
             preTransformDatalog.empty() ? std::move(datalogSpec)
                                         : generateDiff(preTransformDatalog, datalogSpec));
 }
generateDiff()
template<typename A , typename B > static std::string souffle::DebugReporter::generateDiff (const A & prev, const B & curr) inline static
Generate a full-content diff between two sources.
Both arguments are passed into a std::ostream so you may exploit stream implementations.
Definition at line 67 of file DebugReporter.h.
References souffle::execStdOut(), souffle::TempFileStream::getFileName(), and str.
Referenced by souffle::RamTransformer::apply(), and generateDebugReport().
{
         TempFileStream in_prev;
         TempFileStream in_curr;
         in_prev << prev;
         in_curr << curr;
         in_prev.flush();
         in_curr.flush();
         std::string diff_cmd =
                 "diff --new-line-format='+%L' "
                 "     --old-line-format='-%L' "
                 "     --unchanged-line-format=' %L' ";
         return execStdOut(diff_cmd + in_prev.getFileName() + " " + in_curr.getFileName()).str();
     }
getName()
std::string souffle::DebugReporter::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 58 of file DebugReporter.h.
{
         return "DebugReporter";
     }
setDebugReport()
void souffle::DebugReporter::setDebugReport () inline override virtual
Implements souffle::MetaTransformer.
Definition at line 41 of file DebugReporter.h.
 {}
setVerbosity()
void souffle::DebugReporter::setVerbosity (bool verbose) inline override virtual
Implements souffle::MetaTransformer.
Definition at line 43 of file DebugReporter.h.
References souffle::MetaTransformer::verbose, and wrappedTransformer.
{
         this->verbose = verbose;
         if (auto* mt = dynamic_cast<MetaTransformer*>(wrappedTransformer.get())) {
             mt->setVerbosity(verbose);
         }
     }
transform()
bool souffle::DebugReporter::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 31 of file DebugReporter.cpp.
References souffle::MetaTransformer::applySubtransformer(), souffle::DebugReport::endSection(), generateDebugReport(), souffle::AstTranslationUnit::getDebugReport(), souffle::AstTranslationUnit::getProgram(), souffle::now(), souffle::DebugReport::startSection(), and wrappedTransformer.
{
     translationUnit.getDebugReport().startSection();
     std::stringstream datalogSpecOriginal;
     datalogSpecOriginal << *translationUnit.getProgram();
     auto start = std::chrono::high_resolution_clock::now();
     bool changed = applySubtransformer(translationUnit, wrappedTransformer.get());
     auto end = std::chrono::high_resolution_clock::now();
     std::string runtimeStr = "(" + std::to_string(std::chrono::duration<double>(end - start).count()) + "s)";
     if (changed) {
         generateDebugReport(translationUnit, datalogSpecOriginal.str());
         translationUnit.getDebugReport().endSection(
                 wrappedTransformer->getName(), wrappedTransformer->getName() + " " + runtimeStr);
     } else {
         translationUnit.getDebugReport().endSection(wrappedTransformer->getName(),
                 wrappedTransformer->getName() + " " + runtimeStr + " (unchanged)");
     }
     return changed;
 }
Field Documentation
wrappedTransformer
std::unique_ptr<AstTransformer> souffle::DebugReporter::wrappedTransformer private
Definition at line 82 of file DebugReporter.h.
Referenced by disableTransformers(), setVerbosity(), and transform().
The documentation for this class was generated from the following files:
DebugReporter.h
DebugReporter.cpp