souffle: souffle::AstSubsetType Class Reference
souffle::AstSubsetType Class Reference
A subset type is named type that can either be a sub-type of the predefined types (float/unsigned/number/symbol).
#include <AstType.h>
Public Member Functions
AstSubsetType (const AstQualifiedName &name, TypeAttribute type)
Creates a new primitive type.
AstSubsetType * clone () const override
Create a clone (i.e.
TypeAttribute getTypeAttribute () const
Public Member Functions inherited from souffle::AstType
AstType (AstQualifiedName name={""})
const AstQualifiedName & getQualifiedName () const
get type name
void setQualifiedName (const AstQualifiedName &name)
set type name
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
TypeAttribute type
type attribute
Detailed Description
A subset type is named type that can either be a sub-type of the predefined types (float/unsigned/number/symbol).
Definition at line 60 of file AstType.h.
Constructor & Destructor Documentation
AstSubsetType()
souffle::AstSubsetType::AstSubsetType (const AstQualifiedName & name, TypeAttribute type) inline
Creates a new primitive type.
Definition at line 63 of file AstType.h.
 : AstType(name), type(type) {}
Member Function Documentation
clone()
AstSubsetType* souffle::AstSubsetType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstType.
Definition at line 65 of file AstType.h.
References souffle::AstType::getQualifiedName(), and souffle::AstNode::getSrcLoc().
{
         auto res = new AstSubsetType(getQualifiedName(), type);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstSubsetType::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 96 of file AstType.h.
References souffle::AstType::getQualifiedName().
{
         const auto& other = static_cast<const AstSubsetType&>(node);
         return getQualifiedName() == other.getQualifiedName() && type == other.type;
     }
getTypeAttribute()
TypeAttribute souffle::AstSubsetType::getTypeAttribute () const inline
Definition at line 71 of file AstType.h.
{
         return type;
     }
print()
void souffle::AstSubsetType::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 76 of file AstType.h.
References souffle::Float, souffle::AstType::getQualifiedName(), souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
{
         os << ".type " << getQualifiedName() << " <: ";
         switch (type) {
             case TypeAttribute::Signed:
                 os << "number";
                 break;
             case TypeAttribute::Unsigned:
                 os << "unsigned";
                 break;
             case TypeAttribute::Float:
                 os << "float";
                 break;
             case TypeAttribute::Symbol:
                 os << "symbol";
                 break;
             case TypeAttribute::Record:
                 assert(false && "Invalid type");
         }
     }
Field Documentation
type
TypeAttribute souffle::AstSubsetType::type private
type attribute
Definition at line 103 of file AstType.h.
The documentation for this class was generated from the following file:
AstType.h