souffle: souffle::AstTranslator::ValueIndex Class Reference
souffle::AstTranslator::ValueIndex Class Reference
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Public Member Functions
void addVarReference (const AstVariable &var, const Location &l)
void addVarReference (const AstVariable &var, int ident, int pos, std::unique_ptr< RamRelationReference > rel=nullptr)
const Location & getAggregatorLocation (const AstAggregator &agg) const
const Location & getDefinitionPoint (const AstVariable &var) const
const Location & getDefinitionPoint (const AstRecordInit &init) const
const variable_reference_map & getVariableReferences () const
bool isAggregator (const int level) const
bool isDefined (const AstVariable &var) const
bool isSomethingDefinedOn (int level) const
void print (std::ostream &out) const
void setAggregatorLocation (const AstAggregator &agg, const Location &loc)
void setRecordDefinition (const AstRecordInit &init, const Location &l)
void setRecordDefinition (const AstRecordInit &init, int ident, int pos, std::unique_ptr< RamRelationReference > rel=nullptr)
Private Types
using aggregator_location_map = std::vector< std::pair< const AstAggregator *, Location > >
A map from AstAggregators to storage locations.
using record_definition_map = std::map< const AstRecordInit *, Location >
The type mapping record init expressions to their definition points, hence the point where they get grounded/bound.
using variable_reference_map = std::map< std::string, std::set< Location > >
The type mapping variables (referenced by their names) to the locations where they are used.
Private Attributes
aggregator_location_map aggregator_locations
The level of a nested ram operation that is handling a given aggregator operation.
record_definition_map record_definitions
The index of record definition points.
variable_reference_map var_references
The index of variable accesses.
Friends
std::ostream & operator<< (std::ostream &out, const ValueIndex &index) __attribute__((unused))
Detailed Description
A class indexing the location of variables and record references within a loop nest resulting from the conversion of a rule.
Definition at line 146 of file AstTranslator.h.
Member Typedef Documentation
aggregator_location_map
using souffle::AstTranslator::ValueIndex::aggregator_location_map = std::vector<std::pair<const AstAggregator*, Location> > private
A map from AstAggregators to storage locations.
Note, since in this case AstAggregators are indexed by their values (not their address) no standard map can be utilized.
Definition at line 164 of file AstTranslator.h.
record_definition_map
using souffle::AstTranslator::ValueIndex::record_definition_map = std::map<const AstRecordInit*, Location> private
The type mapping record init expressions to their definition points, hence the point where they get grounded/bound.
Definition at line 157 of file AstTranslator.h.
variable_reference_map
using souffle::AstTranslator::ValueIndex::variable_reference_map = std::map<std::string, std::set<Location> > private
The type mapping variables (referenced by their names) to the locations where they are used.
Definition at line 151 of file AstTranslator.h.
Member Function Documentation
addVarReference() [1/2]
void souffle::AstTranslator::ValueIndex::addVarReference (const AstVariable & var, const Location & l) inline
Definition at line 178 of file AstTranslator.h.
References souffle::AstVariable::getName().
{
             std::set<Location>& locs = var_references[var.getName()];
             locs.insert(l);
         }
addVarReference() [2/2]
void souffle::AstTranslator::ValueIndex::addVarReference (const AstVariable & var, int ident, int pos, std::unique_ptr< RamRelationReference > rel = nullptr) inline
Definition at line 183 of file AstTranslator.h.
References souffle::AstTranslator::Location::Location().
{
             addVarReference(var, Location({ident, pos, std::move(rel)}));
         }
getAggregatorLocation()
const Location& souffle::AstTranslator::ValueIndex::getAggregatorLocation (const AstAggregator & agg) const inline
Definition at line 232 of file AstTranslator.h.
References souffle::AstTranslator::Location::Location().
Referenced by souffle::AstTranslator::translateValue().
{
             // search list
             for (const auto& cur : aggregator_locations) {
                 if (*cur.first == agg) {
                     return cur.second;
                 }
             }
             // fail
             std::cout << "Lookup of " << &agg << " = " << agg << " failed\n";
             assert(false && "Requested aggregation operation is not processed!");
             const static Location fail = Location();
             return fail;
         }
getDefinitionPoint() [1/2]
const Location& souffle::AstTranslator::ValueIndex::getDefinitionPoint (const AstVariable & var) const inline
Definition at line 192 of file AstTranslator.h.
References souffle::AstVariable::getName().
Referenced by souffle::AstTranslator::translateValue().
{
             auto pos = var_references.find(var.getName());
             assert(pos != var_references.end() && "Undefined variable referenced!");
             return *pos->second.begin();
         }
getDefinitionPoint() [2/2]
const Location& souffle::AstTranslator::ValueIndex::getDefinitionPoint (const AstRecordInit & init) const inline
Definition at line 215 of file AstTranslator.h.
{
             auto pos = record_definitions.find(&init);
             if (pos != record_definitions.end()) {
                 return pos->second;
             }
             assert(false && "Requested location for undefined record!");
             static Location fail;
             return fail;
         }
getVariableReferences()
const variable_reference_map& souffle::AstTranslator::ValueIndex::getVariableReferences () const inline
Definition at line 198 of file AstTranslator.h.
{
             return var_references;
         }
isAggregator()
bool souffle::AstTranslator::ValueIndex::isAggregator (const int level) const inline
Definition at line 250 of file AstTranslator.h.
References souffle::any_of().
{
             // check for aggregator definitions
             return any_of(aggregator_locations,
                     [&level](const auto& location) { return location.second.identifier == level; });
         }
isDefined()
bool souffle::AstTranslator::ValueIndex::isDefined (const AstVariable & var) const inline
Definition at line 188 of file AstTranslator.h.
References souffle::AstVariable::getName().
Referenced by souffle::AstTranslator::translateValue().
{
             return var_references.find(var.getName()) != var_references.end();
         }
isSomethingDefinedOn()
bool souffle::AstTranslator::ValueIndex::isSomethingDefinedOn (int level) const inline
Definition at line 256 of file AstTranslator.h.
{
             // check for variable definitions
             for (const auto& cur : var_references) {
                 if (cur.second.begin()->identifier == level) {
                     return true;
                 }
             }
             // check for record definitions
             for (const auto& cur : record_definitions) {
                 if (cur.second.identifier == level) {
                     return true;
                 }
             }
             // nothing defined on this level
             return false;
         }
print()
void souffle::AstTranslator::ValueIndex::print (std::ostream & out) const inline
Definition at line 273 of file AstTranslator.h.
References souffle::join().
{
             out << "Variables:\n\t";
             out << join(var_references, "\n\t");
         }
setAggregatorLocation()
void souffle::AstTranslator::ValueIndex::setAggregatorLocation (const AstAggregator & agg, const Location & loc) inline
Definition at line 228 of file AstTranslator.h.
{
             aggregator_locations.push_back(std::make_pair(&agg, loc));
         }
setRecordDefinition() [1/2]
void souffle::AstTranslator::ValueIndex::setRecordDefinition (const AstRecordInit & init, const Location & l) inline
Definition at line 206 of file AstTranslator.h.
References l.
{
             record_definitions[&init] = l;
         }
setRecordDefinition() [2/2]
void souffle::AstTranslator::ValueIndex::setRecordDefinition (const AstRecordInit & init, int ident, int pos, std::unique_ptr< RamRelationReference > rel = nullptr) inline
Definition at line 210 of file AstTranslator.h.
References souffle::AstTranslator::Location::Location().
{
             setRecordDefinition(init, Location({ident, pos, std::move(rel)}));
         }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const ValueIndex & index) friend
Definition at line 278 of file AstTranslator.h.
{
             index.print(out);
             return out;
         }
Field Documentation
aggregator_locations
aggregator_location_map souffle::AstTranslator::ValueIndex::aggregator_locations private
The level of a nested ram operation that is handling a given aggregator operation.
Definition at line 173 of file AstTranslator.h.
record_definitions
record_definition_map souffle::AstTranslator::ValueIndex::record_definitions private
The index of record definition points.
Definition at line 170 of file AstTranslator.h.
var_references
variable_reference_map souffle::AstTranslator::ValueIndex::var_references private
The index of variable accesses.
Definition at line 167 of file AstTranslator.h.
The documentation for this class was generated from the following file:
AstTranslator.h