souffle: souffle::Type Class Reference
souffle::Type Class Reference
An abstract base class for types to be covered within a type environment.
#include <TypeSystem.h>
Public Member Functions
const AstQualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
virtual void print (std::ostream &out=std::cout) const
Type (const TypeEnvironment &environment, AstQualifiedName name)
Type (const Type &other)=delete
virtual ~Type ()=default
Protected Attributes
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
Private Attributes
AstQualifiedName name
The name of this type.
Friends
std::ostream & operator<< (std::ostream &out, const Type &t)
std::ostream & operator<< (std::ostream &out, const Type *t)
Detailed Description
An abstract base class for types to be covered within a type environment.
An abstract base class for types within the AST.
Definition at line 38 of file TypeSystem.h.
Constructor & Destructor Documentation
Type() [1/2]
souffle::Type::Type (const TypeEnvironment & environment, AstQualifiedName name) inline
Definition at line 40 of file TypeSystem.h.
References ~Type().
             : environment(environment), name(std::move(name)) {}
Type() [2/2]
souffle::Type::Type (const Type & other) delete
~Type()
virtual souffle::Type::~Type () virtual default
Referenced by Type().
Member Function Documentation
getName()
const AstQualifiedName& souffle::Type::getName () const inline
Definition at line 47 of file TypeSystem.h.
References name.
Referenced by souffle::TypeEnvironment::addType(), souffle::getTypeQualifier(), souffle::TypeEnvironment::isType(), souffle::SubsetType::print(), souffle::UnionType::print(), souffle::RecordType::print(), and souffle::TypeSet::print().
{
         return name;
     }
getTypeEnvironment()
const TypeEnvironment& souffle::Type::getTypeEnvironment () const inline
Definition at line 51 of file TypeSystem.h.
References environment.
Referenced by souffle::getGreatestCommonSubtypes(), souffle::getLeastCommonSupertypes(), souffle::isFloatType(), souffle::isNumberType(), souffle::isSubtypeOf(), souffle::isSymbolType(), and souffle::isUnsignedType().
{
         return environment;
     }
operator!=()
bool souffle::Type::operator!= (const Type & other) const inline
Definition at line 59 of file TypeSystem.h.
{
         return !(*this == other);
     }
operator<()
bool souffle::Type::operator< (const Type & other) const inline
Definition at line 63 of file TypeSystem.h.
References name.
{
         return name < other.name;
     }
operator==()
bool souffle::Type::operator== (const Type & other) const inline
Definition at line 55 of file TypeSystem.h.
{
         return this == &other;
     }
print()
virtual void souffle::Type::print (std::ostream & out = std::cout) const inline virtual
Reimplemented in souffle::RecordType, souffle::UnionType, and souffle::SubsetType.
Definition at line 67 of file TypeSystem.h.
References name.
Referenced by souffle::UnionType::getElementTypes(), souffle::RecordType::getFields(), and souffle::TypeEnvironment::getNumericTypes().
{
         out << name;
     }
Friends And Related Function Documentation
operator<< [1/2]
std::ostream& operator<< (std::ostream & out, const Type & t) friend
Definition at line 71 of file TypeSystem.h.
{
         return t.print(out), out;
     }
operator<< [2/2]
std::ostream& operator<< (std::ostream & out, const Type * t) friend
Definition at line 75 of file TypeSystem.h.
{
         if (t == nullptr) {
             return out << "-null-";
         }
         return t->print(out), out;
     }
Field Documentation
environment
const TypeEnvironment& souffle::Type::environment protected
A reference to the type environment this type is associated to.
Definition at line 84 of file TypeSystem.h.
Referenced by souffle::UnionType::add(), souffle::RecordType::add(), getTypeEnvironment(), and souffle::isSubtypeOf().
name
AstQualifiedName souffle::Type::name private
The name of this type.
Definition at line 88 of file TypeSystem.h.
Referenced by souffle::RecordType::add(), souffle::TypeEnvironment::addType(), souffle::TypeEnvironment::createRecordType(), souffle::TypeEnvironment::createSubsetType(), souffle::TypeEnvironment::createUnionType(), getName(), souffle::TypeEnvironment::getNumericTypes(), operator<(), and print().
The documentation for this class was generated from the following file:
TypeSystem.h