souffle: souffle::RamSubroutineReturnValue Class Reference
souffle::RamSubroutineReturnValue Class Reference
A statement for returning from a ram subroutine.
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
RamSubroutineReturnValue * clone () const override
Create a clone (i.e.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamExpression * > getValues () const
Getter for expressions.
RamSubroutineReturnValue (std::vector< std::unique_ptr< RamExpression >> vals)
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > expressions
Return expressions.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
A statement for returning from a ram subroutine.
For example:
...
  RETURN (t0.0, t0.1)
Definition at line 1107 of file RamOperation.h.
Constructor & Destructor Documentation
RamSubroutineReturnValue()
souffle::RamSubroutineReturnValue::RamSubroutineReturnValue (std::vector< std::unique_ptr< RamExpression >> vals) inline
Definition at line 1109 of file RamOperation.h.
             : expressions(std::move(vals)) {
         for (const auto& expr : expressions) {
             assert(expr != nullptr && "Expression is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::RamSubroutineReturnValue::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamNode.
Definition at line 1137 of file RamOperation.h.
{
         for (auto& expr : expressions) {
             expr = map(std::move(expr));
         }
     }
clone()
RamSubroutineReturnValue* souffle::RamSubroutineReturnValue::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::RamOperation.
Definition at line 1129 of file RamOperation.h.
{
         std::vector<std::unique_ptr<RamExpression>> newValues;
         for (auto& expr : expressions) {
             newValues.emplace_back(expr->clone());
         }
         return new RamSubroutineReturnValue(std::move(newValues));
     }
equal()
bool souffle::RamSubroutineReturnValue::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamNode.
Definition at line 1156 of file RamOperation.h.
References souffle::equal_targets().
{
         const auto& other = static_cast<const RamSubroutineReturnValue&>(node);
         return equal_targets(expressions, other.expressions);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamSubroutineReturnValue::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamNode.
Definition at line 1121 of file RamOperation.h.
{
         std::vector<const RamNode*> res;
         for (const auto& expr : expressions) {
             res.push_back(expr.get());
         }
         return res;
     }
getValues()
std::vector<RamExpression*> souffle::RamSubroutineReturnValue::getValues () const inline
Getter for expressions.
Definition at line 1117 of file RamOperation.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), and souffle::NodeGenerator::visitSubroutineReturnValue().
{
         return toPtrVector(expressions);
     }
print()
void souffle::RamSubroutineReturnValue::print (std::ostream & os, int tabpos) const inline override protected virtual
Pretty print with indentation.
Implements souffle::RamOperation.
Definition at line 1144 of file RamOperation.h.
References souffle::times().
{
         os << times(" ", tabpos);
         os << "RETURN (";
         for (auto val : getValues()) {
             os << *val;
             if (val != *(getValues().end() - 1)) {
                 os << ", ";
             }
         }
         os << ")" << std::endl;
     }
Field Documentation
expressions
std::vector<std::unique_ptr<RamExpression> > souffle::RamSubroutineReturnValue::expressions protected
Return expressions.
Definition at line 1162 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h