souffle: souffle::AstRecordType Class Reference
souffle::AstRecordType Class Reference
A record type aggregates a list of fields into a new type.
#include <AstType.h>
Data Structures
struct Field
record field
Public Member Functions
void add (const std::string &name, const AstQualifiedName &type)
add field to record type
AstRecordType * clone () const override
Create a clone (i.e.
const std::vector< Field > & getFields () const
get fields of record
void setFieldType (size_t idx, const AstQualifiedName &type)
set field type
Public Member Functions inherited from souffle::AstType
AstType (AstQualifiedName name={""})
const AstQualifiedName & getQualifiedName () const
get type name
void setQualifiedName (const AstQualifiedName &name)
set type name
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Private Attributes
std::vector< Field > fields
record fields
Detailed Description
A record type aggregates a list of fields into a new type.
Each record type has a name making it unique. Two record types are unrelated to all other types (they do not have any super or sub types).
Definition at line 158 of file AstType.h.
Member Function Documentation
add()
void souffle::AstRecordType::add (const std::string & name, const AstQualifiedName & type) inline
add field to record type
Definition at line 171 of file AstType.h.
References souffle::AstType::name.
{
         fields.push_back(Field({name, type}));
     }
clone()
AstRecordType* souffle::AstRecordType::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstType.
Definition at line 186 of file AstType.h.
References souffle::AstType::getQualifiedName(), and souffle::AstNode::getSrcLoc().
{
         auto res = new AstRecordType();
         res->setSrcLoc(getSrcLoc());
         res->setQualifiedName(getQualifiedName());
         res->fields = fields;
         return res;
     }
equal()
bool souffle::AstRecordType::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 209 of file AstType.h.
References souffle::AstType::getQualifiedName().
{
         const auto& other = static_cast<const AstRecordType&>(node);
         return getQualifiedName() == other.getQualifiedName() && fields == other.fields;
     }
getFields()
const std::vector<Field>& souffle::AstRecordType::getFields () const inline
get fields of record
Definition at line 176 of file AstType.h.
Referenced by souffle::AstSemanticChecker::checkRecordType().
{
         return fields;
     }
print()
void souffle::AstRecordType::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 195 of file AstType.h.
References souffle::AstType::getQualifiedName(), and i.
{
         os << ".type " << getQualifiedName() << " = "
            << "[";
         for (unsigned i = 0; i < fields.size(); i++) {
             if (i != 0) {
                 os << ",";
             }
             os << fields[i].name;
             os << ":";
             os << fields[i].type;
         }
         os << "]";
     }
setFieldType()
void souffle::AstRecordType::setFieldType (size_t idx, const AstQualifiedName & type) inline
set field type
Definition at line 181 of file AstType.h.
{
         assert(idx < fields.size() && "record field index out of bounds");
         fields[idx].type = type;
     }
Field Documentation
fields
std::vector<Field> souffle::AstRecordType::fields private
record fields
Definition at line 216 of file AstType.h.
The documentation for this class was generated from the following file:
AstType.h