souffle: souffle::RamIndexOperation Class Reference
souffle::RamIndexOperation Class Reference
#include <RamOperation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply the mapper to all child nodes.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of all embedded child nodes.
std::vector< RamExpression * > getRangePattern () const
Get range pattern.
RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamRelationOperation
const RamRelation & getRelation () const
Get search relation.
RamRelationOperation (std::unique_ptr< RamRelationReference > relRef, int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamTupleOperation
int getTupleId () const
Get identifier.
RamTupleOperation (int ident, std::unique_ptr< RamOperation > nested, std::string profileText="")
void setTupleId (int id)
Set identifier.
Public Member Functions inherited from souffle::RamNestedOperation
RamOperation & getOperation () const
Get nested operation.
const std::string & getProfileText () const
Get profile text.
RamNestedOperation (std::unique_ptr< RamOperation > nested, std::string profileText="")
Public Member Functions inherited from souffle::RamOperation
RamOperation * clone () const override=0
Create a clone (i.e.
Public Member Functions inherited from souffle::RamNode
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void rewrite (const RamNode *oldNode, std::unique_ptr< RamNode > newNode)
Rewrite a child node.
virtual ~RamNode ()=default
Protected Member Functions
bool equal (const RamNode &node) const override
Equality check for two RAM nodes.
void printIndex (std::ostream &os) const
Helper method for printing.
Protected Member Functions inherited from souffle::RamNestedOperation
void print (std::ostream &os, int tabpos) const override
Pretty print with indentation.
Protected Member Functions inherited from souffle::RamOperation
void print (std::ostream &os) const override
Print RAM node.
Protected Attributes
std::vector< std::unique_ptr< RamExpression > > queryPattern
Values of index per column of table (if indexable)
Protected Attributes inherited from souffle::RamRelationOperation
std::unique_ptr< RamRelationReference > relationRef
Search relation.
Protected Attributes inherited from souffle::RamTupleOperation
int identifier
Identifier for the tuple, corresponding to its position in the loop nest.
Protected Attributes inherited from souffle::RamNestedOperation
std::unique_ptr< RamOperation > nestedOperation
Nested operation.
const std::string profileText
Text used by the profiler.
Additional Inherited Members
Static Protected Member Functions inherited from souffle::RamOperation
static void print (const RamOperation *operation, std::ostream &os, int tabpos)
Pretty print jump-bed.
Detailed Description
Definition at line 271 of file RamOperation.h.
Constructor & Destructor Documentation
RamIndexOperation()
souffle::RamIndexOperation::RamIndexOperation (std::unique_ptr< RamRelationReference > r, int ident, std::vector< std::unique_ptr< RamExpression >> queryPattern, std::unique_ptr< RamOperation > nested, std::string profileText = "") inline
Definition at line 273 of file RamOperation.h.
References souffle::getRelation().
             : RamRelationOperation(std::move(r), ident, std::move(nested), std::move(profileText)),
               queryPattern(std::move(queryPattern)) {
         assert(getRangePattern().size() == getRelation().getArity());
         for (const auto& pattern : queryPattern) {
             assert(pattern != nullptr && "pattern is a null-pointer");
         }
     }
Member Function Documentation
apply()
void souffle::RamIndexOperation::apply (const RamNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::RamRelationOperation.
Reimplemented in souffle::RamIndexAggregate, and souffle::RamIndexChoice.
Definition at line 300 of file RamOperation.h.
References souffle::RamRelationOperation::apply().
Referenced by souffle::RamIndexAggregate::apply().
{
         RamRelationOperation::apply(map);
         for (auto& pattern : queryPattern) {
             pattern = map(std::move(pattern));
         }
     }
equal()
bool souffle::RamIndexOperation::equal (const RamNode &) const inline override protected virtual
Equality check for two RAM nodes.
Default action is that nothing needs to be checked.
Reimplemented from souffle::RamRelationOperation.
Reimplemented in souffle::RamIndexAggregate, and souffle::RamIndexChoice.
Definition at line 327 of file RamOperation.h.
References souffle::RamRelationOperation::equal(), and souffle::equal_targets().
Referenced by souffle::RamIndexChoice::equal(), and souffle::RamIndexAggregate::equal().
{
         const auto& other = static_cast<const RamIndexOperation&>(node);
         return RamRelationOperation::equal(other) && equal_targets(queryPattern, other.queryPattern);
     }
getChildNodes()
std::vector<const RamNode*> souffle::RamIndexOperation::getChildNodes () const inline override virtual
Obtain list of all embedded child nodes.
Reimplemented from souffle::RamRelationOperation.
Reimplemented in souffle::RamIndexAggregate, and souffle::RamIndexChoice.
Definition at line 292 of file RamOperation.h.
References souffle::RamRelationOperation::getChildNodes().
Referenced by souffle::RamIndexChoice::getChildNodes(), and souffle::RamIndexAggregate::getChildNodes().
{
         auto res = RamRelationOperation::getChildNodes();
         for (auto& pattern : queryPattern) {
             res.push_back(pattern.get());
         }
         return res;
     }
getRangePattern()
std::vector<RamExpression*> souffle::RamIndexOperation::getRangePattern () const inline
Get range pattern.
Returns
A std::vector of pointers to RamExpression objects
Definition at line 288 of file RamOperation.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::RamLevelAnalysis::getLevel(), souffle::RamIndexAnalysis::getSearchSignature(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::NodeGenerator::visitIndexAggregate(), souffle::NodeGenerator::visitIndexChoice(), souffle::NodeGenerator::visitIndexScan(), souffle::NodeGenerator::visitParallelIndexChoice(), and souffle::NodeGenerator::visitParallelIndexScan().
{
         return toPtrVector(queryPattern);
     }
printIndex()
void souffle::RamIndexOperation::printIndex (std::ostream & os) const inline protected
Helper method for printing.
Definition at line 309 of file RamOperation.h.
References souffle::getRelation(), i, and souffle::isRamUndefValue().
{
         const auto& attrib = getRelation().getAttributeNames();
         bool first = true;
         for (unsigned int i = 0; i < queryPattern.size(); ++i) {
             if (!isRamUndefValue(queryPattern[i].get())) {
                 if (first) {
                     os << " ON INDEX ";
                     first = false;
                 } else {
                     os << " AND ";
                 }
                 os << "t" << getTupleId() << ".";
                 os << attrib[i] << " = ";
                 os << *queryPattern[i];
             }
         }
     }
Field Documentation
queryPattern
std::vector<std::unique_ptr<RamExpression> > souffle::RamIndexOperation::queryPattern protected
Values of index per column of table (if indexable)
Definition at line 333 of file RamOperation.h.
The documentation for this class was generated from the following file:
RamOperation.h