souffle: souffle::AstComponent Class Reference
souffle::AstComponent Class Reference
A AST node describing a component within the input program.
#include <AstComponent.h>
Public Member Functions
void addBaseComponent (std::unique_ptr< AstComponentType > component)
add base components
void addClause (std::unique_ptr< AstClause > c)
add clause
void addComponent (std::unique_ptr< AstComponent > c)
add components
void addInstantiation (std::unique_ptr< AstComponentInit > i)
add instantiation
void addIO (std::unique_ptr< AstIO > directive)
add IO
void addOverride (const std::string &name)
add override
void addRelation (std::unique_ptr< AstRelation > r)
add relation
void addType (std::unique_ptr< AstType > t)
add type
void apply (const AstNodeMapper &mapper) override
Apply the mapper to all child nodes.
AstComponent * clone () const override
Create a clone (i.e.
void copyBaseComponents (const AstComponent *other)
copy base components
const std::vector< AstComponentType * > getBaseComponents () const
get base components
std::vector< const AstNode * > getChildNodes () const override
Obtain a list of all embedded AST child nodes.
std::vector< AstClause * > getClauses () const
get clauses
std::vector< AstComponent * > getComponents () const
get components
const AstComponentType * getComponentType () const
get component type
std::vector< AstComponentInit * > getInstantiations () const
get instantiation
std::vector< AstIO * > getIOs () const
get IO statements
const std::set< std::string > & getOverridden () const
get override
std::vector< AstRelation * > getRelations () const
get relations
std::vector< AstType * > getTypes () const
get types
void setComponentType (std::unique_ptr< AstComponentType > other)
set component type
Public Member Functions inherited from souffle::AstNode
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &os) const override
Output to a given output stream.
Protected Attributes
std::vector< std::unique_ptr< AstComponentType > > baseComponents
base components of component
std::vector< std::unique_ptr< AstClause > > clauses
clauses
std::vector< std::unique_ptr< AstComponent > > components
nested components
std::unique_ptr< AstComponentType > componentType
name of component and its formal component arguments.
std::vector< std::unique_ptr< AstComponentInit > > instantiations
nested component instantiations.
std::vector< std::unique_ptr< AstIO > > ios
I/O directives.
std::set< std::string > overrideRules
clauses of relations that are overwritten by this component
std::vector< std::unique_ptr< AstRelation > > relations
relations
std::vector< std::unique_ptr< AstType > > types
types declarations
Detailed Description
A AST node describing a component within the input program.
Definition at line 155 of file AstComponent.h.
Member Function Documentation
addBaseComponent()
void souffle::AstComponent::addBaseComponent (std::unique_ptr< AstComponentType > component) inline
add base components
Definition at line 173 of file AstComponent.h.
{
         baseComponents.push_back(std::move(component));
     }
addClause()
void souffle::AstComponent::addClause (std::unique_ptr< AstClause > c) inline
add clause
Definition at line 206 of file AstComponent.h.
References clauses.
{
         clauses.push_back(std::move(c));
     }
addComponent()
void souffle::AstComponent::addComponent (std::unique_ptr< AstComponent > c) inline
add components
Definition at line 226 of file AstComponent.h.
{
         components.push_back(std::move(c));
     }
addInstantiation()
void souffle::AstComponent::addInstantiation (std::unique_ptr< AstComponentInit > i) inline
add instantiation
Definition at line 236 of file AstComponent.h.
{
         instantiations.push_back(std::move(i));
     }
addIO()
void souffle::AstComponent::addIO (std::unique_ptr< AstIO > directive) inline
add IO
Definition at line 216 of file AstComponent.h.
References ios.
{
         ios.push_back(std::move(directive));
     }
addOverride()
void souffle::AstComponent::addOverride (const std::string & name) inline
add override
Definition at line 246 of file AstComponent.h.
{
         overrideRules.insert(name);
     }
addRelation()
void souffle::AstComponent::addRelation (std::unique_ptr< AstRelation > r) inline
add relation
Definition at line 196 of file AstComponent.h.
References relations.
{
         relations.push_back(std::move(r));
     }
addType()
void souffle::AstComponent::addType (std::unique_ptr< AstType > t) inline
add type
Definition at line 178 of file AstComponent.h.
References types.
{
         types.push_back(std::move(t));
     }
apply()
void souffle::AstComponent::apply (const AstNodeMapper &) inline override virtual
Apply the mapper to all child nodes.
Reimplemented from souffle::AstNode.
Definition at line 287 of file AstComponent.h.
References clauses, ios, relations, and types.
{
         componentType = mapper(std::move(componentType));
         for (auto& cur : baseComponents) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : components) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : instantiations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : types) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : relations) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : clauses) {
             cur = mapper(std::move(cur));
         }
         for (auto& cur : ios) {
             cur = mapper(std::move(cur));
         }
     }
clone()
AstComponent* souffle::AstComponent::clone () const inline override virtual
Create a clone (i.e.
deep copy) of this node
Implements souffle::AstNode.
Definition at line 255 of file AstComponent.h.
References clauses, ios, relations, and types.
{
         auto* res = new AstComponent();
         res->setComponentType(std::unique_ptr<AstComponentType>(componentType->clone()));
         for (const auto& cur : baseComponents) {
             res->baseComponents.emplace_back(cur->clone());
         }
         for (const auto& cur : components) {
             res->components.emplace_back(cur->clone());
         }
         for (const auto& cur : instantiations) {
             res->instantiations.emplace_back(cur->clone());
         }
         for (const auto& cur : types) {
             res->types.emplace_back(cur->clone());
         }
         for (const auto& cur : relations) {
             res->relations.emplace_back(cur->clone());
         }
         for (const auto& cur : clauses) {
             res->clauses.emplace_back(cur->clone());
         }
         for (const auto& cur : ios) {
             res->ios.emplace_back(cur->clone());
         }
         for (const auto& cur : overrideRules) {
             res->overrideRules.insert(cur);
         }
         return res;
     }
copyBaseComponents()
void souffle::AstComponent::copyBaseComponents (const AstComponent * other) inline
copy base components
Definition at line 188 of file AstComponent.h.
References getBaseComponents().
{
         baseComponents.clear();
         for (const auto& baseComponent : other->getBaseComponents()) {
             baseComponents.emplace_back(baseComponent->clone());
         }
     }
equal()
bool souffle::AstComponent::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 373 of file AstComponent.h.
References clauses, souffle::equal_ptr(), souffle::equal_targets(), ios, relations, and types.
{
         const auto& other = static_cast<const AstComponent&>(node);
         if (equal_ptr(componentType, other.componentType)) {
             return true;
         }
         if (!equal_targets(baseComponents, other.baseComponents)) {
             return false;
         }
         if (!equal_targets(components, other.components)) {
             return false;
         }
         if (!equal_targets(instantiations, other.instantiations)) {
             return false;
         }
         if (!equal_targets(types, other.types)) {
             return false;
         }
         if (!equal_targets(relations, other.relations)) {
             return false;
         }
         if (!equal_targets(clauses, other.clauses)) {
             return false;
         }
         if (!equal_targets(ios, other.ios)) {
             return false;
         }
         if (overrideRules != other.overrideRules) {
             return false;
         }
         return true;
     }
getBaseComponents()
const std::vector<AstComponentType*> souffle::AstComponent::getBaseComponents () const inline
get base components
Definition at line 168 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent(), and copyBaseComponents().
{
         return toPtrVector(baseComponents);
     }
getChildNodes()
std::vector<const AstNode*> souffle::AstComponent::getChildNodes () const inline override virtual
Obtain a list of all embedded AST child nodes.
Reimplemented from souffle::AstNode.
Definition at line 312 of file AstComponent.h.
References clauses, ios, relations, and types.
{
         std::vector<const AstNode*> res;
         res.push_back(componentType.get());
         for (const auto& cur : baseComponents) {
             res.push_back(cur.get());
         }
         for (const auto& cur : components) {
             res.push_back(cur.get());
         }
         for (const auto& cur : instantiations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : types) {
             res.push_back(cur.get());
         }
         for (const auto& cur : relations) {
             res.push_back(cur.get());
         }
         for (const auto& cur : clauses) {
             res.push_back(cur.get());
         }
         for (const auto& cur : ios) {
             res.push_back(cur.get());
         }
         return res;
     }
getClauses()
std::vector<AstClause*> souffle::AstComponent::getClauses () const inline
get clauses
Definition at line 211 of file AstComponent.h.
References clauses, and souffle::toPtrVector().
{
         return toPtrVector(clauses);
     }
getComponents()
std::vector<AstComponent*> souffle::AstComponent::getComponents () const inline
get components
Definition at line 231 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent(), souffle::ComponentLookup::getComponent(), and souffle::ComponentLookup::run().
{
         return toPtrVector(components);
     }
getComponentType()
const AstComponentType* souffle::AstComponent::getComponentType () const inline
get component type
Definition at line 158 of file AstComponent.h.
Referenced by souffle::AstComponentChecker::checkComponent(), and souffle::AstComponentChecker::checkComponentReference().
{
         return componentType.get();
     }
getInstantiations()
std::vector<AstComponentInit*> souffle::AstComponent::getInstantiations () const inline
get instantiation
Definition at line 241 of file AstComponent.h.
References souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(instantiations);
     }
getIOs()
std::vector<AstIO*> souffle::AstComponent::getIOs () const inline
get IO statements
Definition at line 221 of file AstComponent.h.
References ios, and souffle::toPtrVector().
{
         return toPtrVector(ios);
     }
getOverridden()
const std::set<std::string>& souffle::AstComponent::getOverridden () const inline
get override
Definition at line 251 of file AstComponent.h.
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return overrideRules;
     }
getRelations()
std::vector<AstRelation*> souffle::AstComponent::getRelations () const inline
get relations
Definition at line 201 of file AstComponent.h.
References relations, and souffle::toPtrVector().
Referenced by souffle::AstComponentChecker::checkComponent().
{
         return toPtrVector(relations);
     }
getTypes()
std::vector<AstType*> souffle::AstComponent::getTypes () const inline
get types
Definition at line 183 of file AstComponent.h.
References souffle::toPtrVector(), and types.
{
         return toPtrVector(types);
     }
print()
void souffle::AstComponent::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 341 of file AstComponent.h.
References clauses, ios, souffle::join(), relations, and types.
{
         os << ".comp " << *componentType << " ";
         if (!baseComponents.empty()) {
             os << ": " << join(baseComponents, ",", print_deref<std::unique_ptr<AstComponentType>>()) << " ";
         }
         os << "{\n";
         if (!components.empty()) {
             os << join(components, "\n", print_deref<std::unique_ptr<AstComponent>>()) << "\n";
         }
         if (!instantiations.empty()) {
             os << join(instantiations, "\n", print_deref<std::unique_ptr<AstComponentInit>>()) << "\n";
         }
         if (!types.empty()) {
             os << join(types, "\n", print_deref<std::unique_ptr<AstType>>()) << "\n";
         }
         if (!relations.empty()) {
             os << join(relations, "\n", print_deref<std::unique_ptr<AstRelation>>()) << "\n";
         }
         if (!overrideRules.empty()) {
             os << ".override ";
             os << join(overrideRules, ",") << "\n";
         }
         if (!clauses.empty()) {
             os << join(clauses, "\n\n", print_deref<std::unique_ptr<AstClause>>()) << "\n";
         }
         if (!ios.empty()) {
             os << join(ios, "\n\n", print_deref<std::unique_ptr<AstIO>>()) << "\n";
         }
         os << "}\n";
     }
setComponentType()
void souffle::AstComponent::setComponentType (std::unique_ptr< AstComponentType > other) inline
set component type
Definition at line 163 of file AstComponent.h.
{
         componentType = std::move(other);
     }
Field Documentation
baseComponents
std::vector<std::unique_ptr<AstComponentType> > souffle::AstComponent::baseComponents protected
base components of component
Definition at line 410 of file AstComponent.h.
clauses
std::vector<std::unique_ptr<AstClause> > souffle::AstComponent::clauses protected
clauses
Definition at line 419 of file AstComponent.h.
components
std::vector<std::unique_ptr<AstComponent> > souffle::AstComponent::components protected
nested components
Definition at line 425 of file AstComponent.h.
componentType
std::unique_ptr<AstComponentType> souffle::AstComponent::componentType protected
name of component and its formal component arguments.
Definition at line 407 of file AstComponent.h.
instantiations
std::vector<std::unique_ptr<AstComponentInit> > souffle::AstComponent::instantiations protected
nested component instantiations.
Definition at line 428 of file AstComponent.h.
ios
std::vector<std::unique_ptr<AstIO> > souffle::AstComponent::ios protected
I/O directives.
Definition at line 422 of file AstComponent.h.
overrideRules
std::set<std::string> souffle::AstComponent::overrideRules protected
clauses of relations that are overwritten by this component
Definition at line 431 of file AstComponent.h.
relations
std::vector<std::unique_ptr<AstRelation> > souffle::AstComponent::relations protected
relations
Definition at line 416 of file AstComponent.h.
types
std::vector<std::unique_ptr<AstType> > souffle::AstComponent::types protected
types declarations
Definition at line 413 of file AstComponent.h.
The documentation for this class was generated from the following file:
AstComponent.h