souffle: souffle::TypeAnalysis Class Reference
souffle::TypeAnalysis Class Reference
#include <AstTypeAnalysis.h>
Public Member Functions
TypeSet const & getTypes (const AstArgument *argument) const
Get the computed types for the given argument.
void print (std::ostream &os) const override
print the analysis result in HTML format
void run (const AstTranslationUnit &translationUnit) override
run analysis for a Ast translation unit
TypeAnalysis ()
Public Member Functions inherited from souffle::AstAnalysis
AstAnalysis (std::string identifier)
virtual const std::string & getName () const
get name of the analysis
virtual ~AstAnalysis ()=default
Static Public Member Functions
static std::map< const AstArgument *, TypeSet > analyseTypes (const TypeEnvironment &env, const AstClause &clause, const AstProgram *program, std::ostream *logs=nullptr)
Analyse the given clause and computes for each contained argument a set of potential types.
Static Public Attributes
static constexpr const char * name = "type-analysis"
Private Attributes
std::stringstream analysisLogs
std::vector< std::unique_ptr< AstClause > > annotatedClauses
std::map< const AstArgument *, TypeSet > argumentTypes
Additional Inherited Members
Protected Attributes inherited from souffle::AstAnalysis
const std::string identifier
Detailed Description
Definition at line 35 of file AstTypeAnalysis.h.
Constructor & Destructor Documentation
TypeAnalysis()
souffle::TypeAnalysis::TypeAnalysis () inline
Definition at line 39 of file AstTypeAnalysis.h.
References print(), and run().
 : AstAnalysis(name) {}
Member Function Documentation
analyseTypes()
std::map< const AstArgument *, TypeSet > souffle::TypeAnalysis::analyseTypes (const TypeEnvironment & env, const AstClause & clause, const AstProgram * program, std::ostream * logs = nullptr) static
Analyse the given clause and computes for each contained argument a set of potential types.
Generic type analysis framework for clauses.
If the set associated to an argument is empty, no consistent typing can be found and the rule can not be properly typed.
Parameters
env a typing environment describing the set of available types
clause the clause to be typed
program the program
Returns
a map mapping each contained argument to a a set of types
Definition at line 517 of file AstTypeAnalysis.cpp.
References souffle::canBeParsedAsRamFloat(), souffle::canBeParsedAsRamSigned(), souffle::canBeParsedAsRamUnsigned(), souffle::COUNT, e, souffle::Float, souffle::AstNumericConstant::Float, souffle::AstFunctor::getArgType(), souffle::AstAtom::getArguments(), souffle::AstTerm::getArguments(), souffle::AstNegation::getAtom(), souffle::getAtomRelation(), souffle::AstConstant::getConstant(), souffle::TypeEnvironment::getFloatType(), souffle::AstBinaryConstraint::getLHS(), souffle::TypeEnvironment::getNumberType(), souffle::TypeEnvironment::getNumericTypes(), souffle::AstAggregator::getOperator(), souffle::AstFunctor::getReturnType(), souffle::AstBinaryConstraint::getRHS(), souffle::TypeEnvironment::getSymbolType(), souffle::AstAggregator::getTargetExpression(), souffle::AstNumericConstant::getType(), souffle::TypeEnvironment::getType(), souffle::TypeEnvironment::getUnsignedType(), i, souffle::TypeSet::insert(), souffle::AstNumericConstant::Int, souffle::isOverloadedFunctor(), souffle::isSubtypeOf(), souffle::TypeEnvironment::isType(), lhs, souffle::MEAN, souffle::ORD, rhs, souffle::Signed, souffle::Symbol, souffle::AstNumericConstant::Uint, and souffle::Unsigned.
Referenced by getTypes(), and souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries().
{
     struct Analysis : public AstConstraintAnalysis<TypeVar> {
         const TypeEnvironment& env;
         const AstProgram* program;
         std::set<const AstAtom*> negated;
         Analysis(const TypeEnvironment& env, const AstProgram* program) : env(env), program(program) {}
         // predicate
         void visitAtom(const AstAtom& atom) override {
             // get relation
             auto rel = getAtomRelation(&atom, program);
             if (rel == nullptr) {
                 return;  // error in input program
             }
             auto atts = rel->getAttributes();
             auto args = atom.getArguments();
             if (atts.size() != args.size()) {
                 return;  // error in input program
             }
             // set upper boundary of argument types
             for (unsigned i = 0; i < atts.size(); i++) {
                 const auto& typeName = atts[i]->getTypeName();
                 if (env.isType(typeName)) {
                     // check whether atom is not negated
                     if (negated.find(&atom) == negated.end()) {
                         addConstraint(isSubtypeOf(getVar(args[i]), env.getType(typeName)));
                     } else {
                         addConstraint(isSupertypeOf(getVar(args[i]), env.getType(typeName)));
                     }
                 }
             }
         }
         // negations need to be skipped
         void visitNegation(const AstNegation& cur) override {
             // add nested atom to black-list
             negated.insert(cur.getAtom());
         }
         // symbol
         void visitStringConstant(const AstStringConstant& cnst) override {
             addConstraint(isSubtypeOf(getVar(cnst), env.getSymbolType()));
         }
         // Numeric constant
         void visitNumericConstant(const AstNumericConstant& constant) override {
             TypeSet possibleTypes;
             // Check if the type is given.
             if (constant.getType().has_value()) {
                 switch (*constant.getType()) {
                     // Insert a type, but only after checking that parsing is possible.
                     case AstNumericConstant::Type::Int:
                         if (canBeParsedAsRamSigned(constant.getConstant())) {
                             possibleTypes.insert(env.getNumberType());
                         }
                         break;
                     case AstNumericConstant::Type::Uint:
                         if (canBeParsedAsRamUnsigned(constant.getConstant())) {
                             possibleTypes.insert(env.getUnsignedType());
                         }
                         break;
                     case AstNumericConstant::Type::Float:
                         if (canBeParsedAsRamFloat(constant.getConstant())) {
                             possibleTypes.insert(env.getFloatType());
                         }
                         break;
                 }
                 // Else: all numeric types that can be parsed are valid.
             } else {
                 if (canBeParsedAsRamSigned(constant.getConstant())) {
                     possibleTypes.insert(env.getNumberType());
                 }
                 if (canBeParsedAsRamUnsigned(constant.getConstant())) {
                     possibleTypes.insert(env.getUnsignedType());
                 }
                 if (canBeParsedAsRamFloat(constant.getConstant())) {
                     possibleTypes.insert(env.getFloatType());
                 }
             }
             addConstraint(hasSuperTypeInSet(getVar(constant), possibleTypes));
         }
         // binary constraint
         void visitBinaryConstraint(const AstBinaryConstraint& rel) override {
             auto lhs = getVar(rel.getLHS());
             auto rhs = getVar(rel.getRHS());
             addConstraint(isSubtypeOf(lhs, rhs));
             addConstraint(isSubtypeOf(rhs, lhs));
         }
         // intrinsic functor
         void visitFunctor(const AstFunctor& fun) override {
             auto functorVar = getVar(fun);
             // In polymorphic case
             // We only require arguments to share a base type with a return type.
             // (instead of, for example, requiring them to be of the same type)
             // This approach is related to old type semantics
             // See #1296 and tests/semantic/type_system4
             if (auto intrinsicFunctor = dynamic_cast<const AstIntrinsicFunctor*>(&fun)) {
                 if (isOverloadedFunctor(intrinsicFunctor->getFunction())) {
                     for (auto* argument : intrinsicFunctor->getArguments()) {
                         auto argumentVar = getVar(argument);
                         addConstraint(subtypesOfTheSameBaseType(argumentVar, functorVar));
                     }
                     return;
                 }
             }
             try {
                 fun.getReturnType();
             } catch (std::bad_optional_access& e) {
                 return;
             }
             // add a constraint for the return type of the functor
             switch (fun.getReturnType()) {
                 case TypeAttribute::Signed:
                     addConstraint(isSubtypeOf(functorVar, env.getNumberType()));
                     break;
                 case TypeAttribute::Float:
                     addConstraint(isSubtypeOf(functorVar, env.getFloatType()));
                     break;
                 case TypeAttribute::Unsigned:
                     addConstraint(isSubtypeOf(functorVar, env.getUnsignedType()));
                     break;
                 case TypeAttribute::Symbol:
                     addConstraint(isSubtypeOf(functorVar, env.getSymbolType()));
                     break;
                 default:
                     assert(false && "Invalid return type");
             }
             // Special case
             if (auto intrFun = dynamic_cast<const AstIntrinsicFunctor*>(&fun)) {
                 if (intrFun->getFunction() == FunctorOp::ORD) {
                     return;
                 }
             }
             size_t i = 0;
             for (auto arg : fun.getArguments()) {
                 auto argumentVar = getVar(arg);
                 switch (fun.getArgType(i)) {
                     case TypeAttribute::Signed:
                         addConstraint(isSubtypeOf(argumentVar, env.getNumberType()));
                         break;
                     case TypeAttribute::Float:
                         addConstraint(isSubtypeOf(argumentVar, env.getFloatType()));
                         break;
                     case TypeAttribute::Unsigned:
                         addConstraint(isSubtypeOf(argumentVar, env.getUnsignedType()));
                         break;
                     case TypeAttribute::Symbol:
                         addConstraint(isSubtypeOf(argumentVar, env.getSymbolType()));
                         break;
                     default:
                         assert(false && "Invalid argument type");
                 }
                 ++i;
             }
         }
         // counter
         void visitCounter(const AstCounter& counter) override {
             // this value must be a number value
             addConstraint(isSubtypeOf(getVar(counter), env.getNumberType()));
         }
         // components of records
         void visitRecordInit(const AstRecordInit& init) override {
             // link element types with sub-values
             auto rec = getVar(init);
             int i = 0;
             for (const AstArgument* value : init.getArguments()) {
                 addConstraint(isSubtypeOfComponent(getVar(value), rec, i++));
             }
         }
         // visit aggregates
         void visitAggregator(const AstAggregator& agg) override {
             if (agg.getOperator() == AggregateOp::COUNT) {
                 addConstraint(isSubtypeOf(getVar(agg), env.getNumberType()));
             } else if (agg.getOperator() == AggregateOp::MEAN) {
                 addConstraint(isSubtypeOf(getVar(agg), env.getFloatType()));
             } else {
                 addConstraint(hasSuperTypeInSet(getVar(agg), env.getNumericTypes()));
             }
             // If there is a target expression - it should be of the same type as the aggregator.
             if (auto expr = agg.getTargetExpression()) {
                 addConstraint(isSubtypeOf(getVar(expr), getVar(agg)));
                 addConstraint(isSubtypeOf(getVar(agg), getVar(expr)));
             }
         }
     };
     // run analysis
     return Analysis(env, program).analyse(clause, logs);
 }
getTypes()
TypeSet const& souffle::TypeAnalysis::getTypes (const AstArgument * argument) const inline
Get the computed types for the given argument.
Definition at line 48 of file AstTypeAnalysis.h.
References analyseTypes(), and argumentTypes.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::ResolveAnonymousRecordsAliases::findVariablesRecordMapping(), and souffle::PolymorphicObjectsTransformer::transform().
{
         return argumentTypes.at(argument);
     }
print()
void souffle::TypeAnalysis::print (std::ostream &) const override virtual
print the analysis result in HTML format
Reimplemented from souffle::AstAnalysis.
Definition at line 504 of file AstTypeAnalysis.cpp.
Referenced by TypeAnalysis().
{
     os << "-- Analysis logs --" << std::endl;
     os << analysisLogs.str() << std::endl;
     os << "-- Result --" << std::endl;
     for (const auto& cur : annotatedClauses) {
         os << *cur << std::endl;
     }
 }
run()
void souffle::TypeAnalysis::run (const AstTranslationUnit &) override virtual
run analysis for a Ast translation unit
Implements souffle::AstAnalysis.
Definition at line 479 of file AstTypeAnalysis.cpp.
References souffle::Global::config(), souffle::createAnnotatedClause(), souffle::AstTranslationUnit::getAnalysis(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), and souffle::AstProgram::getRelations().
Referenced by TypeAnalysis().
{
     // Check if debugging information is being generated and note where logs should be sent
     std::ostream* debugStream = nullptr;
     if (Global::config().has("debug-report") || Global::config().get("show") == "type-analysis") {
         debugStream = &analysisLogs;
     }
     const auto& program = *translationUnit.getProgram();
     auto* typeEnvAnalysis = translationUnit.getAnalysis<TypeEnvironmentAnalysis>();
     for (const AstRelation* rel : translationUnit.getProgram()->getRelations()) {
         for (const AstClause* clause : getClauses(program, *rel)) {
             // Perform the type analysis
             std::map<const AstArgument*, TypeSet> clauseArgumentTypes =
                     analyseTypes(typeEnvAnalysis->getTypeEnvironment(), *clause, translationUnit.getProgram(),
                             debugStream);
             argumentTypes.insert(clauseArgumentTypes.begin(), clauseArgumentTypes.end());
             if (debugStream != nullptr) {
                 // Store an annotated clause for printing purposes
                 AstClause* annotatedClause = createAnnotatedClause(clause, clauseArgumentTypes);
                 annotatedClauses.emplace_back(annotatedClause);
             }
         }
     }
 }
Field Documentation
analysisLogs
std::stringstream souffle::TypeAnalysis::analysisLogs private
Definition at line 68 of file AstTypeAnalysis.h.
annotatedClauses
std::vector<std::unique_ptr<AstClause> > souffle::TypeAnalysis::annotatedClauses private
Definition at line 67 of file AstTypeAnalysis.h.
argumentTypes
std::map<const AstArgument*, TypeSet> souffle::TypeAnalysis::argumentTypes private
Definition at line 66 of file AstTypeAnalysis.h.
Referenced by getTypes().
name
constexpr const char* souffle::TypeAnalysis::name = "type-analysis" static
Definition at line 37 of file AstTypeAnalysis.h.
The documentation for this class was generated from the following files:
AstTypeAnalysis.h
AstTypeAnalysis.cpp