souffle: souffle::ProvenanceTransformer Class Reference
souffle::ProvenanceTransformer Class Reference
Transformation pass to add provenance information.
#include <AstTransforms.h>
Public Member Functions
std::string getName () const override
Public Member Functions inherited from souffle::AstTransformer
bool apply (AstTranslationUnit &translationUnit)
virtual ~AstTransformer ()=default
Private Member Functions
bool transform (AstTranslationUnit &translationUnit) override
bool transformMaxHeight (AstTranslationUnit &translationUnit)
bool transformSubtreeHeights (AstTranslationUnit &translationUnit)
Detailed Description
Transformation pass to add provenance information.
Definition at line 212 of file AstTransforms.h.
Member Function Documentation
getName()
std::string souffle::ProvenanceTransformer::getName () const inline override virtual
Implements souffle::AstTransformer.
Definition at line 214 of file AstTransforms.h.
References souffle::ResolveAliasesTransformer::transform().
{
         return "ProvenanceTransformer";
     }
transform()
bool souffle::ProvenanceTransformer::transform (AstTranslationUnit & translationUnit) override private virtual
Implements souffle::AstTransformer.
Definition at line 494 of file ProvenanceTransformer.cpp.
References souffle::Global::config(), transformMaxHeight(), and transformSubtreeHeights().
{
     if (Global::config().get("provenance") == "subtreeHeights") {
         return ProvenanceTransformer::transformSubtreeHeights(translationUnit);
     } else {
         return ProvenanceTransformer::transformMaxHeight(translationUnit);
     }
 }
transformMaxHeight()
bool souffle::ProvenanceTransformer::transformMaxHeight (AstTranslationUnit & translationUnit) private
Definition at line 387 of file ProvenanceTransformer.cpp.
References souffle::ADD, souffle::EQREL, souffle::getClauseNum(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), i, souffle::isFact(), souffle::makeInfoRelation(), souffle::MAX, relation, and souffle::transformEqrelRelation().
Referenced by transform().
{
     auto program = translationUnit.getProgram();
     // get next level number
     auto getNextLevelNumber = [&](std::vector<AstArgument*> levels) {
         if (levels.empty()) {
             return static_cast<AstArgument*>(new AstNumericConstant(0));
         }
         if (levels.size() == 1) {
             return static_cast<AstArgument*>(new AstIntrinsicFunctor(FunctorOp::ADD,
                     std::unique_ptr<AstArgument>(levels[0]), std::make_unique<AstNumericConstant>(1)));
         }
         auto currentMax = new AstIntrinsicFunctor(FunctorOp::MAX, std::unique_ptr<AstArgument>(levels[0]),
                 std::unique_ptr<AstArgument>(levels[1]));
         for (size_t i = 2; i < levels.size(); i++) {
             currentMax = new AstIntrinsicFunctor(FunctorOp::MAX, std::unique_ptr<AstArgument>(currentMax),
                     std::unique_ptr<AstArgument>(levels[i]));
         }
         return static_cast<AstArgument*>(new AstIntrinsicFunctor(FunctorOp::ADD,
                 std::unique_ptr<AstArgument>(currentMax), std::make_unique<AstNumericConstant>(1)));
     };
     for (auto relation : program->getRelations()) {
         if (relation->getRepresentation() == RelationRepresentation::EQREL) {
             // Explicitly expand eqrel relation
             transformEqrelRelation(*program, *relation);
         }
     }
     for (auto relation : program->getRelations()) {
         // generate info relations for each clause
         // do this before all other transformations so that we record
         // the original rule without any instrumentation
         for (auto clause : getClauses(*program, *relation)) {
             if (!isFact(*clause)) {
                 // add info relation
                 program->addRelation(
                         makeInfoRelation(*clause, getClauseNum(program, clause), translationUnit));
             }
         }
         relation->addAttribute(
                 std::make_unique<AstAttribute>(std::string("@rule_number"), AstQualifiedName("number")));
         relation->addAttribute(
                 std::make_unique<AstAttribute>(std::string("@level_number"), AstQualifiedName("number")));
         for (auto clause : getClauses(*program, *relation)) {
             size_t clauseNum = getClauseNum(program, clause);
             // mapper to add two provenance columns to atoms
             struct M : public AstNodeMapper {
                 using AstNodeMapper::operator();
                 std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
                     // add provenance columns
                     if (auto atom = dynamic_cast<AstAtom*>(node.get())) {
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     } else if (auto neg = dynamic_cast<AstNegation*>(node.get())) {
                         auto atom = neg->getAtom();
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     }
                     // otherwise - apply mapper recursively
                     node->apply(*this);
                     return node;
                 }
             };
             // add unnamed vars to each atom nested in arguments of head
             clause->getHead()->apply(M());
             // if fact, level number is 0
             if (isFact(*clause)) {
                 clause->getHead()->addArgument(std::make_unique<AstNumericConstant>(0));
                 clause->getHead()->addArgument(std::make_unique<AstNumericConstant>(0));
             } else {
                 std::vector<AstArgument*> bodyLevels;
                 for (size_t i = 0; i < clause->getBodyLiterals().size(); i++) {
                     auto lit = clause->getBodyLiterals()[i];
                     // add unnamed vars to each atom nested in arguments of lit
                     lit->apply(M());
                     // add two provenance columns to lit; first is rule num, second is level num
                     if (auto atom = dynamic_cast<AstAtom*>(lit)) {
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                         atom->addArgument(std::make_unique<AstVariable>("@level_num_" + std::to_string(i)));
                         bodyLevels.push_back(new AstVariable("@level_num_" + std::to_string(i)));
                     }
                 }
                 // add two provenance columns to head lit
                 clause->getHead()->addArgument(std::make_unique<AstNumericConstant>(clauseNum));
                 clause->getHead()->addArgument(std::unique_ptr<AstArgument>(getNextLevelNumber(bodyLevels)));
             }
         }
     }
     return true;
 }
transformSubtreeHeights()
bool souffle::ProvenanceTransformer::transformSubtreeHeights (AstTranslationUnit & translationUnit) private
Definition at line 249 of file ProvenanceTransformer.cpp.
References souffle::ADD, souffle::EQREL, souffle::AstTranslationUnit::getAnalysis(), souffle::getClauseNum(), souffle::getClauses(), souffle::AstTranslationUnit::getProgram(), i, souffle::isFact(), j, souffle::makeInfoRelation(), souffle::makeLambdaAstMapper(), souffle::MAX, relation, and souffle::transformEqrelRelation().
Referenced by transform().
{
     static auto program = translationUnit.getProgram();
     const auto& auxArityAnalysis = *translationUnit.getAnalysis<AuxiliaryArity>();
     // get next level number
     auto getNextLevelNumber = [&](std::vector<AstArgument*> levels) {
         if (levels.empty()) {
             return static_cast<AstArgument*>(new AstNumericConstant(0));
         }
         if (levels.size() == 1) {
             return static_cast<AstArgument*>(new AstIntrinsicFunctor(FunctorOp::ADD,
                     std::unique_ptr<AstArgument>(levels[0]), std::make_unique<AstNumericConstant>(1)));
         }
         auto currentMax = new AstIntrinsicFunctor(FunctorOp::MAX, std::unique_ptr<AstArgument>(levels[0]),
                 std::unique_ptr<AstArgument>(levels[1]));
         for (size_t i = 2; i < levels.size(); i++) {
             currentMax = new AstIntrinsicFunctor(FunctorOp::MAX, std::unique_ptr<AstArgument>(currentMax),
                     std::unique_ptr<AstArgument>(levels[i]));
         }
         return static_cast<AstArgument*>(new AstIntrinsicFunctor(FunctorOp::ADD,
                 std::unique_ptr<AstArgument>(currentMax), std::make_unique<AstNumericConstant>(1)));
     };
     for (auto relation : program->getRelations()) {
         if (relation->getRepresentation() == RelationRepresentation::EQREL) {
             // Explicitly expand eqrel relation
             transformEqrelRelation(*program, *relation);
         }
     }
     for (auto relation : program->getRelations()) {
         // generate info relations for each clause
         // do this before all other transformations so that we record
         // the original rule without any instrumentation
         for (auto clause : getClauses(*program, *relation)) {
             if (!isFact(*clause)) {
                 // add info relation
                 program->addRelation(
                         makeInfoRelation(*clause, getClauseNum(program, clause), translationUnit));
             }
         }
         relation->addAttribute(
                 std::make_unique<AstAttribute>(std::string("@rule_number"), AstQualifiedName("number")));
         relation->addAttribute(
                 std::make_unique<AstAttribute>(std::string("@level_number"), AstQualifiedName("number")));
         for (size_t i = 0; i < auxArityAnalysis.getArity(relation) - 2; i++) {
             relation->addAttribute(std::make_unique<AstAttribute>(
                     std::string("@sublevel_number_" + std::to_string(i)), AstQualifiedName("number")));
         }
         for (auto clause : getClauses(*program, *relation)) {
             size_t clauseNum = getClauseNum(program, clause);
             std::function<std::unique_ptr<AstNode>(std::unique_ptr<AstNode>)> rewriter =
                     [&](std::unique_ptr<AstNode> node) -> std::unique_ptr<AstNode> {
                 // add provenance columns
                 if (auto atom = dynamic_cast<AstAtom*>(node.get())) {
                     // rule number
                     atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     // max level
                     atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     // level number
                     for (size_t i = 0; i < auxArityAnalysis.getArity(atom) - 2; i++) {
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     }
                 } else if (auto neg = dynamic_cast<AstNegation*>(node.get())) {
                     auto atom = neg->getAtom();
                     // rule number
                     atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     // max level
                     atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     // level number
                     for (size_t i = 0; i < auxArityAnalysis.getArity(atom) - 2; i++) {
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                     }
                 }
                 // otherwise - apply mapper recursively
                 node->apply(makeLambdaAstMapper(rewriter));
                 return node;
             };
             // add unnamed vars to each atom nested in arguments of head
             clause->getHead()->apply(makeLambdaAstMapper(rewriter));
             // if fact, level number is 0
             if (isFact(*clause)) {
                 clause->getHead()->addArgument(std::make_unique<AstNumericConstant>(0));
                 for (size_t i = 0; i < auxArityAnalysis.getArity(relation) - 1; i++) {
                     clause->getHead()->addArgument(std::make_unique<AstNumericConstant>(0));
                 }
             } else {
                 std::vector<AstArgument*> bodyLevels;
                 for (size_t i = 0; i < clause->getBodyLiterals().size(); i++) {
                     auto lit = clause->getBodyLiterals()[i];
                     // add unnamed vars to each atom nested in arguments of lit
                     lit->apply(makeLambdaAstMapper(rewriter));
                     // add provenance columns to lit; first rule num, then level nums
                     if (auto atom = dynamic_cast<AstAtom*>(lit)) {
                         // rule num
                         atom->addArgument(std::make_unique<AstUnnamedVariable>());
                         atom->addArgument(
                                 std::make_unique<AstVariable>("@level_number_" + std::to_string(i)));
                         // level nums
                         for (size_t j = 0; j < auxArityAnalysis.getArity(atom) - 2; j++) {
                             atom->addArgument(std::make_unique<AstUnnamedVariable>());
                         }
                         bodyLevels.push_back(new AstVariable("@level_number_" + std::to_string(i)));
                     }
                 }
                 // add provenance columns to head lit
                 // rule number
                 clause->getHead()->addArgument(std::make_unique<AstNumericConstant>(clauseNum));
                 // max level
                 clause->getHead()->addArgument(std::unique_ptr<AstArgument>(getNextLevelNumber(bodyLevels)));
                 // level numbers
                 size_t numAtoms = getBodyLiterals<AstAtom>(*clause).size();
                 for (size_t j = 0; j < numAtoms; j++) {
                     clause->getHead()->addArgument(
                             std::make_unique<AstVariable>("@level_number_" + std::to_string(j)));
                 }
                 for (size_t j = numAtoms; j < auxArityAnalysis.getArity(relation) - 2; j++) {
                     clause->getHead()->addArgument(std::make_unique<AstNumericConstant>(-1));
                 }
             }
         }
     }
     return true;
 }
The documentation for this class was generated from the following files:
AstTransforms.h
ProvenanceTransformer.cpp