souffle: souffle::TypeEnvironment Class Reference
souffle::TypeEnvironment Class Reference
A type environment is a set of types.
#include <TypeSystem.h>
Public Member Functions
void clear ()
RecordType & createRecordType (const AstQualifiedName &name)
SubsetType & createSubsetType (const AstQualifiedName &name, TypeAttribute typeAttribute)
template<typename T , typename... Args>
T & createType (const AstQualifiedName &name, const Args &... args)
UnionType & createUnionType (const AstQualifiedName &name)
TypeSet getAllTypes () const
const Type & getFloatType () const
Type * getModifiableType (const AstQualifiedName &name)
const Type & getNumberType () const
const TypeSet & getNumericTypes () const
const TypeSet & getPredefinedTypes () const
const Type & getSymbolType () const
const Type & getType (const AstQualifiedName &) const
const Type & getUnsignedType () const
bool isPredefinedType (const AstQualifiedName &identifier) const
bool isPredefinedType (const Type &typeName) const
bool isType (const AstQualifiedName &) const
bool isType (const Type &type) const
void print (std::ostream &out) const
void swap (TypeEnvironment &env)
TypeEnvironment ()
TypeEnvironment (const TypeEnvironment &)=delete
~TypeEnvironment ()
Private Member Functions
void addType (Type &type)
Register types created by one of the factory functions.
TypeSet initializePredefinedTypes (void)
Private Attributes
const TypeSet predefinedNumericTypes
const TypeSet predefinedTypes
std::map< AstQualifiedName, Type * > types
The list of covered types.
Friends
std::ostream & operator<< (std::ostream &out, const TypeEnvironment &environment)
Detailed Description
A type environment is a set of types.
It's main purpose is to provide an enumeration of all all types within a given program. Additionally, it manages the life cycle of type instances.
Definition at line 332 of file TypeSystem.h.
Constructor & Destructor Documentation
TypeEnvironment() [1/2]
souffle::TypeEnvironment::TypeEnvironment () inline
Definition at line 335 of file TypeSystem.h.
             : types(), predefinedTypes(initializePredefinedTypes()),
               predefinedNumericTypes(TypeSet(getType("number"), getType("float"), getType("unsigned"))){};
TypeEnvironment() [2/2]
souffle::TypeEnvironment::TypeEnvironment (const TypeEnvironment &) delete
~TypeEnvironment()
souffle::TypeEnvironment::~TypeEnvironment ()
Definition at line 64 of file TypeSystem.cpp.
References types.
{
     for (const auto& cur : types) {
         delete cur.second;
     }
 }
Member Function Documentation
addType()
void souffle::TypeEnvironment::addType (Type & type) private
Register types created by one of the factory functions.
Definition at line 108 of file TypeSystem.cpp.
References souffle::Type::getName(), souffle::Type::name, and types.
{
     const AstQualifiedName& name = type.getName();
     assert(types.find(name) == types.end() && "Error: registering present type!");
     types[name] = &type;
 }
clear()
void souffle::TypeEnvironment::clear ()
Definition at line 70 of file TypeSystem.cpp.
References types.
{
     // clear list of stored types
     for (const auto& cur : types) {
         delete cur.second;
     }
     types.clear();
     // Reinitialize predefined types
     initializePredefinedTypes();
 }
createRecordType()
RecordType& souffle::TypeEnvironment::createRecordType (const AstQualifiedName & name) inline
Definition at line 372 of file TypeSystem.h.
References souffle::getType(), and souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<RecordType>(name);
     }
createSubsetType()
SubsetType& souffle::TypeEnvironment::createSubsetType (const AstQualifiedName & name, TypeAttribute typeAttribute) inline
Definition at line 352 of file TypeSystem.h.
References souffle::Float, souffle::Type::name, souffle::Record, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         switch (typeAttribute) {
             case TypeAttribute::Signed:
                 return createType<SubsetType>(name, getNumberType());
             case TypeAttribute::Unsigned:
                 return createType<SubsetType>(name, getUnsignedType());
             case TypeAttribute::Float:
                 return createType<SubsetType>(name, getFloatType());
             case TypeAttribute::Symbol:
                 return createType<SubsetType>(name, getSymbolType());
             case TypeAttribute::Record:
                 assert(false && "Invalid type attribute");
         }
         return createType<SubsetType>(name, getNumberType());
     }
createType()
template<typename T , typename... Args> T& souffle::TypeEnvironment::createType (const AstQualifiedName & name, const Args &... args) inline
Definition at line 346 of file TypeSystem.h.
{
         auto* res = new T(*this, name, args...);
         addType(*res);
         return *res;
     }
createUnionType()
UnionType& souffle::TypeEnvironment::createUnionType (const AstQualifiedName & name) inline
Definition at line 368 of file TypeSystem.h.
References souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
         return createType<UnionType>(name);
     }
getAllTypes()
TypeSet souffle::TypeEnvironment::getAllTypes () const
Definition at line 100 of file TypeSystem.cpp.
References souffle::TypeSet::insert(), and types.
Referenced by souffle::getLeastCommonSupertypes().
{
     TypeSet res;
     for (const auto& cur : types) {
         res.insert(*cur.second);
     }
     return res;
 }
getFloatType()
const Type& souffle::TypeEnvironment::getFloatType () const inline
Definition at line 392 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::isFloatType().
{
         return getType("float");
     }
getModifiableType()
Type * souffle::TypeEnvironment::getModifiableType (const AstQualifiedName & name)
Definition at line 90 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     auto pos = types.find(name);
     return (pos == types.end()) ? nullptr : pos->second;
 }
getNumberType()
const Type& souffle::TypeEnvironment::getNumberType () const inline
Definition at line 384 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::isNumberType(), and souffle::isSubtypeOf().
{
         return getType("number");
     }
getNumericTypes()
const TypeSet& souffle::TypeEnvironment::getNumericTypes () const inline
Definition at line 416 of file TypeSystem.h.
References souffle::Type::name, and souffle::Type::print().
Referenced by souffle::TypeAnalysis::analyseTypes().
{
         return predefinedNumericTypes;
     }
getPredefinedTypes()
const TypeSet& souffle::TypeEnvironment::getPredefinedTypes () const inline
Definition at line 412 of file TypeSystem.h.
{
         return predefinedTypes;
     }
getSymbolType()
const Type& souffle::TypeEnvironment::getSymbolType () const inline
Definition at line 396 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::isSubtypeOf(), and souffle::isSymbolType().
{
         return getType("symbol");
     }
getType()
const Type & souffle::TypeEnvironment::getType (const AstQualifiedName & ident) const
Definition at line 95 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeAnalysis::analyseTypes(), souffle::AstTranslator::getRecordsTypes(), souffle::AstTranslator::translateDirectives(), souffle::AstTranslator::translateProgram(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     assert(isType(ident));
     return *(types.find(ident)->second);
 }
getUnsignedType()
const Type& souffle::TypeEnvironment::getUnsignedType () const inline
Definition at line 388 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::isUnsignedType().
{
         return getType("unsigned");
     }
initializePredefinedTypes()
TypeSet souffle::TypeEnvironment::initializePredefinedTypes (void) private
Definition at line 54 of file TypeSystem.cpp.
References souffle::getType().
{
     // initialize predefined types.
     createType<PredefinedType>("number");
     createType<PredefinedType>("float");
     createType<PredefinedType>("symbol");
     createType<PredefinedType>("unsigned");
     return TypeSet(getType("number"), getType("float"), getType("symbol"), getType("unsigned"));
 }
isPredefinedType() [1/2]
bool souffle::TypeEnvironment::isPredefinedType (const AstQualifiedName & identifier) const inline
Definition at line 400 of file TypeSystem.h.
References souffle::getType().
Referenced by souffle::AstSemanticChecker::checkRecordType(), souffle::AstSemanticChecker::checkRelationDeclaration(), and souffle::AstSemanticChecker::checkUnionType().
{
         if (isType(identifier)) {
             return isPredefinedType(getType(identifier));
         } else {
             return false;
         }
     }
isPredefinedType() [2/2]
bool souffle::TypeEnvironment::isPredefinedType (const Type & typeName) const inline
Definition at line 408 of file TypeSystem.h.
{
         return predefinedTypes.contains(typeName);
     }
isType() [1/2]
bool souffle::TypeEnvironment::isType (const AstQualifiedName & ident) const
Definition at line 81 of file TypeSystem.cpp.
References types.
Referenced by souffle::UnionType::add(), souffle::RecordType::add(), souffle::TypeAnalysis::analyseTypes(), souffle::getGreatestCommonSubtypes(), souffle::getLeastCommonSupertypes(), souffle::isSubtypeOf(), and souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     return types.find(ident) != types.end();
 }
isType() [2/2]
bool souffle::TypeEnvironment::isType (const Type & type) const
Definition at line 85 of file TypeSystem.cpp.
References souffle::Type::getName(), and souffle::getType().
{
     const Type& t = getType(type.getName());
     return t == type;
 }
print()
void souffle::TypeEnvironment::print (std::ostream & out) const
Definition at line 439 of file TypeSystem.cpp.
References types.
Referenced by souffle::TypeEnvironmentAnalysis::print().
{
     out << "Types:\n";
     for (const auto& cur : types) {
         out << "\t" << *cur.second << "\n";
     }
 }
swap()
void souffle::TypeEnvironment::swap (TypeEnvironment & env) inline
Definition at line 433 of file TypeSystem.h.
References types, and types.
{
         types.swap(env.types);
     }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const TypeEnvironment & environment) friend
Definition at line 428 of file TypeSystem.h.
{
         environment.print(out);
         return out;
     }
Field Documentation
predefinedNumericTypes
const TypeSet souffle::TypeEnvironment::predefinedNumericTypes private
Definition at line 448 of file TypeSystem.h.
predefinedTypes
const TypeSet souffle::TypeEnvironment::predefinedTypes private
Definition at line 446 of file TypeSystem.h.
types
std::map<AstQualifiedName, Type*> souffle::TypeEnvironment::types private
The list of covered types.
Definition at line 444 of file TypeSystem.h.
Referenced by swap().
The documentation for this class was generated from the following files:
TypeSystem.h
TypeSystem.cpp