souffle: souffle::AstFunctorDeclaration Class Reference
souffle::AstFunctorDeclaration Class Reference
AstFunctorDeclaration.
#include <AstFunctorDeclaration.h>
Public Member Functions
AstFunctorDeclaration (const std::string &name, std::vector< TypeAttribute > argsTypes, TypeAttribute returnType)
AstFunctorDeclaration * clone () const override
clone
const std::vector< TypeAttribute > & getArgsTypes () const
get type
size_t getArity () const
get number of arguments
const std::string & getName () const
get name
TypeAttribute getReturnType () const
Public Member Functions inherited from souffle::AstNode
virtual void apply (const AstNodeMapper &)
Apply the mapper to all child nodes.
AstNode ()=default
std::string extloc () const
Return source location of the syntactic element.
virtual std::vector< const AstNode * > getChildNodes () const
Obtain a list of all embedded AST child nodes.
SrcLocation getSrcLoc () const
Return source location of the AstNode.
bool operator!= (const AstNode &other) const
Inequality check for two AST nodes.
bool operator== (const AstNode &other) const
Equivalence check for two AST nodes.
void setSrcLoc (const SrcLocation &l)
Set source location for the AstNode.
virtual ~AstNode ()=default
Protected Member Functions
bool equal (const AstNode &node) const override
Abstract equality check for two AST nodes.
void print (std::ostream &out) const override
Output to a given output stream.
Protected Attributes
const std::vector< TypeAttribute > argsTypes
Types of arguments.
const std::string name
name of functor
const TypeAttribute returnType
Type of the return value.
Detailed Description
AstFunctorDeclaration.
Definition at line 33 of file AstFunctorDeclaration.h.
Constructor & Destructor Documentation
AstFunctorDeclaration()
souffle::AstFunctorDeclaration::AstFunctorDeclaration (const std::string & name, std::vector< TypeAttribute > argsTypes, TypeAttribute returnType) inline
Definition at line 35 of file AstFunctorDeclaration.h.
Referenced by clone().
             : name(name), argsTypes(std::move(argsTypes)), returnType(returnType) {
         assert(name.length() > 0 && "functor name is empty");
     }
Member Function Documentation
clone()
AstFunctorDeclaration* souffle::AstFunctorDeclaration::clone () const inline override virtual
clone
Implements souffle::AstNode.
Definition at line 61 of file AstFunctorDeclaration.h.
References argsTypes, AstFunctorDeclaration(), souffle::AstNode::getSrcLoc(), name, and returnType.
{
         auto* res = new AstFunctorDeclaration(name, argsTypes, returnType);
         res->setSrcLoc(getSrcLoc());
         return res;
     }
equal()
bool souffle::AstFunctorDeclaration::equal (const AstNode &) const inline override protected virtual
Abstract equality check for two AST nodes.
Reimplemented from souffle::AstNode.
Definition at line 91 of file AstFunctorDeclaration.h.
References argsTypes, name, and returnType.
{
         const auto& other = static_cast<const AstFunctorDeclaration&>(node);
         return name == other.name && argsTypes == other.argsTypes && returnType == other.returnType;
     }
getArgsTypes()
const std::vector<TypeAttribute>& souffle::AstFunctorDeclaration::getArgsTypes () const inline
get type
Definition at line 47 of file AstFunctorDeclaration.h.
References argsTypes.
Referenced by souffle::AstUserDefinedFunctorsTransformer::transform().
{
         return argsTypes;
     }
getArity()
size_t souffle::AstFunctorDeclaration::getArity () const inline
get number of arguments
Definition at line 56 of file AstFunctorDeclaration.h.
References argsTypes.
Referenced by souffle::AstUserDefinedFunctorsTransformer::transform().
{
         return argsTypes.size();
     }
getName()
const std::string& souffle::AstFunctorDeclaration::getName () const inline
get name
Definition at line 42 of file AstFunctorDeclaration.h.
References name.
{
         return name;
     }
getReturnType()
TypeAttribute souffle::AstFunctorDeclaration::getReturnType () const inline
Definition at line 51 of file AstFunctorDeclaration.h.
References returnType.
Referenced by souffle::AstUserDefinedFunctorsTransformer::transform().
{
         return returnType;
     }
print()
void souffle::AstFunctorDeclaration::print (std::ostream & os) const inline override protected virtual
Output to a given output stream.
Implements souffle::AstNode.
Definition at line 68 of file AstFunctorDeclaration.h.
References argsTypes, souffle::Float, souffle::join(), name, returnType, souffle::Signed, souffle::Symbol, and souffle::Unsigned.
{
         auto convert = [&](TypeAttribute type) {
             switch (type) {
                 case TypeAttribute::Signed:
                     return "number";
                 case TypeAttribute::Symbol:
                     return "symbol";
                 case TypeAttribute::Float:
                     return "float";
                 case TypeAttribute::Unsigned:
                     return "unsigned";
                 default:
                     abort();
             }
         };
         out << ".declfun " << name << "(";
         std::vector<std::string> args(argsTypes.size());
         std::transform(argsTypes.begin(), argsTypes.end(), args.begin(), convert);
         out << join(args, ",");
         out << "):" << convert(returnType) << std::endl;
     }
Field Documentation
argsTypes
const std::vector<TypeAttribute> souffle::AstFunctorDeclaration::argsTypes protected
Types of arguments.
Definition at line 100 of file AstFunctorDeclaration.h.
Referenced by clone(), equal(), getArgsTypes(), getArity(), and print().
name
const std::string souffle::AstFunctorDeclaration::name protected
name of functor
Definition at line 97 of file AstFunctorDeclaration.h.
Referenced by clone(), equal(), getName(), and print().
returnType
const TypeAttribute souffle::AstFunctorDeclaration::returnType protected
Type of the return value.
Definition at line 103 of file AstFunctorDeclaration.h.
Referenced by clone(), equal(), getReturnType(), and print().
The documentation for this class was generated from the following file:
AstFunctorDeclaration.h