souffle: souffle::Order Class Reference
souffle::Order Class Reference
An order to be enforced for storing tuples within indexes.
#include <InterpreterIndex.h>
Public Member Functions
template<std::size_t Arity>
Tuple< RamDomain, Arity > decode (const Tuple< RamDomain, Arity > &entry) const
template<std::size_t Arity>
Tuple< RamDomain, Arity > encode (const Tuple< RamDomain, Arity > &entry) const
const std::vector< int > & getOrder () const
bool operator!= (const Order &other) const
bool operator< (const Order &other) const
bool operator== (const Order &other) const
Order ()=default
Order (std::vector< int > pos)
std::size_t size () const
bool valid () const
Determines whether this order is a valid order.
Static Public Member Functions
static Order create (size_t arity)
Private Attributes
std::vector< int > order
Friends
std::ostream & operator<< (std::ostream &out, const Order &order)
Detailed Description
An order to be enforced for storing tuples within indexes.
The order is defined by the sequence of component to be considered in sorting tuples.
Definition at line 132 of file InterpreterIndex.h.
Constructor & Destructor Documentation
Order() [1/2]
souffle::Order::Order () default
Order() [2/2]
souffle::Order::Order (std::vector< int > pos) inline
Definition at line 137 of file InterpreterIndex.h.
References souffle::DynTuple::size().
                               : order(std::move(pos)) {
         assert(valid());
     }
Member Function Documentation
create()
Order souffle::Order::create (size_t arity) static
Definition at line 37 of file InterpreterIndex.cpp.
References i, and order.
{
     Order res;
     res.order.resize(arity);
     for (size_t i = 0; i < arity; i++) {
         res.order[i] = i;
     }
     return res;
 }
decode()
template<std::size_t Arity> Tuple<RamDomain, Arity> souffle::Order::decode (const Tuple< RamDomain, Arity > & entry) const inline
Definition at line 161 of file InterpreterIndex.h.
References i.
Referenced by souffle::GenericIndex< Structure >::Source::load().
{
         Tuple<RamDomain, Arity> res{};
         for (std::size_t i = 0; i < Arity; ++i) {
             res[order[i]] = entry[i];
         }
         return res;
     }
encode()
template<std::size_t Arity> Tuple<RamDomain, Arity> souffle::Order::encode (const Tuple< RamDomain, Arity > & entry) const inline
Definition at line 152 of file InterpreterIndex.h.
References i.
Referenced by souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >::bounds(), souffle::GenericIndex< Structure >::GenericIndexView::contains(), and souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >::insert().
{
         Tuple<RamDomain, Arity> res{};
         for (std::size_t i = 0; i < Arity; ++i) {
             res[i] = entry[order[i]];
         }
         return res;
     }
getOrder()
const std::vector<int>& souffle::Order::getOrder () const inline
Definition at line 169 of file InterpreterIndex.h.
References souffle::operator<<().
Referenced by souffle::createIndirectIndex().
{
         return this->order;
     }
operator!=()
bool souffle::Order::operator!= (const Order & other) const
Definition at line 72 of file InterpreterIndex.cpp.
{
     return !(*this == other);
 }
operator<()
bool souffle::Order::operator< (const Order & other) const
Definition at line 76 of file InterpreterIndex.cpp.
References order.
{
     return order < other.order;
 }
operator==()
bool souffle::Order::operator== (const Order & other) const
Definition at line 68 of file InterpreterIndex.cpp.
References order.
{
     return order == other.order;
 }
size()
std::size_t souffle::Order::size () const
Definition at line 46 of file InterpreterIndex.cpp.
References order.
Referenced by souffle::createBrieIndex(), souffle::createBTreeIndex(), souffle::createBTreeProvenanceIndex(), souffle::createEqrelIndex(), and souffle::createIndirectIndex().
{
     return order.size();
 }
valid()
bool souffle::Order::valid () const
Determines whether this order is a valid order.
Definition at line 50 of file InterpreterIndex.cpp.
References i, j, and order.
{
     // Check that all indices are in range.
     for (int i : order) {
         if (i < 0 || i >= int(order.size())) {
             return false;
         }
     }
     // Check that there are no duplicates.
     for (std::size_t i = 0; i < order.size(); i++) {
         for (std::size_t j = i + 1; j < order.size(); j++) {
             if (order[i] == order[j]) {
                 return false;
             }
         }
     }
     return true;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Order & order) friend
Definition at line 80 of file InterpreterIndex.cpp.
{
     return out << "[" << join(order.order) << "]";
 }
Field Documentation
order
std::vector<int> souffle::Order::order private
Definition at line 133 of file InterpreterIndex.h.
Referenced by souffle::GenericIndex< Structure >::Source::clone(), create(), souffle::createBrieIndex(), souffle::createBTreeIndex(), souffle::createBTreeProvenanceIndex(), souffle::createEqrelIndex(), operator<(), souffle::operator<<(), operator==(), souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >::scan(), size(), and valid().
The documentation for this class was generated from the following files:
InterpreterIndex.h
InterpreterIndex.cpp