souffle: souffle::ExplainProvenance Class Reference
souffle::ExplainProvenance Class Reference abstract
#include <ExplainProvenance.h>
Public Member Functions
virtual std::unique_ptr< TreeNode > explain (std::string relName, std::vector< std::string > tuple, size_t depthLimit)=0
virtual std::unique_ptr< TreeNode > explainNegation (std::string relName, size_t ruleNum, const std::vector< std::string > &tuple, std::map< std::string, std::string > &bodyVariables)=0
virtual std::vector< std::string > explainNegationGetVariables (std::string relName, std::vector< std::string > args, size_t ruleNum)=0
ExplainProvenance (SouffleProgram &prog, bool useSublevels)
virtual std::unique_ptr< TreeNode > explainSubproof (std::string relName, RamDomain label, size_t depthLimit)=0
virtual std::string getRule (std::string relName, size_t ruleNum)=0
virtual std::vector< std::string > getRules (const std::string &relName)=0
virtual std::string measureRelation (std::string relName)=0
virtual void printRulesJSON (std::ostream &os)=0
virtual void queryProcess (const std::vector< std::pair< std::string, std::vector< std::string >>> &rels)=0
Process query with given arguments.
virtual void setup ()=0
virtual ~ExplainProvenance ()=default
Protected Member Functions
std::vector< RamDomain > argsToNums (const std::string &relName, const std::vector< std::string > &args) const
std::vector< std::string > decodeArguments (const std::string &relName, const std::vector< RamDomain > &nums) const
Decode arguments from their ram representation and return as strings.
std::string RamDomainToArgument (const char type, const RamDomain num) const
Protected Attributes
SouffleProgram & prog
SymbolTable & symTable
bool useSublevels
Detailed Description
Definition at line 149 of file ExplainProvenance.h.
Constructor & Destructor Documentation
ExplainProvenance()
souffle::ExplainProvenance::ExplainProvenance (SouffleProgram & prog, bool useSublevels) inline
Definition at line 151 of file ExplainProvenance.h.
References souffle::explain().
             : prog(prog), symTable(prog.getSymbolTable()), useSublevels(useSublevels) {}
~ExplainProvenance()
virtual souffle::ExplainProvenance::~ExplainProvenance () virtual default
Member Function Documentation
argsToNums()
std::vector<RamDomain> souffle::ExplainProvenance::argsToNums (const std::string & relName, const std::vector< std::string > & args) const inline protected
Definition at line 188 of file ExplainProvenance.h.
References souffle::SouffleProgram::getRelation(), i, souffle::SymbolTable::lookup(), souffle::ramBitCast(), souffle::RamFloatFromString(), souffle::RamSignedFromString(), and souffle::RamUnsignedFromString().
Referenced by souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), and souffle::ExplainProvenanceImpl::explainNegationGetVariables().
{
         std::vector<RamDomain> nums;
         auto rel = prog.getRelation(relName);
         if (rel == nullptr) {
             return nums;
         }
         for (size_t i = 0; i < args.size(); i++) {
             switch (*(rel->getAttrType(i))) {
                 case 's':
                     if (args[i].size() >= 2 && args[i][0] == '"' && args[i][args[i].size() - 1] == '"') {
                         auto originalStr = args[i].substr(1, args[i].size() - 2);
                         nums.push_back(symTable.lookup(originalStr));
                     }
                     break;
                 case 'f':
                     nums.push_back(ramBitCast(RamFloatFromString(args[i])));
                     break;
                 case 'u':
                     nums.push_back(ramBitCast(RamUnsignedFromString(args[i])));
                     break;
                 default:
                     nums.push_back(RamSignedFromString(args[i]));
                     break;
             }
         }
         return nums;
     }
decodeArguments()
std::vector<std::string> souffle::ExplainProvenance::decodeArguments (const std::string & relName, const std::vector< RamDomain > & nums) const inline protected
Decode arguments from their ram representation and return as strings.
Definition at line 223 of file ExplainProvenance.h.
References souffle::SouffleProgram::getRelation(), and i.
Referenced by souffle::ExplainProvenanceImpl::explain().
{
         std::vector<std::string> args;
         auto rel = prog.getRelation(relName);
         if (rel == nullptr) {
             return args;
         }
         for (size_t i = 0; i < nums.size(); i++) {
             args.push_back(RamDomainToArgument(*rel->getAttrType(i), nums[i]));
         }
         return args;
     }
explain()
virtual std::unique_ptr<TreeNode> souffle::ExplainProvenance::explain (std::string relName, std::vector< std::string > tuple, size_t depthLimit) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
explainNegation()
virtual std::unique_ptr<TreeNode> souffle::ExplainProvenance::explainNegation (std::string relName, size_t ruleNum, const std::vector< std::string > & tuple, std::map< std::string, std::string > & bodyVariables) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
explainNegationGetVariables()
virtual std::vector<std::string> souffle::ExplainProvenance::explainNegationGetVariables (std::string relName, std::vector< std::string > args, size_t ruleNum) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
explainSubproof()
virtual std::unique_ptr<TreeNode> souffle::ExplainProvenance::explainSubproof (std::string relName, RamDomain label, size_t depthLimit) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
getRule()
virtual std::string souffle::ExplainProvenance::getRule (std::string relName, size_t ruleNum) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
getRules()
virtual std::vector<std::string> souffle::ExplainProvenance::getRules (const std::string & relName) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
measureRelation()
virtual std::string souffle::ExplainProvenance::measureRelation (std::string relName) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
printRulesJSON()
virtual void souffle::ExplainProvenance::printRulesJSON (std::ostream & os) pure virtual
Implemented in souffle::ExplainProvenanceImpl.
queryProcess()
virtual void souffle::ExplainProvenance::queryProcess (const std::vector< std::pair< std::string, std::vector< std::string >>> & rels) pure virtual
Process query with given arguments.
Parameters
rels,vector of relation, argument pairs
Implemented in souffle::ExplainProvenanceImpl.
Referenced by souffle::Explain::processCommand().
RamDomainToArgument()
std::string souffle::ExplainProvenance::RamDomainToArgument (const char type, const RamDomain num) const inline protected
Definition at line 239 of file ExplainProvenance.h.
References souffle::SymbolTable::resolve().
{
         std::string arg;
         switch (type) {
             case 's':
                 arg = "\"" + std::string(symTable.resolve(num)) + "\"";
                 break;
             case 'f':
                 arg = std::to_string(ramBitCast<RamFloat>(num));
                 break;
             case 'u':
                 arg = std::to_string(ramBitCast<RamUnsigned>(num));
                 break;
             default:
                 arg = std::to_string(ramBitCast<RamSigned>(num));
         }
         return arg;
     }
setup()
virtual void souffle::ExplainProvenance::setup () pure virtual
Implemented in souffle::ExplainProvenanceImpl.
Field Documentation
prog
SouffleProgram& souffle::ExplainProvenance::prog protected
Definition at line 184 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainSubproof(), souffle::ExplainProvenanceImpl::findQuerySolution(), souffle::ExplainProvenanceImpl::findTuple(), souffle::ExplainProvenanceImpl::measureRelation(), souffle::ExplainProvenanceImpl::queryProcess(), and souffle::ExplainProvenanceImpl::setup().
symTable
SymbolTable& souffle::ExplainProvenance::symTable protected
Definition at line 185 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::findTuple(), and souffle::ExplainProvenanceImpl::measureRelation().
useSublevels
bool souffle::ExplainProvenance::useSublevels protected
Definition at line 186 of file ExplainProvenance.h.
Referenced by souffle::ExplainProvenanceImpl::explain().
The documentation for this class was generated from the following file:
ExplainProvenance.h