souffle: souffle Namespace Reference
souffle Namespace Reference
Souffle - A Datalog Compiler Copyright (c) 2013, 2015, Oracle and/or its affiliates.
Namespaces
column_utils
A namespace enclosing template-meta-programming utilities for handling parameter lists for templates.
detail
gzfstream
index_utils
A namespace enclosing utilities required by indices.
profile
Data Structures
class AdornedClause
class AdornedPredicate
class Adornment
class Assignment
An assignment maps a list of variables to values of their respective property space.
struct ast_visitor_tag
A tag type required for the is_ast_visitor type trait to identify AstVisitors.
class AstAggregator
An argument aggregating a value from a sub-query.
class AstAnalysis
Abstract class for a AST Analysis.
class AstArgument
Argument.
class AstAtom
Subclass of Literal that represents the use of a relation either in the head or in the body of a Clause, e.g., parent(x,y).
class AstAttribute
Intermediate representation of an attribute which stores the name and the type of an attribute.
class AstBinaryConstraint
Subclass of Constraint that represents a binary constraint e.g., x = y.
class AstBooleanConstraint
Boolean Constraint.
class AstClause
Intermediate representation of a datalog clause.
class AstComponent
A AST node describing a component within the input program.
class AstComponentChecker
class AstComponentInit
Component intialization.
class AstComponentType
A component type is.
class AstConstant
Abstract Constant.
class AstConstraint
Logical constraint.
class AstCounter
Counter.
class AstExecutionOrder
An execution order for atoms within a clause.
class AstExecutionPlan
The class utilized to model user-defined execution plans for various versions of clauses.
class AstExecutionPlanChecker
class AstFunctor
Functor class.
class AstFunctorDeclaration
AstFunctorDeclaration.
class AstIntrinsicFunctor
Intrinsic Functor.
class AstIO
I/O operation has a type (input/output/printsize), qualified relation name, and I/O directives.
class AstLiteral
Literal e.g.
struct AstNameComparison
Lexicographical order for AstRelation using the qualified name as an ordering criteria.
class AstNegation
Subclass of Literal that represents a negated atom, * e.g., !parent(x,y).
class AstNilConstant
Nil Constant.
class AstNode
Abstract class for syntactic elements in a Datalog program.
class AstNodeMapper
An abstract class for manipulating AST Nodes by substitution.
class AstNumericConstant
Numeric Constant.
class AstPragma
Representation of a global option.
class AstPragmaChecker
class AstProfileUse
AstAnalysis that loads profile data and has a profile query interface.
class AstProgram
Intermediate representation of a datalog program that consists of relations, clauses and types.
class AstProvenanceNegation
Subclass of Literal that represents a negated atom, * e.g., !parent(x,y).
class AstQualifiedName
Qualified Name class for fully/partially qualified names to identify objects in components.
class AstRecordInit
Record.
class AstRecordType
A record type aggregates a list of fields into a new type.
class AstRelation
class AstSemanticChecker
class AstStringConstant
String Constant.
class AstSubroutineArgument
Subroutine Argument.
class AstSubsetType
A subset type is named type that can either be a sub-type of the predefined types (float/unsigned/number/symbol).
class AstTerm
Abstract Term.
class AstTransformer
class AstTranslationUnit
AstTranslationUnit class.
class AstTranslator
Main class for AST Translator.
class AstType
class AstTypeCast
An argument capable of casting a value of one type into another.
class AstUnionType
A union type combines multiple types into a new super type.
class AstUnnamedVariable
Unnamed Variable.
class AstUserDefinedFunctor
User-Defined Functor.
class AstUserDefinedFunctorsTransformer
Transformation that passes the type information from user functors declaration to functors instances.
class AstVariable
Named Variable.
struct AstVisitor
The generic base type of all AstVisitors realizing the dispatching of visitor calls.
class AuxiliaryArity
Determine the auxiliary arity for relations.
class BaseTable
class BindingStore
class BrieIndex
A index adapter for Bries, using the generic index adapter.
class btree_multiset
A b-tree based multi-set implementation.
class btree_set
A b-tree based set implementation.
class BTreeIndex
A index adapter for B-trees, using the generic index adapter.
class BTreeProvenanceIndex
Btree index for provenance relation.
class CacheAccessCounter
cache hits/misses.
class ChoiceConversionTransformer
Convert (Scan/If)/(IndexScan/If) operaitons to (Choice)/(IndexChoice) operations.
class CmdOptions
A utility class for parsing command line arguments within generated query programs.
class CollapseFiltersTransformer
Transforms consecutive filters into a single filter containing a conjunction.
struct comp_deref
A functor class supporting the values pointers are pointing to.
class ComponentInstantiationTransformer
class ComponentLookup
class ConditionalTransformer
Transformer that executes a sub-transformer iff a condition holds.
class ConstConstraint
Constant constraints for values in query command.
class Constraint
A generic base class for constraints on variables.
class DebugReport
Class representing a HTML report, consisting of a list of sections.
class DebugReporter
Transformation pass which wraps another transformation pass and generates a debug report section for the stage after applying the wrapped transformer, and adds it to the translation unit's debug report.
class DebugReportSection
Class representing a section of a HTML report.
struct deref
A functor dereferencing a given type.
struct deref_less
A functor comparing the dereferenced value of a pointer type utilizing a given comparator.
class Diagnostic
class DiagnosticMessage
class DisjointSet
Structure that emulates a Disjoint Set, i.e.
class DynTuple
A construction-time sized tuple instance easing tuple handling in non-compiled contexts.
class EliminateDuplicatesTransformer
Eliminates duplicated conjunctive terms.
class EqrelIndex
A index adapter for EquivalenceRelation, using the generic index adapter.
struct EqrelMapComparator
class Equivalence
Equivalence class for variables in query command.
class EquivalenceRelation
class ErrorReport
class ExpandFilterTransformer
Transforms RamConjunctions into consecutive filter operations.
class Explain
class ExplainConfig
class ExplainProvenance
class ExplainProvenanceImpl
class FixpointTransformer
Transformer that repeatedly executes a sub-transformer until no changes are made.
class FoldAnonymousRecords
Transformation pass that removes (binary) constraints on the anonymous records.
class GenericIndex
A generic data structure index adapter handling the boundary level order conversion as well as iteration through nested data structures.
class Global
class Graph
A simple graph structure for graph-based operations.
class HoistAggregateTransformer
class HoistConditionsTransformer
Hosts conditions in a loop-nest to the most-outer/semantically-correct loop.
struct id
A functor representing the identity function for a generic type T.
class IfConversionTransformer
Convert IndexScan operations to Filter/Existence Checks.
struct index
The index class is utilized as a template-meta-programming structure to specify and realize indices.
class IndexView
A view on a relation caching local access patterns (not thread safe!).
class IndirectIndex
class InlineRelationsTransformer
Transformation pass to inline marked relations.
class InnerNode
class InterpreterContext
Evaluation context for Interpreter operations.
class InterpreterEngine
This class translate the RAM Program into executable format and interpreter it.
class InterpreterEqRelation
Interpreter Equivalence Relation.
class InterpreterIndex
An index is an abstraction of a data structure.
class InterpreterIndirectRelation
Interpreter Indirect Relation.
class InterpreterNode
This is a shadow node for a RamNode that is enriched for with local information so that the interpreter is executing quickly.
class InterpreterPreamble
This class contains information for views (Hints) creation for RamQuery and RamParallel operation.
class InterpreterProgInterface
Implementation of SouffleProgram interface for an interpreter instance.
struct InterpreterProvenanceUpdater
class InterpreterRelation
A relation, composed of a collection of indexes.
class InterpreterRelInterface
Wrapper class for interpreter relations.
class IOSystem
class IOType
struct IterDerefWrapper
A wrapper for an iterator obtaining pointers of a certain type, dereferencing values before forwarding them to the consumer.
struct lambda_traits
A type trait enabling the deduction of type properties of lambdas.
class LambdaBTreeSet
A b-tree based set implementation.
class LambdaRamNodeMapper
A special RamNodeMapper wrapping a lambda conducting node transformations.
class LeafNode
struct Lock
A small utility class for implementing simple locks.
class Logger
The class utilized to times for the souffle profiling tool.
class LogStatement
class LRUCache
An Least-Recently-Used cache for arbitrary element types.
class LRUCache< T, 0 >
class LRUCache< T, 1 >
class MagicSetTransformer
Magic Set Transformation.
class MainConfig
struct MainOption
class MakeIndexTransformer
Make indexable operations to indexed operations.
class MaterializeAggregationQueriesTransformer
Transformation pass to create artificial relations for bodies of aggregation functions consisting of more than a single atom.
class MaxMatching
Computes a maximum matching with Hopcroft-Karp algorithm
class MetaTransformer
Transformer that coordinates other sub-transformations.
class MinimiseProgramTransformer
Transformation pass to remove equivalent rules.
class MinIndexSelection
computes the minimal index cover for a relation in a RAM Program.
class NameUnnamedVariablesTransformer
Transformation pass to replace unnamed variables with singletons.
class NodeGenerator
class NormaliseConstraintsTransformer
Transformation pass to normalise constraints.
class NullableVector
class NullaryIndex
An index wrapper for nullary indexes.
class NullTransformer
Transformer that does absolutely nothing.
class OptimisticReadWriteLock
A 'sequential' non-locking implementation for an optimistic r/w lock.
class Order
An order to be enforced for storing tuples within indexes.
class ParallelTransformer
Transforms Choice/IndexChoice/IndexScan/Scan into parallel versions.
class ParserDriver
class PartitionBodyLiteralsTransformer
Transformation pass to move literals into new clauses if they are independent of remaining literals.
class PartitionedStream
A partitioned stream is a list of streams each covering a disjoint subset of a specific range.
class PiggyList
class PipelineTransformer
Transformer that holds an arbitrary number of sub-transformations.
class PolymorphicObjectsTransformer
Transformation pass to determine instances of polymorphic object objects = Functors (plus, minus...) binary constraints (>, ...) aggregation numeric constants.
class PrecedenceGraph
Analysis pass computing the precedence graph of the relations of the datalog progam.
struct PredefinedType
PredefinedType = Number/Unsigned/Float/Symbol.
struct print_deref
A functor printing elements after dereferencing it.
class Problem
A problem is a list of constraints for which a solution is desired.
class ProfileEventSingleton
Profile Event Singleton.
class ProgramFactory
Abstract program factory class.
struct property_space
A MPL type for defining a property space.
class ProvenanceTransformer
Transformation pass to add provenance information.
struct ram_visitor_tag
A tag type required for the is_ram_visitor type trait to identify RamVisitors.
class RamAbstractAggregate
Abstract class for aggregation.
class RamAbstractChoice
Abstract class for a choice operation.
class RamAbstractConditional
Abstract conditional statement.
class RamAbstractExistenceCheck
Abstract existence check for a tuple in a relation.
class RamAbstractLog
Abstract class for logging.
class RamAbstractOperator
Abstract class for an operator/functor.
class RamAbstractParallel
Abstract class for parallel operation.
class RamAggregate
Aggregation function applied on some relation.
class RamAnalysis
Abstract class for a RAM Analysis.
class RamAutoIncrement
Increment a counter and return its value.
class RamBinRelationStatement
Abstract class for a binary relation.
class RamBreak
Breaks out of the loop if a condition holds.
class RamChoice
Find a tuple in a relation such that a given condition holds.
class RamClear
Delete tuples of a relation.
class RamComplexityAnalysis
A Ram Analysis for determining the number of relational operations in a condition / expression.
class RamCondition
Abstract class for conditions and boolean values in RAM.
class RamConditionalTransformer
RamConditionalTransformer Composite conditional transformer
class RamConjunction
A conjunction of conditions.
class RamConstant
Represents a Ram Constant.
class RamConstraint
Evaluates a binary constraint with respect to two RamExpressions.
class RamDebugInfo
Debug statement.
class RamEmptinessCheck
Emptiness check for a relation.
class RamExistenceCheck
Existence check for a tuple(-pattern) in a relation.
class RamExit
Exit statement for a loop.
class RamExpression
Abstract class for describing scalar values in RAM.
class RamExtend
Extend equivalence relation.
class RamFalse
class RamFilter
Checks whether a given condition holds.
class RamFloatConstant
Represents a float constant.
class RamIndexAggregate
Indexed aggregation on a relation.
class RamIndexAnalysis
class RamIndexChoice
Use an index to find a tuple in a relation such that a given condition holds.
class RamIndexOperation
class RamIndexScan
Search for tuples of a relation matching a criteria.
class RamIntrinsicOperator
Operator that represents an intrinsic (built-in) functor.
class RamIO
I/O statement for a relation.
class RamLevelAnalysis
A Ram Analysis for determining the level of a expression/condition.
class RamListStatement
Abstract class for a list of RAM statements.
class RamLogRelationTimer
Execution time logger for a statement.
class RamLogSize
Log relation size and a logging message.
class RamLogTimer
Execution time logger for a statement.
class RamLoop
Execute statement until statement terminates loop via an exit statement.
class RamLoopTransformer
RamLoopTransformer Composite loop transformer
class RamMetaTransformer
RamMetaTransformer Abstract class to identifier meta transformer
class RamNegation
Negates a given condition.
class RamNestedOperation
Abstract class for a nesting operations in a loop-nest.
class RamNode
RamNode is a superclass for all RAM IR classes.
class RamNodeMapper
An abstract class for manipulating RAM Nodes by substitution.
class RamOperation
Abstract class for a relational algebra operation.
class RamPackRecord
Packs a record's arguments into a reference.
class RamParallel
Parallel block of statements.
class RamParallelChoice
class RamParallelIndexChoice
Use an index to find a tuple in a relation such that a given condition holds in parallel.
class RamParallelIndexScan
Search for tuples of a relation matching a criteria.
class RamParallelScan
Iterate all tuples of a relation in parallel.
class RamProgram
RAM program relation declaration and functions.
class RamProject
Project a result into the target relation.
class RamProvenanceExistenceCheck
Provenance Existence check for a relation.
class RamQuery
A relational algebra query.
class RamRelation
A RAM Relation in the RAM intermediate representation.
class RamRelationOperation
Abstract class for operations on relations.
class RamRelationReference
A RAM Relation in the RAM intermediate representation.
class RamRelationStatement
RAM Statements with a single relation.
class RamScan
Iterate all tuples of a relation.
class RamSequence
Sequence of RAM statements.
class RamSignedConstant
Represents a signed constant.
class RamStatement
Abstract class for RAM statements.
class RamSubroutineArgument
Access argument of a subroutine.
class RamSubroutineReturnValue
A statement for returning from a ram subroutine.
class RamSwap
Swap operation with respect to two relations.
class RamTransformer
RamTransformer abstract transformer class for a translation unit
class RamTransformerSequence
RamTransformerSequence Composite sequence transformer
class RamTranslationUnit
Translating a RAM program.
class RamTrue
True value condition.
class RamTupleElement
Access element from the current tuple in a tuple environment.
class RamTupleOperation
Abstract class for relation searches and lookups.
class RamUndefValue
An undefined expression.
class RamUnpackRecord
Record lookup.
class RamUnsignedConstant
Represents a unsigned constant.
class RamUserDefinedOperator
Operator that represents an extrinsic (user-defined) functor.
struct RamVisitor
The generic base type of all RamVisitors realizing the dispatching of visitor calls.
class RandomInsertPiggyList
A PiggyList that allows insertAt functionality.
struct range
A utility class enabling representation of ranges by pairing two iterator instances marking lower and upper boundaries.
class ReadCinCSVFactory
class ReadFileCSV
class ReadFileCSVFactory
class ReadSQLiteFactory
class ReadStream
class ReadStreamCSV
class ReadStreamFactory
class ReadStreamSQLite
class ReadWriteLock
class RecordMap
Bidirectional mappping between records and record references.
class RecordTable
struct RecordType
A record type combining a list of fields into a new, aggregated type.
class RecursiveClauses
Analysis pass identifying clauses which are recursive.
class ReduceExistentialsTransformer
Transformation pass to reduce unnecessary computation for relations that only appear in the form A(_,...,_).
class RedundantRelations
Analysis pass identifying relations which do not contribute to the computation of the output relations.
class Relation
Object-oriented wrapper class for Souffle's templatized relations.
class RelationDetailCache
Analysis pass mapping identifiers with relations and clauses.
class RelationSchedule
Analysis pass computing a schedule for computing relations.
class RelationScheduleStep
A single step in a relation schedule, consisting of the relations computed in the step and the relations that are no longer required at that step.
class RelationWrapper
Relation wrapper used internally in the generated Datalog program.
class RemoveBooleanConstraintsTransformer
Transformation pass to remove constant boolean constraints Should be called after any transformation that may generate boolean constraints.
class RemoveEmptyRelationsTransformer
Transformation pass to remove all empty relations and rules that use empty relations.
class RemoveRedundantRelationsTransformer
Transformation pass to remove relations which are redundant (do not contribute to output).
class RemoveRedundantSumsTransformer
Transformation pass to remove expressions of the form sum k : { ...
class RemoveRelationCopiesTransformer
Transformation pass to replaces copy of relations by their origin.
class RemoveTypecastsTransformer
Transformation to remove typecasts.
class ReorderConditionsTransformer
Reorders conjunctive terms depending on cost, i.e., cheap terms should be executed first.
class ReorderFilterBreak
class ReorderLiteralsTransformer
Transformation pass to reorder body literals.
class ReplaceSingletonVariablesTransformer
Transformation pass to replace singleton variables with unnamed variables.
class ReportIndexTransformer
class ResolveAliasesTransformer
Transformation pass to eliminate grounded aliases.
class ResolveAnonymousRecordsAliases
Transformer resolving aliases for anonymous records.
class RuleBody
struct scanner_data
class SCCGraph
Analysis pass computing the strongly connected component (SCC) graph for the datalog program.
class ScreenBuffer
struct set_property_space
A property space for set-based properties based on sub-set lattices.
class SignalHandler
Class SignalHandler captures signals and reports the context where the signal occurs.
class SingleValueIterator
An iterator to be utilized if there is only a single element to iterate over.
class SouffleProgram
Abstract base class for generated Datalog programs.
class SparseArray
A sparse array simulates an array associating to every element of uint32_t an element of a generic type T.
class SparseBitMap
A sparse bit-map is a bit map virtually assigning a bit value to every value if the uint32_t domain.
class SparseDisjointSet
class SpinLock
A 'sequential' non-locking implementation for a spin lock.
class SrcLocation
A class describing a range in an input file.
class Stream
An abstract perspective on a data range.
class SubsetType
A primitive type.
class SymbolTable
Global pool of re-usable strings.
class Synthesiser
A RAM synthesiser: synthesises a C++ program from a RAM program.
class SynthesiserBrieRelation
class SynthesiserDirectRelation
class SynthesiserEqrelRelation
class SynthesiserIndirectRelation
class SynthesiserInfoRelation
class SynthesiserNullaryRelation
class SynthesiserRelation
class t_info
info relations
class t_nullaries
Nullary relations.
class Table
class TempFileStream
class TopologicallySortedSCCGraph
Analysis pass computing a topologically sorted strongly connected component (SCC) graph.
class TreeNode
class Trie
The most generic implementation of a Trie forming the top-level of any Trie storing tuples of arity > 1.
class Trie< 1u >
A template specialization for tries representing a set.
struct Tuple
The type of object stored within relations representing the actual tuple value.
class tuple
Defines a tuple for the OO interface such that relations with varying columns can be accessed.
class TupleIdTransformer
Ordering tupleIds in RamTupleOperation operations correctly.
class TupleRef
A type-erased reference to tuples.
class Type
An abstract base class for types to be covered within a type environment.
class TypeAnalysis
class TypeBinding
Class that encapsulates std::map of types binding that comes from .init c = Comp<MyType> Type binding in this example would be T->MyType if the component code is .comp Comp<T> ...
class TypeEnvironment
A type environment is a set of types.
class TypeEnvironmentAnalysis
struct TypeSet
A collection to represent sets of types.
class UnionType
A union type combining a list of types into a new, aggregated type.
class UniqueAggregationVariablesTransformer
Transformation pass to rename aggregation variables to make them unique.
struct Variable
A variable to be utilized within constraints to be handled by the constraint solver.
class WhileTransformer
Transformer that repeatedly executes a sub-transformer while a condition is met.
class WriteCoutCSV
class WriteCoutCSVFactory
class WriteCoutPrintSize
class WriteCoutPrintSizeFactory
class WriteFileCSV
class WriteFileCSVFactory
class WriteSQLiteFactory
class WriteStream
class WriteStreamCSV
class WriteStreamFactory
class WriteStreamSQLite
Typedefs
using AstRelationSet = std::set< const AstRelation *, AstNameComparison >
using block_t = uint64_t
template<std::size_t Arity>
using comparator = typename index_utils::get_full_index< Arity >::type::comparator
using IndexFactory = std::unique_ptr< InterpreterIndex >(*)(const Order &)
using IndexViewPtr = std::unique_ptr< IndexView >
using parent_t = uint64_t
using RamDomain = int32_t
using RamFloat = float
using RamSigned = RamDomain
using RamUnsigned = uint32_t
using rank_t = uint8_t
using SearchSignature = uint64_t
search signature of a RAM operation; each bit represents an attribute of a relation.
using sips_t = std::function< unsigned int(std::vector< AstAtom * >, const std::set< std::string > &)>
template<std::size_t Arity>
using t_tuple = typename souffle::Tuple< RamDomain, Arity >
using time_point = std::chrono::high_resolution_clock::time_point
using yyscan_t = void *
Enumerations
enum AggregateOp {
AggregateOp::MAX, AggregateOp::MIN, AggregateOp::SUM, AggregateOp::FMAX,
AggregateOp::FMIN, AggregateOp::FSUM, AggregateOp::MEAN, AggregateOp::UMAX,
AggregateOp::UMIN, AggregateOp::USUM, AggregateOp::COUNT
}
Types of aggregation functions.
enum BinaryConstraintOp {
BinaryConstraintOp::EQ, BinaryConstraintOp::FEQ, BinaryConstraintOp::NE, BinaryConstraintOp::FNE,
BinaryConstraintOp::LT, BinaryConstraintOp::ULT, BinaryConstraintOp::FLT, BinaryConstraintOp::SLT,
BinaryConstraintOp::LE, BinaryConstraintOp::ULE, BinaryConstraintOp::FLE, BinaryConstraintOp::SLE,
BinaryConstraintOp::GT, BinaryConstraintOp::UGT, BinaryConstraintOp::FGT, BinaryConstraintOp::SGT,
BinaryConstraintOp::GE, BinaryConstraintOp::UGE, BinaryConstraintOp::FGE, BinaryConstraintOp::SGE,
BinaryConstraintOp::MATCH, BinaryConstraintOp::CONTAINS, BinaryConstraintOp::NOT_MATCH, BinaryConstraintOp::NOT_CONTAINS
}
Binary Constraint Operators.
enum FunctorOp {
FunctorOp::ORD, FunctorOp::STRLEN, FunctorOp::NEG, FunctorOp::FNEG,
FunctorOp::BNOT, FunctorOp::UBNOT, FunctorOp::LNOT, FunctorOp::ULNOT,
FunctorOp::TONUMBER, FunctorOp::TOSTRING, FunctorOp::ITOU, FunctorOp::UTOI,
FunctorOp::ITOF, FunctorOp::FTOI, FunctorOp::UTOF, FunctorOp::FTOU,
FunctorOp::ADD, FunctorOp::SUB, FunctorOp::MUL, FunctorOp::DIV,
FunctorOp::EXP, FunctorOp::MAX, FunctorOp::MIN, FunctorOp::MOD,
FunctorOp::BAND, FunctorOp::BOR, FunctorOp::BXOR, FunctorOp::BSHIFT_L,
FunctorOp::BSHIFT_R, FunctorOp::BSHIFT_R_UNSIGNED, FunctorOp::LAND, FunctorOp::LOR,
FunctorOp::UADD, FunctorOp::USUB, FunctorOp::UMUL, FunctorOp::UDIV,
FunctorOp::UEXP, FunctorOp::UMAX, FunctorOp::UMIN, FunctorOp::UMOD,
FunctorOp::UBAND, FunctorOp::UBOR, FunctorOp::UBXOR, FunctorOp::UBSHIFT_L,
FunctorOp::UBSHIFT_R, FunctorOp::UBSHIFT_R_UNSIGNED, FunctorOp::ULAND, FunctorOp::ULOR,
FunctorOp::FADD, FunctorOp::FSUB, FunctorOp::FMUL, FunctorOp::FDIV,
FunctorOp::FEXP, FunctorOp::FMAX, FunctorOp::FMIN, FunctorOp::SMAX,
FunctorOp::SMIN, FunctorOp::CAT, FunctorOp::SUBSTR
}
enum InterpreterNodeType {
I_Constant, I_TupleElement, I_AutoIncrement, I_IntrinsicOperator,
I_UserDefinedOperator, I_PackRecord, I_SubroutineArgument, I_True,
I_False, I_Conjunction, I_Negation, I_EmptinessCheck,
I_ExistenceCheck, I_ProvenanceExistenceCheck, I_Constraint, I_TupleOperation,
I_Scan, I_ParallelScan, I_IndexScan, I_ParallelIndexScan,
I_Choice, I_ParallelChoice, I_IndexChoice, I_ParallelIndexChoice,
I_UnpackRecord, I_Aggregate, I_IndexAggregate, I_Break,
I_Filter, I_Project, I_SubroutineReturnValue, I_Sequence,
I_Parallel, I_Loop, I_Exit, I_LogRelationTimer,
I_LogTimer, I_DebugInfo, I_Clear, I_LogSize,
I_IO, I_Query, I_Extend, I_Swap
}
enum RelationQualifier {
RelationQualifier::INPUT, RelationQualifier::OUTPUT, RelationQualifier::PRINTSIZE, RelationQualifier::OVERRIDABLE,
RelationQualifier::INLINE, RelationQualifier::SUPPRESSED
}
Space of qualifiers that a relation can have.
enum RelationRepresentation {
RelationRepresentation::DEFAULT, RelationRepresentation::BRIE, RelationRepresentation::BTREE, RelationRepresentation::EQREL,
RelationRepresentation::INFO
}
Space of internal representations that a relation can have.
enum RelationTag {
RelationTag::INPUT, RelationTag::OUTPUT, RelationTag::PRINTSIZE, RelationTag::OVERRIDABLE,
RelationTag::INLINE, RelationTag::SUPPRESSED, RelationTag::BRIE, RelationTag::BTREE,
RelationTag::EQREL
}
Space of user-chosen tags that a relation can have.
enum TypeAttribute {
TypeAttribute::Symbol, TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float,
TypeAttribute::Record
}
Functions
std::string absPath (const std::string &path)
C++-style realpath.
std::set< AstQualifiedName > addAggregators (AstClause *clause, std::set< AstQualifiedName > ignoredNames)
std::set< AstQualifiedName > addBackwardDependencies (const AstProgram *program, std::set< AstQualifiedName > relations)
std::set< AstQualifiedName > addForwardDependencies (const AstProgram *program, std::set< AstQualifiedName > relations)
std::set< AstQualifiedName > addIgnoredRelations (const AstProgram *program, std::set< AstQualifiedName > relations)
template<typename Container , typename UnaryPredicate >
bool all_of (const Container &c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
template<typename Container , typename UnaryPredicate >
bool any_of (const Container &c, UnaryPredicate p)
A generic test checking whether any elements within a container satisfy a certain predicate.
void appendStmt (std::vector< std::unique_ptr< RamStatement >> &stmtList, std::unique_ptr< RamStatement > stmt)
append statement to a list of statements
std::vector< unsigned int > applySips (sips_t sipsFunction, std::vector< AstAtom *> atoms)
Finds the new ordering of a vector of atoms after the given SIPS is applied.
bool areBijectivelyEquivalent (const AstClause *left, const AstClause *right)
Check whether two clauses are bijectively equivalent.
bool areSubtypesOf (const TypeSet &s, const Type &b)
Determines whether all types in s are subtypes of type b.
std::string baseName (const std::string &filename)
std::pair< std::string, std::set< std::string > > bindArguments (AstAtom *currAtom, std::set< std::string > boundArgs, BindingStore &compositeBindings)
BindingStore bindComposites (const AstProgram *program)
bool canBeParsedAsRamFloat (const std::string &string)
Can a string be parsed as RamFloat.
bool canBeParsedAsRamSigned (const std::string &string)
Can a string be parsed as RamSigned.
bool canBeParsedAsRamUnsigned (const std::string &string)
Can a string be parsed as RamUnsigned.
template<typename toType , typename baseType >
bool castEq (const baseType *left, const baseType *right)
Cast the values, from baseType to toType and compare using ==.
template<typename A >
std::unique_ptr< A > clone (const A *node)
template<typename A >
std::unique_ptr< A > clone (const std::unique_ptr< A > &node)
template<typename A >
std::vector< std::unique_ptr< A > > clone (const std::vector< std::unique_ptr< A >> &xs)
AstClause * cloneHead (const AstClause *clause)
Returns a clause which contains head of the given clause.
AstArgument * combineAggregators (std::vector< AstAggregator *> aggrs, FunctorOp fun)
std::vector< std::vector< AstLiteral * > > combineNegatedLiterals (std::vector< std::vector< AstLiteral *>> litGroups)
Return the negated version of a disjunction of conjunctions.
void compileToBinary (std::string compileCmd, const std::string &sourceFilename)
Compiles the given source file to a binary file.
bool contains (std::set< AdornedPredicate > adornedPredicates, const AstQualifiedName &atomName, const std::string &atomAdornment)
template<typename C >
bool contains (const C &container, const typename C::value_type &element)
A utility to check generically whether a given element is contained in a given container.
template<typename C >
bool contains (const C &container, const typename C::value_type::first_type &element)
Version of contains specialized for maps.
bool containsAggregators (AstClause *clause)
bool containsInlinedAtom (const AstProgram &program, const AstClause &clause)
Checks if a given clause contains an atom that should be inlined.
AggregateOp convertOverloadedAggregator (const AggregateOp op, const TypeAttribute type)
Convert aggregator to a give type.
BinaryConstraintOp convertOverloadedConstraint (const BinaryConstraintOp constraintOp, const TypeAttribute toType)
Convert Constraint to work with requested type.
FunctorOp convertOverloadedFunctor (const FunctorOp functor, const TypeAttribute toType)
Convert an overloaded functor, so that it works with the requested type.
AstQualifiedName createAdornedIdentifier (const AstQualifiedName &relationName, const std::string &adornment)
AstClause * createAnnotatedClause (const AstClause *clause, const std::map< const AstArgument *, TypeSet > argumentTypes)
std::unique_ptr< InterpreterIndex > createBrieIndex (const Order &order)
std::unique_ptr< InterpreterIndex > createBTreeIndex (const Order &order)
std::unique_ptr< InterpreterIndex > createBTreeProvenanceIndex (const Order &order)
std::unique_ptr< InterpreterIndex > createEqrelIndex (const Order &order)
std::unique_ptr< InterpreterIndex > createIndirectIndex (const Order &order)
AstQualifiedName createMagicIdentifier (const AstQualifiedName &relationName, size_t outputNumber)
AstRelation * createMagicRelation (AstRelation *original, const AstQualifiedName &magicPredName)
AstRelation * createNewRelation (AstRelation *original, const AstQualifiedName &newName)
AstQualifiedName createSubIdentifier (const AstQualifiedName &relationName, size_t start, size_t length)
template<typename Iter >
IterDerefWrapper< Iter > derefIter (const Iter &iter)
A factory function enabling the construction of a dereferencing iterator utilizing the automated deduction of template parameters.
std::string dirName (const std::string &name)
C++-style dirname.
long duration_in_ns (const time_point &start, const time_point &end)
long duration_in_us (const time_point &start, const time_point &end)
bool endsWith (const std::string &value, const std::string &ending)
Determines whether the given value string ends with the given end string.
template<typename T >
bool eqTypeTypeAttribute (const TypeAttribute ramType, const T &type)
Determine if a type analysis' result is equivalent to the given TypeAttribute.
template<typename T >
bool equal_ptr (const T *a, const T *b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
template<typename T >
bool equal_ptr (const std::unique_ptr< T > &a, const std::unique_ptr< T > &b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
template<typename Container , typename Comparator >
bool equal_targets (const Container &a, const Container &b, const Comparator &comp)
A function testing whether two containers are equal with the given Comparator.
template<typename T , template< typename... > class Container>
bool equal_targets (const Container< T *> &a, const Container< T *> &b)
A function testing whether two containers of pointers are referencing equivalent targets.
template<typename T , template< typename... > class Container>
bool equal_targets (const Container< std::unique_ptr< T >> &a, const Container< std::unique_ptr< T >> &b)
A function testing whether two containers of unique pointers are referencing equivalent targets.
template<typename Key , typename Value >
bool equal_targets (const std::map< Key, std::unique_ptr< Value >> &a, const std::map< Key, std::unique_ptr< Value >> &b)
A function testing whether two maps of unique pointers are referencing to equivalent targets.
std::string escape (const std::string &inputString, const std::string &needle, const std::string &replacement)
std::string escape (const std::string &inputString)
std::string escapeJSONstring (const std::string &JSONstr)
Escape JSON string.
std::stringstream execStdOut (char const *cmd)
std::stringstream execStdOut (std::string const &cmd)
void executeBinary (const std::string &binaryFilename)
Executes a binary file.
bool existDir (const std::string &name)
Check whether a directory exists in the file system.
bool existFile (const std::string &name)
Check whether a file exists in the file system.
void explain (SouffleProgram &prog, bool ncurses, bool useSubtreelevels)
std::string extractAdornment (const AstQualifiedName &magicRelationName)
AstArgument * extractConstant (const std::string &normalisedConstant)
std::vector< std::vector< unsigned int > > extractPermutations (const std::vector< std::vector< unsigned int >> &permutationMatrix)
Extract valid permutations from a given permutation matrix of valid moves.
std::string fileExtension (const std::string &path)
File extension, with all else removed.
std::vector< AstQualifiedName > findInlineCycle (const PrecedenceGraph &precedenceGraph, std::map< const AstRelation *, const AstRelation *> &origins, const AstRelation *current, AstRelationSet &unvisited, AstRelationSet &visiting, AstRelationSet &visited)
Find a cycle consisting entirely of inlined relations.
std::string findTool (const std::string &tool, const std::string &base, const std::string &path)
DebugReportSection formatCodeSection (const std::string &id, const std::string &title, std::string code)
std::vector< std::vector< AstLiteral * > > formNegatedLiterals (AstProgram &program, AstAtom *atom)
Forms the bodies that will replace the negation of a given inlined atom.
TypeAttribute functorOpArgType (const size_t arg, const FunctorOp op)
Check the type of argument indicated by arg (0-indexed) of a functor op.
TypeAttribute functorReturnType (const FunctorOp op)
Check a functor's return type (codomain).
std::stringstream & genJsonRules (std::stringstream &ss, const std::string &name, size_t maxRows)
const AstRelation * getAtomRelation (const AstAtom *atom, const AstProgram *program)
Returns the relation referenced by the given atom.
std::vector< TypeAttribute > getBinaryConstraintTypes (const BinaryConstraintOp op)
Get type binary constraint operates on.
template<typename T , typename C >
std::vector< T * > getBodyLiterals (const C &clause)
Returns literals of a particular type in the body of a clause.
std::set< const AstRelation * > getBodyRelations (const AstClause *clause, const AstProgram *program)
Returns the relations referenced in the body of the given clause.
size_t getClauseNum (const AstProgram *program, const AstClause *clause)
Returns the index of a clause within its relation, ignoring facts.
std::vector< AstClause * > getClauses (const AstProgram &program, const AstQualifiedName &relationName)
Returns a vector of clauses in the program describing the relation with the given name.
std::vector< AstClause * > getClauses (const AstProgram &program, const AstRelation &rel)
Returns a vector of clauses in the program describing the given relation.
std::string getCurrentFilename (const std::vector< std::string > &filenames)
int getEndpoint (std::string mainName)
const AstFunctorDeclaration * getFunctorDeclaration (const AstProgram &program, const std::string &name)
Returns the functor declaration with the given name in the program.
TypeSet getGreatestCommonSubtypes (const Type &a, const Type &b)
Computes the greatest common sub types of the two given types.
TypeSet getGreatestCommonSubtypes (const TypeSet &set)
Computes the greatest common sub types of all the types in the given set.
TypeSet getGreatestCommonSubtypes (const TypeSet &a, const TypeSet &b)
The set of pair-wise greatest common sub types of the types in the two given sets.
template<typename... Types>
TypeSet getGreatestCommonSubtypes (const Types &... types)
Computes the greatest common sub types of the given types.
std::map< const AstArgument *, bool > getGroundedTerms (const AstClause &clause)
Analyse the given clause and computes for each contained argument whether it is a grounded value or not.
const AstRelation * getHeadRelation (const AstClause *clause, const AstProgram *program)
Returns the relation referenced by the head of the given clause.
template<typename C >
C::value_type getIf (const C &container, std::function< bool(const typename C::value_type)> pred)
Returns the first element in a container that satisfies a given predicate, nullptr otherwise.
NullableVector< AstArgument * > getInlinedArgument (AstProgram &program, const AstArgument *arg)
Returns a vector of arguments that should replace the given argument after one step of inlining.
NullableVector< AstAtom * > getInlinedAtom (AstProgram &program, AstAtom &atom)
Returns a vector of atoms that should replace the given atom after one step of inlining.
std::vector< AstClause * > getInlinedClause (AstProgram &program, const AstClause &clause)
Returns a list of clauses that should replace the given clause after one step of inlining.
NullableVector< std::vector< AstLiteral * > > getInlinedLiteral (AstProgram &program, AstLiteral *lit)
Tries to perform a single step of inlining on the given literal.
souffle::SouffleProgram * getInstance (const char *p)
TypeSet getLeastCommonSupertypes (const Type &a, const Type &b)
Computes the least common super types of the two given types.
TypeSet getLeastCommonSupertypes (const TypeSet &set)
Computes the least common super types of all the types in the given set.
TypeSet getLeastCommonSupertypes (const TypeSet &a, const TypeSet &b)
The set of pair-wise least common super types of the types in the two given sets.
template<typename... Types>
TypeSet getLeastCommonSupertypes (const Types &... types)
Computes the least common super types of the given types.
int getNextAtomMaxBoundSIPS (std::vector< AstAtom *> &atoms, const std::set< std::string > &boundArgs, const std::set< AstQualifiedName > &edb, BindingStore &compositeBindings)
int getNextAtomMaxRatioSIPS (std::vector< AstAtom *> &atoms, const std::set< std::string > &boundArgs, const std::set< AstQualifiedName > &, BindingStore &compositeBindings)
int getNextAtomNaiveSIPS (std::vector< AstAtom *> atoms, const std::set< std::string > &boundArgs, const std::set< AstQualifiedName > &edb, BindingStore &compositeBindings)
int getNextAtomSIPS (std::vector< AstAtom *> &atoms, std::set< std::string > boundArgs, std::set< AstQualifiedName > edb, BindingStore &compositeBindings)
std::string getNextEdbName (AstProgram *program)
template<typename C >
C::mapped_type const & getOr (const C &container, typename C::key_type key, const typename C::mapped_type &defaultValue)
Get value for a given key; if not found, return default value.
Lock & getOutputLock ()
Obtains a reference to the lock synchronizing output operations.
std::vector< const AstRecordInit * > getRecords (const AstNode &root)
Obtains a list of all records referenced within the AST rooted by the given root node.
AstRelation * getRelation (const AstProgram &program, const AstQualifiedName &name)
Returns the relation with the given name in the program.
RelationQualifier getRelationQualifierFromTag (const RelationTag &tag)
Get the corresponding RelationQualifier for a valid RelationTag.
RelationRepresentation getRelationRepresentationFromTag (const RelationTag &tag)
Get the corresponding RelationRepresentation for a valid RelationTag.
sips_t getSipsFunction (const std::string &sipsChosen)
Returns a SIPS function based on the SIPS option provided.
ss<< R"_("code": [)_";bool firstCol=true;while(getline(source_file, str)) { comma(firstCol, ",\");ss<< '"' << Tools::cleanJsonOut(str) << '"';} ss<< "],\";source_file.close();} auto usages=getUsageStats(100);auto beginTime=run-> getStarttime ()
std::string getString (const AstArgument *arg)
std::string getSymbolForFunctorOp (const FunctorOp op)
Return a string representation of a functor.
const AstType * getType (const AstProgram &program, const AstQualifiedName &name)
Returns the type with the given name in the program.
template<typename T >
TypeAttribute getTypeAttribute (const T &type)
Convert a type analysis' type/set of type to the the TypeAttribute.
TypeAttribute getTypeAttributeAggregate (const AggregateOp op)
Get return type of the aggregate.
std::string getTypeQualifier (const Type &type)
Returns full type qualifier for a given type.
std::vector< const AstVariable * > getVariables (const AstNode &root)
Obtains a list of all variables referenced within the AST rooted by the given root node.
bool hasBoundArgument (AstAtom *atom, const std::set< std::string > &boundArgs, BindingStore &compositeBindings)
bool hasClauseWithAggregatedRelation (const AstRelation *relation, const AstRelation *aggRelation, const AstProgram *program, const AstLiteral *&foundLiteral)
Returns whether the given relation has any clauses which contain an aggregation over of a specific relation.
bool hasClauseWithNegatedRelation (const AstRelation *relation, const AstRelation *negRelation, const AstProgram *program, const AstLiteral *&foundLiteral)
Returns whether the given relation has any clauses which contain a negation of a specific relation.
bool hasFloatType (const TypeSet &types)
Is any value in the set float.
bool hasPrefix (const std::string &str, const std::string &prefix)
bool hasSignedType (const TypeSet &types)
Is any value in the set signed.
static bool hasUnnamedVariable (const AstArgument *arg)
static bool hasUnnamedVariable (const AstLiteral *lit)
bool hasUnsignedType (const TypeSet &types)
Is any value in the set unsigned.
std::string identifier (std::string id)
Valid C++ identifier, note that this does not ensure the uniqueness of identifiers returned.
const std::string identifierToString (const AstQualifiedName &name)
Helper functions.
std::pair< NullableVector< AstLiteral * >, std::vector< AstBinaryConstraint * > > inlineBodyLiterals (AstAtom *atom, AstClause *atomInlineClause)
Inlines the given atom based on a given clause.
bool isAggRel (const AstQualifiedName &rel)
bool isBindingConstraint (AstArgument *lhs, AstArgument *rhs, std::set< std::string > boundArgs)
bool isBoundArgument (AstArgument *arg, const std::set< std::string > &boundArgs, BindingStore &compositeBindings)
bool isBoundComposite (const AstVariable *compositeVariable, const std::set< std::string > &boundArgs, BindingStore &compositeBindings)
static bool isConstantArithExpr (const AstArgument &argument)
bool isEqConstraint (const BinaryConstraintOp constraintOp)
bool isEqualAdornment (const AstQualifiedName &pred1, const std::string &adorn1, const AstQualifiedName &pred2, const std::string &adorn2)
bool isExecutable (const std::string &name)
Check whether a given file exists and it is an executable.
bool isFact (const AstClause &clause)
Returns whether the given clause is a fact.
bool isFloatType (const Type &type)
Determines whether the given type is a float type.
bool isFloatType (const TypeSet &s)
Determines whether all the types in the given set are float types.
bool isInfixFunctorOp (const FunctorOp op)
Determines whether a functor should be written using infix notation (e.g.
bool isNumber (const char *str)
Check whether a string is a sequence of digits.
bool isNumberType (const Type &type)
Determines whether the given type is a number type.
bool isNumberType (const TypeSet &s)
Determines whether all the types in the given set are number types.
bool isNumericType (TypeAttribute ramType)
Check if type is numeric.
template<typename T >
bool isNumericType (const T &type)
Determines whether the type is numeric.
template<typename T >
bool isOrderableType (const T &type)
bool isOrderedBinaryConstraintOp (const BinaryConstraintOp op)
Determines whether arguments of constraint are orderable.
bool isOverloaded (const BinaryConstraintOp constraintOp)
Utility function, informing whether constraint is overloaded.
bool isOverloadedAggregator (const AggregateOp op)
bool isOverloadedFunctor (const FunctorOp functor)
Indicate whether a functor is overloaded.
bool isPrefix (const std::string &prefix, const std::string &element)
Determine if one string is a prefix of another.
bool isProposition (const AstAtom *atom)
bool isRamTrue (const RamCondition *cond)
Determines if a condition represents true.
bool isRamUndefValue (const RamExpression *expr)
Determines if an expression represents an undefined value.
bool isRecordType (const Type &type)
Determines whether the given type is a record type.
bool isRecordType (const TypeSet &s)
Determines whether all the types in the given set are record types.
bool isRecursiveClause (const AstClause &clause)
Returns whether the given clause is recursive.
bool isRecursiveType (const Type &type)
Determines whether the given type is a recursive type.
bool isRelationQualifierTag (const RelationTag &tag)
Check if a given relation tag is a relation qualifier.
bool isRelationRepresentationTag (const RelationTag &tag)
Check if a given relation tag sets a relation representation.
bool isRule (const AstClause &clause)
Returns whether the given clause is a rule.
bool isSubtypeOf (const Type &a, const Type &b)
Determines whether type a is a subtype of type b.
bool isSymbolType (const Type &type)
Determines whether the given type is a symbol type.
bool isSymbolType (const TypeSet &s)
Determines whether all the types in the given set are symbol types.
bool isUnsignedType (const Type &type)
Determines whether the given type is a number type.
bool isUnsignedType (const TypeSet &s)
Determines whether all the types in the given set are number types.
bool isValidFunctorOpArity (const FunctorOp op, const size_t arity)
Checks whether a functor operation can have a given argument count.
bool isValidMove (const AstClause *left, size_t leftIdx, const AstClause *right, size_t rightIdx)
Check if the atom at leftIdx in the left clause can potentially be matched up with the atom at rightIdx in the right clause.
bool isValidPermutation (const AstClause *left, const AstClause *right, const std::vector< unsigned int > &permutation)
Check whether a valid variable mapping exists for the given permutation.
template<typename Iter , typename Printer >
detail::joined_sequence< Iter, Printer > join (const Iter &a, const Iter &b, const std::string &sep, const Printer &p)
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
template<typename Iter , typename T = typename Iter::value_type>
detail::joined_sequence< Iter, detail::print< id< T > > > join (const Iter &a, const Iter &b, const std::string &sep=",")
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
template<typename Container , typename Printer , typename Iter = typename Container::const_iterator>
detail::joined_sequence< Iter, Printer > join (const Container &c, const std::string &sep, const Printer &p)
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
template<typename Container , typename Iter = typename Container::const_iterator, typename T = typename Iter::value_type>
detail::joined_sequence< Iter, detail::print< id< T > > > join (const Container &c, const std::string &sep=",")
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
int main (int argc, char **argv)
template<typename Iter >
range< Iter > make_range (const Iter &a, const Iter &b)
A utility function enabling the construction of ranges without explicitly specifying the iterator type.
std::unique_ptr< AstRelation > makeInfoRelation (AstClause &originalClause, size_t originalClauseNum, AstTranslationUnit &translationUnit)
template<typename Lambda >
detail::LambdaNodeMapper< Lambda > makeLambdaAstMapper (const Lambda &lambda)
Creates a node mapper based on a corresponding lambda expression.
template<typename Lambda >
LambdaRamNodeMapper< Lambda > makeLambdaRamMapper (const Lambda &lambda)
Creates a node mapper based on a corresponding lambda expression.
AstQualifiedName makeRelationName (const AstQualifiedName &orig, const std::string &type, int num=-1)
void nameInlinedUnderscores (AstProgram &program)
Removes all underscores in all atoms of inlined relations.
void negateConstraint (AstConstraint *constraint)
Negate an ast constraint.
BinaryConstraintOp negatedConstraintOp (const BinaryConstraintOp op)
Negated Constraint Operator Each operator requires a negated operator which is necessary for the expansion of complex rule bodies with disjunction and negation.
AstLiteral * negateLiteral (AstLiteral *lit)
Returns the negated version of a given literal.
SrcLocation nextSrcLoc (SrcLocation orig)
template<typename Container , typename UnaryPredicate >
bool none_of (const Container &c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
void normaliseInlinedHeads (AstProgram &program)
Replace constants in the head of inlined clauses with (constrained) variables.
time_point now ()
unsigned int numBoundArguments (const AstAtom *atom, const std::set< std::string > &boundVariables)
Counts the number of bound arguments in a given atom.
AstQualifiedName operator+ (const std::string &name, const AstQualifiedName &id)
std::ostream & operator<< (std::ostream &out, TupleRef ref)
std::ostream & operator<< (std::ostream &os, TypeAttribute T)
std::ostream & operator<< (std::ostream &out, const Order &order)
std::ostream & operator<< (std::ostream &os, RelationQualifier qualifier)
std::ostream & operator<< (std::ostream &out, const RuleBody &body)
std::ostream & operator<< (std::ostream &os, RelationRepresentation representation)
template<typename T , unsigned size>
std::ostream & operator<< (std::ostream &out, const LRUCache< T, size > &cache)
template<std::size_t Arity>
RamDomain pack (RecordTable &recordTab, Tuple< RamDomain, Arity > tuple)
helper to convert tuple to record reference for the synthesiser
std::string pathJoin (const std::string &first, const std::string &second)
Join two paths together; note that this does not resolve overlaps or relative paths.
template<typename To = RamDomain, typename From >
To ramBitCast (From source)
In C++20 there will be a new way to cast between types by reinterpreting bits (std::bit_cast), but as of January 2020 it is not yet supported.
RamFloat RamFloatFromString (const std::string &str, std::size_t *position=nullptr)
Converts a string to a RamFloat.
RamSigned RamSignedFromString (const std::string &str, std::size_t *position=nullptr, const int base=10)
Converts a string to a RamSigned.
RamUnsigned RamUnsignedFromString (const std::string &str, std::size_t *position=nullptr, const int base=10)
Converts a string to a RamUnsigned.
bool reduceLocallyEquivalentClauses (AstTranslationUnit &translationUnit)
Reduces locally-redundant clauses.
bool reduceSingletonRelations (AstTranslationUnit &translationUnit)
Removes redundant singleton relations.
bool reduceSubstitution (std::vector< std::pair< AstArgument *, AstArgument *>> &sub)
Reduces a vector of substitutions.
void removeRelationClauses (AstProgram &program, const AstQualifiedName &name)
Removes the set of clauses with the given relation name.
void renameVariables (AstArgument *arg)
Renames all variables in a given argument uniquely.
std::vector< std::string > reorderAdornment (std::vector< std::string > adornment, std::vector< unsigned int > order)
AstClause * reorderAtoms (const AstClause *clause, const std::vector< unsigned int > &newOrder)
Reorders the atoms of a clause to be in the given order.
AstClause * reorderClauseWithSips (sips_t sipsFunction, AstClause *clause)
std::vector< unsigned int > reorderOrdering (std::vector< unsigned int > order)
void replaceUnderscores (AstProgram *program)
void separateDBs (AstProgram *program)
std::string simpleName (const std::string &path)
File name, with extension removed.
std::vector< std::string > split (const std::string &s, char delim, int times=-1)
utility function to split a string
std::vector< std::string > splitString (const std::string &str, char delimiter)
Splits a string given a delimiter.
std::string stringify (const std::string &input)
Stringify a string using escapes for newline, tab, double-quotes and semicolons.
template<typename Var >
std::shared_ptr< Constraint< Var > > sub (const Var &a, const Var &b, const std::string &symbol="")
A generic factory for constraints of the form.
template<typename Var , typename Val = typename Var::property_space::value_type>
std::shared_ptr< Constraint< Var > > sub (const Val &a, const Var &b, const std::string &symbol="")
A generic factory for constraints of the form.
std::string tempFile ()
Generate temporary file.
template<typename T >
detail::multiplying_printer< T > times (const T &value, unsigned num)
A utility printing a given value multiple times.
BinaryConstraintOp toBinaryConstraintOp (const std::string &symbol)
Converts symbolic representation of an operator to the operator.
std::string toBinaryConstraintSymbol (const BinaryConstraintOp op)
Converts operator to its symbolic representation.
std::unique_ptr< RamCondition > toCondition (const std::vector< std::unique_ptr< RamCondition >> &conds)
Convert list of conditions to a conjunction.
std::vector< std::unique_ptr< RamCondition > > toConjunctionList (const RamCondition *condition)
Convert terms of a conjunction to a list.
template<typename T >
std::vector< T * > toPtrVector (const std::vector< std::unique_ptr< T >> &v)
A utility function enabling the creation of a vector of pointers.
const std::string & toString (const std::string &str)
A generic function converting strings into strings (trivial case).
template<typename T >
std::enable_if< detail::is_printable< T >::value, std::string >::type toString (const T &value)
A generic function converting arbitrary objects to strings by utilizing their print capability.
template<typename T >
std::enable_if<!detail::is_printable< T >::value, std::string >::type toString (const T &)
A fallback for the to-string function in case an unprintable object is supposed to be printed.
template<typename T >
std::vector< T > toVector ()
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
template<typename T , typename... R>
std::vector< T > toVector (const T &first, const R &... rest)
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
void transformEqrelRelation (AstProgram &program, AstRelation &rel)
Transform eqrel relations to explicitly define equivalence relations.
std::string unescape (const std::string &inputString, const std::string &needle, const std::string &replacement)
std::string unescape (const std::string &inputString)
NullableVector< std::pair< AstArgument *, AstArgument * > > unifyAtoms (AstAtom *first, AstAtom *second)
Returns the nullable vector of substitutions needed to unify the two given atoms.
static const std::vector< SrcLocation > usesInvalidWitness (const std::vector< AstLiteral *> &literals, const std::set< std::unique_ptr< AstArgument >> &groundedArguments)
template<typename R , typename... Ps, typename... Args>
void visitDepthFirst (const AstNode &root, AstVisitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirst (const RamNode &root, RamVisitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the RAM fragments rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
template<typename R , typename N >
void visitDepthFirst (const AstNode &root, const std::function< R(const N &)> &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type>
std::enable_if<!detail::is_ast_visitor< Lambda >::value, void >::type visitDepthFirst (const AstNode &root, const Lambda &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename T , typename Lambda >
void visitDepthFirst (const std::vector< T *> &list, const Lambda &fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename T , typename Lambda >
void visitDepthFirst (const std::vector< std::unique_ptr< T >> &list, const Lambda &fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename R , typename N >
void visitDepthFirst (const RamNode &root, const std::function< R(const N &)> &fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type>
std::enable_if<!detail::is_ram_visitor< Lambda >::value, void >::type visitDepthFirst (const RamNode &root, const Lambda &fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirstPostOrder (const AstNode &root, AstVisitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given visitor to each encountered node.
template<typename R , typename N >
void visitDepthFirstPostOrder (const AstNode &root, const std::function< R(const N &)> &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type>
std::enable_if<!detail::is_ast_visitor< Lambda >::value, void >::type visitDepthFirstPostOrder (const AstNode &root, const Lambda &fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirstPreOrder (const AstNode &root, AstVisitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
template<typename R , typename... Ps, typename... Args>
void visitDepthFirstPreOrder (const RamNode &root, RamVisitor< R, Ps... > &visitor, Args &... args)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
std::string which (const std::string &name)
Simple implementation of a which tool.
Variables
else
ss<< R"_("usage": [)_";bool firstRow=true;Usage previousUsage=*usages.begin();previousUsage.time=beginTime;for(auto usage :usages) { comma(firstRow);ss<< '[';ss<<(usage.time - beginTime).count()/1000000.0<< ", ";ss<< 100.0 *(usage.usertime - previousUsage.usertime)/(usage.time - previousUsage.time)<< ", ";ss<< 100.0 *(usage.systemtime - previousUsage.systemtime)/(usage.time - previousUsage.time)<< ", ";ss<< usage.maxRSS *1024<< ", ";ss<< '"'; bool firstCol = true; for (auto& cur : out.getProgramRun()->getRelationsAtTime(previousUsage.time, usage.time)) { comma(firstCol); ss << cur-> getName ()
template<typename T >
constexpr bool isRamType
constexpr RamFloat MAX_RAM_FLOAT = std::numeric_limits<RamFloat>::max()
constexpr RamSigned MAX_RAM_SIGNED = std::numeric_limits<RamSigned>::max()
constexpr RamUnsigned MAX_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::max()
constexpr RamFloat MIN_RAM_FLOAT = std::numeric_limits<RamFloat>::min()
constexpr RamSigned MIN_RAM_SIGNED = std::numeric_limits<RamSigned>::min()
lower and upper boundaries for the ram types
constexpr RamUnsigned MIN_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::min()
constexpr block_t rank_mask = (1ul << split_size) - 1
constexpr uint8_t split_size = 8u
Detailed Description
Souffle - A Datalog Compiler Copyright (c) 2013, 2015, Oracle and/or its affiliates.
All rights reserved Licensed under the Universal Permissive License v 1.0 as shown at:
https://opensource.org/licenses/UPL
<souffle root>="">/licenses/SOUFFLE-UPL.txt
Typedef Documentation
AstRelationSet
using souffle::AstRelationSet = typedef std::set<const AstRelation*, AstNameComparison>
Definition at line 181 of file AstRelation.h.
block_t
using souffle::block_t = typedef uint64_t
Definition at line 45 of file UnionFind.h.
comparator
template<std::size_t Arity> using souffle::comparator = typedef typename index_utils::get_full_index<Arity>::type::comparator
Definition at line 565 of file InterpreterIndex.cpp.
IndexFactory
using souffle::IndexFactory = typedef std::unique_ptr<InterpreterIndex> (*)(const Order&)
Definition at line 475 of file InterpreterIndex.h.
IndexViewPtr
using souffle::IndexViewPtr = typedef std::unique_ptr<IndexView>
Definition at line 387 of file InterpreterIndex.h.
parent_t
using souffle::parent_t = typedef uint64_t
Definition at line 39 of file UnionFind.h.
RamDomain
using souffle::RamDomain = typedef int32_t
Definition at line 92 of file RamTypes.h.
RamFloat
using souffle::RamFloat = typedef float
Definition at line 96 of file RamTypes.h.
RamSigned
using souffle::RamSigned = typedef RamDomain
Definition at line 93 of file RamTypes.h.
RamUnsigned
using souffle::RamUnsigned = typedef uint32_t
Definition at line 94 of file RamTypes.h.
rank_t
using souffle::rank_t = typedef uint8_t
Definition at line 37 of file UnionFind.h.
SearchSignature
using souffle::SearchSignature = typedef uint64_t
search signature of a RAM operation; each bit represents an attribute of a relation.
A one represents that the attribute has an assigned value; a zero represents that no value exists (i.e. attribute is unbounded) in the search.
Definition at line 144 of file RamTypes.h.
sips_t
using souffle::sips_t = typedef std::function<unsigned int(std::vector<AstAtom*>, const std::set<std::string>&)>
Definition at line 40 of file ReorderLiteralsTransformer.cpp.
t_tuple
template<std::size_t Arity> using souffle::t_tuple = typedef typename souffle::Tuple<RamDomain, Arity>
Definition at line 569 of file InterpreterIndex.cpp.
time_point
using souffle::time_point = typedef std::chrono::high_resolution_clock::time_point
Definition at line 1033 of file Util.h.
yyscan_t
using souffle::yyscan_t = typedef void*
Definition at line 39 of file ParserDriver.h.
Enumeration Type Documentation
AggregateOp
enum souffle::AggregateOp strong
Types of aggregation functions.
Enumerator
MAX
MIN
SUM
FMAX
FMIN
FSUM
MEAN
UMAX
UMIN
USUM
COUNT
Definition at line 24 of file AggregateOp.h.
{
     MAX,
     MIN,
     SUM,
     FMAX,
     FMIN,
     FSUM,
     MEAN,
     UMAX,
     UMIN,
     USUM,
     COUNT,
 };
BinaryConstraintOp
enum souffle::BinaryConstraintOp strong
Binary Constraint Operators.
Enumerator
EQ
FEQ
NE
FNE
LT
ULT
FLT
SLT
LE
ULE
FLE
SLE
GT
UGT
FGT
SGT
GE
UGE
FGE
SGE
MATCH
CONTAINS
NOT_MATCH
NOT_CONTAINS
Definition at line 34 of file BinaryConstraintOps.h.
{
     EQ,           // equivalence of two values
     FEQ,          // float equiv; b/c NaNs are never equiv
     NE,           // whether two values are different
     FNE,          // float diff; b/c NaNs are always different
     LT,           // signed <
     ULT,          // Unsigned <
     FLT,          // Float <
     SLT,          // Symbol <
     LE,           // signed
     ULE,          // Unsigned
     FLE,          // Float
     SLE,          // Symbol
     GT,           // signed >
     UGT,          // unsigned >
     FGT,          // float >
     SGT,          // Symbol >
     GE,           // signed
     UGE,          // Unsigned
     FGE,          // Float
     SGE,          // Symbol
     MATCH,        // matching string
     CONTAINS,     // whether a sub-string is contained in a string
     NOT_MATCH,    // not matching string
     NOT_CONTAINS  // whether a sub-string is not contained in a string
 };
FunctorOp
enum souffle::FunctorOp strong
Enumerator
ORD
Unary Functor Operators.
STRLEN
NEG
FNEG
BNOT
UBNOT
LNOT
ULNOT
TONUMBER
TOSTRING
ITOU
UTOI
ITOF
FTOI
UTOF
FTOU
ADD
Binary Functor Operators.
SUB
MUL
DIV
EXP
MAX
MIN
MOD
BAND
BOR
BXOR
BSHIFT_L
BSHIFT_R
BSHIFT_R_UNSIGNED
LAND
LOR
UADD
USUB
UMUL
UDIV
UEXP
UMAX
UMIN
UMOD
UBAND
UBOR
UBXOR
UBSHIFT_L
UBSHIFT_R
UBSHIFT_R_UNSIGNED
ULAND
ULOR
FADD
FSUB
FMUL
FDIV
FEXP
FMAX
FMIN
SMAX
SMIN
CAT
SUBSTR
Ternary Functor Operators.
Definition at line 27 of file FunctorOps.h.
                      {
     /** Unary Functor Operators */
     ORD,       // ordinal number of a string
     STRLEN,    // length of a string
     NEG,       // Signed numeric negation
     FNEG,      // Float numeric negation
     BNOT,      // Signed bitwise negation
     UBNOT,     // Unsigned bitwise negation
     LNOT,      // Signed logical negation
     ULNOT,     // Unsigned logical negation
     TONUMBER,  // convert string to number
     TOSTRING,  // convert number to string
     ITOU,      // convert signed number to unsigned
     UTOI,      // convert unsigned number to signed
     ITOF,      // convert signed number to float
     FTOI,      // convert float number to signed number.
     UTOF,      // convert unsigned number to a float.
     FTOU,      // convert float to unsigned number.
     /** Binary Functor Operators */
     ADD,                 // addition
     SUB,                 // subtraction
     MUL,                 // multiplication
     DIV,                 // division
     EXP,                 // exponent
     MAX,                 // max of two numbers
     MIN,                 // min of two numbers
     MOD,                 // modulus
     BAND,                // bitwise and
     BOR,                 // bitwise or
     BXOR,                // bitwise exclusive or
     BSHIFT_L,            // bitwise shift left
     BSHIFT_R,            // bitwise shift right
     BSHIFT_R_UNSIGNED,   // bitwise shift right (unsigned)
     LAND,                // logical and
     LOR,                 // logical or
     UADD,                // addition
     USUB,                // subtraction
     UMUL,                // multiplication
     UDIV,                // division
     UEXP,                // exponent
     UMAX,                // max of two numbers
     UMIN,                // min of two numbers
     UMOD,                // modulus
     UBAND,               // bitwise and
     UBOR,                // bitwise or
     UBXOR,               // bitwise exclusive or
     UBSHIFT_L,           // bitwise shift right
     UBSHIFT_R,           // bitwise shift right
     UBSHIFT_R_UNSIGNED,  // bitwise shift right (unsigned)
     ULAND,               // logical and
     ULOR,                // logical or
     FADD,                // addition
     FSUB,                // subtraction
     FMUL,                // multiplication
     FDIV,                // division
     FEXP,                // exponent
     FMAX,                // max of two floats
     FMIN,                // min of two floats
     SMAX,                // max of two symbols
     SMIN,                // min of two symbols
     CAT,  // string concatenation
     /** Ternary Functor Operators */
     SUBSTR,  // substring
 };
InterpreterNodeType
enum souffle::InterpreterNodeType
Enumerator
I_Constant
I_TupleElement
I_AutoIncrement
I_IntrinsicOperator
I_UserDefinedOperator
I_PackRecord
I_SubroutineArgument
I_True
I_False
I_Conjunction
I_Negation
I_EmptinessCheck
I_ExistenceCheck
I_ProvenanceExistenceCheck
I_Constraint
I_TupleOperation
I_Scan
I_ParallelScan
I_IndexScan
I_ParallelIndexScan
I_Choice
I_ParallelChoice
I_IndexChoice
I_ParallelIndexChoice
I_UnpackRecord
I_Aggregate
I_IndexAggregate
I_Break
I_Filter
I_Project
I_SubroutineReturnValue
I_Sequence
I_Parallel
I_Loop
I_Exit
I_LogRelationTimer
I_LogTimer
I_DebugInfo
I_Clear
I_LogSize
I_IO
I_Query
I_Extend
I_Swap
Definition at line 32 of file InterpreterNode.h.
{
     I_Constant,
     I_TupleElement,
     I_AutoIncrement,
     I_IntrinsicOperator,
     I_UserDefinedOperator,
     I_PackRecord,
     I_SubroutineArgument,
     I_True,
     I_False,
     I_Conjunction,
     I_Negation,
     I_EmptinessCheck,
     I_ExistenceCheck,
     I_ProvenanceExistenceCheck,
     I_Constraint,
     I_TupleOperation,
     I_Scan,
     I_ParallelScan,
     I_IndexScan,
     I_ParallelIndexScan,
     I_Choice,
     I_ParallelChoice,
     I_IndexChoice,
     I_ParallelIndexChoice,
     I_UnpackRecord,
     I_Aggregate,
     I_IndexAggregate,
     I_Break,
     I_Filter,
     I_Project,
     I_SubroutineReturnValue,
     I_Sequence,
     I_Parallel,
     I_Loop,
     I_Exit,
     I_LogRelationTimer,
     I_LogTimer,
     I_DebugInfo,
     I_Clear,
     I_LogSize,
     I_IO,
     I_Query,
     I_Extend,
     I_Swap,
 };
RelationQualifier
enum souffle::RelationQualifier strong
Space of qualifiers that a relation can have.
Enumerator
INPUT
OUTPUT
PRINTSIZE
OVERRIDABLE
INLINE
SUPPRESSED
Definition at line 35 of file RelationTag.h.
{
     INPUT,        // relation read from csv
     OUTPUT,       // relation written to csv
     PRINTSIZE,    // number of tuples written to stdout
     OVERRIDABLE,  // rules defined in component can be overwritten by sub-component
     INLINE,       // inlined
     SUPPRESSED,   // warnings suppressed
 };
RelationRepresentation
enum souffle::RelationRepresentation strong
Space of internal representations that a relation can have.
Enumerator
DEFAULT
BRIE
BTREE
EQREL
INFO
Definition at line 45 of file RelationTag.h.
{
     DEFAULT,  // use default data-structure
     BRIE,     // use brie data-structure
     BTREE,    // use btree data-structure
     EQREL,    // use union data-structure
     INFO,     // info relation for provenance
 };
RelationTag
enum souffle::RelationTag strong
Space of user-chosen tags that a relation can have.
Enumerator
INPUT
OUTPUT
PRINTSIZE
OVERRIDABLE
INLINE
SUPPRESSED
BRIE
BTREE
EQREL
Definition at line 22 of file RelationTag.h.
{
     INPUT,        // relation read from csv
     OUTPUT,       // relation written to csv
     PRINTSIZE,    // number of tuples written to stdout
     OVERRIDABLE,  // rules defined in component can be overwritten by sub-component
     INLINE,       // inlined
     SUPPRESSED,   // warnings suppressed
     BRIE,         // use brie data-structure
     BTREE,        // use btree data-structure
     EQREL,        // use union data-structure
 };
TypeAttribute
enum souffle::TypeAttribute strong
Enumerator
Symbol
Signed
Unsigned
Float
Record
Definition at line 28 of file RamTypes.h.
{
     Symbol,
     Signed,    // Signed number
     Unsigned,  // Unsigned number
     Float,     // Floating point number.
     Record,
 };
Function Documentation
absPath()
std::string souffle::absPath (const std::string & path) inline
C++-style realpath.
Definition at line 1139 of file Util.h.
{
     char buf[PATH_MAX];
     char* res = realpath(path.c_str(), buf);
     return (res == nullptr) ? "" : std::string(buf);
 }
addAggregators()
std::set<AstQualifiedName> souffle::addAggregators (AstClause * clause, std::set< AstQualifiedName > ignoredNames)
Definition at line 285 of file MagicSet.cpp.
References souffle::AstAtom::getQualifiedName(), and visitDepthFirst().
Referenced by souffle::Adornment::run().
{
     std::set<AstQualifiedName> retVal = std::move(ignoredNames);
     visitDepthFirst(*clause, [&](const AstAggregator& aggregator) {
         visitDepthFirst(aggregator, [&](const AstAtom& atom) { retVal.insert(atom.getQualifiedName()); });
     });
     return retVal;
 }
addBackwardDependencies()
std::set<AstQualifiedName> souffle::addBackwardDependencies (const AstProgram * program, std::set< AstQualifiedName > relations)
Definition at line 297 of file MagicSet.cpp.
References contains(), getClauses(), souffle::AstAtom::getQualifiedName(), souffle::AstProgram::getRelations(), and visitDepthFirst().
Referenced by addIgnoredRelations().
{
     bool relationsAdded = false;
     std::set<AstQualifiedName> result;
     for (AstQualifiedName relName : relations) {
         // Add the relation itself
         result.insert(relName);
     }
     // Add in all relations that need to use an ignored relation
     for (AstRelation* rel : program->getRelations()) {
         for (AstClause* clause : getClauses(*program, *rel)) {
             AstQualifiedName clauseHeadName = clause->getHead()->getQualifiedName();
             if (!contains(relations, clauseHeadName)) {
                 // Clause hasn't been added yet, so check if it needs to be added
                 visitDepthFirst(*clause, [&](const AstAtom& subatom) {
                     AstQualifiedName atomName = subatom.getQualifiedName();
                     if (contains(relations, atomName)) {
                         // Clause uses one of the given relations
                         result.insert(clauseHeadName);
                         // Clause name hasn't been seen yet, so fixed point not reached
                         relationsAdded = true;
                     }
                 });
             }
         }
     }
     if (relationsAdded) {
         // Keep going until we reach a fixed point
         return addBackwardDependencies(program, result);
     } else {
         return result;
     }
 }
addForwardDependencies()
std::set<AstQualifiedName> souffle::addForwardDependencies (const AstProgram * program, std::set< AstQualifiedName > relations)
Definition at line 337 of file MagicSet.cpp.
References contains(), getClauses(), souffle::AstAtom::getQualifiedName(), getRelation(), and visitDepthFirst().
Referenced by souffle::Adornment::run().
{
     bool relationsAdded = false;
     std::set<AstQualifiedName> result;
     for (AstQualifiedName relName : relations) {
         // Add the relation itself
         result.insert(relName);
         // Add in all the relations that it needs to use
         AstRelation* associatedRelation = getRelation(*program, relName);
         for (AstClause* clause : getClauses(*program, *associatedRelation)) {
             visitDepthFirst(*clause, [&](const AstAtom& subatom) {
                 AstQualifiedName atomName = subatom.getQualifiedName();
                 result.insert(atomName);
                 if (!contains(relations, atomName)) {
                     // Hasn't been seen yet, so fixed point not reached
                     relationsAdded = true;
                 }
             });
         }
     }
     if (relationsAdded) {
         // Keep going until we reach a fixed point
         return addForwardDependencies(program, result);
     } else {
         return result;
     }
 }
addIgnoredRelations()
std::set<AstQualifiedName> souffle::addIgnoredRelations (const AstProgram * program, std::set< AstQualifiedName > relations)
Definition at line 370 of file MagicSet.cpp.
References addBackwardDependencies(), souffle::Global::config(), contains(), souffle::AstProgram::getRelations(), relations, and splitString().
Referenced by souffle::Adornment::run().
{
     // get a vector of all relations specified by the option
     std::vector<std::string> specifiedRelations = splitString(Global::config().get("magic-transform"), ',');
     // if a star was used as a relation, then magic set will be performed for all nodes
     if (contains(specifiedRelations, "*")) {
         return relations;
     }
     // find all specified relations
     std::set<AstQualifiedName> targetRelations;
     for (AstRelation* rel : program->getRelations()) {
         std::string mainName = rel->getQualifiedName().getQualifiers()[0];
         if (contains(specifiedRelations, mainName)) {
             targetRelations.insert(rel->getQualifiedName());
         }
     }
     // add all backward-dependencies to the list of relations to transform;
     // if we want to magic transform 'a', then we also have to magic transform
     // every relation that (directly or indirectly) uses 'a' in its clauses
     targetRelations = addBackwardDependencies(program, targetRelations);
     // ignore all relations not specified by the option
     std::set<AstQualifiedName> retVal(relations);
     for (AstRelation* rel : program->getRelations()) {
         if (!contains(targetRelations, rel->getQualifiedName())) {
             retVal.insert(rel->getQualifiedName());
         }
     }
     return retVal;
 }
all_of()
template<typename Container , typename UnaryPredicate > bool souffle::all_of (const Container & c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
Parameters
c the container
p the predicate
Returns
true if for all elements x in c the predicate p(x) is true, false otherwise; for empty containers the result is always true
Definition at line 996 of file Util.h.
Referenced by areSubtypesOf(), isConstantArithExpr(), isFloatType(), isNumberType(), isRecordType(), souffle::TypeSet::isSubsetOf(), isSymbolType(), isUnsignedType(), souffle::PolymorphicObjectsTransformer::transform(), and souffle::ConstConstraint::verify().
{
     return std::all_of(c.begin(), c.end(), p);
 }
any_of()
template<typename Container , typename UnaryPredicate > bool souffle::any_of (const Container & c, UnaryPredicate p)
A generic test checking whether any elements within a container satisfy a certain predicate.
Parameters
c the container
p the predicate
Returns
true if there is an element x in c such that predicate p(x) is true, false otherwise; for empty containers the result is always false
Definition at line 1010 of file Util.h.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::AstTranslator::ClauseTranslator::createValueIndex(), getLeastCommonSupertypes(), hasFloatType(), hasSignedType(), hasUnnamedVariable(), hasUnsignedType(), souffle::AstTranslator::ValueIndex::isAggregator(), isRecursiveType(), and souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms().
{
     return std::any_of(c.begin(), c.end(), p);
 }
appendStmt()
void souffle::appendStmt (std::vector< std::unique_ptr< RamStatement >> & stmtList, std::unique_ptr< RamStatement > stmt) inline
append statement to a list of statements
Definition at line 75 of file AstTranslator.cpp.
Referenced by souffle::AstTranslator::makeNegationSubproofSubroutine(), souffle::AstTranslator::translateNonRecursiveRelation(), souffle::AstTranslator::translateProgram(), and souffle::AstTranslator::translateRecursiveRelation().
{
     if (stmt) {
         stmtList.push_back(std::move(stmt));
     }
 }
applySips()
std::vector<unsigned int> souffle::applySips (sips_t sipsFunction, std::vector< AstAtom *> atoms)
Finds the new ordering of a vector of atoms after the given SIPS is applied.
Definition at line 308 of file ReorderLiteralsTransformer.cpp.
References souffle::AstAtom::getArguments().
Referenced by reorderClauseWithSips().
{
     std::set<std::string> boundVariables;
     std::vector<unsigned int> newOrder(atoms.size());
     unsigned int numAdded = 0;
     while (numAdded < atoms.size()) {
         // grab the next atom, based on the SIPS function
         unsigned int nextIdx = sipsFunction(atoms, boundVariables);
         AstAtom* nextAtom = atoms[nextIdx];
         // set all arguments that are variables as bound
         // note: arguments that are functors, etc., do not newly bind anything
         for (AstArgument* arg : nextAtom->getArguments()) {
             if (auto* var = dynamic_cast<AstVariable*>(arg)) {
                 boundVariables.insert(var->getName());
             }
         }
         newOrder[numAdded] = nextIdx;  // add to the ordering
         atoms[nextIdx] = nullptr;      // mark as done
         numAdded++;                    // move on
     }
     return newOrder;
 }
areBijectivelyEquivalent()
bool souffle::areBijectivelyEquivalent (const AstClause * left, const AstClause * right)
Check whether two clauses are bijectively equivalent.
Definition at line 249 of file MinimiseProgramTransformer.cpp.
References extractPermutations(), souffle::AstAtom::getArity(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), i, isValidMove(), isValidPermutation(), j, and visitDepthFirst().
Referenced by reduceLocallyEquivalentClauses(), and reduceSingletonRelations().
{
     // only check bijective equivalence for a subset of the possible clauses
     auto isValidClause = [&](const AstClause* clause) {
         // check that all body literals are atoms
         // i.e. avoid clauses with constraints or negations
         // TODO (azreika): extend to constraints and negations
         for (AstLiteral* lit : clause->getBodyLiterals()) {
             if (dynamic_cast<AstAtom*>(lit) == nullptr) {
                 return false;
             }
         }
         // check that all arguments are either constants or variables
         // i.e. only allow primitive arguments
         bool valid = true;
         visitDepthFirst(*clause, [&](const AstArgument& arg) {
             if (dynamic_cast<const AstVariable*>(&arg) == nullptr &&
                     dynamic_cast<const AstConstant*>(&arg) == nullptr) {
                 valid = false;
             }
         });
         return valid;
     };
     if (!isValidClause(left) || !isValidClause(right)) {
         return false;
     }
     // rules must be the same length to be equal
     if (left->getBodyLiterals().size() != right->getBodyLiterals().size()) {
         return false;
     }
     // head atoms must have the same arity
     if (left->getHead()->getArity() != right->getHead()->getArity()) {
         return false;
     }
     // set up the n x n permutation matrix, where n is the number of
     // atoms in the clause, including the head atom
     size_t size = left->getBodyLiterals().size() + 1;
     auto permutationMatrix = std::vector<std::vector<unsigned int>>(size);
     for (auto& i : permutationMatrix) {
         i = std::vector<unsigned int>(size);
     }
     // create permutation matrix
     permutationMatrix[0][0] = 1;
     for (size_t i = 1; i < size; i++) {
         for (size_t j = 1; j < size; j++) {
             if (isValidMove(left, i, right, j)) {
                 permutationMatrix[i][j] = 1;
             }
         }
     }
     // check if any of these permutations have valid variable mappings associated with them
     std::vector<std::vector<unsigned int>> permutations = extractPermutations(permutationMatrix);
     for (auto permutation : permutations) {
         if (isValidPermutation(left, right, permutation)) {
             // valid permutation with valid corresponding variable mapping exists
             // therefore, the two clauses are equivalent!
             return true;
         }
     }
     return false;
 }
areSubtypesOf()
bool souffle::areSubtypesOf (const TypeSet & s, const Type & b)
Determines whether all types in s are subtypes of type b.
Definition at line 435 of file TypeSystem.cpp.
References all_of(), and isSubtypeOf().
Referenced by isOrderableType().
{
     return all_of(s, [&](const Type& t) { return isSubtypeOf(t, b); });
 }
baseName()
std::string souffle::baseName (const std::string & filename) inline
Definition at line 1182 of file Util.h.
Referenced by souffle::SrcLocation::extloc(), getCurrentFilename(), main(), souffle::ReadFileCSV::ReadFileCSV(), and souffle::ReadFileCSV::readNextTuple().
{
     if (filename.empty()) {
         return ".";
     }
     size_t lastNotSlash = filename.find_last_not_of('/');
     if (lastNotSlash == std::string::npos) {
         return "/";
     }
     size_t lastSlashBeforeBasename = filename.find_last_of('/', lastNotSlash - 1);
     if (lastSlashBeforeBasename == std::string::npos) {
         lastSlashBeforeBasename = static_cast<size_t>(-1);
     }
     return filename.substr(lastSlashBeforeBasename + 1, lastNotSlash - lastSlashBeforeBasename);
 }
bindArguments()
std::pair<std::string, std::set<std::string> > souffle::bindArguments (AstAtom * currAtom, std::set< std::string > boundArgs, BindingStore & compositeBindings)
Definition at line 444 of file MagicSet.cpp.
References souffle::AstAtom::getArguments(), getString(), and isBoundArgument().
Referenced by souffle::Adornment::run().
{
     std::set<std::string> newlyBoundArgs;
     std::string atomAdornment = "";
     for (AstArgument* arg : currAtom->getArguments()) {
         if (isBoundArgument(arg, boundArgs, compositeBindings)) {
             atomAdornment += "b";  // bound
         } else {
             atomAdornment += "f";  // free
             std::string argName = getString(arg);
             newlyBoundArgs.insert(argName);  // now bound
         }
     }
     // add newly bound arguments to the list of bound arguments
     for (std::string newArg : newlyBoundArgs) {
         boundArgs.insert(newArg);
     }
     return std::make_pair(atomAdornment, boundArgs);
 }
bindComposites()
BindingStore souffle::bindComposites (const AstProgram * program)
Definition at line 594 of file MagicSet.cpp.
References souffle::BindingStore::addBinding(), constraints, EQ, FEQ, Float, getClauses(), and souffle::AstProgram::getRelations().
Referenced by souffle::Adornment::run().
{
     struct M : public AstNodeMapper {
         BindingStore& compositeBindings;
         std::set<AstBinaryConstraint*>& constraints;
         mutable int changeCount;
         M(BindingStore& compositeBindings, std::set<AstBinaryConstraint*>& constraints, int changeCount)
                 : compositeBindings(compositeBindings), constraints(constraints), changeCount(changeCount) {}
         int getChangeCount() const {
             return changeCount;
         }
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* functor = dynamic_cast<AstFunctor*>(node.get())) {
                 // functor found
                 changeCount++;
                 // create new variable name (with appropriate suffix)
                 std::stringstream newVariableName;
                 newVariableName << "+functor" << changeCount;
                 // add the binding to the BindingStore
                 compositeBindings.addBinding(newVariableName.str(), functor);
                 // create new constraint (+functorX = original-functor)
                 auto newVariable = std::make_unique<AstVariable>(newVariableName.str());
                 auto opEq = functor->getReturnType() == TypeAttribute::Float ? BinaryConstraintOp::FEQ
                                                                              : BinaryConstraintOp::EQ;
                 constraints.insert(
                         new AstBinaryConstraint(opEq, std::unique_ptr<AstArgument>(newVariable->clone()),
                                 std::unique_ptr<AstArgument>(functor->clone())));
                 // update functor to be the variable created
                 return newVariable;
             } else if (auto* record = dynamic_cast<AstRecordInit*>(node.get())) {
                 // record found
                 changeCount++;
                 // create new variable name (with appropriate suffix)
                 std::stringstream newVariableName;
                 newVariableName << "+record" << changeCount;
                 // add the binding to the BindingStore
                 compositeBindings.addBinding(newVariableName.str(), record);
                 // create new constraint (+recordX = original-record)
                 auto newVariable = std::make_unique<AstVariable>(newVariableName.str());
                 constraints.insert(new AstBinaryConstraint(BinaryConstraintOp::EQ,
                         std::unique_ptr<AstArgument>(newVariable->clone()),
                         std::unique_ptr<AstArgument>(record->clone())));
                 // update record to be the variable created
                 return newVariable;
             }
             node->apply(*this);
             return node;
         }
     };
     BindingStore compositeBindings;
     int changeCount = 0;  // number of functors/records seen so far
     // apply the change to all clauses in the program
     for (AstRelation* rel : program->getRelations()) {
         for (AstClause* clause : getClauses(*program, *rel)) {
             std::set<AstBinaryConstraint*> constraints;
             M update(compositeBindings, constraints, changeCount);
             clause->apply(update);
             changeCount = update.getChangeCount();
             for (AstBinaryConstraint* constraint : constraints) {
                 clause->addToBody(std::unique_ptr<AstBinaryConstraint>(constraint));
             }
         }
     }
     return compositeBindings;
 }
canBeParsedAsRamFloat()
bool souffle::canBeParsedAsRamFloat (const std::string & string) inline
Can a string be parsed as RamFloat.
Definition at line 262 of file Util.h.
References RamFloatFromString().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::ExplainProvenanceImpl::queryProcess().
{
     size_t charactersRead = 0;
     try {
         RamFloatFromString(string, &charactersRead);
     } catch (...) {
         return false;
     }
     return charactersRead == string.size();
 }
canBeParsedAsRamSigned()
bool souffle::canBeParsedAsRamSigned (const std::string & string) inline
Can a string be parsed as RamSigned.
Souffle (parser, not fact file readers) accepts: hex, binary and base 10. Integer can be negative, in all 3 formats this means that it starts with minus (c++ default semantics).
Definition at line 232 of file Util.h.
References RamSignedFromString().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::ExplainProvenanceImpl::queryProcess().
{
     size_t charactersRead = 0;
     try {
         RamSignedFromString(string, &charactersRead, 0);
     } catch (...) {
         return false;
     }
     return charactersRead == string.size();
 }
canBeParsedAsRamUnsigned()
bool souffle::canBeParsedAsRamUnsigned (const std::string & string) inline
Can a string be parsed as RamUnsigned.
Souffle accepts: hex, binary and base 10.
Definition at line 249 of file Util.h.
References RamUnsignedFromString().
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::ExplainProvenanceImpl::queryProcess().
{
     size_t charactersRead = 0;
     try {
         RamUnsignedFromString(string, &charactersRead, 0);
     } catch (...) {
         return false;
     }
     return charactersRead == string.size();
 }
castEq()
template<typename toType , typename baseType > bool souffle::castEq (const baseType * left, const baseType * right)
Cast the values, from baseType to toType and compare using ==.
(if casting fails -> return false.)
Template Parameters
baseType,initial Type of values
toType,type where equality comparison takes place.
Definition at line 495 of file Util.h.
{
     if (auto castedLeft = dynamic_cast<const toType*>(left)) {
         if (auto castedRight = dynamic_cast<const toType*>(right)) {
             return castedLeft == castedRight;
         }
     }
     return false;
 }
clone() [1/3]
template<typename A > std::unique_ptr<A> souffle::clone (const A * node)
Definition at line 465 of file Util.h.
Referenced by souffle::AstClause::clone(), clone(), souffle::AstAggregator::clone(), souffle::SparseArray< value_t, BITS, merge_op >::clone(), cloneHead(), souffle::MakeIndexTransformer::constructPattern(), createMagicRelation(), getInlinedArgument(), getInlinedAtom(), souffle::AstTranslator::makeSubproofSubroutine(), souffle::SparseArray< value_t, BITS, merge_op >::merge(), souffle::RamNode::operator!=(), souffle::SparseArray< value_t, BITS, merge_op >::operator=(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::SparseArray< value_t, BITS, merge_op >::SparseArray(), souffle::MagicSetTransformer::transform(), and souffle::FoldAnonymousRecords::transformClause().
{
     return node ? std::unique_ptr<A>(node->clone()) : nullptr;
 }
clone() [2/3]
template<typename A > std::unique_ptr<A> souffle::clone (const std::unique_ptr< A > & node)
Definition at line 470 of file Util.h.
{
     return node ? std::unique_ptr<A>(node->clone()) : nullptr;
 }
clone() [3/3]
template<typename A > std::vector<std::unique_ptr<A> > souffle::clone (const std::vector< std::unique_ptr< A >> & xs)
Definition at line 475 of file Util.h.
References clone().
{
     std::vector<std::unique_ptr<A>> ys;
     ys.reserve(xs.size());
     for (auto&& x : xs) {
         ys.emplace_back(clone(x));
     }
     return ys;
 }
cloneHead()
AstClause * souffle::cloneHead (const AstClause * clause)
Returns a clause which contains head of the given clause.
Parameters
clause the clause which head to be cloned
Returns
pointer to clause which has head cloned from given clause
Definition at line 179 of file AstUtils.cpp.
References souffle::AstAtom::clone(), souffle::AstExecutionPlan::clone(), clone(), souffle::AstClause::getExecutionPlan(), souffle::AstClause::getHead(), and souffle::AstNode::getSrcLoc().
Referenced by getBodyLiterals(), getInlinedClause(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::ResolveAliasesTransformer::removeTrivialEquality(), reorderAtoms(), and souffle::RemoveBooleanConstraintsTransformer::transform().
{
     auto* clone = new AstClause();
     clone->setSrcLoc(clause->getSrcLoc());
     clone->setHead(std::unique_ptr<AstAtom>(clause->getHead()->clone()));
     if (clause->getExecutionPlan() != nullptr) {
         clone->setExecutionPlan(std::unique_ptr<AstExecutionPlan>(clause->getExecutionPlan()->clone()));
     }
     return clone;
 }
combineAggregators()
AstArgument* souffle::combineAggregators (std::vector< AstAggregator *> aggrs, FunctorOp fun)
Definition at line 504 of file InlineRelationsTransformer.cpp.
References isValidFunctorOpArity(), renameVariables(), and rhs.
Referenced by getInlinedArgument().
{
     assert(isValidFunctorOpArity(fun, 2) && "not a binary functor");
     // Due to variable scoping issues with aggregators, we rename all variables uniquely in the
     // added aggregator
     renameVariables(aggrs[0]);
     if (aggrs.size() == 1) {
         return aggrs[0];
     }
     AstArgument* rhs = combineAggregators(std::vector<AstAggregator*>(aggrs.begin() + 1, aggrs.end()), fun);
     AstArgument* result = new AstIntrinsicFunctor(
             fun, std::unique_ptr<AstArgument>(aggrs[0]), std::unique_ptr<AstArgument>(rhs));
     return result;
 }
combineNegatedLiterals()
std::vector<std::vector<AstLiteral*> > souffle::combineNegatedLiterals (std::vector< std::vector< AstLiteral *>> litGroups)
Return the negated version of a disjunction of conjunctions.
E.g. (a1(x) ^ a2(x) ^ ...) v (b1(x) ^ b2(x) ^ ...) –into-> (!a1(x) ^ !b1(x)) v (!a2(x) ^ !b2(x)) v ...
Definition at line 366 of file InlineRelationsTransformer.cpp.
References i, and negateLiteral().
Referenced by formNegatedLiterals().
{
     std::vector<std::vector<AstLiteral*>> negation;
     // Corner case: !() = ()
     if (litGroups.empty()) {
         return negation;
     }
     std::vector<AstLiteral*> litGroup = litGroups[0];
     if (litGroups.size() == 1) {
         // !(a1 ^ a2 ^ a3 ^ ...) --into-> !a1 v !a2 v !a3 v ...
         for (auto& i : litGroup) {
             std::vector<AstLiteral*> newVec;
             newVec.push_back(negateLiteral(i));
             negation.push_back(newVec);
         }
         // Done!
         return negation;
     }
     // Produce the negated versions of all disjunctions ignoring the first recursively
     std::vector<std::vector<AstLiteral*>> combinedRHS = combineNegatedLiterals(
             std::vector<std::vector<AstLiteral*>>(litGroups.begin() + 1, litGroups.end()));
     // We now just need to add the negation of a single literal from the untouched LHS
     // to every single conjunction on the RHS to finalise creating every possible combination
     for (AstLiteral* lhsLit : litGroup) {
         for (std::vector<AstLiteral*> rhsVec : combinedRHS) {
             std::vector<AstLiteral*> newVec;
             newVec.push_back(negateLiteral(lhsLit));
             for (AstLiteral* lit : rhsVec) {
                 newVec.push_back(lit->clone());
             }
             negation.push_back(newVec);
         }
     }
     for (std::vector<AstLiteral*> rhsVec : combinedRHS) {
         for (AstLiteral* lit : rhsVec) {
             delete lit;
         }
     }
     return negation;
 }
compileToBinary()
void souffle::compileToBinary (std::string compileCmd, const std::string & sourceFilename)
Compiles the given source file to a binary file.
Definition at line 98 of file main.cpp.
References souffle::Global::config(), and splitString().
Referenced by main().
{
     // add source code
     compileCmd += ' ';
     for (const std::string& path : splitString(Global::config().get("library-dir"), ' ')) {
         // The first entry may be blank
         if (path.empty()) {
             continue;
         }
         compileCmd += "-L" + path + ' ';
     }
     for (const std::string& library : splitString(Global::config().get("libraries"), ' ')) {
         // The first entry may be blank
         if (library.empty()) {
             continue;
         }
         compileCmd += "-l" + library + ' ';
     }
     compileCmd += sourceFilename;
     // run executable
     if (system(compileCmd.c_str()) != 0) {
         throw std::invalid_argument("failed to compile C++ source <" + sourceFilename + ">");
     }
 }
contains() [1/3]
bool souffle::contains (std::set< AdornedPredicate > adornedPredicates, const AstQualifiedName & atomName, const std::string & atomAdornment)
Definition at line 46 of file MagicSet.cpp.
References isEqualAdornment().
Referenced by addBackwardDependencies(), addForwardDependencies(), addIgnoredRelations(), souffle::AstSemanticChecker::checkClause(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::contains(), souffle::Trie< Arity >::contains(), souffle::Trie< 1u >::contains(), souffle::FoldAnonymousRecords::containsValidRecordConstraint(), souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainNegationGetVariables(), getNextAtomMaxBoundSIPS(), getNextAtomNaiveSIPS(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::getSplitPoint(), souffle::WriteFileCSVFactory::getWriter(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::grow_parent(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::insert_inner(), isBoundArgument(), isBoundComposite(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, true, WeakComparator, Updater >::operator==(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::rebalance_or_split(), souffle::Adornment::run(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::split(), and souffle::MagicSetTransformer::transform().
{
     for (AdornedPredicate seenPred : adornedPredicates) {
         if (isEqualAdornment(seenPred.getQualifiedName(), seenPred.getAdornment(), atomName, atomAdornment)) {
             return true;
         }
     }
     return false;
 }
contains() [2/3]
template<typename C > bool souffle::contains (const C & container, const typename C::value_type & element)
A utility to check generically whether a given element is contained in a given container.
Definition at line 298 of file Util.h.
{
     return std::find(container.begin(), container.end(), element) != container.end();
 }
contains() [3/3]
template<typename C > bool souffle::contains (const C & container, const typename C::value_type::first_type & element)
Version of contains specialized for maps.
This workaround is needed because of set container, for which value_type == key_type, which is ambiguous in this context.
Definition at line 309 of file Util.h.
{
     return container.find(element) != container.end();
 }
containsAggregators()
bool souffle::containsAggregators (AstClause * clause)
Definition at line 164 of file MagicSet.cpp.
References visitDepthFirst().
Referenced by souffle::Adornment::run().
{
     bool found = false;
     // check for aggregators
     visitDepthFirst(*clause, [&](const AstAggregator&) { found = true; });
     return found;
 }
containsInlinedAtom()
bool souffle::containsInlinedAtom (const AstProgram & program, const AstClause & clause)
Checks if a given clause contains an atom that should be inlined.
Definition at line 176 of file InlineRelationsTransformer.cpp.
References souffle::AstAtom::getQualifiedName(), getRelation(), souffle::AstRelation::hasQualifier(), INLINE, and visitDepthFirst().
Referenced by souffle::InlineRelationsTransformer::transform().
{
     bool foundInlinedAtom = false;
     visitDepthFirst(clause, [&](const AstAtom& atom) {
         AstRelation* rel = getRelation(program, atom.getQualifiedName());
         if (rel->hasQualifier(RelationQualifier::INLINE)) {
             foundInlinedAtom = true;
         }
     });
     return foundInlinedAtom;
 }
convertOverloadedAggregator()
AggregateOp souffle::convertOverloadedAggregator (const AggregateOp op, const TypeAttribute type) inline
Convert aggregator to a give type.
Eg. sum, float fsum.
Definition at line 85 of file AggregateOp.h.
References Float, FMAX, FMIN, FSUM, MAX, MIN, SUM, UMAX, UMIN, Unsigned, and USUM.
Referenced by souffle::PolymorphicObjectsTransformer::transform().
{
     switch (op) {
         case AggregateOp::SUM:
             if (type == TypeAttribute::Float) {
                 return AggregateOp::FSUM;
             } else if (type == TypeAttribute::Unsigned) {
                 return AggregateOp::USUM;
             } else {
                 assert(false && "Invalid argument;");
             }
             break;
         case AggregateOp::MAX:
             if (type == TypeAttribute::Float) {
                 return AggregateOp::FMAX;
             } else if (type == TypeAttribute::Unsigned) {
                 return AggregateOp::UMAX;
             } else {
                 assert(false && "Invalid argument;");
             }
             break;
         case AggregateOp::MIN:
             if (type == TypeAttribute::Float) {
                 return AggregateOp::FMIN;
             } else if (type == TypeAttribute::Unsigned) {
                 return AggregateOp::UMIN;
             } else {
                 assert(false && "Invalid argument;");
             }
             break;
         default:
             assert(false && "Invalid argument");
     }
 }
convertOverloadedConstraint()
BinaryConstraintOp souffle::convertOverloadedConstraint (const BinaryConstraintOp constraintOp, const TypeAttribute toType) inline
Convert Constraint to work with requested type.
Example: constraintOp = LT, toType = Float -> FLT (less-than working on floats).
Definition at line 95 of file BinaryConstraintOps.h.
References COMPARE_CONSTRAINT, COMPARE_CONSTRAINT_FLOAT_OR_RAW, EQ, GE, GT, isOverloaded(), LE, LT, and NE.
Referenced by souffle::PolymorphicObjectsTransformer::transform().
{
     auto FAIL = [&]() -> BinaryConstraintOp {
         std::cerr << "invalid binary constraint overload: " << int(constraintOp) << " " << int(toType);
         assert(false && "invalid binary constraint overload");
         exit(EXIT_FAILURE);
     };
     // clang-format off
 #define COMPARE_CONSTRAINT_FLOAT_OR_RAW(op)                             \
     case BinaryConstraintOp::op:                                        \
         switch (toType) {                                               \
         default                     : return BinaryConstraintOp::   op; \
         case TypeAttribute::Float   : return BinaryConstraintOp::F##op; \
         }
 #define COMPARE_CONSTRAINT(op)                                          \
     case BinaryConstraintOp::op:                                        \
         switch (toType) {                                               \
         case TypeAttribute::Signed  : return BinaryConstraintOp::   op; \
         case TypeAttribute::Unsigned: return BinaryConstraintOp::U##op; \
         case TypeAttribute::Float   : return BinaryConstraintOp::F##op; \
         case TypeAttribute::Symbol  : return BinaryConstraintOp::S##op; \
         case TypeAttribute::Record  : return FAIL();                    \
         }                                                               \
         assert(false && "unhandled TypeAttr");                          \
         break; /* HACK: GCC-9 is incorrectly reporting a case fallthru */
     // clang-format on
     switch (constraintOp) {
         COMPARE_CONSTRAINT_FLOAT_OR_RAW(EQ)
         COMPARE_CONSTRAINT_FLOAT_OR_RAW(NE)
         COMPARE_CONSTRAINT(LT)
         COMPARE_CONSTRAINT(LE)
         COMPARE_CONSTRAINT(GT)
         COMPARE_CONSTRAINT(GE)
         default:
             assert(false && "Invalid constraint conversion");
     }
 #undef COMPARE_CONSTRAINT_FLOAT_OR_RAW
 #undef COMPARE_CONSTRAINT
     assert(isOverloaded(constraintOp) && "missing handler for overloadable constraint op");
     assert(!isOverloaded(constraintOp) && "can't overload this binary op");
     exit(EXIT_FAILURE);
 }
convertOverloadedFunctor()
FunctorOp souffle::convertOverloadedFunctor (const FunctorOp functor, const TypeAttribute toType) inline
Convert an overloaded functor, so that it works with the requested type.
Example: toType = Float, functor = PLUS -> FPLUS (version of plus working on floats)
Definition at line 493 of file FunctorOps.h.
References ADD, BAND, BNOT, BOR, BSHIFT_L, BSHIFT_R, BXOR, DIV, EXP, FADD, FDIV, FEXP, Float, FMAX, FMIN, FMUL, FNEG, FSUB, LAND, LNOT, LOR, MAX, MIN, MOD, MUL, NEG, SMAX, SMIN, SUB, Symbol, UADD, UBAND, UBNOT, UBOR, UBSHIFT_L, UBSHIFT_R, UBXOR, UDIV, UEXP, ULAND, ULNOT, ULOR, UMAX, UMIN, UMOD, UMUL, Unsigned, and USUB.
Referenced by souffle::PolymorphicObjectsTransformer::transform().
{
     switch (functor) {
         case FunctorOp::NEG:
             assert(toType == TypeAttribute::Float && "Invalid functor conversion from NEG");
             return FunctorOp::FNEG;
         case FunctorOp::BNOT:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion from UBNOT");
             return FunctorOp::UBNOT;
         case FunctorOp::LNOT:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion from LNOT");
             return FunctorOp::ULNOT;
         /* Binary */
         case FunctorOp::ADD:
             if (toType == TypeAttribute::Float) {
                 return FunctorOp::FADD;
             } else if (toType == TypeAttribute::Unsigned) {
                 return FunctorOp::UADD;
             }
             assert(false && "Invalid functor conversion");
             break;
         case FunctorOp::SUB:
             if (toType == TypeAttribute::Float) {
                 return FunctorOp::FSUB;
             } else if (toType == TypeAttribute::Unsigned) {
                 return FunctorOp::USUB;
             }
             assert(false && "Invalid functor conversion");
             break;
         case FunctorOp::MUL:
             if (toType == TypeAttribute::Float) {
                 return FunctorOp::FMUL;
             } else if (toType == TypeAttribute::Unsigned) {
                 return FunctorOp::UMUL;
             }
             assert(false && "Invalid functor conversion");
             break;
         case FunctorOp::DIV:
             if (toType == TypeAttribute::Float) {
                 return FunctorOp::FDIV;
             } else if (toType == TypeAttribute::Unsigned) {
                 return FunctorOp::UDIV;
             }
             assert(false && "Invalid functor conversion");
             break;
         case FunctorOp::EXP:
             if (toType == TypeAttribute::Float) {
                 return FunctorOp::FEXP;
             } else if (toType == TypeAttribute::Unsigned) {
                 return FunctorOp::UEXP;
             }
             assert(false && "Invalid functor conversion");
             break;
         case FunctorOp::MAX:
             if (toType == TypeAttribute::Float) {
                 return FunctorOp::FMAX;
             } else if (toType == TypeAttribute::Unsigned) {
                 return FunctorOp::UMAX;
             } else if (toType == TypeAttribute::Symbol) {
                 return FunctorOp::SMAX;
             }
             assert(false && "Invalid functor conversion");
             break;
         case FunctorOp::MIN:
             if (toType == TypeAttribute::Float) {
                 return FunctorOp::FMIN;
             } else if (toType == TypeAttribute::Unsigned) {
                 return FunctorOp::UMIN;
             } else if (toType == TypeAttribute::Symbol) {
                 return FunctorOp::SMIN;
             }
             assert(false && "Invalid functor conversion");
             break;
         case FunctorOp::BAND:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::UBAND;
         case FunctorOp::BOR:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::UBOR;
         case FunctorOp::BXOR:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::UBXOR;
         case FunctorOp::BSHIFT_L:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::UBSHIFT_L;
         case FunctorOp::BSHIFT_R:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::UBSHIFT_R;
         case FunctorOp::LAND:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::ULAND;
         case FunctorOp::LOR:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::ULOR;
         case FunctorOp::MOD:
             assert(toType == TypeAttribute::Unsigned && "Invalid functor conversion");
             return FunctorOp::UMOD;
         default:
             assert(false && "Invalid functor");
     }
 }
createAdornedIdentifier()
AstQualifiedName souffle::createAdornedIdentifier (const AstQualifiedName & relationName, const std::string & adornment)
Definition at line 246 of file MagicSet.cpp.
References souffle::AstQualifiedName::append(), souffle::AstQualifiedName::getQualifiers(), and i.
Referenced by souffle::MagicSetTransformer::transform().
{
     std::vector<std::string> relationNames = relationName.getQualifiers();
     // change the base name
     std::stringstream newMainName;
     newMainName.str("");
     // add a '+' to avoid name conflict
     newMainName << relationNames[0] << "+_" << adornment;
     AstQualifiedName newRelationName(newMainName.str());
     // add in the other names
     for (size_t i = 1; i < relationNames.size(); i++) {
         newRelationName.append(relationNames[i]);
     }
     return newRelationName;
 }
createAnnotatedClause()
AstClause* souffle::createAnnotatedClause (const AstClause * clause, const std::map< const AstArgument *, TypeSet > argumentTypes)
Definition at line 416 of file AstTypeAnalysis.cpp.
References souffle::AstClause::apply(), souffle::AstClause::clone(), i, types, and visitDepthFirst().
Referenced by souffle::TypeAnalysis::run().
{
     // Annotates each variable with its type based on a given type analysis result
     struct TypeAnnotator : public AstNodeMapper {
         const std::map<const AstArgument*, TypeSet>& types;
         TypeAnnotator(const std::map<const AstArgument*, TypeSet>& types) : types(types) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* var = dynamic_cast<AstVariable*>(node.get())) {
                 std::stringstream newVarName;
                 newVarName << var->getName() << "&isin;" << types.find(var)->second;
                 return std::make_unique<AstVariable>(newVarName.str());
             } else if (auto* var = dynamic_cast<AstUnnamedVariable*>(node.get())) {
                 std::stringstream newVarName;
                 newVarName << "_"
                            << "&isin;" << types.find(var)->second;
                 return std::make_unique<AstVariable>(newVarName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     /* Note:
      * Because the type of each argument is stored in the form [address -> type-set],
      * the type-analysis result does not immediately apply to the clone due to differing
      * addresses.
      * Two ways around this:
      *  (1) Perform the type-analysis again for the cloned clause
      *  (2) Keep track of the addresses of equivalent arguments in the cloned clause
      * Method (2) was chosen to avoid having to recompute the analysis each time.
      */
     AstClause* annotatedClause = clause->clone();
     // Maps x -> y, where x is the address of an argument in the original clause, and y
     // is the address of the equivalent argument in the clone.
     std::map<const AstArgument*, const AstArgument*> memoryMap;
     std::vector<const AstArgument*> originalAddresses;
     visitDepthFirst(*clause, [&](const AstArgument& arg) { originalAddresses.push_back(&arg); });
     std::vector<const AstArgument*> cloneAddresses;
     visitDepthFirst(*annotatedClause, [&](const AstArgument& arg) { cloneAddresses.push_back(&arg); });
     assert(cloneAddresses.size() == originalAddresses.size());
     for (size_t i = 0; i < originalAddresses.size(); i++) {
         memoryMap[originalAddresses[i]] = cloneAddresses[i];
     }
     // Map the types to the clause clone
     std::map<const AstArgument*, TypeSet> cloneArgumentTypes;
     for (auto& pair : argumentTypes) {
         cloneArgumentTypes[memoryMap[pair.first]] = pair.second;
     }
     // Create the type-annotated clause
     TypeAnnotator annotator(cloneArgumentTypes);
     annotatedClause->apply(annotator);
     return annotatedClause;
 }
createBrieIndex()
std::unique_ptr< InterpreterIndex > souffle::createBrieIndex (const Order & order)
Definition at line 695 of file InterpreterIndex.cpp.
References souffle::Order::order, and souffle::Order::size().
{
     switch (order.size()) {
         case 0:
             return std::make_unique<NullaryIndex>();
         case 1:
             return std::make_unique<BrieIndex<1>>(order);
         case 2:
             return std::make_unique<BrieIndex<2>>(order);
         case 3:
             return std::make_unique<BrieIndex<3>>(order);
         case 4:
             return std::make_unique<BrieIndex<4>>(order);
         case 5:
             return std::make_unique<BrieIndex<5>>(order);
         case 6:
             return std::make_unique<BrieIndex<6>>(order);
         case 7:
             return std::make_unique<BrieIndex<7>>(order);
         case 8:
             return std::make_unique<BrieIndex<8>>(order);
         case 9:
             return std::make_unique<BrieIndex<9>>(order);
         case 10:
             return std::make_unique<BrieIndex<10>>(order);
         case 11:
             return std::make_unique<BrieIndex<11>>(order);
         case 12:
             return std::make_unique<BrieIndex<12>>(order);
     }
     assert(false && "Requested arity not yet supported. Feel free to add it.");
     return {};
 }
createBTreeIndex()
std::unique_ptr< InterpreterIndex > souffle::createBTreeIndex (const Order & order)
Definition at line 626 of file InterpreterIndex.cpp.
References souffle::Order::order, and souffle::Order::size().
{
     switch (order.size()) {
         case 0:
             return std::make_unique<NullaryIndex>();
         case 1:
             return std::make_unique<BTreeIndex<1>>(order);
         case 2:
             return std::make_unique<BTreeIndex<2>>(order);
         case 3:
             return std::make_unique<BTreeIndex<3>>(order);
         case 4:
             return std::make_unique<BTreeIndex<4>>(order);
         case 5:
             return std::make_unique<BTreeIndex<5>>(order);
         case 6:
             return std::make_unique<BTreeIndex<6>>(order);
         case 7:
             return std::make_unique<BTreeIndex<7>>(order);
         case 8:
             return std::make_unique<BTreeIndex<8>>(order);
         case 9:
             return std::make_unique<BTreeIndex<9>>(order);
         case 10:
             return std::make_unique<BTreeIndex<10>>(order);
         case 11:
             return std::make_unique<BTreeIndex<11>>(order);
         case 12:
             return std::make_unique<BTreeIndex<12>>(order);
     }
     assert(false && "Requested arity not yet supported. Feel free to add it.");
     return {};
 }
createBTreeProvenanceIndex()
std::unique_ptr< InterpreterIndex > souffle::createBTreeProvenanceIndex (const Order & order)
Definition at line 659 of file InterpreterIndex.cpp.
References souffle::Order::order, and souffle::Order::size().
Referenced by souffle::NodeGenerator::createRelation().
{
     switch (order.size()) {
         case 0:
         case 1:
             assert(false && "Provenance relation with arity < 2.");
         case 2:
             return std::make_unique<BTreeProvenanceIndex<2>>(order);
         case 3:
             return std::make_unique<BTreeProvenanceIndex<3>>(order);
         case 4:
             return std::make_unique<BTreeProvenanceIndex<4>>(order);
         case 5:
             return std::make_unique<BTreeProvenanceIndex<5>>(order);
         case 6:
             return std::make_unique<BTreeProvenanceIndex<6>>(order);
         case 7:
             return std::make_unique<BTreeProvenanceIndex<7>>(order);
         case 8:
             return std::make_unique<BTreeProvenanceIndex<8>>(order);
         case 9:
             return std::make_unique<BTreeProvenanceIndex<9>>(order);
         case 10:
             return std::make_unique<BTreeProvenanceIndex<10>>(order);
         case 11:
             return std::make_unique<BTreeProvenanceIndex<11>>(order);
         case 12:
             return std::make_unique<BTreeProvenanceIndex<12>>(order);
         case 13:
             return std::make_unique<BTreeProvenanceIndex<13>>(order);
         case 14:
             return std::make_unique<BTreeProvenanceIndex<14>>(order);
     }
     assert(false && "Requested arity not yet supported. Feel free to add it.");
     return {};
 }
createEqrelIndex()
std::unique_ptr< InterpreterIndex > souffle::createEqrelIndex (const Order & order)
Definition at line 733 of file InterpreterIndex.cpp.
References souffle::Order::order, and souffle::Order::size().
{
     assert(order.size() == 2 && "Eqrel index must have tuple of 2 arities");
     return std::make_unique<EqrelIndex>(order);
 }
createIndirectIndex()
std::unique_ptr< InterpreterIndex > souffle::createIndirectIndex (const Order & order)
Definition at line 728 of file InterpreterIndex.cpp.
References souffle::Order::getOrder(), and souffle::Order::size().
{
     assert(order.size() != 0 && "IndirectIndex does not work with nullary relation\n");
     return std::make_unique<IndirectIndex>(order.getOrder());
 }
createMagicIdentifier()
AstQualifiedName souffle::createMagicIdentifier (const AstQualifiedName & relationName, size_t outputNumber)
Definition at line 228 of file MagicSet.cpp.
References souffle::AstQualifiedName::append(), souffle::AstQualifiedName::getQualifiers(), and i.
Referenced by souffle::MagicSetTransformer::transform().
{
     std::vector<std::string> relationNames = relationName.getQualifiers();
     // change the base name to magic-relation format
     std::stringstream newMainName;
     newMainName.str("");
     newMainName << "+m" << outputNumber << "_" << relationNames[0];  // use "+m" to avoid conflicts
     AstQualifiedName newRelationName(newMainName.str());
     // copy over the other relation names
     for (size_t i = 1; i < relationNames.size(); i++) {
         newRelationName.append(relationNames[i]);
     }
     return newRelationName;
 }
createMagicRelation()
AstRelation* souffle::createMagicRelation (AstRelation * original, const AstQualifiedName & magicPredName)
Definition at line 996 of file MagicSet.cpp.
References clone(), extractAdornment(), souffle::AstRelation::getArity(), and souffle::AstRelation::getAttributes().
Referenced by souffle::MagicSetTransformer::transform().
{
     // get the adornment of this argument
     std::string adornment = extractAdornment(magicPredName);
     // create the relation
     auto* newMagicRelation = new AstRelation();
     newMagicRelation->setQualifiedName(magicPredName);
     // copy over (bound) attributes from the original relation
     std::vector<AstAttribute*> attrs = original->getAttributes();
     for (size_t currentArg = 0; currentArg < original->getArity(); currentArg++) {
         if (adornment[currentArg] == 'b') {
             newMagicRelation->addAttribute(std::unique_ptr<AstAttribute>(attrs[currentArg]->clone()));
         }
     }
     return newMagicRelation;
 }
createNewRelation()
AstRelation* souffle::createNewRelation (AstRelation * original, const AstQualifiedName & newName)
Definition at line 211 of file MagicSet.cpp.
References souffle::AstRelation::getAttributes(), souffle::AstRelation::getRepresentation(), souffle::AstNode::getSrcLoc(), and nextSrcLoc().
Referenced by separateDBs(), and souffle::MagicSetTransformer::transform().
{
     auto* newRelation = new AstRelation();
     newRelation->setSrcLoc(nextSrcLoc(original->getSrcLoc()));
     newRelation->setQualifiedName(newName);
     // copy over the attributes from the original relation
     for (AstAttribute* attr : original->getAttributes()) {
         newRelation->addAttribute(std::unique_ptr<AstAttribute>(attr->clone()));
     }
     // copy over internal representation
     newRelation->setRepresentation(original->getRepresentation());
     return newRelation;
 }
createSubIdentifier()
AstQualifiedName souffle::createSubIdentifier (const AstQualifiedName & relationName, size_t start, size_t length)
Definition at line 265 of file MagicSet.cpp.
References souffle::AstQualifiedName::append(), souffle::AstQualifiedName::getQualifiers(), and i.
Referenced by souffle::MagicSetTransformer::transform().
{
     std::vector<std::string> relationNames = relationName.getQualifiers();
     // get the substring of the base name
     std::stringstream newMainName;
     newMainName.str("");
     newMainName << relationNames[0].substr(start, length);
     AstQualifiedName newRelationName(newMainName.str());
     // add in the remaining names
     for (size_t i = 1; i < relationNames.size(); i++) {
         newRelationName.append(relationNames[i]);
     }
     return newRelationName;
 }
derefIter()
template<typename Iter > IterDerefWrapper<Iter> souffle::derefIter (const Iter & iter)
A factory function enabling the construction of a dereferencing iterator utilizing the automated deduction of template parameters.
Definition at line 80 of file IterUtils.h.
References souffle::IterDerefWrapper< Iter, T >::iter.
Referenced by souffle::TypeSet::begin(), and souffle::TypeSet::end().
{
     return IterDerefWrapper<Iter>(iter);
 }
dirName()
std::string souffle::dirName (const std::string & name) inline
C++-style dirname.
Definition at line 1115 of file Util.h.
Referenced by getCurrentFilename().
{
     if (name.empty()) {
         return ".";
     }
     size_t lastNotSlash = name.find_last_not_of('/');
     // All '/'
     if (lastNotSlash == std::string::npos) {
         return "/";
     }
     size_t leadingSlash = name.find_last_of('/', lastNotSlash);
     // No '/'
     if (leadingSlash == std::string::npos) {
         return ".";
     }
     // dirname is '/'
     if (leadingSlash == 0) {
         return "/";
     }
     return name.substr(0, leadingSlash);
 }
duration_in_ns()
long souffle::duration_in_ns (const time_point & start, const time_point & end) inline
Definition at line 1047 of file Util.h.
{
     return static_cast<long>(std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count());
 }
duration_in_us()
long souffle::duration_in_us (const time_point & start, const time_point & end) inline
Definition at line 1042 of file Util.h.
{
     return static_cast<long>(std::chrono::duration_cast<std::chrono::microseconds>(end - start).count());
 }
endsWith()
bool souffle::endsWith (const std::string & value, const std::string & ending) inline
Determines whether the given value string ends with the given end string.
Definition at line 898 of file Util.h.
{
     if (value.size() < ending.size()) {
         return false;
     }
     return std::equal(ending.rbegin(), ending.rend(), value.rbegin());
 }
eqTypeTypeAttribute()
template<typename T > bool souffle::eqTypeTypeAttribute (const TypeAttribute ramType, const T & type)
Determine if a type analysis' result is equivalent to the given TypeAttribute.
Definition at line 464 of file TypeSystem.h.
References Float, isFloatType(), isNumberType(), isRecordType(), isSymbolType(), isUnsignedType(), Record, Signed, Symbol, and Unsigned.
Referenced by souffle::AstSemanticChecker::checkProgram().
{
     switch (ramType) {
         case TypeAttribute::Signed:
             return isNumberType(type);
         case TypeAttribute::Unsigned:
             return isUnsignedType(type);
         case TypeAttribute::Float:
             return isFloatType(type);
         case TypeAttribute::Symbol:
             return isSymbolType(type);
         case TypeAttribute::Record:
             return isRecordType(type);
     }
     assert(false && "unhandled `TypeAttribute`");
     exit(EXIT_FAILURE);
 }
equal_ptr() [1/2]
template<typename T > bool souffle::equal_ptr (const T * a, const T * b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
Definition at line 574 of file Util.h.
References souffle::range< Iter >::b.
Referenced by souffle::RamRelationStatement::equal(), souffle::RamNestedOperation::equal(), souffle::RamConjunction::equal(), souffle::RamProgram::equal(), souffle::AstNegation::equal(), souffle::RamRelationReference::equal(), souffle::RamNegation::equal(), souffle::RamRelationOperation::equal(), souffle::RamBinRelationStatement::equal(), souffle::AstClause::equal(), souffle::RamConstraint::equal(), souffle::AstBinaryConstraint::equal(), souffle::RamAbstractExistenceCheck::equal(), souffle::RamQuery::equal(), souffle::AstComponent::equal(), souffle::RamEmptinessCheck::equal(), souffle::RamAbstractChoice::equal(), souffle::AstTypeCast::equal(), souffle::RamLoop::equal(), souffle::RamExit::equal(), souffle::AstAggregator::equal(), souffle::RamAbstractLog::equal(), souffle::RamAbstractAggregate::equal(), souffle::RamUnpackRecord::equal(), souffle::RamAbstractConditional::equal(), souffle::RamProject::equal(), and equal_ptr().
{
     if (a == nullptr && b == nullptr) {
         return true;
     }
     if (a != nullptr && b != nullptr) {
         return *a == *b;
     }
     return false;
 }
equal_ptr() [2/2]
template<typename T > bool souffle::equal_ptr (const std::unique_ptr< T > & a, const std::unique_ptr< T > & b)
Compares two values referenced by a pointer where the case where both pointers are null is also considered equivalent.
Definition at line 589 of file Util.h.
References equal_ptr().
{
     return equal_ptr(a.get(), b.get());
 }
equal_targets() [1/4]
template<typename Container , typename Comparator > bool souffle::equal_targets (const Container & a, const Container & b, const Comparator & comp)
A function testing whether two containers are equal with the given Comparator.
Definition at line 524 of file Util.h.
Referenced by souffle::RamAbstractOperator::equal(), souffle::AstAtom::equal(), souffle::AstExecutionPlan::equal(), souffle::RamProgram::equal(), souffle::AstRelation::equal(), souffle::AstClause::equal(), souffle::AstTerm::equal(), souffle::AstProgram::equal(), souffle::RamAbstractExistenceCheck::equal(), souffle::RamIndexOperation::equal(), souffle::AstComponent::equal(), souffle::RamListStatement::equal(), souffle::RamPackRecord::equal(), souffle::AstAggregator::equal(), souffle::RamProject::equal(), souffle::RamSubroutineReturnValue::equal(), equal_targets(), and souffle::RemoveRelationCopiesTransformer::removeRelationCopies().
{
     // check reference
     if (&a == &b) {
         return true;
     }
     // check size
     if (a.size() != b.size()) {
         return false;
     }
     // check content
     return std::equal(a.begin(), a.end(), b.begin(), comp);
 }
equal_targets() [2/4]
template<typename T , template< typename... > class Container> bool souffle::equal_targets (const Container< T *> & a, const Container< T *> & b)
A function testing whether two containers of pointers are referencing equivalent targets.
Definition at line 544 of file Util.h.
References equal_targets().
{
     return equal_targets(a, b, comp_deref<T*>());
 }
equal_targets() [3/4]
template<typename T , template< typename... > class Container> bool souffle::equal_targets (const Container< std::unique_ptr< T >> & a, const Container< std::unique_ptr< T >> & b)
A function testing whether two containers of unique pointers are referencing equivalent targets.
Definition at line 553 of file Util.h.
References souffle::range< Iter >::a, souffle::range< Iter >::b, and equal_targets().
{
     return equal_targets(a, b, comp_deref<std::unique_ptr<T>>());
 }
equal_targets() [4/4]
template<typename Key , typename Value > bool souffle::equal_targets (const std::map< Key, std::unique_ptr< Value >> & a, const std::map< Key, std::unique_ptr< Value >> & b)
A function testing whether two maps of unique pointers are referencing to equivalent targets.
Definition at line 562 of file Util.h.
References souffle::range< Iter >::a, souffle::range< Iter >::b, and equal_targets().
{
     auto comp = comp_deref<std::unique_ptr<Value>>();
     return equal_targets(
             a, b, [&comp](auto& a, auto& b) { return a.first == b.first && comp(a.second, b.second); });
 }
escape() [1/2]
std::string souffle::escape (const std::string & inputString, const std::string & needle, const std::string & replacement) inline
Definition at line 1337 of file Util.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::Synthesiser::generateCode(), souffle::RamIO::print(), and souffle::profile::EventProcessorSingleton::process().
{
     std::string result = inputString;
     size_t pos = 0;
     while ((pos = result.find(needle, pos)) != std::string::npos) {
         result = result.replace(pos, needle.length(), replacement);
         pos += replacement.length();
     }
     return result;
 }
escape() [2/2]
std::string souffle::escape (const std::string & inputString) inline
Definition at line 1348 of file Util.h.
{
     std::string escaped = escape(inputString, "\"", "\\\"");
     escaped = escape(escaped, "\t", "\\t");
     escaped = escape(escaped, "\r", "\\r");
     escaped = escape(escaped, "\n", "\\n");
     return escaped;
 }
escapeJSONstring()
std::string souffle::escapeJSONstring (const std::string & JSONstr) inline
Escape JSON string.
Definition at line 1293 of file Util.h.
Referenced by souffle::Synthesiser::generateCode().
{
     std::ostringstream destination;
     // Iterate over all characters except first and last
     for (char c : JSONstr) {
         if (c == '\"') {
             destination << "\\";
         }
         destination << c;
     }
     return destination.str();
 }
execStdOut() [1/2]
std::stringstream souffle::execStdOut (char const * cmd) inline
Definition at line 1356 of file Util.h.
Referenced by souffle::DebugReporter::generateDiff().
{
     FILE* in = popen(cmd, "r");
     std::stringstream data;
     while (in != nullptr) {
         char c = fgetc(in);
         if (feof(in) != 0) {
             break;
         }
         data << c;
     }
     pclose(in);
     return data;
 }
execStdOut() [2/2]
std::stringstream souffle::execStdOut (std::string const & cmd) inline
Definition at line 1370 of file Util.h.
{
     return execStdOut(cmd.c_str());
 }
executeBinary()
void souffle::executeBinary (const std::string & binaryFilename)
Executes a binary file.
Definition at line 63 of file main.cpp.
References souffle::Global::config(), isExecutable(), and splitString().
Referenced by main().
{
     assert(!binaryFilename.empty() && "binary filename cannot be blank");
     // check whether the executable exists
     if (!isExecutable(binaryFilename)) {
         throw std::invalid_argument("Generated executable <" + binaryFilename + "> could not be found");
     }
     // run the executable
     if (Global::config().has("library-dir")) {
         std::string ldPath;
         for (const std::string& library : splitString(Global::config().get("library-dir"), ' ')) {
             ldPath += library + ':';
         }
         ldPath.back() = ' ';
         setenv("LD_LIBRARY_PATH", ldPath.c_str(), 1);
         setenv("DYLD_LIBRARY_PATH", ldPath.c_str(), 1);
     }
     int exitCode = system(binaryFilename.c_str());
     if (Global::config().get("dl-program").empty()) {
         remove(binaryFilename.c_str());
         remove((binaryFilename + ".cpp").c_str());
     }
     // exit with same code as executable
     if (exitCode != EXIT_SUCCESS) {
         exit(exitCode);
     }
 }
existDir()
bool souffle::existDir (const std::string & name) inline
Check whether a directory exists in the file system.
Definition at line 1071 of file Util.h.
Referenced by main().
{
     struct stat buffer = {};
     if (stat(name.c_str(), &buffer) == 0) {
         if ((buffer.st_mode & S_IFDIR) != 0) {
             return true;
         }
     }
     return false;
 }
existFile()
bool souffle::existFile (const std::string & name) inline
Check whether a file exists in the file system.
Definition at line 1058 of file Util.h.
Referenced by getCurrentFilename(), and main().
{
     struct stat buffer = {};
     if (stat(name.c_str(), &buffer) == 0) {
         if ((buffer.st_mode & S_IFMT) != 0) {
             return true;
         }
     }
     return false;
 }
explain()
void souffle::explain (SouffleProgram & prog, bool ncurses, bool useSubtreelevels) inline
Definition at line 621 of file Explain.h.
Referenced by souffle::ExplainProvenance::ExplainProvenance(), main(), souffle::Explain::parseTuple(), souffle::Explain::printError(), and souffle::Explain::processCommand().
{
     ExplainProvenanceImpl prov(prog, useSubtreelevels);
     if (ncurses) {
 #ifdef USE_NCURSES
         ExplainNcurses exp(prov);
         exp.explain();
 #else
         std::cout << "The ncurses-based interface is not enabled\n";
 #endif
     } else {
         ExplainConsole exp(prov);
         exp.explain();
     }
 }
extractAdornment()
std::string souffle::extractAdornment (const AstQualifiedName & magicRelationName)
Definition at line 962 of file MagicSet.cpp.
References getEndpoint(), and souffle::AstQualifiedName::getQualifiers().
Referenced by createMagicRelation().
{
     std::string baseRelationName = magicRelationName.getQualifiers()[0];
     int endpt = getEndpoint(baseRelationName);
     std::string adornment = baseRelationName.substr(endpt + 1, baseRelationName.size() - (endpt + 1));
     return adornment;
 }
extractConstant()
AstArgument* souffle::extractConstant (const std::string & normalisedConstant)
Definition at line 970 of file MagicSet.cpp.
References souffle::AstNumericConstant::Float, souffle::AstNumericConstant::Int, and souffle::AstNumericConstant::Uint.
Referenced by souffle::MagicSetTransformer::transform().
{
     // strip off the prefix up to (and including) the first underscore
     size_t argStart = normalisedConstant.find('_');
     std::string arg = normalisedConstant.substr(argStart + 1, normalisedConstant.size());
     // -- check if string or num constant --
     char indicatorChar = arg[arg.size() - 1];  // 'n' or 's'
     std::string stringRep = arg.substr(0, arg.size() - 2);
     if (indicatorChar == 's') {
         // string argument
         return new AstStringConstant(stringRep);
     } else if (indicatorChar == 'n') {
         // numeric argument
         return new AstNumericConstant(stringRep, AstNumericConstant::Type::Int);
     } else if (indicatorChar == 'u') {
         return new AstNumericConstant(stringRep, AstNumericConstant::Type::Uint);
     } else if (indicatorChar == 'f') {
         return new AstNumericConstant(stringRep, AstNumericConstant::Type::Float);
     } else {
         // invalid format
         return nullptr;
     }
 }
extractPermutations()
std::vector<std::vector<unsigned int> > souffle::extractPermutations (const std::vector< std::vector< unsigned int >> & permutationMatrix)
Extract valid permutations from a given permutation matrix of valid moves.
Definition at line 41 of file MinimiseProgramTransformer.cpp.
References i, j, and seen.
Referenced by areBijectivelyEquivalent().
{
     size_t clauseSize = permutationMatrix.size();
     // keep track of the possible end-positions of each atom in the first clause
     std::vector<std::vector<unsigned int>> validMoves;
     for (size_t i = 0; i < clauseSize; i++) {
         std::vector<unsigned int> currentRow;
         for (size_t j = 0; j < clauseSize; j++) {
             if (permutationMatrix[i][j] == 1) {
                 currentRow.push_back(j);
             }
         }
         validMoves.push_back(currentRow);
     }
     // extract the possible permutations, DFS style
     std::vector<std::vector<unsigned int>> permutations;
     std::vector<unsigned int> seen(clauseSize);
     std::vector<unsigned int> currentPermutation;
     std::stack<std::vector<unsigned int>> todoStack;
     todoStack.push(validMoves[0]);
     size_t currentIdx = 0;
     while (!todoStack.empty()) {
         if (currentIdx == clauseSize) {
             // permutation is complete
             permutations.push_back(currentPermutation);
             if (currentIdx == 0) {
                 // already at starting position, so no more permutations possible
                 break;
             }
             // undo the last number added to the permutation
             currentIdx--;
             seen[currentPermutation[currentIdx]] = 0;
             currentPermutation.pop_back();
             // see if we can pick up other permutations
             continue;
         }
         // pull out the possibilities for the current point of the permutation
         std::vector<unsigned int> possibilities = todoStack.top();
         todoStack.pop();
         if (possibilities.empty()) {
             // no more possibilities at this point, so undo our last move
             if (currentIdx == 0) {
                 // already at starting position, so no more permutations possible
                 break;
             }
             currentIdx--;
             seen[currentPermutation[currentIdx]] = 0;
             currentPermutation.pop_back();
             // continue looking for permutations
             continue;
         }
         // try the next possibility
         unsigned int nextNum = possibilities[0];
         // update the possibility vector for the current position
         possibilities.erase(possibilities.begin());
         todoStack.push(possibilities);
         if (seen[nextNum] != 0u) {
             // number already seen in this permutation
             continue;
         } else {
             // number can be used
             seen[nextNum] = 1;
             currentPermutation.push_back(nextNum);
             currentIdx++;
             // if we havent reached the end of the permutation,
             // push up the valid moves for the next position
             if (currentIdx < clauseSize) {
                 todoStack.push(validMoves[currentIdx]);
             }
         }
     }
     // found all permutations
     return permutations;
 }
fileExtension()
std::string souffle::fileExtension (const std::string & path) inline
File extension, with all else removed.
Definition at line 1221 of file Util.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::AstTranslator::translateProgram().
{
     std::string name = path;
     const size_t lastDot = name.find_last_of('.');
     // file has no extension
     if (lastDot == std::string::npos) {
         return std::string();
     }
     const size_t lastSlash = name.find_last_of('/');
     // last slash occurs after last dot, so no extension
     if (lastSlash != std::string::npos && lastSlash > lastDot) {
         return std::string();
     }
     // last dot after last slash, or no slash
     return name.substr(lastDot + 1);
 }
findInlineCycle()
std::vector<AstQualifiedName> souffle::findInlineCycle (const PrecedenceGraph & precedenceGraph, std::map< const AstRelation *, const AstRelation *> & origins, const AstRelation * current, AstRelationSet & unvisited, AstRelationSet & visiting, AstRelationSet & visited)
Find a cycle consisting entirely of inlined relations.
If no cycle exists, then an empty vector is returned.
Definition at line 1141 of file AstSemanticChecker.cpp.
References souffle::AstRelation::getQualifiedName(), souffle::PrecedenceGraph::graph(), and INLINE.
Referenced by souffle::AstSemanticChecker::checkInlining().
{
     std::vector<AstQualifiedName> result;
     if (current == nullptr) {
         // Not looking at any nodes at the moment, so choose any node from the unvisited list
         if (unvisited.empty()) {
             // Nothing left to visit - so no cycles exist!
             return result;
         }
         // Choose any element from the unvisited set
         current = *unvisited.begin();
         origins[current] = nullptr;
         // Move it to "currently visiting"
         unvisited.erase(current);
         visiting.insert(current);
         // Check if we can find a cycle beginning from this node
         std::vector<AstQualifiedName> subresult =
                 findInlineCycle(precedenceGraph, origins, current, unvisited, visiting, visited);
         if (subresult.empty()) {
             // No cycle found, try again from another node
             return findInlineCycle(precedenceGraph, origins, nullptr, unvisited, visiting, visited);
         } else {
             // Cycle found! Return it
             return subresult;
         }
     }
     // Check neighbours
     const AstRelationSet& successors = precedenceGraph.graph().successors(current);
     for (const AstRelation* successor : successors) {
         // Only care about inlined neighbours in the graph
         if (successor->hasQualifier(RelationQualifier::INLINE)) {
             if (visited.find(successor) != visited.end()) {
                 // The neighbour has already been visited, so move on
                 continue;
             }
             if (visiting.find(successor) != visiting.end()) {
                 // Found a cycle!!
                 // Construct the cycle in reverse
                 while (current != nullptr) {
                     result.push_back(current->getQualifiedName());
                     current = origins[current];
                 }
                 return result;
             }
             // Node has not been visited yet
             origins[successor] = current;
             // Move from unvisited to visiting
             unvisited.erase(successor);
             visiting.insert(successor);
             // Visit recursively and check if a cycle is formed
             std::vector<AstQualifiedName> subgraphCycle =
                     findInlineCycle(precedenceGraph, origins, successor, unvisited, visiting, visited);
             if (!subgraphCycle.empty()) {
                 // Found a cycle!
                 return subgraphCycle;
             }
         }
     }
     // Visited all neighbours with no cycle found, so done visiting this node.
     visiting.erase(current);
     visited.insert(current);
     return result;
 }
findTool()
std::string souffle::findTool (const std::string & tool, const std::string & base, const std::string & path) inline
Definition at line 1165 of file Util.h.
Referenced by main().
{
     std::string dir = dirName(base);
     std::stringstream sstr(path);
     std::string sub;
     while (std::getline(sstr, sub, ':')) {
         std::string subpath = dir + "/" + sub + '/' + tool;
         if (isExecutable(subpath)) {
             return absPath(subpath);
         }
     }
     return "";
 }
formatCodeSection()
DebugReportSection souffle::formatCodeSection (const std::string & id, const std::string & title, std::string code)
Definition at line 50 of file DebugReporter.cpp.
References i.
{
     std::stringstream codeHTML;
     std::string escapedCode = std::move(code);
     while (true) {
         size_t i = escapedCode.find("<");
         if (i == std::string::npos) {
             break;
         }
         escapedCode.replace(i, 1, "&lt;");
     }
     codeHTML << "<pre>" << escapedCode << "</pre>\n";
     return DebugReportSection(id, title, codeHTML.str());
 }
formNegatedLiterals()
std::vector<std::vector<AstLiteral*> > souffle::formNegatedLiterals (AstProgram & program, AstAtom * atom)
Forms the bodies that will replace the negation of a given inlined atom.
E.g. a(x) <- (a11(x), a12(x)) ; (a21(x), a22(x)) => !a(x) <- (!a11(x), !a21(x)) ; (!a11(x), !a22(x)) ; ... Essentially, produce every combination (m_1 ^ m_2 ^ ...) where m_i is the negation of a literal in the ith rule of a.
Definition at line 422 of file InlineRelationsTransformer.cpp.
References combineNegatedLiterals(), getClauses(), souffle::AstAtom::getQualifiedName(), getRelation(), souffle::NullableVector< T >::getVector(), inlineBodyLiterals(), and souffle::NullableVector< T >::isValid().
Referenced by getInlinedLiteral().
{
     // Constraints added to unify atoms should not be negated and should be added to
     // all the final rule combinations produced, and so should be stored separately.
     std::vector<std::vector<AstLiteral*>> addedBodyLiterals;
     std::vector<std::vector<AstBinaryConstraint*>> addedConstraints;
     // Go through every possible clause associated with the given atom
     for (AstClause* inClause : getClauses(program, *getRelation(program, atom->getQualifiedName()))) {
         // Form the replacement clause by inlining based on the current clause
         std::pair<NullableVector<AstLiteral*>, std::vector<AstBinaryConstraint*>> inlineResult =
                 inlineBodyLiterals(atom, inClause);
         NullableVector<AstLiteral*> replacementBodyLiterals = inlineResult.first;
         std::vector<AstBinaryConstraint*> currConstraints = inlineResult.second;
         if (!replacementBodyLiterals.isValid()) {
             // Failed to unify, so just move on
             continue;
         }
         addedBodyLiterals.push_back(replacementBodyLiterals.getVector());
         addedConstraints.push_back(currConstraints);
     }
     // We now have a list of bodies needed to inline the given atom.
     // We want to inline the negated version, however, which is done using De Morgan's Law.
     std::vector<std::vector<AstLiteral*>> negatedAddedBodyLiterals =
             combineNegatedLiterals(addedBodyLiterals);
     // Add in the necessary constraints to all the body literals
     for (auto& negatedAddedBodyLiteral : negatedAddedBodyLiterals) {
         for (std::vector<AstBinaryConstraint*> constraintGroup : addedConstraints) {
             for (AstBinaryConstraint* constraint : constraintGroup) {
                 negatedAddedBodyLiteral.push_back(constraint->clone());
             }
         }
     }
     // Free up the old body literals and constraints
     for (std::vector<AstLiteral*> litGroup : addedBodyLiterals) {
         for (AstLiteral* lit : litGroup) {
             delete lit;
         }
     }
     for (std::vector<AstBinaryConstraint*> consGroup : addedConstraints) {
         for (AstConstraint* cons : consGroup) {
             delete cons;
         }
     }
     return negatedAddedBodyLiterals;
 }
functorOpArgType()
TypeAttribute souffle::functorOpArgType (const size_t arg, const FunctorOp op) inline
Check the type of argument indicated by arg (0-indexed) of a functor op.
Definition at line 362 of file FunctorOps.h.
References ADD, BAND, BNOT, BOR, BSHIFT_L, BSHIFT_R, BSHIFT_R_UNSIGNED, BXOR, CAT, DIV, EXP, FADD, FDIV, FEXP, Float, FMAX, FMIN, FMUL, FNEG, FSUB, FTOI, FTOU, ITOF, ITOU, LAND, LNOT, LOR, MAX, MIN, MOD, MUL, NEG, ORD, Record, Signed, SMAX, SMIN, STRLEN, SUB, SUBSTR, Symbol, TONUMBER, TOSTRING, UADD, UBAND, UBNOT, UBOR, UBSHIFT_L, UBSHIFT_R, UBSHIFT_R_UNSIGNED, UBXOR, UDIV, UEXP, ULAND, ULNOT, ULOR, UMAX, UMIN, UMOD, UMUL, Unsigned, USUB, UTOF, and UTOI.
Referenced by souffle::AstIntrinsicFunctor::getArgType().
{
     switch (op) {
         // Special case
         case FunctorOp::ORD:
             assert(false && "ord is a special function that returns a Ram Representation of the element");
         case FunctorOp::ITOF:
         case FunctorOp::ITOU:
         case FunctorOp::NEG:
         case FunctorOp::BNOT:
         case FunctorOp::LNOT:
         case FunctorOp::TOSTRING:
             assert(arg == 0 && "unary functor out of bound");
             return TypeAttribute::Signed;
         case FunctorOp::FNEG:
         case FunctorOp::FTOI:
         case FunctorOp::FTOU:
             assert(arg == 0 && "unary functor out of bound");
             return TypeAttribute::Float;
         case FunctorOp::STRLEN:
         case FunctorOp::TONUMBER:
             assert(arg == 0 && "unary functor out of bound");
             return TypeAttribute::Symbol;
         case FunctorOp::UBNOT:
         case FunctorOp::ULNOT:
         case FunctorOp::UTOI:
         case FunctorOp::UTOF:
             assert(arg == 0 && "unary functor out of bound");
             return TypeAttribute::Unsigned;
         case FunctorOp::ADD:
         case FunctorOp::SUB:
         case FunctorOp::MUL:
         case FunctorOp::DIV:
         case FunctorOp::EXP:
         case FunctorOp::MOD:
         case FunctorOp::BAND:
         case FunctorOp::BOR:
         case FunctorOp::BXOR:
         case FunctorOp::BSHIFT_L:
         case FunctorOp::BSHIFT_R:
         case FunctorOp::BSHIFT_R_UNSIGNED:
         case FunctorOp::LAND:
         case FunctorOp::LOR:
             assert(arg < 2 && "binary functor out of bound");
             return TypeAttribute::Signed;
         case FunctorOp::UADD:
         case FunctorOp::USUB:
         case FunctorOp::UMUL:
         case FunctorOp::UDIV:
         case FunctorOp::UEXP:
         case FunctorOp::UMOD:
         case FunctorOp::UBAND:
         case FunctorOp::UBOR:
         case FunctorOp::UBXOR:
         case FunctorOp::UBSHIFT_L:
         case FunctorOp::UBSHIFT_R:
         case FunctorOp::UBSHIFT_R_UNSIGNED:
         case FunctorOp::ULAND:
         case FunctorOp::ULOR:
             assert(arg < 2 && "binary functor out of bound");
             return TypeAttribute::Unsigned;
         case FunctorOp::FADD:
         case FunctorOp::FSUB:
         case FunctorOp::FMUL:
         case FunctorOp::FDIV:
         case FunctorOp::FEXP:
             assert(arg < 2 && "binary functor out of bound");
             return TypeAttribute::Float;
         case FunctorOp::SUBSTR:
             assert(arg < 3 && "ternary functor out of bound");
             if (arg == 0) {
                 return TypeAttribute::Symbol;
             } else {
                 return TypeAttribute::Signed;  // In the future: Change to unsigned
             }
         case FunctorOp::MAX:
         case FunctorOp::MIN:
             return TypeAttribute::Signed;
         case FunctorOp::UMAX:
         case FunctorOp::UMIN:
             return TypeAttribute::Unsigned;
         case FunctorOp::FMAX:
         case FunctorOp::FMIN:
             return TypeAttribute::Float;
         case FunctorOp::SMAX:
         case FunctorOp::SMIN:
         case FunctorOp::CAT:
             return TypeAttribute::Symbol;
     }
     assert(false && "unsupported operator");
     exit(EXIT_FAILURE);
     return TypeAttribute::Record;  // silence warning.
 }
functorReturnType()
TypeAttribute souffle::functorReturnType (const FunctorOp op) inline
Check a functor's return type (codomain).
Definition at line 288 of file FunctorOps.h.
References ADD, BAND, BNOT, BOR, BSHIFT_L, BSHIFT_R, BSHIFT_R_UNSIGNED, BXOR, CAT, DIV, EXP, FADD, FDIV, FEXP, Float, FMAX, FMIN, FMUL, FNEG, FSUB, FTOI, FTOU, ITOF, ITOU, LAND, LNOT, LOR, MAX, MIN, MOD, MUL, NEG, ORD, Record, Signed, SMAX, SMIN, STRLEN, SUB, SUBSTR, Symbol, TONUMBER, TOSTRING, UADD, UBAND, UBNOT, UBOR, UBSHIFT_L, UBSHIFT_R, UBSHIFT_R_UNSIGNED, UBXOR, UDIV, UEXP, ULAND, ULNOT, ULOR, UMAX, UMIN, UMOD, UMUL, Unsigned, USUB, UTOF, and UTOI.
Referenced by souffle::AstIntrinsicFunctor::getReturnType().
{
     switch (op) {
         case FunctorOp::ORD:
         case FunctorOp::STRLEN:
         case FunctorOp::NEG:
         case FunctorOp::BNOT:
         case FunctorOp::LNOT:
         case FunctorOp::TONUMBER:
         case FunctorOp::ADD:
         case FunctorOp::SUB:
         case FunctorOp::MUL:
         case FunctorOp::DIV:
         case FunctorOp::EXP:
         case FunctorOp::BAND:
         case FunctorOp::BOR:
         case FunctorOp::BXOR:
         case FunctorOp::BSHIFT_L:
         case FunctorOp::BSHIFT_R:
         case FunctorOp::BSHIFT_R_UNSIGNED:
         case FunctorOp::LAND:
         case FunctorOp::LOR:
         case FunctorOp::MOD:
         case FunctorOp::MAX:
         case FunctorOp::MIN:
         case FunctorOp::FTOI:
         case FunctorOp::UTOI:
             return TypeAttribute::Signed;
         case FunctorOp::UBNOT:
         case FunctorOp::ITOU:
         case FunctorOp::FTOU:
         case FunctorOp::ULNOT:
         case FunctorOp::UADD:
         case FunctorOp::USUB:
         case FunctorOp::UMUL:
         case FunctorOp::UDIV:
         case FunctorOp::UEXP:
         case FunctorOp::UMAX:
         case FunctorOp::UMIN:
         case FunctorOp::UMOD:
         case FunctorOp::UBAND:
         case FunctorOp::UBOR:
         case FunctorOp::UBXOR:
         case FunctorOp::UBSHIFT_L:
         case FunctorOp::UBSHIFT_R:
         case FunctorOp::UBSHIFT_R_UNSIGNED:
         case FunctorOp::ULAND:
         case FunctorOp::ULOR:
             return TypeAttribute::Unsigned;
         case FunctorOp::FMAX:
         case FunctorOp::FMIN:
         case FunctorOp::FNEG:
         case FunctorOp::FADD:
         case FunctorOp::FSUB:
         case FunctorOp::ITOF:
         case FunctorOp::UTOF:
         case FunctorOp::FMUL:
         case FunctorOp::FDIV:
         case FunctorOp::FEXP:
             return TypeAttribute::Float;
         case FunctorOp::SMAX:
         case FunctorOp::SMIN:
         case FunctorOp::TOSTRING:
         case FunctorOp::CAT:
         case FunctorOp::SUBSTR:
             return TypeAttribute::Symbol;
     }
     assert(false && "Bad functor return type query");
     exit(EXIT_FAILURE);
     return TypeAttribute::Record;  // Silence warning.
 }
genJsonRules()
std::stringstream& souffle::genJsonRules (std::stringstream & ss, const std::string & name, size_t maxRows)
Definition at line 322 of file Tui.h.
References souffle::profile::Tools::cleanJsonOut(), souffle::profile::OutputProcessor::getProgramRun(), souffle::profile::Table::getRows(), souffle::profile::OutputProcessor::getVersions(), i, souffle::Table< T, blockSize >::size(), souffle::profile::Tools::split(), souffle::profile::ss, and toString().
Referenced by genJsonAtoms().
{
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         ss << '"' << name << R"_(":{)_";
         bool firstRow = true;
         auto rows = ruleTable.getRows();
         std::stable_sort(rows.begin(), rows.end(), [](std::shared_ptr<Row> left, std::shared_ptr<Row> right) {
             return (*left)[0]->getDoubleVal() > (*right)[0]->getDoubleVal();
         });
         maxRows = std::min(rows.size(), maxRows);
         for (size_t i = 0; i < maxRows; ++i) {
             Row& row = *rows[i];
             std::vector<std::string> part = Tools::split(row[6]->toString(0), ".");
             std::string strRel = "R" + part[0].substr(1);
             Table versionTable = out.getVersions(strRel, row[6]->toString(0));
             std::string src;
             if (versionTable.rows.size() > 0) {
                 if (versionTable.rows[0]->cells[9] != nullptr) {
                     src = (*versionTable.rows[0])[9]->toString(0);
                 } else {
                     src = "-";
                 }
             } else {
                 src = row[10]->toString(-1);
             }
             comma(firstRow);
             ss << "\n ";
             ss << '"' << row[6]->toString(0) << R"_(": [)_";
             ss << '"' << Tools::cleanJsonOut(row[5]->toString(0)) << R"_(", )_";
             ss << '"' << Tools::cleanJsonOut(row[6]->toString(0)) << R"_(", )_";
             ss << row[0]->getDoubleVal() << ", ";
             ss << row[1]->getDoubleVal() << ", ";
             ss << row[2]->getDoubleVal() << ", ";
             ss << row[4]->getLongVal() << ", ";
             ss << '"' << src << R"_(", )_";
             ss << "[";
             bool has_ver = false;
             bool firstCol = true;
             for (auto& _ver_row : versionTable.getRows()) {
                 comma(firstCol);
                 has_ver = true;
                 Row ver_row = *_ver_row;
                 ss << '[';
                 ss << '"' << Tools::cleanJsonOut(ver_row[5]->toString(0)) << R"_(", )_";
                 ss << '"' << Tools::cleanJsonOut(ver_row[6]->toString(0)) << R"_(", )_";
                 ss << ver_row[0]->getDoubleVal() << ", ";
                 ss << ver_row[1]->getDoubleVal() << ", ";
                 ss << ver_row[2]->getDoubleVal() << ", ";
                 ss << ver_row[4]->getLongVal() << ", ";
                 ss << '"' << src << R"_(", )_";
                 ss << ver_row[8]->getLongVal();
                 ss << ']';
             }
             ss << "], ";
             if (row[6]->toString(0).at(0) != 'C') {
                 ss << "{}, {}]";
             } else {
                 ss << R"_({"tot_t": [)_";
                 std::vector<uint64_t> iteration_tuples;
                 bool firstCol = true;
                 for (auto& i : run->getRelation(row[7]->toString(0))->getIterations()) {
                     bool add = false;
                     std::chrono::microseconds totalTime{};
                     uint64_t totalSize = 0L;
                     for (auto& rul : i->getRules()) {
                         if (rul.second->getId() == row[6]->toString(0)) {
                             totalTime += rul.second->getRuntime();
                             totalSize += rul.second->size();
                             add = true;
                         }
                     }
                     if (add) {
                         comma(firstCol);
                         ss << totalTime.count();
                         iteration_tuples.push_back(totalSize);
                     }
                 }
                 ss << R"_(], "tuples": [)_";
                 firstCol = true;
                 for (auto& i : iteration_tuples) {
                     comma(firstCol);
                     ss << i;
                 }
                 ss << "]}, {";
                 if (has_ver) {
                     ss << R"_("tot_t": [)_";
                     firstCol = true;
                     for (auto& row : versionTable.rows) {
                         comma(firstCol);
                         ss << (*row)[0]->getDoubleVal();
                     }
                     ss << R"_(], "tuples": [)_";
                     firstCol = true;
                     for (auto& row : versionTable.rows) {
                         comma(firstCol);
                         ss << (*row)[4]->getLongVal();
                     }
                     ss << ']';
                 }
                 ss << "}]";
             }
         }
         ss << "\n}";
         return ss;
     }
     std::stringstream& genJsonUsage(std::stringstream& ss) {
         const std::shared_ptr<ProgramRun>& run = out.getProgramRun();
         auto comma = [&ss](bool& first, const std::string& delimiter = ", ") {
             if (!first) {
                 ss << delimiter;
             } else {
                 first = false;
             }
         };
         std::string source_loc = (*relationTable.getRows()[0])[7]->getStringVal();
         std::string source_file_loc = Tools::split(source_loc, " ").at(0);
         std::ifstream source_file(source_file_loc);
         if (!source_file.is_open()) {
             std::cout << "Error opening \"" << source_file_loc << "\", creating GUI without source locator."
                       << std::endl;
         } else {
getAtomRelation()
const AstRelation * souffle::getAtomRelation (const AstAtom * atom, const AstProgram * program)
Returns the relation referenced by the given atom.
Parameters
atom the atom
program the program containing the relations
Returns
relation referenced by the atom
Definition at line 75 of file AstUtils.cpp.
References souffle::AstAtom::getQualifiedName(), and getRelation().
Referenced by souffle::TypeAnalysis::analyseTypes(), getBodyLiterals(), getBodyRelations(), getHeadRelation(), hasClauseWithAggregatedRelation(), hasClauseWithNegatedRelation(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::AstExecutionPlanChecker::transform(), and souffle::AstTranslator::translateRecursiveRelation().
{
     return getRelation(*program, atom->getQualifiedName());
 }
getBinaryConstraintTypes()
std::vector<TypeAttribute> souffle::getBinaryConstraintTypes (const BinaryConstraintOp op) inline
Get type binary constraint operates on.
Definition at line 313 of file BinaryConstraintOps.h.
References COMPARE_EQUALS, COMPARE_OP, CONTAINS, EQ, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, and Symbol.
Referenced by souffle::AstSemanticChecker::checkProgram().
{
     // clang-format off
 #define COMPARE_EQUALS(op)                                                             \
     case BinaryConstraintOp::F##op: return { TypeAttribute::Float };                   \
     case BinaryConstraintOp::   op:                                                    \
         return { TypeAttribute::Signed, TypeAttribute::Unsigned, TypeAttribute::Float, \
                  TypeAttribute::Symbol, TypeAttribute::Record };
 #define COMPARE_OP(op)                                                  \
     case BinaryConstraintOp::   op: return { TypeAttribute::Signed   }; \
     case BinaryConstraintOp::U##op: return { TypeAttribute::Unsigned }; \
     case BinaryConstraintOp::F##op: return { TypeAttribute::Float    }; \
     case BinaryConstraintOp::S##op: return { TypeAttribute::Symbol   };
     // clang-format on
     switch (op) {
         COMPARE_EQUALS(EQ)
         COMPARE_EQUALS(NE)
         COMPARE_OP(LT)
         COMPARE_OP(LE)
         COMPARE_OP(GT)
         COMPARE_OP(GE)
         case BinaryConstraintOp::MATCH:
         case BinaryConstraintOp::NOT_MATCH:
         case BinaryConstraintOp::CONTAINS:
         case BinaryConstraintOp::NOT_CONTAINS:
             return {TypeAttribute::Symbol};
     }
     assert(false && "Uncovered case!");
     exit(EXIT_FAILURE);
 #undef COMPARE_EQUALS
 #undef COMPARE_OP
 }
getBodyLiterals()
template<typename T , typename C > std::vector<T*> souffle::getBodyLiterals (const C & clause)
Returns literals of a particular type in the body of a clause.
Parameters
the clause
Returns
vector of body literals of the specified type
Definition at line 68 of file AstUtils.h.
References cloneHead(), getAtomRelation(), getBodyRelations(), getClauseNum(), getClauses(), getFunctorDeclaration(), getHeadRelation(), getRelation(), getType(), hasClauseWithAggregatedRelation(), hasClauseWithNegatedRelation(), isFact(), isRecursiveClause(), isRule(), negateConstraint(), relation, removeRelationClauses(), and reorderAtoms().
Referenced by souffle::AstClause::print().
{
     std::vector<T*> res;
     for (auto& lit : clause.getBodyLiterals()) {
         if (T* t = dynamic_cast<T*>(lit)) {
             res.push_back(t);
         }
     }
     return res;
 }
getBodyRelations()
std::set< const AstRelation * > souffle::getBodyRelations (const AstClause * clause, const AstProgram * program)
Returns the relations referenced in the body of the given clause.
Parameters
clause the clause
program the program containing the relations
Returns
relation referenced in the clause body
Definition at line 83 of file AstUtils.cpp.
References souffle::AstAtom::getArguments(), getAtomRelation(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), and visitDepthFirst().
Referenced by getBodyLiterals(), and souffle::PrecedenceGraph::run().
{
     std::set<const AstRelation*> bodyRelations;
     for (const auto& lit : clause->getBodyLiterals()) {
         visitDepthFirst(
                 *lit, [&](const AstAtom& atom) { bodyRelations.insert(getAtomRelation(&atom, program)); });
     }
     for (const auto& arg : clause->getHead()->getArguments()) {
         visitDepthFirst(
                 *arg, [&](const AstAtom& atom) { bodyRelations.insert(getAtomRelation(&atom, program)); });
     }
     return bodyRelations;
 }
getClauseNum()
size_t souffle::getClauseNum (const AstProgram * program, const AstClause * clause)
Returns the index of a clause within its relation, ignoring facts.
Used in provenance as a unique ID for clauses within their relations.
Parameters
program the program
clause the clause to get the index of
Returns
the index of the clause ignoring facts; 0 for facts
Definition at line 96 of file AstUtils.cpp.
References getClauses(), souffle::AstClause::getHead(), souffle::AstAtom::getQualifiedName(), getRelation(), and isFact().
Referenced by getBodyLiterals(), souffle::ProvenanceTransformer::transformMaxHeight(), souffle::ProvenanceTransformer::transformSubtreeHeights(), and souffle::AstTranslator::translateProgram().
{
     // TODO (azreika): This number might change between the provenance transformer and the AST->RAM
     // translation. Might need a better way to assign IDs to clauses... (see PR #1288).
     const AstRelation* rel = getRelation(*program, clause->getHead()->getQualifiedName());
     assert(rel != nullptr && "clause relation does not exist");
     size_t clauseNum = 1;
     for (const auto* cur : getClauses(*program, *rel)) {
         bool isFact = cur->getBodyLiterals().empty();
         if (cur == clause) {
             return isFact ? 0 : clauseNum;
         }
         if (!isFact) {
             clauseNum++;
         }
     }
     assert(false && "clause does not exist");
 }
getClauses() [1/2]
std::vector< AstClause * > souffle::getClauses (const AstProgram & program, const AstQualifiedName & relationName)
Returns a vector of clauses in the program describing the relation with the given name.
Parameters
program the program
name the name of the relation to search for
Returns
vector of clauses describing the relation with the given name
Definition at line 42 of file AstUtils.cpp.
References clauses, and souffle::AstProgram::getClauses().
Referenced by addBackwardDependencies(), addForwardDependencies(), bindComposites(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkProgram(), souffle::AstSemanticChecker::checkRelation(), souffle::AuxiliaryArity::computeArity(), formNegatedLiterals(), getBodyLiterals(), getClauseNum(), getClauses(), souffle::RelationDetailCache::getClauses(), getInlinedLiteral(), hasClauseWithAggregatedRelation(), hasClauseWithNegatedRelation(), normaliseInlinedHeads(), reduceLocallyEquivalentClauses(), reduceSingletonRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), removeRelationClauses(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), replaceUnderscores(), souffle::TypeAnalysis::run(), souffle::PrecedenceGraph::run(), souffle::Adornment::run(), separateDBs(), souffle::ResolveAliasesTransformer::transform(), souffle::AstExecutionPlanChecker::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::InlineRelationsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::NameUnnamedVariablesTransformer::transform(), souffle::ReorderLiteralsTransformer::transform(), souffle::NormaliseConstraintsTransformer::transform(), souffle::ProvenanceTransformer::transformMaxHeight(), souffle::ProvenanceTransformer::transformSubtreeHeights(), souffle::AstTranslator::translateNonRecursiveRelation(), and souffle::AstTranslator::translateRecursiveRelation().
{
     std::vector<AstClause*> clauses;
     for (AstClause* clause : program.getClauses()) {
         if (clause->getHead()->getQualifiedName() == relationName) {
             clauses.push_back(clause);
         }
     }
     return clauses;
 }
getClauses() [2/2]
std::vector< AstClause * > souffle::getClauses (const AstProgram & program, const AstRelation & rel)
Returns a vector of clauses in the program describing the given relation.
Parameters
program the program
rel the relation to search for
Returns
vector of clauses describing the given relation
Definition at line 52 of file AstUtils.cpp.
References getClauses(), and souffle::AstRelation::getQualifiedName().
{
     return getClauses(program, rel.getQualifiedName());
 }
getCurrentFilename()
std::string souffle::getCurrentFilename (const std::vector< std::string > & filenames)
Definition at line 27 of file SrcLocation.cpp.
References baseName(), dirName(), and existFile().
Referenced by souffle::SrcLocation::extloc(), souffle::SrcLocation::operator<(), and souffle::SrcLocation::print().
{
     if (filenames.empty()) {
         return "";
     }
     std::string path = ".";
     for (std::string filename : filenames) {
         if (!filename.empty() && filename[0] == '/') {
             path = dirName(filename);
         } else if (existFile(path + "/" + filename)) {
             path = dirName(path + "/" + filename);
         } else if (existFile(filename)) {
             path = dirName(filename);
         } else {
             path = ".";
         }
     }
     return path + "/" + baseName(filenames.back());
 }
getEndpoint()
int souffle::getEndpoint (std::string mainName)
Definition at line 69 of file MagicSet.cpp.
Referenced by extractAdornment(), and souffle::MagicSetTransformer::transform().
{
     int endpt = mainName.size() - 1;
     while (endpt >= 0 && mainName[endpt] != '_') {
         endpt--;
     }
     if (endpt == -1) {
         endpt = mainName.size();
     }
     return endpt;
 }
getFunctorDeclaration()
const AstFunctorDeclaration * souffle::getFunctorDeclaration (const AstProgram & program, const std::string & name)
Returns the functor declaration with the given name in the program.
Parameters
program the program
name the name of the functor declaration to search for
Returns
the functor declaration if it exists; nullptr otherwise
Definition at line 64 of file AstUtils.cpp.
References souffle::AstProgram::getFunctorDeclarations(), and getIf().
Referenced by souffle::ParserDriver::addFunctorDeclaration(), souffle::AstProgram::addFunctorDeclaration(), getBodyLiterals(), and souffle::AstUserDefinedFunctorsTransformer::transform().
{
     return getIf(program.getFunctorDeclarations(),
             [&](const AstFunctorDeclaration* f) { return f->getName() == name; });
 }
getGreatestCommonSubtypes() [1/4]
TypeSet souffle::getGreatestCommonSubtypes (const Type & a, const Type & b)
Computes the greatest common sub types of the two given types.
Definition at line 540 of file TypeSystem.cpp.
References b, souffle::UnionType::getElementTypes(), souffle::Type::getTypeEnvironment(), souffle::TypeSet::insert(), isSubtypeOf(), and souffle::TypeEnvironment::isType().
Referenced by getGreatestCommonSubtypes(), and getLeastCommonSupertypes().
{
     // make sure they are in the same type environment
     assert(a.getTypeEnvironment().isType(a) && a.getTypeEnvironment().isType(b));
     // if they are equal it is easy
     if (a == b) {
         return TypeSet(a);
     }
     // equally simple - check whether one is a sub-type of the other
     if (isSubtypeOf(a, b)) {
         return TypeSet(a);
     }
     if (isSubtypeOf(b, a)) {
         return TypeSet(b);
     }
     // last option: if both are unions with common sub-types
     TypeSet res;
     if (isUnion(a) && isUnion(b)) {
         // collect common sub-types of union types
         struct collector : public TypeVisitor<void> {
             const Type& b;
             TypeSet& res;
             collector(const Type& b, TypeSet& res) : b(b), res(res) {}
             void visit(const Type& type) const override {
                 if (isSubtypeOf(type, b)) {
                     res.insert(type);
                 } else {
                     TypeVisitor<void>::visit(type);
                 }
             }
             void visitUnionType(const UnionType& type) const override {
                 for (const auto& cur : type.getElementTypes()) {
                     visit(*cur);
                 }
             }
         };
         // collect all common sub-types
         collector(b, res).visit(a);
     }
     // otherwise there is no common super type
     return res;
 }
getGreatestCommonSubtypes() [2/4]
TypeSet souffle::getGreatestCommonSubtypes (const TypeSet & set)
Computes the greatest common sub types of all the types in the given set.
Definition at line 588 of file TypeSystem.cpp.
References souffle::TypeSet::begin(), getGreatestCommonSubtypes(), and souffle::TypeSet::insert().
{
     // handle the empty set
     if (set.empty()) {
         return set;
     }
     // handle the all set => empty set (since no common sub-type)
     if (set.isAll()) {
         return TypeSet();
     }
     TypeSet res;
     auto it = set.begin();
     res.insert(*it);
     ++it;
     // refine sub-set step by step
     for (; it != set.end(); ++it) {
         TypeSet tmp;
         for (const Type& cur : res) {
             tmp.insert(getGreatestCommonSubtypes(cur, *it));
         }
         res = tmp;
     }
     // done
     return res;
 }
getGreatestCommonSubtypes() [3/4]
TypeSet souffle::getGreatestCommonSubtypes (const TypeSet & a, const TypeSet & b)
The set of pair-wise greatest common sub types of the types in the two given sets.
Definition at line 617 of file TypeSystem.cpp.
References b, souffle::TypeSet::empty(), getGreatestCommonSubtypes(), souffle::TypeSet::insert(), and souffle::TypeSet::isAll().
{
     // special cases
     if (a.empty()) {
         return a;
     }
     if (b.empty()) {
         return b;
     }
     if (a.isAll()) {
         return b;
     }
     if (b.isAll()) {
         return a;
     }
     // compute pairwise greatest common sub types
     TypeSet res;
     for (const Type& x : a) {
         for (const Type& y : b) {
             res.insert(getGreatestCommonSubtypes(x, y));
         }
     }
     return res;
 }
getGreatestCommonSubtypes() [4/4]
template<typename... Types> TypeSet souffle::getGreatestCommonSubtypes (const Types &... types)
Computes the greatest common sub types of the given types.
Definition at line 643 of file TypeSystem.h.
References getGreatestCommonSubtypes().
{
     return getGreatestCommonSubtypes(TypeSet(types...));
 }
getGroundedTerms()
std::map< const AstArgument *, bool > souffle::getGroundedTerms (const AstClause & clause)
Analyse the given clause and computes for each contained argument whether it is a grounded value or not.
Parameters
clause the clause to be analyzed
Returns
a map mapping each contained argument to a boolean indicating whether the argument represents a grounded value or not
Definition at line 148 of file AstGroundAnalysis.cpp.
References souffle::AstAtom::getArguments(), souffle::AstTerm::getArguments(), souffle::AstNegation::getAtom(), souffle::AstClause::getHead(), souffle::AstBinaryConstraint::getLHS(), souffle::AstBinaryConstraint::getOperator(), souffle::AstBinaryConstraint::getRHS(), souffle::AstTypeCast::getValue(), isEqConstraint(), lhs, and rhs.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::ResolveAnonymousRecordsAliases::findVariablesRecordMapping(), souffle::AstSemanticChecker::isDependent(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), and usesInvalidWitness().
{
     struct Analysis : public AstConstraintAnalysis<BoolDisjunctVar> {
         std::set<const AstAtom*> ignore;
         // atoms are producing grounded variables
         void visitAtom(const AstAtom& cur) override {
             // some atoms need to be skipped (head or negation)
             if (ignore.find(&cur) != ignore.end()) {
                 return;
             }
             // all arguments are grounded
             for (const auto& arg : cur.getArguments()) {
                 addConstraint(isTrue(getVar(arg)));
             }
         }
         // negations need to be skipped
         void visitNegation(const AstNegation& cur) override {
             // add nested atom to black-list
             ignore.insert(cur.getAtom());
         }
         // also skip head
         void visitClause(const AstClause& clause) override {
             // ignore head
             ignore.insert(clause.getHead());
         }
         // binary equality relations propagates groundness
         void visitBinaryConstraint(const AstBinaryConstraint& cur) override {
             // only target equality
             if (!isEqConstraint(cur.getOperator())) {
                 return;
             }
             // if equal, link right and left side
             auto lhs = getVar(cur.getLHS());
             auto rhs = getVar(cur.getRHS());
             addConstraint(imply(lhs, rhs));
             addConstraint(imply(rhs, lhs));
         }
         // record init nodes
         void visitRecordInit(const AstRecordInit& init) override {
             auto cur = getVar(init);
             std::vector<BoolDisjunctVar> vars;
             // if record is grounded, so are all its arguments
             for (const auto& arg : init.getArguments()) {
                 auto arg_var = getVar(arg);
                 addConstraint(imply(cur, arg_var));
                 vars.push_back(arg_var);
             }
             // if all arguments are grounded, so is the record
             addConstraint(imply(vars, cur));
         }
         // constants are also sources of grounded values
         void visitConstant(const AstConstant& c) override {
             addConstraint(isTrue(getVar(c)));
         }
         // aggregators are grounding values
         void visitAggregator(const AstAggregator& c) override {
             addConstraint(isTrue(getVar(c)));
         }
         // functors with grounded values are grounded values
         void visitFunctor(const AstFunctor& cur) override {
             auto fun = getVar(cur);
             std::vector<BoolDisjunctVar> varArgs;
             for (const auto& arg : cur.getArguments()) {
                 varArgs.push_back(getVar(arg));
             }
             addConstraint(imply(varArgs, fun));
         }
         // casts propogate groundedness in and out
         void visitTypeCast(const AstTypeCast& cast) override {
             addConstraint(imply(getVar(cast.getValue()), getVar(cast)));
         }
     };
     // run analysis on given clause
     return Analysis().analyse(clause);
 }
getHeadRelation()
const AstRelation * souffle::getHeadRelation (const AstClause * clause, const AstProgram * program)
Returns the relation referenced by the head of the given clause.
Parameters
clause the clause
program the program containing the relations
Returns
relation referenced by the clause head
Definition at line 79 of file AstUtils.cpp.
References getAtomRelation(), and souffle::AstClause::getHead().
Referenced by souffle::RecursiveClauses::computeIsRecursive(), and getBodyLiterals().
{
     return getAtomRelation(clause->getHead(), program);
 }
getIf()
template<typename C > C::value_type souffle::getIf (const C & container, std::function< bool(const typename C::value_type)> pred)
Returns the first element in a container that satisfies a given predicate, nullptr otherwise.
Definition at line 318 of file Util.h.
Referenced by getFunctorDeclaration(), getRelation(), and getType().
{
     auto res = std::find_if(container.begin(), container.end(),
             [&](const typename C::value_type item) { return pred(item); });
     return res == container.end() ? nullptr : *res;
 }
getInlinedArgument()
NullableVector<AstArgument*> souffle::getInlinedArgument (AstProgram & program, const AstArgument * arg)
Returns a vector of arguments that should replace the given argument after one step of inlining.
Note: This function is currently generalised to perform any required inlining within aggregators as well, making it simple to extend to this later on if desired (and the semantic check is removed).
Definition at line 529 of file InlineRelationsTransformer.cpp.
References ADD, clone(), combineAggregators(), COUNT, FADD, FMAX, FMIN, FSUM, getInlinedLiteral(), souffle::NullableVector< T >::getVector(), i, souffle::NullableVector< T >::isValid(), j, MAX, MEAN, MIN, souffle::AstAggregator::setBody(), souffle::AstNode::setSrcLoc(), SUM, UADD, UMAX, UMIN, and USUM.
Referenced by getInlinedAtom(), and getInlinedLiteral().
{
     bool changed = false;
     std::vector<AstArgument*> versions;
     // Each argument has to be handled differently - essentially, want to go down to
     // nested aggregators, and inline their bodies if needed.
     if (const auto* aggr = dynamic_cast<const AstAggregator*>(arg)) {
         // First try inlining the target expression if necessary
         if (aggr->getTargetExpression() != nullptr) {
             NullableVector<AstArgument*> argumentVersions =
                     getInlinedArgument(program, aggr->getTargetExpression());
             if (argumentVersions.isValid()) {
                 // An element in the target expression can be inlined!
                 changed = true;
                 // Create a new aggregator per version of the target expression
                 for (AstArgument* newArg : argumentVersions.getVector()) {
                     auto* newAggr =
                             new AstAggregator(aggr->getOperator(), std::unique_ptr<AstArgument>(newArg));
                     std::vector<std::unique_ptr<AstLiteral>> newBody;
                     for (AstLiteral* lit : aggr->getBodyLiterals()) {
                         newBody.push_back(std::unique_ptr<AstLiteral>(lit->clone()));
                     }
                     newAggr->setBody(std::move(newBody));
                     versions.push_back(newAggr);
                 }
             }
         }
         // Try inlining body arguments if the target expression has not been changed.
         // (At this point we only handle one step of inlining at a time)
         if (!changed) {
             std::vector<AstLiteral*> bodyLiterals = aggr->getBodyLiterals();
             for (size_t i = 0; i < bodyLiterals.size(); i++) {
                 AstLiteral* currLit = bodyLiterals[i];
                 NullableVector<std::vector<AstLiteral*>> literalVersions =
                         getInlinedLiteral(program, currLit);
                 if (literalVersions.isValid()) {
                     // Literal can be inlined!
                     changed = true;
                     AggregateOp op = aggr->getOperator();
                     // Create an aggregator (with the same operation) for each possible body
                     std::vector<AstAggregator*> aggrVersions;
                     for (std::vector<AstLiteral*> inlineVersions : literalVersions.getVector()) {
                         std::unique_ptr<AstArgument> target;
                         if (aggr->getTargetExpression() != nullptr) {
                             target = std::unique_ptr<AstArgument>(aggr->getTargetExpression()->clone());
                         }
                         auto* newAggr = new AstAggregator(aggr->getOperator(), std::move(target));
                         std::vector<std::unique_ptr<AstLiteral>> newBody;
                         // Add in everything except the current literal being replaced
                         for (size_t j = 0; j < bodyLiterals.size(); j++) {
                             if (i != j) {
                                 newBody.push_back(std::unique_ptr<AstLiteral>(bodyLiterals[j]->clone()));
                             }
                         }
                         // Add in everything new that replaces that literal
                         for (AstLiteral* addedLit : inlineVersions) {
                             newBody.push_back(std::unique_ptr<AstLiteral>(addedLit));
                         }
                         newAggr->setBody(std::move(newBody));
                         aggrVersions.push_back(newAggr);
                     }
                     // Utility lambda: get functor used to tie aggregators together.
                     auto aggregateToFunctor = [](AggregateOp op) {
                         switch (op) {
                             case AggregateOp::MIN:
                                 return FunctorOp::MIN;
                             case AggregateOp::FMIN:
                                 return FunctorOp::FMIN;
                             case AggregateOp::UMIN:
                                 return FunctorOp::UMIN;
                             case AggregateOp::MAX:
                                 return FunctorOp::MAX;
                             case AggregateOp::FMAX:
                                 return FunctorOp::FMAX;
                             case AggregateOp::UMAX:
                                 return FunctorOp::UMAX;
                             case AggregateOp::SUM:
                                 return FunctorOp::ADD;
                             case AggregateOp::FSUM:
                                 return FunctorOp::FADD;
                             case AggregateOp::USUM:
                                 return FunctorOp::UADD;
                             case AggregateOp::COUNT:
                                 return FunctorOp::ADD;
                             case AggregateOp::MEAN:
                                 assert(false && "no translation");
                             default:
                                 assert(false && "Unsupported aggregate operation");
                         }
                     };
                     // Create the actual overall aggregator that ties the replacement aggregators together.
                     // example: min x : { a(x) }. <=> min ( min x : { a1(x) }, min x : { a2(x) }, ... )
                     if (op != AggregateOp::MEAN) {
                         versions.push_back(combineAggregators(aggrVersions, aggregateToFunctor(op)));
                     }
                 }
                 // Only perform one stage of inlining at a time.
                 if (changed) {
                     break;
                 }
             }
         }
     } else if (const auto* functor = dynamic_cast<const AstFunctor*>(arg)) {
         size_t i = 0;
         for (auto funArg : functor->getArguments()) {
             // TODO (azreika): use unique pointers
             // try inlining each argument from left to right
             NullableVector<AstArgument*> argumentVersions = getInlinedArgument(program, funArg);
             if (argumentVersions.isValid()) {
                 changed = true;
                 for (AstArgument* newArgVersion : argumentVersions.getVector()) {
                     // same functor but with new argument version
                     std::vector<std::unique_ptr<AstArgument>> argsCopy;
                     size_t j = 0;
                     for (auto& functorArg : functor->getArguments()) {
                         if (j == i) {
                             argsCopy.emplace_back(newArgVersion);
                         } else {
                             argsCopy.emplace_back(functorArg->clone());
                         }
                         ++j;
                     }
                     if (const auto* intrFunc = dynamic_cast<const AstIntrinsicFunctor*>(arg)) {
                         auto* newFunctor =
                                 new AstIntrinsicFunctor(intrFunc->getFunction(), std::move(argsCopy));
                         newFunctor->setSrcLoc(functor->getSrcLoc());
                         versions.push_back(newFunctor);
                     } else if (const auto* userFunc = dynamic_cast<const AstUserDefinedFunctor*>(arg)) {
                         auto* newFunctor =
                                 new AstUserDefinedFunctor(userFunc->getName(), std::move(argsCopy));
                         newFunctor->setSrcLoc(userFunc->getSrcLoc());
                         versions.push_back(newFunctor);
                     }
                 }
                 // only one step at a time
                 break;
             }
             ++i;
         }
     } else if (const auto* cast = dynamic_cast<const AstTypeCast*>(arg)) {
         NullableVector<AstArgument*> argumentVersions = getInlinedArgument(program, cast->getValue());
         if (argumentVersions.isValid()) {
             changed = true;
             for (AstArgument* newArg : argumentVersions.getVector()) {
                 AstArgument* newTypeCast =
                         new AstTypeCast(std::unique_ptr<AstArgument>(newArg), cast->getType());
                 versions.push_back(newTypeCast);
             }
         }
     } else if (const auto* record = dynamic_cast<const AstRecordInit*>(arg)) {
         std::vector<AstArgument*> recordArguments = record->getArguments();
         for (size_t i = 0; i < recordArguments.size(); i++) {
             AstArgument* currentRecArg = recordArguments[i];
             NullableVector<AstArgument*> argumentVersions = getInlinedArgument(program, currentRecArg);
             if (argumentVersions.isValid()) {
                 changed = true;
                 for (AstArgument* newArgumentVersion : argumentVersions.getVector()) {
                     auto* newRecordArg = new AstRecordInit();
                     for (size_t j = 0; j < recordArguments.size(); j++) {
                         if (i == j) {
                             newRecordArg->addArgument(std::unique_ptr<AstArgument>(newArgumentVersion));
                         } else {
                             newRecordArg->addArgument(
                                     std::unique_ptr<AstArgument>(recordArguments[j]->clone()));
                         }
                     }
                     versions.push_back(newRecordArg);
                 }
             }
             // Only perform one stage of inlining at a time.
             if (changed) {
                 break;
             }
         }
     }
     if (changed) {
         // Return a valid vector - replacements need to be made!
         return NullableVector<AstArgument*>(versions);
     } else {
         // Return an invalid vector - no inlining has occurred
         return NullableVector<AstArgument*>();
     }
 }
getInlinedAtom()
NullableVector<AstAtom*> souffle::getInlinedAtom (AstProgram & program, AstAtom & atom)
Returns a vector of atoms that should replace the given atom after one step of inlining.
Assumes the relation the atom belongs to is not inlined itself.
Definition at line 731 of file InlineRelationsTransformer.cpp.
References clone(), souffle::AstAtom::getArguments(), getInlinedArgument(), souffle::AstAtom::getQualifiedName(), souffle::AstNode::getSrcLoc(), souffle::NullableVector< T >::getVector(), i, souffle::NullableVector< T >::isValid(), and j.
Referenced by getInlinedClause(), and getInlinedLiteral().
{
     bool changed = false;
     std::vector<AstAtom*> versions;
     // Try to inline each of the atom's arguments
     std::vector<AstArgument*> arguments = atom.getArguments();
     for (size_t i = 0; i < arguments.size(); i++) {
         AstArgument* arg = arguments[i];
         NullableVector<AstArgument*> argumentVersions = getInlinedArgument(program, arg);
         if (argumentVersions.isValid()) {
             // Argument has replacements
             changed = true;
             // Create a new atom per new version of the argument
             for (AstArgument* newArgument : argumentVersions.getVector()) {
                 auto args = atom.getArguments();
                 std::vector<std::unique_ptr<AstArgument>> newArgs;
                 for (size_t j = 0; j < args.size(); j++) {
                     if (j == i) {
                         newArgs.emplace_back(newArgument);
                     } else {
                         newArgs.emplace_back(args[j]->clone());
                     }
                 }
                 auto* newAtom = new AstAtom(atom.getQualifiedName(), std::move(newArgs), atom.getSrcLoc());
                 versions.push_back(newAtom);
             }
         }
         // Only perform one stage of inlining at a time.
         if (changed) {
             break;
         }
     }
     if (changed) {
         // Return a valid vector - replacements need to be made!
         return NullableVector<AstAtom*>(versions);
     } else {
         // Return an invalid vector - no replacements need to be made
         return NullableVector<AstAtom*>();
     }
 }
getInlinedClause()
std::vector<AstClause*> souffle::getInlinedClause (AstProgram & program, const AstClause & clause)
Returns a list of clauses that should replace the given clause after one step of inlining.
If no inlining can occur, the list will only contain a clone of the original clause.
Definition at line 915 of file InlineRelationsTransformer.cpp.
References souffle::AstClause::addToBody(), souffle::AstClause::clone(), cloneHead(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), getInlinedAtom(), getInlinedLiteral(), souffle::AstNode::getSrcLoc(), souffle::NullableVector< T >::getVector(), i, and souffle::NullableVector< T >::isValid().
Referenced by souffle::InlineRelationsTransformer::transform().
{
     bool changed = false;
     std::vector<AstClause*> versions;
     // Try to inline things contained in the arguments of the head first.
     // E.g. `a(x, max y : { b(y) }) :- c(x).`, where b should be inlined.
     AstAtom* head = clause.getHead();
     NullableVector<AstAtom*> headVersions = getInlinedAtom(program, *head);
     if (headVersions.isValid()) {
         // The head atom can be inlined!
         changed = true;
         // Produce the new clauses with the replacement head atoms
         for (AstAtom* newHead : headVersions.getVector()) {
             auto* newClause = new AstClause();
             newClause->setSrcLoc(clause.getSrcLoc());
             newClause->setHead(std::unique_ptr<AstAtom>(newHead));
             // The body will remain unchanged
             for (AstLiteral* lit : clause.getBodyLiterals()) {
                 newClause->addToBody(std::unique_ptr<AstLiteral>(lit->clone()));
             }
             versions.push_back(newClause);
         }
     }
     // Only perform one stage of inlining at a time.
     // If the head atoms did not need inlining, try inlining atoms nested in the body.
     if (!changed) {
         std::vector<AstLiteral*> bodyLiterals = clause.getBodyLiterals();
         for (size_t i = 0; i < bodyLiterals.size(); i++) {
             AstLiteral* currLit = bodyLiterals[i];
             // Three possible cases when trying to inline a literal:
             //  1) The literal itself may be directly inlined. In this case, the atom can be replaced
             //    with multiple different bodies, as the inlined atom may have several rules.
             //  2) Otherwise, the literal itself may not need to be inlined, but a subnode (e.g. an argument)
             //    may need to be inlined. In this case, an altered literal must replace the original.
             //    Again, several possible versions may exist, as the inlined relation may have several rules.
             //  3) The literal does not depend on any inlined relations, and so does not need to be changed.
             NullableVector<std::vector<AstLiteral*>> litVersions = getInlinedLiteral(program, currLit);
             if (litVersions.isValid()) {
                 // Case 1 and 2: Inlining has occurred!
                 changed = true;
                 // The literal may be replaced with several different bodies.
                 // Create a new clause for each possible version.
                 std::vector<std::vector<AstLiteral*>> bodyVersions = litVersions.getVector();
                 // Create the base clause with the current literal removed
                 auto baseClause = std::unique_ptr<AstClause>(cloneHead(&clause));
                 for (AstLiteral* oldLit : bodyLiterals) {
                     if (currLit != oldLit) {
                         baseClause->addToBody(std::unique_ptr<AstLiteral>(oldLit->clone()));
                     }
                 }
                 for (std::vector<AstLiteral*> body : bodyVersions) {
                     AstClause* replacementClause = baseClause->clone();
                     // Add in the current set of literals replacing the inlined literal
                     // In Case 2, each body contains exactly one literal
                     for (AstLiteral* newLit : body) {
                         replacementClause->addToBody(std::unique_ptr<AstLiteral>(newLit));
                     }
                     versions.push_back(replacementClause);
                 }
             }
             // Only replace at most one literal per iteration
             if (changed) {
                 break;
             }
         }
     }
     if (!changed) {
         // Case 3: No inlining changes, so a clone of the original should be returned
         std::vector<AstClause*> ret;
         ret.push_back(clause.clone());
         return ret;
     } else {
         // Inlining changes, so return the replacement clauses.
         return versions;
     }
 }
getInlinedLiteral()
NullableVector< std::vector< AstLiteral * > > souffle::getInlinedLiteral (AstProgram & program, AstLiteral * lit)
Tries to perform a single step of inlining on the given literal.
Returns a pair of nullable vectors (v, w) such that:
v is valid if and only if the literal can be directly inlined, whereby it contains the bodies that replace it
if v is not valid, then w is valid if and only if the literal cannot be inlined directly, but contains a subargument that can be. In this case, it will contain the versions that will replace it.
If both are invalid, then no more inlining can occur on this literal and we are done.
Definition at line 787 of file InlineRelationsTransformer.cpp.
References formNegatedLiterals(), getClauses(), getInlinedArgument(), getInlinedAtom(), getRelation(), souffle::NullableVector< T >::getVector(), souffle::AstRelation::hasQualifier(), INLINE, inlineBodyLiterals(), and souffle::NullableVector< T >::isValid().
Referenced by getInlinedArgument(), getInlinedClause(), and souffle::NullableVector< T >::getVector().
{
     bool inlined = false;
     bool changed = false;
     std::vector<std::vector<AstLiteral*>> addedBodyLiterals;
     std::vector<AstLiteral*> versions;
     if (auto* atom = dynamic_cast<AstAtom*>(lit)) {
         // Check if this atom is meant to be inlined
         AstRelation* rel = getRelation(program, atom->getQualifiedName());
         if (rel->hasQualifier(RelationQualifier::INLINE)) {
             // We found an atom in the clause that needs to be inlined!
             // The clause needs to be replaced
             inlined = true;
             // N new clauses should be formed, where N is the number of clauses
             // associated with the inlined relation
             for (AstClause* inClause : getClauses(program, *rel)) {
                 // Form the replacement clause
                 std::pair<NullableVector<AstLiteral*>, std::vector<AstBinaryConstraint*>> inlineResult =
                         inlineBodyLiterals(atom, inClause);
                 NullableVector<AstLiteral*> replacementBodyLiterals = inlineResult.first;
                 std::vector<AstBinaryConstraint*> currConstraints = inlineResult.second;
                 if (!replacementBodyLiterals.isValid()) {
                     // Failed to unify the atoms! We can skip this one...
                     continue;
                 }
                 // Unification successful - the returned vector of literals represents one possible body
                 // replacement We can add in the unification constraints as part of these literals.
                 std::vector<AstLiteral*> bodyResult = replacementBodyLiterals.getVector();
                 for (AstBinaryConstraint* cons : currConstraints) {
                     bodyResult.push_back(cons);
                 }
                 addedBodyLiterals.push_back(bodyResult);
             }
         } else {
             // Not meant to be inlined, but a subargument may be
             NullableVector<AstAtom*> atomVersions = getInlinedAtom(program, *atom);
             if (atomVersions.isValid()) {
                 // Subnode needs to be inlined, so we have a vector of replacement atoms
                 changed = true;
                 for (AstAtom* newAtom : atomVersions.getVector()) {
                     versions.push_back(newAtom);
                 }
             }
         }
     } else if (auto neg = dynamic_cast<AstNegation*>(lit)) {
         // For negations, check the corresponding atom
         AstAtom* atom = neg->getAtom();
         NullableVector<std::vector<AstLiteral*>> atomVersions = getInlinedLiteral(program, atom);
         if (atomVersions.isValid()) {
             // The atom can be inlined
             inlined = true;
             if (atomVersions.getVector().empty()) {
                 // No clauses associated with the atom, so just becomes a true literal
                 addedBodyLiterals.push_back({new AstBooleanConstraint(true)});
             } else {
                 // Suppose an atom a(x) is inlined and has the following rules:
                 //  - a(x) :- a11(x), a12(x).
                 //  - a(x) :- a21(x), a22(x).
                 // Then, a(x) <- (a11(x) ^ a12(x)) v (a21(x) ^ a22(x))
                 //  => !a(x) <- (!a11(x) v !a12(x)) ^ (!a21(x) v !a22(x))
                 //  => !a(x) <- (!a11(x) ^ !a21(x)) v (!a11(x) ^ !a22(x)) v ...
                 // Essentially, produce every combination (m_1 ^ m_2 ^ ...) where m_i is a
                 // negated literal in the ith rule of a.
                 addedBodyLiterals = formNegatedLiterals(program, atom);
             }
         }
         if (atomVersions.isValid()) {
             for (const auto& curVec : atomVersions.getVector()) {
                 for (auto* cur : curVec) {
                     delete cur;
                 }
             }
         }
     } else if (auto* constraint = dynamic_cast<AstBinaryConstraint*>(lit)) {
         NullableVector<AstArgument*> lhsVersions = getInlinedArgument(program, constraint->getLHS());
         if (lhsVersions.isValid()) {
             changed = true;
             for (AstArgument* newLhs : lhsVersions.getVector()) {
                 AstLiteral* newLit = new AstBinaryConstraint(constraint->getOperator(),
                         std::unique_ptr<AstArgument>(newLhs),
                         std::unique_ptr<AstArgument>(constraint->getRHS()->clone()));
                 versions.push_back(newLit);
             }
         } else {
             NullableVector<AstArgument*> rhsVersions = getInlinedArgument(program, constraint->getRHS());
             if (rhsVersions.isValid()) {
                 changed = true;
                 for (AstArgument* newRhs : rhsVersions.getVector()) {
                     AstLiteral* newLit = new AstBinaryConstraint(constraint->getOperator(),
                             std::unique_ptr<AstArgument>(constraint->getLHS()->clone()),
                             std::unique_ptr<AstArgument>(newRhs));
                     versions.push_back(newLit);
                 }
             }
         }
     }
     if (changed) {
         // Not inlined directly but found replacement literals
         // Rewrite these as single-literal bodies
         for (AstLiteral* version : versions) {
             std::vector<AstLiteral*> newBody;
             newBody.push_back(version);
             addedBodyLiterals.push_back(newBody);
         }
         inlined = true;
     }
     if (inlined) {
         return NullableVector<std::vector<AstLiteral*>>(addedBodyLiterals);
     } else {
         return NullableVector<std::vector<AstLiteral*>>();
     }
 }
getInstance()
souffle::SouffleProgram* souffle::getInstance (const char * p) inline
Definition at line 60 of file CompiledSouffle.h.
References souffle::ProgramFactory::newInstance().
{
     return souffle::ProgramFactory::newInstance(p);
 }
getLeastCommonSupertypes() [1/4]
TypeSet souffle::getLeastCommonSupertypes (const Type & a, const Type & b)
Computes the least common super types of the two given types.
Definition at line 446 of file TypeSystem.cpp.
References any_of(), souffle::TypeEnvironment::getAllTypes(), souffle::Type::getTypeEnvironment(), souffle::TypeSet::insert(), isSubtypeOf(), and souffle::TypeEnvironment::isType().
Referenced by getLeastCommonSupertypes(), and isOrderableType().
{
     // make sure they are in the same type environment
     assert(a.getTypeEnvironment().isType(a) && a.getTypeEnvironment().isType(b));
     // if they are equal it is easy
     if (a == b) {
         return TypeSet(a);
     }
     // equally simple - check whether one is a sub-type of the other
     if (isSubtypeOf(a, b)) {
         return TypeSet(b);
     }
     if (isSubtypeOf(b, a)) {
         return TypeSet(a);
     }
     // harder: no obvious relation => hard way
     TypeSet superTypes;
     TypeSet all = a.getTypeEnvironment().getAllTypes();
     for (const Type& cur : all) {
         if (isSubtypeOf(a, cur) && isSubtypeOf(b, cur)) {
             superTypes.insert(cur);
         }
     }
     // filter out non-least super types
     TypeSet res;
     for (const Type& cur : superTypes) {
         bool least = !any_of(superTypes, [&](const Type& t) { return t != cur && isSubtypeOf(t, cur); });
         if (least) {
             res.insert(cur);
         }
     }
     return res;
 }
getLeastCommonSupertypes() [2/4]
TypeSet souffle::getLeastCommonSupertypes (const TypeSet & set)
Computes the least common super types of all the types in the given set.
Definition at line 484 of file TypeSystem.cpp.
References souffle::TypeSet::begin(), getLeastCommonSupertypes(), and souffle::TypeSet::insert().
{
     // handle the empty set
     if (set.empty()) {
         return set;
     }
     // handle the all set => empty set (since no common super-type)
     if (set.isAll()) {
         return TypeSet();
     }
     TypeSet res;
     auto it = set.begin();
     res.insert(*it);
     ++it;
     // refine sub-set step by step
     for (; it != set.end(); ++it) {
         TypeSet tmp;
         for (const Type& cur : res) {
             tmp.insert(getLeastCommonSupertypes(cur, *it));
         }
         res = tmp;
     }
     // done
     return res;
 }
getLeastCommonSupertypes() [3/4]
TypeSet souffle::getLeastCommonSupertypes (const TypeSet & a, const TypeSet & b)
The set of pair-wise least common super types of the types in the two given sets.
Definition at line 514 of file TypeSystem.cpp.
References b, souffle::TypeSet::empty(), getLeastCommonSupertypes(), souffle::TypeSet::insert(), and souffle::TypeSet::isAll().
{
     // special cases
     if (a.empty()) {
         return a;
     }
     if (b.empty()) {
         return b;
     }
     if (a.isAll()) {
         return b;
     }
     if (b.isAll()) {
         return a;
     }
     // compute pairwise least common super types
     TypeSet res;
     for (const Type& x : a) {
         for (const Type& y : b) {
             res.insert(getLeastCommonSupertypes(x, y));
         }
     }
     return res;
 }
getLeastCommonSupertypes() [4/4]
template<typename... Types> TypeSet souffle::getLeastCommonSupertypes (const Types &... types)
Computes the least common super types of the given types.
Definition at line 618 of file TypeSystem.h.
References getGreatestCommonSubtypes(), and getLeastCommonSupertypes().
{
     return getLeastCommonSupertypes(TypeSet(types...));
 }
getNextAtomMaxBoundSIPS()
int souffle::getNextAtomMaxBoundSIPS (std::vector< AstAtom *> & atoms, const std::set< std::string > & boundArgs, const std::set< AstQualifiedName > & edb, BindingStore & compositeBindings)
Definition at line 511 of file MagicSet.cpp.
References contains(), souffle::AstAtom::getArguments(), souffle::AstAtom::getQualifiedName(), i, and isBoundArgument().
Referenced by getNextAtomSIPS().
{
     int maxBound = -1;
     int maxIndex = 0;
     bool maxIsEDB = false;  // checks if current max index is an EDB predicate
     for (size_t i = 0; i < atoms.size(); i++) {
         AstAtom* currAtom = atoms[i];
         if (currAtom == nullptr) {
             // already done - move on
             continue;
         }
         int numBound = 0;
         for (AstArgument* arg : currAtom->getArguments()) {
             if (isBoundArgument(arg, boundArgs, compositeBindings)) {
                 numBound++;
             }
         }
         if (numBound > maxBound) {
             maxBound = numBound;
             maxIndex = i;
             maxIsEDB = contains(edb, currAtom->getQualifiedName());
         } else if (!maxIsEDB && numBound == maxBound && contains(edb, currAtom->getQualifiedName())) {
             // prioritise EDB predicates
             maxIsEDB = true;
             maxIndex = i;
         }
     }
     return maxIndex;
 }
getNextAtomMaxRatioSIPS()
int souffle::getNextAtomMaxRatioSIPS (std::vector< AstAtom *> & atoms, const std::set< std::string > & boundArgs, const std::set< AstQualifiedName > & , BindingStore & compositeBindings)
Definition at line 546 of file MagicSet.cpp.
References souffle::AstAtom::getArguments(), souffle::AstAtom::getArity(), i, and isBoundArgument().
{
     double maxRatio = -1;
     int maxIndex = 0;
     for (size_t i = 0; i < atoms.size(); i++) {
         AstAtom* currAtom = atoms[i];
         if (currAtom == nullptr) {
             // already done - move on
             continue;
         }
         int numArguments = currAtom->getArity();
         if (numArguments == 0) {
             return i;  // no arguments!
         }
         int numBound = 0;
         for (AstArgument* arg : currAtom->getArguments()) {
             if (isBoundArgument(arg, boundArgs, compositeBindings)) {
                 numBound++;
             }
         }
         double currRatio = numBound * 1.0 / numArguments;
         if (currRatio == 1) {
             return i;  // all bound, not going to get better than this
         }
         if (currRatio > maxRatio) {
             maxRatio = currRatio;
             maxIndex = i;
         }
     }
     return maxIndex;
 }
getNextAtomNaiveSIPS()
int souffle::getNextAtomNaiveSIPS (std::vector< AstAtom *> atoms, const std::set< std::string > & boundArgs, const std::set< AstQualifiedName > & edb, BindingStore & compositeBindings)
Definition at line 470 of file MagicSet.cpp.
References contains(), souffle::AstAtom::getQualifiedName(), hasBoundArgument(), and i.
{
     // find the first available atom with at least one bound argument
     int firstedb = -1;
     int firstidb = -1;
     for (size_t i = 0; i < atoms.size(); i++) {
         AstAtom* currAtom = atoms[i];
         if (currAtom == nullptr) {
             // already done - move on
             continue;
         }
         AstQualifiedName atomName = currAtom->getQualifiedName();
         // check if this is the first edb or idb atom met
         if (contains(edb, atomName)) {
             if (firstedb < 0) {
                 firstedb = i;
             }
         } else if (firstidb < 0) {
             firstidb = i;
         }
         // if it has at least one bound argument, then adorn this atom next
         if (hasBoundArgument(currAtom, boundArgs, compositeBindings)) {
             return i;
         }
     }
     // all unadorned body atoms only have free arguments
     // choose the first edb remaining if available
     if (firstedb >= 0) {
         return firstedb;
     } else {
         return firstidb;
     }
 }
getNextAtomSIPS()
int souffle::getNextAtomSIPS (std::vector< AstAtom *> & atoms, std::set< std::string > boundArgs, std::set< AstQualifiedName > edb, BindingStore & compositeBindings)
Definition at line 587 of file MagicSet.cpp.
References getNextAtomMaxBoundSIPS().
Referenced by souffle::Adornment::run().
{
     return getNextAtomMaxBoundSIPS(atoms, boundArgs, edb, compositeBindings);
 }
getNextEdbName()
std::string souffle::getNextEdbName (AstProgram * program)
Definition at line 196 of file MagicSet.cpp.
References getRelation().
Referenced by separateDBs().
{
     static int edbNum = 0;
     std::stringstream newEdbName;
     // find the next unused relation name of the form "newedbX", X an integer
     do {
         newEdbName.str("");  // check
         edbNum++;
         newEdbName << "newedb" << edbNum;
     } while (getRelation(*program, newEdbName.str()) != nullptr);
     return newEdbName.str();
 }
getOr()
template<typename C > C::mapped_type const& souffle::getOr (const C & container, typename C::key_type key, const typename C::mapped_type & defaultValue)
Get value for a given key; if not found, return default value.
Definition at line 328 of file Util.h.
Referenced by souffle::ReadFileCSV::getFileName(), souffle::ReadStreamCSV::getInputColumnMap(), souffle::ReadFileCSV::ReadFileCSV(), souffle::WriteCoutCSV::WriteCoutCSV(), souffle::WriteFileCSV::WriteFileCSV(), and souffle::WriteFileCSV::writeNextTuple().
{
     auto it = container.find(key);
     if (it != container.end()) {
         return it->second;
     } else {
         return defaultValue;
     }
 }
getOutputLock()
Lock& souffle::getOutputLock () inline
Obtains a reference to the lock synchronizing output operations.
Definition at line 568 of file ParallelUtils.h.
Referenced by souffle::WriteCoutPrintSize::WriteCoutPrintSize().
{
     static Lock outputLock;
     return outputLock;
 }
getRecords()
std::vector< const AstRecordInit * > souffle::getRecords (const AstNode & root)
Obtains a list of all records referenced within the AST rooted by the given root node.
Parameters
root the root of the AST to be searched
Returns
a list of all records referenced within
Definition at line 35 of file AstUtils.cpp.
References visitDepthFirst().
Referenced by souffle::AstSemanticChecker::checkProgram().
{
     // simply collect the list of all records by visiting all records
     std::vector<const AstRecordInit*> recs;
     visitDepthFirst(root, [&](const AstRecordInit& rec) { recs.push_back(&rec); });
     return recs;
 }
getRelation()
AstRelation * souffle::getRelation (const AstProgram & program, const AstQualifiedName & name)
Returns the relation with the given name in the program.
Parameters
program the program
name the name of the relation to search for
Returns
the relation if it exists; nullptr otherwise
Definition at line 56 of file AstUtils.cpp.
References getIf(), and souffle::AstProgram::getRelations().
Referenced by addForwardDependencies(), souffle::ParserDriver::addRelation(), souffle::AstProgram::addRelation(), souffle::AstSemanticChecker::checkAtom(), souffle::AstSemanticChecker::checkFact(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkIO(), souffle::AstSemanticChecker::checkProgram(), containsInlinedAtom(), formNegatedLiterals(), souffle::AuxiliaryArity::getArity(), getAtomRelation(), getBodyLiterals(), getClauseNum(), souffle::AstTranslator::getEvaluationArity(), getInlinedLiteral(), getNextEdbName(), souffle::SouffleProgram::getRelationName(), souffle::SouffleProgram::getRelationSize(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::RamIO::print(), souffle::RamClear::print(), souffle::RamScan::print(), souffle::RamParallelScan::print(), souffle::RamAbstractExistenceCheck::print(), souffle::RamIndexScan::print(), souffle::RamParallelIndexScan::print(), souffle::RamEmptinessCheck::print(), souffle::RamChoice::print(), souffle::RamParallelChoice::print(), souffle::RamIndexChoice::print(), souffle::RamParallelIndexChoice::print(), souffle::RamLogRelationTimer::print(), souffle::RamLogSize::print(), souffle::RamAggregate::print(), souffle::RamIndexAggregate::print(), souffle::RamProject::print(), souffle::RamIndexOperation::printIndex(), souffle::RamIndexChoice::RamIndexChoice(), souffle::RamIndexOperation::RamIndexOperation(), reduceSingletonRelations(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::IOType::run(), souffle::Adornment::run(), souffle::ReduceExistentialsTransformer::transform(), and souffle::MagicSetTransformer::transform().
{
     return getIf(program.getRelations(), [&](const AstRelation* r) { return r->getQualifiedName() == name; });
 }
getRelationQualifierFromTag()
RelationQualifier souffle::getRelationQualifierFromTag (const RelationTag & tag) inline
Get the corresponding RelationQualifier for a valid RelationTag.
Definition at line 87 of file RelationTag.h.
References INLINE, INPUT, OUTPUT, OVERRIDABLE, PRINTSIZE, and SUPPRESSED.
{
     switch (tag) {
         case RelationTag::INPUT:
             return RelationQualifier::INPUT;
         case RelationTag::OUTPUT:
             return RelationQualifier::OUTPUT;
         case RelationTag::PRINTSIZE:
             return RelationQualifier::PRINTSIZE;
         case RelationTag::OVERRIDABLE:
             return RelationQualifier::OVERRIDABLE;
         case RelationTag::INLINE:
             return RelationQualifier::INLINE;
         case RelationTag::SUPPRESSED:
             return RelationQualifier::SUPPRESSED;
         default:
             assert(false && "invalid relation tag");
     }
 }
getRelationRepresentationFromTag()
RelationRepresentation souffle::getRelationRepresentationFromTag (const RelationTag & tag) inline
Get the corresponding RelationRepresentation for a valid RelationTag.
Definition at line 109 of file RelationTag.h.
References BRIE, BTREE, and EQREL.
{
     switch (tag) {
         case RelationTag::BRIE:
             return RelationRepresentation::BRIE;
         case RelationTag::BTREE:
             return RelationRepresentation::BTREE;
         case RelationTag::EQREL:
             return RelationRepresentation::EQREL;
         default:
             assert(false && "invalid relation tag");
     }
 }
getSipsFunction()
sips_t souffle::getSipsFunction (const std::string & sipsChosen)
Returns a SIPS function based on the SIPS option provided.
The SIPS function will return the index of the appropriate atom in a clause given a goal.
E.g. the 'max-bound' SIPS function will return the atom in the clause with the maximum number of bound arguments.
Definition at line 79 of file ReorderLiteralsTransformer.cpp.
References souffle::AstAtom::getArity(), souffle::AstVariable::getName(), i, isProposition(), lhs, numBoundArguments(), rhs, and visitDepthFirst().
Referenced by souffle::ReorderLiteralsTransformer::transform().
{
     // --- Create the appropriate SIPS function ---
     // Each SIPS function has a priority metric (e.g. max-bound atoms).
     // Arguments:
     //      - a vector of atoms to choose from (nullpointers in the vector will be ignored)
     //      - the set of variables bound so far
     // Returns: the index of the atom maximising the priority metric
     sips_t getNextAtomSips;
     if (sipsChosen == "naive") {
         // Goal: choose the first atom with at least one bound argument, or with no arguments
         getNextAtomSips = [&](std::vector<AstAtom*> atoms, const std::set<std::string>& boundVariables) {
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const AstAtom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // no arguments
                     return i;
                 }
                 if (numBoundArguments(currAtom, boundVariables) >= 1) {
                     // at least one bound argument
                     return i;
                 }
             }
             // none found; choose the first non-null
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 if (atoms[i] != nullptr) {
                     return i;
                 }
             }
             // fall back to the first
             return 0U;
         };
     } else if (sipsChosen == "all-bound") {
         // Goal: prioritise atoms with all arguments bound
         getNextAtomSips = [&](std::vector<AstAtom*> atoms, const std::set<std::string>& boundVariables) {
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const AstAtom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // no arguments, so all are trivially bound
                     return i;
                 }
                 int arity = currAtom->getArity();
                 int numBound = numBoundArguments(currAtom, boundVariables);
                 if (numBound == arity) {
                     // all arguments are bound!
                     return i;
                 }
             }
             // none found; choose the first non-null
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 if (atoms[i] != nullptr) {
                     return i;
                 }
             }
             // fall back to the first
             return 0U;
         };
     } else if (sipsChosen == "max-bound") {
         // Goal: choose the atom with the maximum number of bound variables
         //       - exception: propositions should be prioritised
         getNextAtomSips = [&](std::vector<AstAtom*> atoms, const std::set<std::string>& boundVariables) {
             int currMaxBound = -1;
             unsigned int currMaxIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const AstAtom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions should be prioritised
                     return i;
                 }
                 int numBound = numBoundArguments(currAtom, boundVariables);
                 if (numBound > currMaxBound) {
                     currMaxBound = numBound;
                     currMaxIdx = i;
                 }
             }
             return currMaxIdx;
         };
     } else if (sipsChosen == "max-ratio") {
         // Goal: choose the atom with the maximum ratio of bound to unbound
         getNextAtomSips = [&](std::vector<AstAtom*> atoms, const std::set<std::string>& boundVariables) {
             auto isLargerRatio = [&](std::pair<int, int> lhs, std::pair<int, int> rhs) {
                 return (lhs.first * rhs.second > lhs.second * rhs.first);
             };
             auto currMaxRatio = std::pair<int, int>(-1, 1);  // set to -1
             unsigned int currMaxIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const AstAtom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions are as bound as possible
                     return i;
                 }
                 int numBound = numBoundArguments(currAtom, boundVariables);
                 int numArgs = currAtom->getArity();
                 auto currRatio = std::pair<int, int>(numBound, numArgs);
                 if (isLargerRatio(currRatio, currMaxRatio)) {
                     currMaxRatio = currRatio;
                     currMaxIdx = i;
                 }
             }
             return currMaxIdx;
         };
     } else if (sipsChosen == "least-free") {
         // Goal: choose the atom with the least number of unbound arguments
         getNextAtomSips = [&](std::vector<AstAtom*> atoms, const std::set<std::string>& boundVariables) {
             int currLeastFree = -1;
             unsigned int currLeastIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const AstAtom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions have 0 unbound arguments, which is minimal
                     return i;
                 }
                 int numBound = numBoundArguments(currAtom, boundVariables);
                 int numFree = currAtom->getArity() - numBound;
                 if (currLeastFree == -1 || numFree < currLeastFree) {
                     currLeastFree = numFree;
                     currLeastIdx = i;
                 }
             }
             return currLeastIdx;
         };
     } else if (sipsChosen == "least-free-vars") {
         // Goal: choose the atom with the least amount of unbound variables
         getNextAtomSips = [&](std::vector<AstAtom*> atoms, const std::set<std::string>& boundVariables) {
             int currLeastFree = -1;
             unsigned int currLeastIdx = 0U;
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 const AstAtom* currAtom = atoms[i];
                 if (currAtom == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 if (isProposition(currAtom)) {
                     // propositions have 0 unbound variables, which is minimal
                     return i;
                 }
                 // use a set to hold all free variables to avoid double-counting
                 std::set<std::string> freeVars;
                 visitDepthFirst(*currAtom, [&](const AstVariable& var) {
                     if (boundVariables.find(var.getName()) == boundVariables.end()) {
                         freeVars.insert(var.getName());
                     }
                 });
                 int numFreeVars = freeVars.size();
                 if (currLeastFree == -1 || numFreeVars < currLeastFree) {
                     currLeastFree = numFreeVars;
                     currLeastIdx = i;
                 }
             }
             return currLeastIdx;
         };
     } else {
         // chosen SIPS is not implemented, so keep the same order
         // Goal: leftmost atom first
         getNextAtomSips = [&](std::vector<AstAtom*> atoms,
                                   const std::set<std::string>& /* boundVariables */) {
             for (unsigned int i = 0; i < atoms.size(); i++) {
                 if (atoms[i] == nullptr) {
                     // already processed - move on
                     continue;
                 }
                 return i;
             }
             // fall back to the first
             return 0U;
         };
     }
     return getNextAtomSips;
 }
getStarttime()
ss<< R"_("code": [)_"; bool firstCol = true; while (getline(source_file, str)) { comma(firstCol, ",\n"); ss << '"' << Tools::cleanJsonOut(str) << '"'; } ss << "],\n"; source_file.close(); } auto usages = getUsageStats(100); auto beginTime = run-> souffle::getStarttime ()
getString()
std::string souffle::getString (const AstArgument * arg)
Definition at line 83 of file MagicSet.cpp.
Referenced by bindArguments(), isBindingConstraint(), souffle::Adornment::run(), and souffle::MagicSetTransformer::transform().
{
     std::stringstream argStream;
     argStream << *arg;
     return argStream.str();
 }
getSymbolForFunctorOp()
std::string souffle::getSymbolForFunctorOp (const FunctorOp op) inline
Return a string representation of a functor.
Unary Functor Operators
Binary Functor Operators
Ternary Functor Operators
Definition at line 179 of file FunctorOps.h.
References ADD, BAND, BNOT, BOR, BSHIFT_L, BSHIFT_R, BSHIFT_R_UNSIGNED, BXOR, CAT, DIV, EXP, FADD, FDIV, FEXP, FMAX, FMIN, FMUL, FNEG, FSUB, FTOI, FTOU, ITOF, ITOU, LAND, LNOT, LOR, MAX, MIN, MOD, MUL, NEG, ORD, SMAX, SMIN, STRLEN, SUB, SUBSTR, TONUMBER, TOSTRING, UADD, UBAND, UBNOT, UBOR, UBSHIFT_L, UBSHIFT_R, UBSHIFT_R_UNSIGNED, UBXOR, UDIV, UEXP, ULAND, ULNOT, ULOR, UMAX, UMIN, UMOD, UMUL, USUB, UTOF, and UTOI.
Referenced by souffle::RamIntrinsicOperator::print(), and souffle::AstIntrinsicFunctor::print().
{
     switch (op) {
         /** Unary Functor Operators */
         case FunctorOp::ITOF:
             return "itof";
         case FunctorOp::ITOU:
             return "itou";
         case FunctorOp::UTOF:
             return "utof";
         case FunctorOp::UTOI:
             return "utoi";
         case FunctorOp::FTOI:
             return "ftoi";
         case FunctorOp::FTOU:
             return "ftou";
         case FunctorOp::ORD:
             return "ord";
         case FunctorOp::STRLEN:
             return "strlen";
         case FunctorOp::NEG:
         case FunctorOp::FNEG:
             return "-";
         case FunctorOp::BNOT:
         case FunctorOp::UBNOT:
             return "bnot";
         case FunctorOp::LNOT:
         case FunctorOp::ULNOT:
             return "lnot";
         case FunctorOp::TONUMBER:
             return "to_number";
         case FunctorOp::TOSTRING:
             return "to_string";
         /** Binary Functor Operators */
         case FunctorOp::ADD:
         case FunctorOp::FADD:
         case FunctorOp::UADD:
             return "+";
         case FunctorOp::SUB:
         case FunctorOp::USUB:
         case FunctorOp::FSUB:
             return "-";
         case FunctorOp::MUL:
         case FunctorOp::UMUL:
         case FunctorOp::FMUL:
             return "*";
         case FunctorOp::DIV:
         case FunctorOp::UDIV:
         case FunctorOp::FDIV:
             return "/";
         case FunctorOp::EXP:
         case FunctorOp::FEXP:
         case FunctorOp::UEXP:
             return "^";
         case FunctorOp::MOD:
         case FunctorOp::UMOD:
             return "%";
         case FunctorOp::BAND:
         case FunctorOp::UBAND:
             return "band";
         case FunctorOp::BOR:
         case FunctorOp::UBOR:
             return "bor";
         case FunctorOp::BXOR:
         case FunctorOp::UBXOR:
             return "bxor";
         case FunctorOp::BSHIFT_L:
         case FunctorOp::UBSHIFT_L:
             return "bshl";
         case FunctorOp::BSHIFT_R:
         case FunctorOp::UBSHIFT_R:
             return "bshr";
         case FunctorOp::BSHIFT_R_UNSIGNED:
         case FunctorOp::UBSHIFT_R_UNSIGNED:
             return "bshru";
         case FunctorOp::LAND:
         case FunctorOp::ULAND:
             return "land";
         case FunctorOp::LOR:
         case FunctorOp::ULOR:
             return "lor";
         /* N-ary Functor Operators */
         case FunctorOp::MAX:
         case FunctorOp::UMAX:
         case FunctorOp::FMAX:
         case FunctorOp::SMAX:
             return "max";
         case FunctorOp::MIN:
         case FunctorOp::UMIN:
         case FunctorOp::FMIN:
         case FunctorOp::SMIN:
             return "min";
         case FunctorOp::CAT:
             return "cat";
         /** Ternary Functor Operators */
         case FunctorOp::SUBSTR:
             return "substr";
     }
     assert(false && "unsupported operator");
     exit(EXIT_FAILURE);
     return "?";
 }
getType()
const AstType * souffle::getType (const AstProgram & program, const AstQualifiedName & name)
Returns the type with the given name in the program.
Parameters
program the program
name the name of the type to search for
Returns
the type if it exists; nullptr otherwise
Definition at line 60 of file AstUtils.cpp.
References getIf(), and souffle::AstProgram::getTypes().
Referenced by souffle::ParserDriver::addType(), souffle::AstProgram::addType(), souffle::AstSemanticChecker::checkRecordType(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::AstSemanticChecker::checkUnionType(), souffle::AstNumericConstant::clone(), souffle::TypeEnvironment::createRecordType(), getBodyLiterals(), souffle::TypeEnvironment::getFloatType(), souffle::TypeEnvironment::getNumberType(), souffle::TypeEnvironment::getSymbolType(), souffle::TypeEnvironment::getUnsignedType(), souffle::TypeEnvironment::initializePredefinedTypes(), souffle::TypeEnvironment::isPredefinedType(), and souffle::TypeEnvironment::isType().
{
     return getIf(program.getTypes(), [&](const AstType* t) { return t->getQualifiedName() == name; });
 }
getTypeAttribute()
template<typename T > TypeAttribute souffle::getTypeAttribute (const T & type)
Convert a type analysis' type/set of type to the the TypeAttribute.
Definition at line 485 of file TypeSystem.h.
References Float, isFloatType(), isNumberType(), isRecordType(), isSymbolType(), isUnsignedType(), Record, Signed, Symbol, and Unsigned.
Referenced by getTypeQualifier().
{
     TypeAttribute primitiveType;
     if (isNumberType(type)) {
         primitiveType = TypeAttribute::Signed;
     } else if (isUnsignedType(type)) {
         primitiveType = TypeAttribute::Unsigned;
     } else if (isFloatType(type)) {
         primitiveType = TypeAttribute::Float;
     } else if (isRecordType(type)) {
         primitiveType = TypeAttribute::Record;
     } else if (isSymbolType(type)) {
         primitiveType = TypeAttribute::Symbol;
     } else {
         std::cerr << "Unknown type class" << std::endl;
         std::exit(EXIT_FAILURE);
     }
     return primitiveType;
 }
getTypeAttributeAggregate()
TypeAttribute souffle::getTypeAttributeAggregate (const AggregateOp op) inline
Get return type of the aggregate.
Definition at line 44 of file AggregateOp.h.
References COUNT, Float, FMAX, FMIN, FSUM, MAX, MEAN, MIN, Signed, SUM, UMAX, UMIN, Unsigned, and USUM.
Referenced by souffle::AstSemanticChecker::checkProgram(), and souffle::Synthesiser::emitCode().
{
     switch (op) {
         case AggregateOp::COUNT:
         case AggregateOp::MAX:
         case AggregateOp::MIN:
         case AggregateOp::SUM:
             return TypeAttribute::Signed;
         case AggregateOp::MEAN:
         case AggregateOp::FMAX:
         case AggregateOp::FMIN:
         case AggregateOp::FSUM:
             return TypeAttribute::Float;
         case AggregateOp::UMAX:
         case AggregateOp::UMIN:
         case AggregateOp::USUM:
             return TypeAttribute::Unsigned;
     }
     assert(false && "invalid argument");
     exit(EXIT_FAILURE);
 }
getTypeQualifier()
std::string souffle::getTypeQualifier (const Type & type)
Returns full type qualifier for a given type.
Definition at line 253 of file TypeSystem.cpp.
References Float, souffle::UnionType::getElementTypes(), souffle::RecordType::getFields(), souffle::Type::getName(), getTypeAttribute(), Record, seen, Signed, str, Symbol, toString(), and Unsigned.
Referenced by souffle::AstTranslator::getRecordsTypes(), souffle::AstTranslator::translateDirectives(), and souffle::AstTranslator::translateProgram().
{
     struct visitor : public VisitOnceTypeVisitor<std::string> {
         std::string visitUnionType(const UnionType& type) const override {
             std::string str = visitType(type);
             str += "[";
             bool first = true;
             for (auto unionType : type.getElementTypes()) {
                 if (first) {
                     first = false;
                 } else {
                     str += ",";
                 }
                 str += visit(*unionType);
             }
             str += "]";
             return str;
         }
         std::string visitRecordType(const RecordType& type) const override {
             std::string str = visitType(type);
             str += "{";
             bool first = true;
             for (auto field : type.getFields()) {
                 if (first) {
                     first = false;
                 } else {
                     str += ",";
                 }
                 str += field.name;
                 str += "#";
                 str += visit(field.type);
             }
             str += "}";
             return str;
         }
         std::string visitType(const Type& type) const override {
             std::string str;
             switch (getTypeAttribute(type)) {
                 case TypeAttribute::Signed:
                     str.append("i");
                     break;
                 case TypeAttribute::Unsigned:
                     str.append("u");
                     break;
                 case TypeAttribute::Float:
                     str.append("f");
                     break;
                 case TypeAttribute::Symbol:
                     str.append("s");
                     break;
                 case TypeAttribute::Record:
                     str.append("r");
                     break;
             }
             str.append(":");
             str.append(toString(type.getName()));
             seen[&type] = str;
             return str;
         }
     };
     return visitor().visit(type);
 }
getVariables()
std::vector< const AstVariable * > souffle::getVariables (const AstNode & root)
Obtains a list of all variables referenced within the AST rooted by the given root node.
Parameters
root the root of the AST to be searched
Returns
a list of all variables referenced within
Definition at line 28 of file AstUtils.cpp.
References visitDepthFirst().
Referenced by souffle::AstSemanticChecker::checkProgram().
{
     // simply collect the list of all variables by visiting all variables
     std::vector<const AstVariable*> vars;
     visitDepthFirst(root, [&](const AstVariable& var) { vars.push_back(&var); });
     return vars;
 }
hasBoundArgument()
bool souffle::hasBoundArgument (AstAtom * atom, const std::set< std::string > & boundArgs, BindingStore & compositeBindings)
Definition at line 136 of file MagicSet.cpp.
References souffle::AstAtom::getArguments(), and isBoundArgument().
Referenced by getNextAtomNaiveSIPS().
{
     for (AstArgument* arg : atom->getArguments()) {
         if (isBoundArgument(arg, boundArgs, compositeBindings)) {
             return true;
         }
     }
     return false;
 }
hasClauseWithAggregatedRelation()
bool souffle::hasClauseWithAggregatedRelation (const AstRelation * relation, const AstRelation * aggRelation, const AstProgram * program, const AstLiteral *& foundLiteral)
Returns whether the given relation has any clauses which contain an aggregation over of a specific relation.
Parameters
relation the relation to search the clauses of
aggRelation the relation to search for in aggregations in clause bodies
program the program containing the relations
foundLiteral set to the literal found in an aggregation
Definition at line 129 of file AstUtils.cpp.
References getAtomRelation(), getClauses(), and visitDepthFirst().
Referenced by souffle::AstSemanticChecker::checkProgram(), and getBodyLiterals().
{
     for (const AstClause* cl : getClauses(*program, *relation)) {
         bool hasAgg = false;
         visitDepthFirst(*cl, [&](const AstAggregator& cur) {
             visitDepthFirst(cur, [&](const AstAtom& atom) {
                 if (aggRelation == getAtomRelation(&atom, program)) {
                     foundLiteral = &atom;
                     hasAgg = true;
                 }
             });
         });
         if (hasAgg) {
             return true;
         }
     }
     return false;
 }
hasClauseWithNegatedRelation()
bool souffle::hasClauseWithNegatedRelation (const AstRelation * relation, const AstRelation * negRelation, const AstProgram * program, const AstLiteral *& foundLiteral)
Returns whether the given relation has any clauses which contain a negation of a specific relation.
Parameters
relation the relation to search the clauses of
negRelation the relation to search for negations of in clause bodies
program the program containing the relations
foundLiteral set to the negation literal that was found
Definition at line 116 of file AstUtils.cpp.
References getAtomRelation(), and getClauses().
Referenced by souffle::AstSemanticChecker::checkProgram(), and getBodyLiterals().
{
     for (const AstClause* cl : getClauses(*program, *relation)) {
         for (const auto* neg : getBodyLiterals<AstNegation>(*cl)) {
             if (negRelation == getAtomRelation(neg->getAtom(), program)) {
                 foundLiteral = neg;
                 return true;
             }
         }
     }
     return false;
 }
hasFloatType()
bool souffle::hasFloatType (const TypeSet & types)
Is any value in the set float.
Definition at line 327 of file TypeSystem.cpp.
References any_of(), souffle::TypeSet::isAll(), and isFloatType().
Referenced by souffle::AstSemanticChecker::checkProgram(), isOrderableType(), and souffle::PolymorphicObjectsTransformer::transform().
{
     return types.isAll() || any_of(types, (bool (*)(const Type&)) & isFloatType);
 }
hasPrefix()
bool souffle::hasPrefix (const std::string & str, const std::string & prefix)
Definition at line 57 of file MagicSet.cpp.
Referenced by isAggRel(), isBoundArgument(), replaceUnderscores(), and souffle::MagicSetTransformer::transform().
{
     return str.substr(0, prefix.size()) == prefix;
 }
hasSignedType()
bool souffle::hasSignedType (const TypeSet & types)
Is any value in the set signed.
Definition at line 319 of file TypeSystem.cpp.
References any_of(), souffle::TypeSet::isAll(), and isNumberType().
Referenced by souffle::AstSemanticChecker::checkProgram(), isOrderableType(), and souffle::PolymorphicObjectsTransformer::transform().
{
     return types.isAll() || any_of(types, (bool (*)(const Type&)) & isNumberType);
 }
hasUnnamedVariable() [1/2]
static bool souffle::hasUnnamedVariable (const AstArgument * arg) static
Definition at line 402 of file AstSemanticChecker.cpp.
References any_of().
Referenced by souffle::AstSemanticChecker::checkClause(), souffle::AstSemanticChecker::checkLiteral(), and hasUnnamedVariable().
{
     if (dynamic_cast<const AstUnnamedVariable*>(arg) != nullptr) {
         return true;
     }
     if (dynamic_cast<const AstVariable*>(arg) != nullptr) {
         return false;
     }
     if (dynamic_cast<const AstConstant*>(arg) != nullptr) {
         return false;
     }
     if (dynamic_cast<const AstCounter*>(arg) != nullptr) {
         return false;
     }
     if (const auto* cast = dynamic_cast<const AstTypeCast*>(arg)) {
         return hasUnnamedVariable(cast->getValue());
     }
     if (const auto* term = dynamic_cast<const AstTerm*>(arg)) {
         return any_of(term->getArguments(), hasUnnamedVariable);
     }
     if (dynamic_cast<const AstAggregator*>(arg) != nullptr) {
         return false;
     }
     std::cout << "Unsupported Argument type: " << typeid(*arg).name() << "\n";
     assert(false && "Unsupported Argument Type!");
     return false;
 }
hasUnnamedVariable() [2/2]
static bool souffle::hasUnnamedVariable (const AstLiteral * lit) static
Definition at line 429 of file AstSemanticChecker.cpp.
References any_of(), and hasUnnamedVariable().
{
     if (const auto* at = dynamic_cast<const AstAtom*>(lit)) {
         return any_of(at->getArguments(), (bool (*)(const AstArgument*))hasUnnamedVariable);
     }
     if (const auto* neg = dynamic_cast<const AstNegation*>(lit)) {
         return hasUnnamedVariable(neg->getAtom());
     }
     if (dynamic_cast<const AstConstraint*>(lit) != nullptr) {
         if (dynamic_cast<const AstBooleanConstraint*>(lit) != nullptr) {
             return false;
         }
         if (const auto* br = dynamic_cast<const AstBinaryConstraint*>(lit)) {
             return hasUnnamedVariable(br->getLHS()) || hasUnnamedVariable(br->getRHS());
         }
     }
     std::cout << "Unsupported Literal type: " << typeid(lit).name() << "\n";
     assert(false && "Unsupported Argument Type!");
     return false;
 }
hasUnsignedType()
bool souffle::hasUnsignedType (const TypeSet & types)
Is any value in the set unsigned.
Definition at line 323 of file TypeSystem.cpp.
References any_of(), souffle::TypeSet::isAll(), and isUnsignedType().
Referenced by souffle::AstSemanticChecker::checkProgram(), isOrderableType(), and souffle::PolymorphicObjectsTransformer::transform().
{
     return types.isAll() || any_of(types, (bool (*)(const Type&)) & isUnsignedType);
 }
identifier()
std::string souffle::identifier (std::string id) inline
Valid C++ identifier, note that this does not ensure the uniqueness of identifiers returned.
Definition at line 1307 of file Util.h.
Referenced by souffle::RamTupleElement::clone(), souffle::MakeIndexTransformer::constructPattern(), souffle::Synthesiser::emitCode(), souffle::RamTupleOperation::equal(), souffle::RamTupleElement::equal(), souffle::MakeIndexTransformer::getExpression(), souffle::MakeIndexTransformer::getName(), souffle::RamTupleOperation::getTupleId(), souffle::RamTupleElement::getTupleId(), main(), souffle::RamTupleElement::print(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::MakeIndexTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::MakeIndexTransformer::rewriteScan(), souffle::ChoiceConversionTransformer::rewriteScan(), and souffle::RamTupleOperation::setTupleId().
{
     for (size_t i = 0; i < id.length(); i++) {
         if (((isalpha(id[i]) == 0) && i == 0) || ((isalnum(id[i]) == 0) && id[i] != '_')) {
             id[i] = '_';
         }
     }
     return id;
 }
identifierToString()
const std::string souffle::identifierToString (const AstQualifiedName & name)
Helper functions.
Definition at line 48 of file ProvenanceTransformer.cpp.
References souffle::profile::ss.
Referenced by makeInfoRelation(), and makeRelationName().
{
     std::stringstream ss;
     ss << name;
     return ss.str();
 }
inlineBodyLiterals()
std::pair<NullableVector<AstLiteral*>, std::vector<AstBinaryConstraint*> > souffle::inlineBodyLiterals (AstAtom * atom, AstClause * atomInlineClause)
Inlines the given atom based on a given clause.
Returns the vector of replacement literals and the necessary constraints. If unification is unsuccessful, the vector of literals is marked as invalid.
Definition at line 281 of file InlineRelationsTransformer.cpp.
References souffle::AstClause::apply(), souffle::AstClause::clone(), constraints, EQ, souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::NullableVector< T >::getVector(), souffle::NullableVector< T >::isValid(), and unifyAtoms().
Referenced by formNegatedLiterals(), and getInlinedLiteral().
{
     bool changed = false;
     std::vector<AstLiteral*> addedLits;
     std::vector<AstBinaryConstraint*> constraints;
     // Rename the variables in the inlined clause to avoid conflicts when unifying multiple atoms
     // - particularly when an inlined relation appears twice in a clause.
     static int inlineCount = 0;
     // Make a temporary clone so we can rename variables without fear
     AstClause* atomClause = atomInlineClause->clone();
     struct VariableRenamer : public AstNodeMapper {
         int varnum;
         VariableRenamer(int varnum) : varnum(varnum) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* var = dynamic_cast<AstVariable*>(node.get())) {
                 // Rename the variable
                 auto newVar = std::unique_ptr<AstVariable>(var->clone());
                 std::stringstream newName;
                 newName << "<inlined_" << var->getName() << "_" << varnum << ">";
                 newVar->setName(newName.str());
                 return newVar;
             }
             node->apply(*this);
             return node;
         }
     };
     VariableRenamer update(inlineCount);
     atomClause->apply(update);
     inlineCount++;
     // Get the constraints needed to unify the two atoms
     NullableVector<std::pair<AstArgument*, AstArgument*>> res = unifyAtoms(atomClause->getHead(), atom);
     if (res.isValid()) {
         changed = true;
         for (std::pair<AstArgument*, AstArgument*> pair : res.getVector()) {
             // FIXME: float equiv (`FEQ`)
             constraints.push_back(new AstBinaryConstraint(BinaryConstraintOp::EQ,
                     std::unique_ptr<AstArgument>(pair.first->clone()),
                     std::unique_ptr<AstArgument>(pair.second->clone())));
         }
         // Add in the body of the current clause of the inlined atom
         for (AstLiteral* lit : atomClause->getBodyLiterals()) {
             addedLits.push_back(lit->clone());
         }
     }
     delete atomClause;
     if (changed) {
         return std::make_pair(NullableVector<AstLiteral*>(addedLits), constraints);
     } else {
         return std::make_pair(NullableVector<AstLiteral*>(), constraints);
     }
 }
isAggRel()
bool souffle::isAggRel (const AstQualifiedName & rel)
Definition at line 62 of file MagicSet.cpp.
References souffle::AstQualifiedName::getQualifiers(), and hasPrefix().
Referenced by souffle::MagicSetTransformer::transform().
{
     // TODO (azreika): this covers too much (e.g. user-defined __agg_rel_x)
     //                 need a way to determine if created by aggregates
     return hasPrefix(rel.getQualifiers()[0], "__agg_rel_");
 }
isBindingConstraint()
bool souffle::isBindingConstraint (AstArgument * lhs, AstArgument * rhs, std::set< std::string > boundArgs)
Definition at line 147 of file MagicSet.cpp.
References getString().
Referenced by souffle::Adornment::run().
{
     std::string lhs_name = getString(lhs);
     std::string rhs_name = getString(rhs);
     // only want to check variables we have not bound yet
     if ((dynamic_cast<AstVariable*>(lhs) != nullptr) && (boundArgs.find(lhs_name) == boundArgs.end())) {
         // return true if the rhs is a bound variable or a constant
         if ((dynamic_cast<AstVariable*>(rhs) != nullptr) && (boundArgs.find(rhs_name) != boundArgs.end())) {
             return true;
         } else if (dynamic_cast<AstConstant*>(rhs) != nullptr) {
             return true;
         }
     }
     return false;
 }
isBoundArgument()
bool souffle::isBoundArgument (AstArgument * arg, const std::set< std::string > & boundArgs, BindingStore & compositeBindings)
Definition at line 115 of file MagicSet.cpp.
References contains(), hasPrefix(), and isBoundComposite().
Referenced by bindArguments(), getNextAtomMaxBoundSIPS(), getNextAtomMaxRatioSIPS(), and hasBoundArgument().
{
     if (auto* var = dynamic_cast<AstVariable*>(arg)) {
         std::string variableName = var->getName();
         if (hasPrefix(variableName, "+functor") || hasPrefix(variableName, "+record")) {
             if (isBoundComposite(var, boundArgs, compositeBindings)) {
                 return true;
             }
         }
         if (contains(boundArgs, variableName)) {
             return true;  // found a bound argument, so can stop
         }
     } else {
         assert(false && "incomplete checks (MST)");
     }
     return false;
 }
isBoundComposite()
bool souffle::isBoundComposite (const AstVariable * compositeVariable, const std::set< std::string > & boundArgs, BindingStore & compositeBindings)
Definition at line 90 of file MagicSet.cpp.
References souffle::BindingStore::addVariableBoundComposite(), contains(), souffle::AstVariable::getName(), and souffle::BindingStore::getVariableDependencies().
Referenced by isBoundArgument().
{
     std::string variableName = compositeVariable->getName();
     if (contains(boundArgs, variableName)) {
         return true;
     }
     bool bound = true;
     // a composite argument is bound iff all its subvariables are bound
     auto dependencies = compositeBindings.getVariableDependencies(variableName);
     for (const std::string& var : dependencies) {
         if (!contains(boundArgs, var)) {
             bound = false;
         }
     }
     if (bound) {
         // composite variable bound only because its constituent variables are bound
         compositeBindings.addVariableBoundComposite(variableName);
     }
     return bound;
 }
isConstantArithExpr()
static bool souffle::isConstantArithExpr (const AstArgument & argument) static
Definition at line 566 of file AstSemanticChecker.cpp.
References all_of(), and isNumericType().
Referenced by souffle::AstSemanticChecker::checkConstant().
{
     if (dynamic_cast<const AstNumericConstant*>(&argument) != nullptr) {
         return true;
     }
     if (const auto* functor = dynamic_cast<const AstIntrinsicFunctor*>(&argument)) {
         // Check return type.
         if (!isNumericType(functor->getReturnType())) {
             return false;
         }
         // Check arguments
         return all_of(functor->getArguments(), [](auto* arg) { return isConstantArithExpr(*arg); });
     }
     return false;
 }
isEqConstraint()
bool souffle::isEqConstraint (const BinaryConstraintOp constraintOp) inline
Definition at line 61 of file BinaryConstraintOps.h.
References EQ, and FEQ.
Referenced by souffle::FoldAnonymousRecords::expandRecordBinaryConstraint(), souffle::ResolveAnonymousRecordsAliases::findVariablesRecordMapping(), souffle::MakeIndexTransformer::getExpression(), getGroundedTerms(), souffle::FoldAnonymousRecords::isValidRecordConstraint(), souffle::ResolveAliasesTransformer::removeTrivialEquality(), souffle::ResolveAnonymousRecordsAliases::replaceUnnamedVariable(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::Adornment::run(), and souffle::FoldAnonymousRecords::transformClause().
{
     switch (constraintOp) {
         case BinaryConstraintOp::EQ:
         case BinaryConstraintOp::FEQ:
             return true;
         default:
             break;
     }
     return false;
 }
isEqualAdornment()
bool souffle::isEqualAdornment (const AstQualifiedName & pred1, const std::string & adorn1, const AstQualifiedName & pred2, const std::string & adorn2)
Definition at line 40 of file MagicSet.cpp.
Referenced by contains().
{
     return ((pred1 == pred2) && (adorn1 == adorn2));
 }
isExecutable()
bool souffle::isExecutable (const std::string & name) inline
Check whether a given file exists and it is an executable.
Definition at line 1084 of file Util.h.
Referenced by executeBinary(), and main().
{
     return existFile(name) && (access(name.c_str(), X_OK) == 0);
 }
isFact()
bool souffle::isFact (const AstClause & clause)
Returns whether the given clause is a fact.
Returns
true iff the clause is a fact
Definition at line 159 of file AstUtils.cpp.
References souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), and visitDepthFirst().
Referenced by souffle::AstSemanticChecker::checkClause(), souffle::AstSemanticChecker::checkFact(), souffle::AstSemanticChecker::checkProgram(), getBodyLiterals(), getClauseNum(), isRule(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::Adornment::run(), separateDBs(), souffle::NormaliseConstraintsTransformer::transform(), souffle::ProvenanceTransformer::transformMaxHeight(), souffle::ProvenanceTransformer::transformSubtreeHeights(), and souffle::AstTranslator::ClauseTranslator::translateClause().
{
     // there must be a head
     if (clause.getHead() == nullptr) {
         return false;
     }
     // there must not be any body clauses
     if (!clause.getBodyLiterals().empty()) {
         return false;
     }
     // and there are no aggregates
     bool hasAggregates = false;
     visitDepthFirst(*clause.getHead(), [&](const AstAggregator&) { hasAggregates = true; });
     return !hasAggregates;
 }
isFloatType() [1/2]
bool souffle::isFloatType (const Type & type)
Determines whether the given type is a float type.
Definition at line 331 of file TypeSystem.cpp.
References souffle::TypeEnvironment::getFloatType(), and souffle::Type::getTypeEnvironment().
Referenced by eqTypeTypeAttribute(), getTypeAttribute(), hasFloatType(), isFloatType(), isNumericType(), isOrderableType(), and souffle::PolymorphicObjectsTransformer::transform().
{
     return isOfRootType(type, type.getTypeEnvironment().getFloatType());
 }
isFloatType() [2/2]
bool souffle::isFloatType (const TypeSet & s)
Determines whether all the types in the given set are float types.
Definition at line 335 of file TypeSystem.cpp.
References all_of(), souffle::TypeSet::empty(), souffle::TypeSet::isAll(), and isFloatType().
{
     return !s.empty() && !s.isAll() && all_of(s, (bool (*)(const Type&)) & isFloatType);
 }
isInfixFunctorOp()
bool souffle::isInfixFunctorOp (const FunctorOp op) inline
Determines whether a functor should be written using infix notation (e.g.
a + b + c) or prefix notation (e.g. +(a,b,c))
Definition at line 598 of file FunctorOps.h.
References ADD, BAND, BOR, BSHIFT_L, BSHIFT_R, BSHIFT_R_UNSIGNED, BXOR, DIV, EXP, FADD, FDIV, FEXP, FMUL, FSUB, LAND, LOR, MOD, MUL, SUB, UADD, UBAND, UBOR, UBSHIFT_L, UBSHIFT_R, UBSHIFT_R_UNSIGNED, UBXOR, UDIV, UEXP, ULAND, ULOR, UMOD, UMUL, and USUB.
Referenced by souffle::RamIntrinsicOperator::print(), and souffle::AstIntrinsicFunctor::print().
{
     switch (op) {
         case FunctorOp::ADD:
         case FunctorOp::FADD:
         case FunctorOp::UADD:
         case FunctorOp::SUB:
         case FunctorOp::USUB:
         case FunctorOp::FSUB:
         case FunctorOp::MUL:
         case FunctorOp::FMUL:
         case FunctorOp::UMUL:
         case FunctorOp::DIV:
         case FunctorOp::FDIV:
         case FunctorOp::UDIV:
         case FunctorOp::EXP:
         case FunctorOp::FEXP:
         case FunctorOp::UEXP:
         case FunctorOp::BAND:
         case FunctorOp::UBAND:
         case FunctorOp::BOR:
         case FunctorOp::UBOR:
         case FunctorOp::BXOR:
         case FunctorOp::BSHIFT_L:
         case FunctorOp::UBSHIFT_L:
         case FunctorOp::BSHIFT_R:
         case FunctorOp::UBSHIFT_R:
         case FunctorOp::BSHIFT_R_UNSIGNED:
         case FunctorOp::UBSHIFT_R_UNSIGNED:
         case FunctorOp::UBXOR:
         case FunctorOp::LAND:
         case FunctorOp::ULAND:
         case FunctorOp::LOR:
         case FunctorOp::ULOR:
         case FunctorOp::MOD:
         case FunctorOp::UMOD:
             return true;
         default:
             return false;
     }
 }
isNumber()
bool souffle::isNumber (const char * str) inline
Check whether a string is a sequence of digits.
Definition at line 275 of file Util.h.
Referenced by souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainNegationGetVariables(), and main().
{
     if (str == nullptr) {
         return false;
     }
     while (*str != 0) {
         if (isdigit(*str) == 0) {
             return false;
         }
         str++;
     }
     return true;
 }
isNumberType() [1/2]
bool souffle::isNumberType (const Type & type)
Determines whether the given type is a number type.
Definition at line 339 of file TypeSystem.cpp.
References souffle::TypeEnvironment::getNumberType(), and souffle::Type::getTypeEnvironment().
Referenced by eqTypeTypeAttribute(), getTypeAttribute(), hasSignedType(), isNumberType(), isNumericType(), isOrderableType(), isSubtypeOf(), and souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries().
{
     return isOfRootType(type, type.getTypeEnvironment().getNumberType());
 }
isNumberType() [2/2]
bool souffle::isNumberType (const TypeSet & s)
Determines whether all the types in the given set are number types.
Definition at line 343 of file TypeSystem.cpp.
References all_of(), souffle::TypeSet::empty(), souffle::TypeSet::isAll(), and isNumberType().
{
     return !s.empty() && !s.isAll() && all_of(s, (bool (*)(const Type&)) & isNumberType);
 }
isNumericType() [1/2]
bool souffle::isNumericType (TypeAttribute ramType) inline
Check if type is numeric.
Definition at line 61 of file RamTypes.h.
References Float, Record, Signed, Symbol, and Unsigned.
Referenced by isConstantArithExpr(), and isOrderableType().
{
     switch (ramType) {
         case TypeAttribute::Signed:
         case TypeAttribute::Unsigned:
         case TypeAttribute::Float:
             return true;
         case TypeAttribute::Symbol:
         case TypeAttribute::Record:
             return false;
     }
     return false;  // silence warning
 }
isNumericType() [2/2]
template<typename T > bool souffle::isNumericType (const T & type) inline
Determines whether the type is numeric.
Definition at line 508 of file TypeSystem.h.
References isFloatType(), isNumberType(), and isUnsignedType().
{
     return isFloatType(type) || isNumberType(type) || isUnsignedType(type);
 }
isOrderableType()
template<typename T > bool souffle::isOrderableType (const T & type) inline
Definition at line 513 of file TypeSystem.h.
References areSubtypesOf(), b, getLeastCommonSupertypes(), hasFloatType(), hasSignedType(), hasUnsignedType(), isFloatType(), isNumberType(), isNumericType(), isRecordType(), isRecursiveType(), isSubtypeOf(), isSymbolType(), isUnsignedType(), and types.
{
     return isNumericType(type) || isSymbolType(type);
 }
isOrderedBinaryConstraintOp()
bool souffle::isOrderedBinaryConstraintOp (const BinaryConstraintOp op) inline
Determines whether arguments of constraint are orderable.
Definition at line 276 of file BinaryConstraintOps.h.
References CONTAINS, EQ, FEQ, FGE, FGT, FLE, FLT, FNE, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, SGE, SGT, SLE, SLT, UGE, UGT, ULE, and ULT.
Referenced by souffle::AstSemanticChecker::checkProgram(), and souffle::ExplainProvenanceImpl::explain().
{
     switch (op) {
         case BinaryConstraintOp::EQ:
         case BinaryConstraintOp::FEQ:
         case BinaryConstraintOp::NE:
         case BinaryConstraintOp::FNE:
         case BinaryConstraintOp::LT:
         case BinaryConstraintOp::ULT:
         case BinaryConstraintOp::FLT:
         case BinaryConstraintOp::LE:
         case BinaryConstraintOp::ULE:
         case BinaryConstraintOp::FLE:
         case BinaryConstraintOp::GE:
         case BinaryConstraintOp::UGE:
         case BinaryConstraintOp::FGE:
         case BinaryConstraintOp::GT:
         case BinaryConstraintOp::UGT:
         case BinaryConstraintOp::FGT:
         case BinaryConstraintOp::SLT:
         case BinaryConstraintOp::SLE:
         case BinaryConstraintOp::SGE:
         case BinaryConstraintOp::SGT:
             return true;
         case BinaryConstraintOp::MATCH:
         case BinaryConstraintOp::NOT_MATCH:
         case BinaryConstraintOp::CONTAINS:
         case BinaryConstraintOp::NOT_CONTAINS:
             return false;
     }
     assert(false && "Uncovered case!");
     exit(EXIT_FAILURE);
 }
isOverloaded()
bool souffle::isOverloaded (const BinaryConstraintOp constraintOp) inline
Utility function, informing whether constraint is overloaded.
Only the signed version's are treated as overloaded (as they are returned by the parser).
Definition at line 76 of file BinaryConstraintOps.h.
References EQ, GE, GT, LE, LT, and NE.
Referenced by convertOverloadedConstraint(), and souffle::PolymorphicObjectsTransformer::transform().
{
     switch (constraintOp) {
         case BinaryConstraintOp::EQ:
         case BinaryConstraintOp::NE:
         case BinaryConstraintOp::LT:
         case BinaryConstraintOp::LE:
         case BinaryConstraintOp::GT:
         case BinaryConstraintOp::GE:
             return true;
         default:
             break;
     }
     return false;
 }
isOverloadedAggregator()
bool souffle::isOverloadedAggregator (const AggregateOp op) inline
Definition at line 68 of file AggregateOp.h.
References MAX, MIN, and SUM.
Referenced by souffle::PolymorphicObjectsTransformer::transform().
{
     switch (op) {
         case AggregateOp::MAX:
         case AggregateOp::MIN:
         case AggregateOp::SUM:
             return true;
         default:
             break;
     }
     return false;
 }
isOverloadedFunctor()
bool souffle::isOverloadedFunctor (const FunctorOp functor) inline
Indicate whether a functor is overloaded.
At the moment, the signed versions are treated as representatives (because parser always returns a signed version).
Definition at line 460 of file FunctorOps.h.
References ADD, BAND, BNOT, BOR, BXOR, DIV, EXP, LAND, LNOT, LOR, MAX, MIN, MOD, MUL, NEG, and SUB.
Referenced by souffle::TypeAnalysis::analyseTypes(), and souffle::PolymorphicObjectsTransformer::transform().
{
     switch (functor) {
         /* Unary */
         case FunctorOp::NEG:
         case FunctorOp::BNOT:
         case FunctorOp::LNOT:
         /* Binary */
         case FunctorOp::ADD:
         case FunctorOp::SUB:
         case FunctorOp::MUL:
         case FunctorOp::DIV:
         case FunctorOp::EXP:
         case FunctorOp::BAND:
         case FunctorOp::BOR:
         case FunctorOp::BXOR:
         case FunctorOp::LAND:
         case FunctorOp::LOR:
         case FunctorOp::MOD:
         case FunctorOp::MAX:
         case FunctorOp::MIN:
             return true;
             break;
         default:
             break;
     }
     return false;
 }
isPrefix()
bool souffle::isPrefix (const std::string & prefix, const std::string & element) inline
Determine if one string is a prefix of another.
Definition at line 879 of file Util.h.
Referenced by RamSignedFromString(), RamUnsignedFromString(), and souffle::ReadStreamCSV::readRamUnsigned().
{
     auto itPrefix = prefix.begin();
     auto itElement = element.begin();
     while (itPrefix != prefix.end() && itElement != element.end()) {
         if (*itPrefix != *itElement) {
             break;
         }
         ++itPrefix;
         ++itElement;
     }
     return itPrefix == prefix.end();
 }
isProposition()
bool souffle::isProposition (const AstAtom * atom) inline
Definition at line 42 of file ReorderLiteralsTransformer.cpp.
References souffle::AstAtom::getArguments().
Referenced by getSipsFunction(), and souffle::ReorderLiteralsTransformer::transform().
{
     return atom->getArguments().empty();
 }
isRamTrue()
bool souffle::isRamTrue (const RamCondition * cond) inline
Determines if a condition represents true.
Definition at line 32 of file RamUtils.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamAggregate::print(), souffle::RamIndexAggregate::print(), souffle::MakeIndexTransformer::rewriteIndexScan(), and souffle::MakeIndexTransformer::rewriteScan().
{
     return nullptr != dynamic_cast<const RamTrue*>(cond);
 }
isRamUndefValue()
bool souffle::isRamUndefValue (const RamExpression * expr) inline
Determines if an expression represents an undefined value.
Definition at line 27 of file RamUtils.h.
Referenced by souffle::Synthesiser::emitCode(), souffle::RamIndexAnalysis::isTotalSignature(), souffle::RamIndexAnalysis::print(), souffle::RamIndexOperation::printIndex(), and souffle::AstTranslator::ClauseTranslator::translateClause().
{
     return nullptr != dynamic_cast<const RamUndefValue*>(expr);
 }
isRecordType() [1/2]
bool souffle::isRecordType (const Type & type)
Determines whether the given type is a record type.
Definition at line 363 of file TypeSystem.cpp.
Referenced by souffle::AstSemanticChecker::checkProgram(), eqTypeTypeAttribute(), getTypeAttribute(), isOrderableType(), and isRecordType().
{
     return dynamic_cast<const RecordType*>(&type) != nullptr;
 }
isRecordType() [2/2]
bool souffle::isRecordType (const TypeSet & s)
Determines whether all the types in the given set are record types.
Definition at line 367 of file TypeSystem.cpp.
References all_of(), souffle::TypeSet::empty(), souffle::TypeSet::isAll(), and isRecordType().
{
     return !s.empty() && !s.isAll() && all_of(s, (bool (*)(const Type&)) & isRecordType);
 }
isRecursiveClause()
bool souffle::isRecursiveClause (const AstClause & clause)
Returns whether the given clause is recursive.
Parameters
clause the clause to check
Returns
true iff the clause is recursive
Definition at line 148 of file AstUtils.cpp.
References souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstAtom::getQualifiedName(), and visitDepthFirst().
Referenced by getBodyLiterals(), and souffle::ReduceExistentialsTransformer::transform().
{
     AstQualifiedName relationName = clause.getHead()->getQualifiedName();
     bool recursive = false;
     visitDepthFirst(clause.getBodyLiterals(), [&](const AstAtom& atom) {
         if (atom.getQualifiedName() == relationName) {
             recursive = true;
         }
     });
     return recursive;
 }
isRecursiveType()
bool souffle::isRecursiveType (const Type & type)
Determines whether the given type is a recursive type.
Definition at line 371 of file TypeSystem.cpp.
References any_of(), souffle::UnionType::getElementTypes(), and souffle::RecordType::getFields().
Referenced by isOrderableType().
{
     struct visitor : public VisitOnceTypeVisitor<bool> {
         const Type& trg;
         visitor(const Type& trg) : trg(trg) {}
         bool visit(const Type& type) const override {
             if (trg == type) {
                 return true;
             }
             return VisitOnceTypeVisitor<bool>::visit(type);
         }
         bool visitUnionType(const UnionType& type) const override {
             auto reachesTrg = [&](const Type* cur) { return this->visit(*cur); };
             return any_of(type.getElementTypes(), reachesTrg);
         }
         bool visitRecordType(const RecordType& type) const override {
             auto reachesTrg = [&](const RecordType::Field& cur) { return this->visit(cur.type); };
             return any_of(type.getFields(), reachesTrg);
         }
     };
     // record types are recursive if they contain themselves
     if (const auto* r = dynamic_cast<const RecordType*>(&type)) {
         auto reachesOrigin = visitor(type);
         return any_of(r->getFields(),
                 [&](const RecordType::Field& field) -> bool { return reachesOrigin(field.type); });
     }
     return false;
 }
isRelationQualifierTag()
bool souffle::isRelationQualifierTag (const RelationTag & tag) inline
Check if a given relation tag is a relation qualifier.
Definition at line 70 of file RelationTag.h.
References INLINE, INPUT, OUTPUT, OVERRIDABLE, PRINTSIZE, and SUPPRESSED.
{
     switch (tag) {
         case RelationTag::INPUT:
         case RelationTag::OUTPUT:
         case RelationTag::PRINTSIZE:
         case RelationTag::OVERRIDABLE:
         case RelationTag::INLINE:
         case RelationTag::SUPPRESSED:
             return true;
         default:
             return false;
     }
 }
isRelationRepresentationTag()
bool souffle::isRelationRepresentationTag (const RelationTag & tag) inline
Check if a given relation tag sets a relation representation.
Definition at line 56 of file RelationTag.h.
References BRIE, BTREE, and EQREL.
{
     switch (tag) {
         case RelationTag::BRIE:
         case RelationTag::BTREE:
         case RelationTag::EQREL:
             return true;
         default:
             return false;
     }
 }
isRule()
bool souffle::isRule (const AstClause & clause)
Returns whether the given clause is a rule.
Returns
true iff the clause is a rule
Definition at line 175 of file AstUtils.cpp.
References souffle::AstClause::getHead(), and isFact().
Referenced by getBodyLiterals(), and souffle::AstTranslator::ClauseTranslator::translateClause().
{
     return (clause.getHead() != nullptr) && !isFact(clause);
 }
isSubtypeOf()
bool souffle::isSubtypeOf (const Type & a, const Type & b)
Determines whether type a is a subtype of type b.
Definition at line 401 of file TypeSystem.cpp.
References souffle::Type::environment, souffle::SubsetType::getBaseType(), souffle::TypeEnvironment::getNumberType(), souffle::TypeEnvironment::getSymbolType(), souffle::Type::getTypeEnvironment(), isNumberType(), isSymbolType(), and souffle::TypeEnvironment::isType().
Referenced by souffle::TypeAnalysis::analyseTypes(), areSubtypesOf(), getGreatestCommonSubtypes(), getLeastCommonSupertypes(), and isOrderableType().
{
     // make sure they are both in the same environment
     auto& environment = a.getTypeEnvironment();
     assert(environment.isType(a) && environment.isType(b));
     // first check - a type is a sub-type of itself
     if (a == b) {
         return true;
     }
     // check for predefined types
     if (b == environment.getNumberType()) {
         return isNumberType(a);
     }
     if (b == environment.getSymbolType()) {
         return isSymbolType(a);
     }
     // check primitive type chains
     if (isA<SubsetType>(a)) {
         if (isSubtypeOf(as<SubsetType>(a).getBaseType(), b)) {
             return true;
         }
     }
     // next - if b is a union type
     if (isUnion(b)) {
         return isSubType(a, as<UnionType>(b));
     }
     // done
     return false;
 }
isSymbolType() [1/2]
bool souffle::isSymbolType (const Type & type)
Determines whether the given type is a symbol type.
Definition at line 355 of file TypeSystem.cpp.
References souffle::TypeEnvironment::getSymbolType(), and souffle::Type::getTypeEnvironment().
Referenced by souffle::AstSemanticChecker::checkProgram(), eqTypeTypeAttribute(), getTypeAttribute(), isOrderableType(), isSubtypeOf(), isSymbolType(), and souffle::PolymorphicObjectsTransformer::transform().
{
     return isOfRootType(type, type.getTypeEnvironment().getSymbolType());
 }
isSymbolType() [2/2]
bool souffle::isSymbolType (const TypeSet & s)
Determines whether all the types in the given set are symbol types.
Definition at line 359 of file TypeSystem.cpp.
References all_of(), souffle::TypeSet::empty(), souffle::TypeSet::isAll(), and isSymbolType().
{
     return !s.empty() && !s.isAll() && all_of(s, (bool (*)(const Type&)) & isSymbolType);
 }
isUnsignedType() [1/2]
bool souffle::isUnsignedType (const Type & type)
Determines whether the given type is a number type.
Definition at line 347 of file TypeSystem.cpp.
References souffle::Type::getTypeEnvironment(), and souffle::TypeEnvironment::getUnsignedType().
Referenced by eqTypeTypeAttribute(), getTypeAttribute(), hasUnsignedType(), isNumericType(), isOrderableType(), isUnsignedType(), and souffle::PolymorphicObjectsTransformer::transform().
{
     return isOfRootType(type, type.getTypeEnvironment().getUnsignedType());
 }
isUnsignedType() [2/2]
bool souffle::isUnsignedType (const TypeSet & s)
Determines whether all the types in the given set are number types.
Definition at line 351 of file TypeSystem.cpp.
References all_of(), souffle::TypeSet::empty(), souffle::TypeSet::isAll(), and isUnsignedType().
{
     return !s.empty() && !s.isAll() && all_of(s, (bool (*)(const Type&)) & isUnsignedType);
 }
isValidFunctorOpArity()
bool souffle::isValidFunctorOpArity (const FunctorOp op, const size_t arity) inline
Checks whether a functor operation can have a given argument count.
Unary Functor Operators
Binary Functor Operators
Ternary Functor Operators
Non-fixed
Definition at line 98 of file FunctorOps.h.
References ADD, BAND, BNOT, BOR, BSHIFT_L, BSHIFT_R, BSHIFT_R_UNSIGNED, BXOR, CAT, DIV, EXP, FADD, FDIV, FEXP, FMAX, FMIN, FMUL, FNEG, FSUB, FTOI, FTOU, ITOF, ITOU, LAND, LNOT, LOR, MAX, MIN, MOD, MUL, NEG, ORD, SMAX, SMIN, STRLEN, SUB, SUBSTR, TONUMBER, TOSTRING, UADD, UBAND, UBNOT, UBOR, UBSHIFT_L, UBSHIFT_R, UBSHIFT_R_UNSIGNED, UBXOR, UDIV, UEXP, ULAND, ULNOT, ULOR, UMAX, UMIN, UMOD, UMUL, USUB, UTOF, and UTOI.
Referenced by souffle::AstIntrinsicFunctor::AstIntrinsicFunctor(), and combineAggregators().
{
     switch (op) {
         /** Unary Functor Operators */
         case FunctorOp::ORD:
         case FunctorOp::STRLEN:
         case FunctorOp::NEG:
         case FunctorOp::FNEG:
         case FunctorOp::BNOT:
         case FunctorOp::UBNOT:
         case FunctorOp::LNOT:
         case FunctorOp::ULNOT:
         case FunctorOp::TONUMBER:
         case FunctorOp::TOSTRING:
         case FunctorOp::ITOU:
         case FunctorOp::UTOI:
         case FunctorOp::ITOF:
         case FunctorOp::FTOI:
         case FunctorOp::UTOF:
         case FunctorOp::FTOU:
             return arity == 1;
         /** Binary Functor Operators */
         case FunctorOp::ADD:
         case FunctorOp::SUB:
         case FunctorOp::MUL:
         case FunctorOp::DIV:
         case FunctorOp::EXP:
         case FunctorOp::MOD:
         case FunctorOp::BAND:
         case FunctorOp::BOR:
         case FunctorOp::BXOR:
         case FunctorOp::BSHIFT_L:
         case FunctorOp::BSHIFT_R:
         case FunctorOp::BSHIFT_R_UNSIGNED:
         case FunctorOp::LAND:
         case FunctorOp::LOR:
         case FunctorOp::UADD:
         case FunctorOp::USUB:
         case FunctorOp::UMUL:
         case FunctorOp::UDIV:
         case FunctorOp::UEXP:
         case FunctorOp::UMOD:
         case FunctorOp::UBAND:
         case FunctorOp::UBOR:
         case FunctorOp::UBXOR:
         case FunctorOp::UBSHIFT_L:
         case FunctorOp::UBSHIFT_R:
         case FunctorOp::UBSHIFT_R_UNSIGNED:
         case FunctorOp::ULAND:
         case FunctorOp::ULOR:
         case FunctorOp::FADD:
         case FunctorOp::FSUB:
         case FunctorOp::FMUL:
         case FunctorOp::FDIV:
         case FunctorOp::FEXP:
             return arity == 2;
         /** Ternary Functor Operators */
         case FunctorOp::SUBSTR:
             return arity == 3;
         /** Non-fixed */
         case FunctorOp::MAX:
         case FunctorOp::MIN:
         case FunctorOp::UMAX:
         case FunctorOp::UMIN:
         case FunctorOp::FMAX:
         case FunctorOp::FMIN:
         case FunctorOp::SMAX:
         case FunctorOp::SMIN:
         case FunctorOp::CAT:
             return arity >= 2;
     }
     assert(false && "unsupported operator");
     return false;
 }
isValidMove()
bool souffle::isValidMove (const AstClause * left, size_t leftIdx, const AstClause * right, size_t rightIdx)
Check if the atom at leftIdx in the left clause can potentially be matched up with the atom at rightIdx in the right clause.
NOTE: index 0 refers to the head atom, index 1 to the first body atom, and so on.
Definition at line 136 of file MinimiseProgramTransformer.cpp.
References souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), and souffle::AstAtom::getQualifiedName().
Referenced by areBijectivelyEquivalent().
{
     // handle the case where one of the indices refers to the head
     if (leftIdx == 0 && rightIdx == 0) {
         const AstAtom* leftHead = left->getHead();
         const AstAtom* rightHead = right->getHead();
         return leftHead->getQualifiedName() == rightHead->getQualifiedName();
     } else if (leftIdx == 0 || rightIdx == 0) {
         return false;
     }
     // both must hence be body atoms
     int leftBodyAtomIdx = leftIdx - 1;
     const AstAtom* leftAtom = dynamic_cast<AstAtom*>(left->getBodyLiterals()[leftBodyAtomIdx]);
     assert(leftAtom != nullptr && "expected atom");
     int rightBodyAtomIdx = rightIdx - 1;
     const AstAtom* rightAtom = dynamic_cast<AstAtom*>(right->getBodyLiterals()[rightBodyAtomIdx]);
     assert(rightAtom != nullptr && "expected atom");
     return leftAtom->getQualifiedName() == rightAtom->getQualifiedName();
 }
isValidPermutation()
bool souffle::isValidPermutation (const AstClause * left, const AstClause * right, const std::vector< unsigned int > & permutation)
Check whether a valid variable mapping exists for the given permutation.
Definition at line 161 of file MinimiseProgramTransformer.cpp.
References souffle::AstClause::clone(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstVariable::getName(), getName, i, j, reorderAtoms(), and visitDepthFirst().
Referenced by areBijectivelyEquivalent().
{
     // --- perform the permutation ---
     auto reorderedLeft = std::unique_ptr<AstClause>(left->clone());
     // deduce the body atom permutation from the full clause permutation
     std::vector<unsigned int> bodyPermutation(permutation.begin() + 1, permutation.end());
     for (unsigned int& i : bodyPermutation) {
         i -= 1;
     }
     // currently, <permutation[i] == j> indicates that atom i should map to position j
     // internally, for the clause class' reordering function, <permutation[i] == j> indicates
     // that position i should contain atom j
     // rearrange the permutation to match the internals
     // TODO (azreika): perhaps change the internal reordering strategy because this came up in MST too
     std::vector<unsigned int> reorderedPermutation(bodyPermutation.size());
     for (size_t i = 0; i < bodyPermutation.size(); i++) {
         reorderedPermutation[bodyPermutation[i]] = i;
     }
     // perform the permutation
     reorderedLeft.reset(reorderAtoms(reorderedLeft.get(), reorderedPermutation));
     // --- check if a valid variable exists corresponding to this permutation ---
     std::map<std::string, std::string> variableMap;
     visitDepthFirst(*reorderedLeft, [&](const AstVariable& var) { variableMap[var.getName()] = ""; });
     // need to match the variables in the body
     std::vector<AstLiteral*> leftAtoms = reorderedLeft->getBodyLiterals();
     std::vector<AstLiteral*> rightAtoms = right->getBodyLiterals();
     // need to match the variables in the head
     leftAtoms.push_back(reorderedLeft->getHead());
     rightAtoms.push_back(right->getHead());
     // check if a valid variable mapping exists
     auto isVariable = [](const AstArgument* arg) { return dynamic_cast<const AstVariable*>(arg) != nullptr; };
     bool validMapping = true;
     for (size_t i = 0; i < leftAtoms.size() && validMapping; i++) {
         // match arguments
         assert(dynamic_cast<AstAtom*>(leftAtoms[i]) != nullptr && "expected atom");
         assert(dynamic_cast<AstAtom*>(rightAtoms[i]) != nullptr && "expected atom");
         std::vector<AstArgument*> leftArgs = dynamic_cast<AstAtom*>(leftAtoms[i])->getArguments();
         std::vector<AstArgument*> rightArgs = dynamic_cast<AstAtom*>(rightAtoms[i])->getArguments();
         for (size_t j = 0; j < leftArgs.size(); j++) {
             AstArgument* leftArg = leftArgs[j];
             AstArgument* rightArg = rightArgs[j];
             if (isVariable(leftArg) && isVariable(rightArg)) {
                 // both variables, their names should match to each other through the clause
                 std::string leftVarName = dynamic_cast<AstVariable*>(leftArg)->getName();
                 std::string rightVarName = dynamic_cast<AstVariable*>(rightArg)->getName();
                 std::string currentMap = variableMap[leftVarName];
                 if (currentMap.empty()) {
                     // unassigned yet, so assign it appropriately
                     variableMap[leftVarName] = rightVarName;
                 } else if (currentMap != rightVarName) {
                     // mapping is inconsistent!
                     // clauses cannot be equivalent under this permutation
                     validMapping = false;
                     break;
                 }
             } else if (castEq<AstStringConstant>(leftArg, rightArg)) {
                 validMapping = true;
             } else if (castEq<AstNumericConstant>(leftArg, rightArg)) {
                 validMapping = true;
             } else if (dynamic_cast<AstNilConstant*>(leftArg) != nullptr) {
                 validMapping = dynamic_cast<AstNilConstant*>(rightArg) != nullptr;
             } else {
                 // not the same type, failed!
                 validMapping = false;
                 break;
             }
         }
     }
     // return whether a valid variable mapping exists for this permutation
     return validMapping;
 }
join() [1/4]
template<typename Iter , typename Printer > detail::joined_sequence<Iter, Printer> souffle::join (const Iter & a, const Iter & b, const std::string & sep, const Printer & p)
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 701 of file Util.h.
References souffle::range< Iter >::a, souffle::range< Iter >::b, and p.
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::AstSemanticChecker::checkRecursiveUnionTypes(), souffle::AstSemanticChecker::checkTypes(), souffle::Synthesiser::emitCode(), souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::Synthesiser::generateCode(), souffle::SynthesiserDirectRelation::generateTypeStruct(), souffle::SynthesiserIndirectRelation::generateTypeStruct(), souffle::SynthesiserBrieRelation::generateTypeStruct(), souffle::AstTranslator::getOutputDirectives(), souffle::AstTranslator::getRelationName(), souffle::SynthesiserDirectRelation::getTypeName(), souffle::SynthesiserIndirectRelation::getTypeName(), souffle::SynthesiserBrieRelation::getTypeName(), join(), main(), makeInfoRelation(), operator<<(), std::operator<<(), souffle::IOType::print(), souffle::AstExecutionOrder::print(), souffle::AstFunctorDeclaration::print(), souffle::AstComponentType::print(), souffle::AstQualifiedName::print(), souffle::AstIO::print(), souffle::AstAtom::print(), souffle::RamIntrinsicOperator::print(), souffle::AstExecutionPlan::print(), souffle::RamIO::print(), souffle::UnionType::print(), souffle::AstRelation::print(), souffle::AstUnionType::print(), souffle::RecordType::print(), souffle::RamUserDefinedOperator::print(), souffle::SymbolTable::print(), souffle::AstClause::print(), souffle::AstProgram::print(), souffle::AstTranslator::ValueIndex::print(), souffle::TypeSet::print(), souffle::RamAbstractExistenceCheck::print(), souffle::SCCGraph::print(), souffle::AstIntrinsicFunctor::print(), souffle::AstComponent::print(), souffle::TopologicallySortedSCCGraph::print(), souffle::AstUserDefinedFunctor::print(), souffle::Problem< Var >::print(), souffle::AstRecordInit::print(), souffle::RamPackRecord::print(), souffle::AstAggregator::print(), souffle::RamProject::print(), and souffle::AstQualifiedName::toString().
{
     return souffle::detail::joined_sequence<Iter, Printer>(a, b, sep, p);
 }
join() [2/4]
template<typename Iter , typename T = typename Iter::value_type> detail::joined_sequence<Iter, detail::print<id<T> > > souffle::join (const Iter & a, const Iter & b, const std::string & sep = ",")
Creates an object to be forwarded to some output stream for printing sequences of elements interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 713 of file Util.h.
References join().
{
     return join(a, b, sep, detail::print<id<T>>());
 }
join() [3/4]
template<typename Container , typename Printer , typename Iter = typename Container::const_iterator> detail::joined_sequence<Iter, Printer> souffle::join (const Container & c, const std::string & sep, const Printer & p)
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 725 of file Util.h.
References join(), and p.
{
     return join(c.begin(), c.end(), sep, p);
 }
join() [4/4]
template<typename Container , typename Iter = typename Container::const_iterator, typename T = typename Iter::value_type> detail::joined_sequence<Iter, detail::print<id<T> > > souffle::join (const Container & c, const std::string & sep = ",")
Creates an object to be forwarded to some output stream for printing the content of containers interspersed by a given separator.
For use cases see the test case {util_test.cpp}.
Definition at line 737 of file Util.h.
References join().
{
     return join(c.begin(), c.end(), sep, detail::print<id<T>>());
 }
main()
int souffle::main (int argc, char ** argv)
Ensure that code generation is enabled if using SWIG interface option.
Definition at line 124 of file main.cpp.
References souffle::DebugReport::addSection(), baseName(), compileToBinary(), souffle::Global::config(), e, souffle::DebugReport::endSection(), executeBinary(), existDir(), existFile(), explain(), findTool(), souffle::MainConfig::help(), identifier(), isExecutable(), isNumber(), join(), now(), souffle::ParserDriver::parseTranslationUnit(), souffle::MainConfig::processArgs(), RAM_DOMAIN_SIZE, souffle::profile::Tui::runProf(), simpleName(), splitString(), souffle::profile::ss, souffle::DebugReport::startSection(), tempFile(), souffle::AstTranslator::translateUnit(), and which().
Referenced by main().
{
     /* Time taking for overall runtime */
     auto souffle_start = std::chrono::high_resolution_clock::now();
     /* have all to do with command line arguments in its own scope, as these are accessible through the global
      * configuration only */
     try {
         std::stringstream header;
         header << "============================================================================" << std::endl;
         header << "souffle -- A datalog engine." << std::endl;
         header << "Usage: souffle [OPTION] FILE." << std::endl;
         header << "----------------------------------------------------------------------------" << std::endl;
         header << "Options:" << std::endl;
         std::stringstream footer;
         footer << "----------------------------------------------------------------------------" << std::endl;
         footer << "Version: " << PACKAGE_VERSION << "" << std::endl;
         footer << "----------------------------------------------------------------------------" << std::endl;
         footer << "Copyright (c) 2016-20 The Souffle Developers." << std::endl;
         footer << "Copyright (c) 2013-16 Oracle and/or its affiliates." << std::endl;
         footer << "All rights reserved." << std::endl;
         footer << "============================================================================" << std::endl;
         // command line options, the environment will be filled with the arguments passed to them, or
         // the empty string if they take none
         // main option, the datalog program itself, has an empty key
         std::vector<MainOption> options{{"", 0, "", "", false, ""},
                 {"fact-dir", 'F', "DIR", ".", false, "Specify directory for fact files."},
                 {"include-dir", 'I', "DIR", ".", true, "Specify directory for include files."},
                 {"output-dir", 'D', "DIR", ".", false,
                         "Specify directory for output files. If <DIR> is `-` then stdout is used."},
                 {"jobs", 'j', "N", "1", false,
                         "Run interpreter/compiler in parallel using N threads, N=auto for system "
                         "default."},
                 {"compile", 'c', "", "", false,
                         "Generate C++ source code, compile to a binary executable, then run this "
                         "executable."},
                 {"generate", 'g', "FILE", "", false,
                         "Generate C++ source code for the given Datalog program and write it to "
                         "<FILE>. If <FILE> is `-` then stdout is used."},
                 {"swig", 's', "LANG", "", false,
                         "Generate SWIG interface for given language. The values <LANG> accepts is java and "
                         "python. "},
                 {"library-dir", 'L', "DIR", "", true, "Specify directory for library files."},
                 {"libraries", 'l', "FILE", "", true, "Specify libraries."},
                 {"no-warn", 'w', "", "", false, "Disable warnings."},
                 {"magic-transform", 'm', "RELATIONS", "", false,
                         "Enable magic set transformation changes on the given relations, use '*' "
                         "for all."},
                 {"macro", 'M', "MACROS", "", false, "Set macro definitions for the pre-processor"},
                 {"disable-transformers", 'z', "TRANSFORMERS", "", false,
                         "Disable the given AST transformers."},
                 {"dl-program", 'o', "FILE", "", false,
                         "Generate C++ source code, written to <FILE>, and compile this to a "
                         "binary executable (without executing it)."},
                 {"live-profile", '\2', "", "", false, "Enable live profiling."},
                 {"profile", 'p', "FILE", "", false, "Enable profiling, and write profile data to <FILE>."},
                 {"profile-use", 'u', "FILE", "", false,
                         "Use profile log-file <FILE> for profile-guided optimization."},
                 {"debug-report", 'r', "FILE", "", false, "Write HTML debug report to <FILE>."},
                 {"pragma", 'P', "OPTIONS", "", false, "Set pragma options."},
                 {"provenance", 't', "[ none | explain | explore | subtreeHeights ]", "", false,
                         "Enable provenance instrumentation and interaction."},
                 {"verbose", 'v', "", "", false, "Verbose output."},
                 {"version", '\3', "", "", false, "Version."},
                 {"show", '\4',
                         "[ parse-errors | precedence-graph | scc-graph | transformed-datalog | "
                         "transformed-ram | type-analysis ]",
                         "", false, "Print selected program information."},
                 {"parse-errors", '\5', "", "", false, "Show parsing errors, if any, then exit."},
                 {"help", 'h', "", "", false, "Display this help message."}};
         Global::config().processArgs(argc, argv, header.str(), footer.str(), options);
         // ------ command line arguments -------------
         // Take in pragma options from the command line
         if (Global::config().has("pragma")) {
             std::vector<std::string> configOptions = splitString(Global::config().get("pragma"), ';');
             for (const std::string& option : configOptions) {
                 size_t splitPoint = option.find(':');
                 std::string optionName = option.substr(0, splitPoint);
                 std::string optionValue = (splitPoint == std::string::npos)
                                                   ? ""
                                                   : option.substr(splitPoint + 1, option.length());
                 if (!Global::config().has(optionName)) {
                     Global::config().set(optionName, optionValue);
                 }
             }
         }
         /* for the version option, if given print the version text then exit */
         if (Global::config().has("version")) {
             std::cout << "Souffle: " << PACKAGE_VERSION;
             std::cout << "(" << RAM_DOMAIN_SIZE << "bit Domains)";
             std::cout << std::endl;
             std::cout << "Copyright (c) 2016-19 The Souffle Developers." << std::endl;
             std::cout << "Copyright (c) 2013-16 Oracle and/or its affiliates." << std::endl;
             return 0;
         }
         Global::config().set("version", PACKAGE_VERSION);
         /* for the help option, if given simply print the help text then exit */
         if (!Global::config().has("") || Global::config().has("help")) {
             std::cout << Global::config().help();
             return 0;
         }
         /* check that datalog program exists */
         if (!existFile(Global::config().get(""))) {
             throw std::runtime_error("cannot open file " + std::string(Global::config().get("")));
         }
         /* for the jobs option, to determine the number of threads used */
 #ifdef _OPENMP
         if (isNumber(Global::config().get("jobs").c_str())) {
             if (std::stoi(Global::config().get("jobs")) < 1) {
                 throw std::runtime_error("-j/--jobs may only be set to 'auto' or an integer greater than 0.");
             }
         } else {
             if (!Global::config().has("jobs", "auto")) {
                 throw std::runtime_error("-j/--jobs may only be set to 'auto' or an integer greater than 0.");
             }
             Global::config().set("jobs", "0");
         }
 #else
         // Check that -j option has not been changed from the default
         if (Global::config().get("jobs") != "1") {
             std::cerr << "\nThis installation of Souffle does not support concurrent jobs.\n";
         }
 #endif
         /* if an output directory is given, check it exists */
         if (Global::config().has("output-dir") && !Global::config().has("output-dir", "-") &&
                 !existDir(Global::config().get("output-dir")) &&
                 !(Global::config().has("generate") ||
                         (Global::config().has("dl-program") && !Global::config().has("compile")))) {
             throw std::runtime_error(
                     "output directory " + Global::config().get("output-dir") + " does not exists");
         }
         /* collect all input directories for the c pre-processor */
         if (Global::config().has("include-dir")) {
             std::string currentInclude = "";
             std::string allIncludes = "";
             for (const char& ch : Global::config().get("include-dir")) {
                 if (ch == ' ') {
                     if (!existDir(currentInclude)) {
                         throw std::runtime_error("include directory " + currentInclude + " does not exists");
                     } else {
                         allIncludes += " -I";
                         allIncludes += currentInclude;
                         currentInclude = "";
                     }
                 } else {
                     currentInclude += ch;
                 }
             }
             allIncludes += " -I" + currentInclude;
             Global::config().set("include-dir", allIncludes);
         }
         /* collect all macro definitions for the pre-processor */
         if (Global::config().has("macro")) {
             std::string currentMacro = "";
             std::string allMacros = "";
             for (const char& ch : Global::config().get("macro")) {
                 if (ch == ' ') {
                     allMacros += " -D";
                     allMacros += currentMacro;
                     currentMacro = "";
                 } else {
                     currentMacro += ch;
                 }
             }
             allMacros += " -D" + currentMacro;
             Global::config().set("macro", allMacros);
         }
         /* turn on compilation of executables */
         if (Global::config().has("dl-program")) {
             Global::config().set("compile");
         }
         if (Global::config().has("live-profile") && !Global::config().has("profile")) {
             Global::config().set("profile");
         }
     } catch (std::exception& e) {
         std::cerr << e.what() << std::endl;
         exit(1);
     }
     /**
      * Ensure that code generation is enabled if using SWIG interface option.
      */
     if (Global::config().has("swig") && !Global::config().has("generate")) {
         Global::config().set("generate", simpleName(Global::config().get("")));
     }
     // ------ start souffle -------------
     std::string souffleExecutable = which(argv[0]);
     if (souffleExecutable.empty()) {
         throw std::runtime_error("failed to determine souffle executable path");
     }
     /* Create the pipe to establish a communication between cpp and souffle */
     std::string cmd = ::which("mcpp");
     if (!isExecutable(cmd)) {
         throw std::runtime_error("failed to locate mcpp pre-processor");
     }
     cmd += " -e utf8 -W0 " + Global::config().get("include-dir");
     if (Global::config().has("macro")) {
         cmd += " " + Global::config().get("macro");
     }
     // Add RamDomain size as a macro
     cmd += " -DRAM_DOMAIN_SIZE=" + std::to_string(RAM_DOMAIN_SIZE);
     cmd += " " + Global::config().get("");
     FILE* in = popen(cmd.c_str(), "r");
     /* Time taking for parsing */
     auto parser_start = std::chrono::high_resolution_clock::now();
     // ------- parse program -------------
     // parse file
     ErrorReport errReport(Global::config().has("no-warn"));
     DebugReport debugReport;
     std::unique_ptr<AstTranslationUnit> astTranslationUnit =
             ParserDriver::parseTranslationUnit("<stdin>", in, errReport, debugReport);
     // close input pipe
     int preprocessor_status = pclose(in);
     if (preprocessor_status == -1) {
         perror(nullptr);
         throw std::runtime_error("failed to close pre-processor pipe");
     }
     /* Report run-time of the parser if verbose flag is set */
     if (Global::config().has("verbose")) {
         auto parser_end = std::chrono::high_resolution_clock::now();
         std::cout << "Parse Time: " << std::chrono::duration<double>(parser_end - parser_start).count()
                   << "sec\n";
     }
     if (Global::config().get("show") == "parse-errors") {
         std::cout << astTranslationUnit->getErrorReport();
         return astTranslationUnit->getErrorReport().getNumErrors();
     }
     // ------- check for parse errors -------------
     if (astTranslationUnit->getErrorReport().getNumErrors() != 0) {
         std::cerr << astTranslationUnit->getErrorReport();
         std::cerr << std::to_string(astTranslationUnit->getErrorReport().getNumErrors()) +
                              " errors generated, evaluation aborted"
                   << std::endl;
         exit(1);
     }
     // ------- rewriting / optimizations -------------
     /* set up additional global options based on pragma declaratives */
     (std::make_unique<AstPragmaChecker>())->apply(*astTranslationUnit);
     /* construct the transformation pipeline */
     // Magic-Set pipeline
     auto magicPipeline = std::make_unique<ConditionalTransformer>(Global::config().has("magic-transform"),
             std::make_unique<PipelineTransformer>(std::make_unique<NormaliseConstraintsTransformer>(),
                     std::make_unique<MagicSetTransformer>(), std::make_unique<ResolveAliasesTransformer>(),
                     std::make_unique<RemoveRelationCopiesTransformer>(),
                     std::make_unique<RemoveEmptyRelationsTransformer>(),
                     std::make_unique<RemoveRedundantRelationsTransformer>()));
     // Equivalence pipeline
     auto equivalencePipeline =
             std::make_unique<PipelineTransformer>(std::make_unique<MinimiseProgramTransformer>(),
                     std::make_unique<RemoveRelationCopiesTransformer>(),
                     std::make_unique<RemoveEmptyRelationsTransformer>(),
                     std::make_unique<RemoveRedundantRelationsTransformer>());
     // Partitioning pipeline
     auto partitionPipeline =
             std::make_unique<PipelineTransformer>(std::make_unique<NameUnnamedVariablesTransformer>(),
                     std::make_unique<PartitionBodyLiteralsTransformer>(),
                     std::make_unique<ReplaceSingletonVariablesTransformer>());
     // Provenance pipeline
     auto provenancePipeline = std::make_unique<PipelineTransformer>(std::make_unique<ConditionalTransformer>(
             Global::config().has("provenance"), std::make_unique<ProvenanceTransformer>()));
     // Main pipeline
     auto pipeline = std::make_unique<PipelineTransformer>(std::make_unique<AstComponentChecker>(),
             std::make_unique<ComponentInstantiationTransformer>(),
             std::make_unique<UniqueAggregationVariablesTransformer>(),
             std::make_unique<AstUserDefinedFunctorsTransformer>(),
             std::make_unique<FixpointTransformer>(
                     std::make_unique<PipelineTransformer>(std::make_unique<ResolveAnonymousRecordsAliases>(),
                             std::make_unique<FoldAnonymousRecords>())),
             std::make_unique<PolymorphicObjectsTransformer>(), std::make_unique<AstSemanticChecker>(),
             std::make_unique<RemoveTypecastsTransformer>(),
             std::make_unique<RemoveBooleanConstraintsTransformer>(),
             std::make_unique<ResolveAliasesTransformer>(), std::make_unique<MinimiseProgramTransformer>(),
             std::make_unique<InlineRelationsTransformer>(), std::make_unique<ResolveAliasesTransformer>(),
             std::make_unique<RemoveRedundantRelationsTransformer>(),
             std::make_unique<RemoveRelationCopiesTransformer>(),
             std::make_unique<RemoveEmptyRelationsTransformer>(),
             std::make_unique<ReplaceSingletonVariablesTransformer>(),
             std::make_unique<FixpointTransformer>(
                     std::make_unique<PipelineTransformer>(std::make_unique<ReduceExistentialsTransformer>(),
                             std::make_unique<RemoveRedundantRelationsTransformer>())),
             std::make_unique<RemoveRelationCopiesTransformer>(), std::move(partitionPipeline),
             std::make_unique<FixpointTransformer>(std::make_unique<MinimiseProgramTransformer>()),
             std::make_unique<RemoveRelationCopiesTransformer>(),
             std::make_unique<ReorderLiteralsTransformer>(),
             std::make_unique<PipelineTransformer>(std::make_unique<ResolveAliasesTransformer>(),
                     std::make_unique<MaterializeAggregationQueriesTransformer>()),
             std::make_unique<RemoveRedundantSumsTransformer>(),
             std::make_unique<RemoveEmptyRelationsTransformer>(),
             std::make_unique<ReorderLiteralsTransformer>(), std::move(magicPipeline),
             std::make_unique<AstExecutionPlanChecker>(), std::move(provenancePipeline));
     // Disable unwanted transformations
     if (Global::config().has("disable-transformers")) {
         std::vector<std::string> givenTransformers =
                 splitString(Global::config().get("disable-transformers"), ',');
         pipeline->disableTransformers(
                 std::set<std::string>(givenTransformers.begin(), givenTransformers.end()));
     }
     // Set up the debug report if necessary
     if (Global::config().has("debug-report")) {
         auto parser_end = std::chrono::high_resolution_clock::now();
         std::stringstream ss;
         // Add current time
         std::time_t time = std::time(nullptr);
         ss << "Executed at ";
         ss << std::put_time(std::localtime(&time), "%F %T") << "\n";
         // Add config
         ss << "(\n";
         ss << join(Global::config().data(), ",\n", [](std::ostream& out, const auto& arg) {
             out << "  \"" << arg.first << "\" -> \"" << arg.second << '"';
         });
         ss << "\n)";
         debugReport.addSection("Configuration", "Configuration", ss.str());
         // Add parsing runtime
         std::string runtimeStr =
                 "(" + std::to_string(std::chrono::duration<double>(parser_end - parser_start).count()) + "s)";
         debugReport.addSection("Parsing", "Parsing " + runtimeStr, "");
         pipeline->setDebugReport();
     }
     // Toggle pipeline verbosity
     pipeline->setVerbosity(Global::config().has("verbose"));
     // Apply all the transformations
     pipeline->apply(*astTranslationUnit);
     if (Global::config().has("show")) {
         // Output the transformed datalog and return
         if (Global::config().get("show") == "transformed-datalog") {
             std::cout << *astTranslationUnit->getProgram() << std::endl;
             return 0;
         }
         // Output the precedence graph in graphviz dot format and return
         if (Global::config().get("show") == "precedence-graph") {
             astTranslationUnit->getAnalysis<PrecedenceGraph>()->print(std::cout);
             std::cout << std::endl;
             return 0;
         }
         // Output the scc graph in graphviz dot format and return
         if (Global::config().get("show") == "scc-graph") {
             astTranslationUnit->getAnalysis<SCCGraph>()->print(std::cout);
             std::cout << std::endl;
             return 0;
         }
         // Output the type analysis
         if (Global::config().get("show") == "type-analysis") {
             astTranslationUnit->getAnalysis<TypeAnalysis>()->print(std::cout);
             std::cout << std::endl;
             return 0;
         }
     }
     // ------- execution -------------
     /* translate AST to RAM */
     debugReport.startSection();
     std::unique_ptr<RamTranslationUnit> ramTranslationUnit =
             AstTranslator().translateUnit(*astTranslationUnit);
     debugReport.endSection("ast-to-ram", "Translate AST to RAM");
     std::unique_ptr<RamTransformer> ramTransform = std::make_unique<RamTransformerSequence>(
             std::make_unique<RamLoopTransformer>(
                     std::make_unique<RamTransformerSequence>(std::make_unique<ExpandFilterTransformer>(),
                             std::make_unique<HoistConditionsTransformer>(),
                             std::make_unique<MakeIndexTransformer>())),
             std::make_unique<IfConversionTransformer>(), std::make_unique<ChoiceConversionTransformer>(),
             std::make_unique<CollapseFiltersTransformer>(), std::make_unique<TupleIdTransformer>(),
             std::make_unique<RamLoopTransformer>(std::make_unique<RamTransformerSequence>(
                     std::make_unique<HoistAggregateTransformer>(), std::make_unique<TupleIdTransformer>())),
             std::make_unique<ExpandFilterTransformer>(), std::make_unique<HoistConditionsTransformer>(),
             std::make_unique<CollapseFiltersTransformer>(),
             std::make_unique<EliminateDuplicatesTransformer>(),
             std::make_unique<ReorderConditionsTransformer>(),
             std::make_unique<RamLoopTransformer>(std::make_unique<ReorderFilterBreak>()),
             std::make_unique<RamConditionalTransformer>(
                     // job count of 0 means all cores are used.
                     []() -> bool { return std::stoi(Global::config().get("jobs")) != 1; },
                     std::make_unique<ParallelTransformer>()),
             std::make_unique<ReportIndexTransformer>());
     ramTransform->apply(*ramTranslationUnit);
     if (ramTranslationUnit->getErrorReport().getNumIssues() != 0) {
         std::cerr << ramTranslationUnit->getErrorReport();
     }
     // Output the transformed RAM program and return
     if (Global::config().get("show") == "transformed-ram") {
         std::cout << ramTranslationUnit->getProgram();
         return 0;
     }
     try {
         if (!Global::config().has("compile") && !Global::config().has("dl-program") &&
                 !Global::config().has("generate") && !Global::config().has("swig")) {
             // ------- interpreter -------------
             std::thread profiler;
             // Start up profiler if needed
             if (Global::config().has("live-profile") && !Global::config().has("compile")) {
                 profiler = std::thread([]() { profile::Tui().runProf(); });
             }
             // configure and execute interpreter
             std::unique_ptr<InterpreterEngine> interpreter(
                     std::make_unique<InterpreterEngine>(*ramTranslationUnit));
             interpreter->executeMain();
             // If the profiler was started, join back here once it exits.
             if (profiler.joinable()) {
                 profiler.join();
             }
             if (Global::config().has("provenance")) {
                 // Test for bugged combination of provenance, interpreted souffle, and concurrency
                 if (Global::config().get("jobs") != "1") {
                     throw std::runtime_error("Provenance is not supported with parallel interpreted mode");
                 }
                 // only run explain interface if interpreted
                 InterpreterProgInterface interface(*interpreter);
                 if (Global::config().get("provenance") == "explain" ||
                         Global::config().get("provenance") == "subtreeHeights") {
                     explain(interface, false, Global::config().get("provenance") == "subtreeHeights");
                 } else if (Global::config().get("provenance") == "explore") {
                     explain(interface, true, false);
                 }
             }
         } else {
             // ------- compiler -------------
             std::unique_ptr<Synthesiser> synthesiser = std::make_unique<Synthesiser>(*ramTranslationUnit);
             // Find the base filename for code generation and execution
             std::string baseFilename;
             if (Global::config().has("dl-program")) {
                 baseFilename = Global::config().get("dl-program");
             } else if (Global::config().has("generate")) {
                 baseFilename = Global::config().get("generate");
                 // trim .cpp extension if it exists
                 if (baseFilename.size() >= 4 && baseFilename.substr(baseFilename.size() - 4) == ".cpp") {
                     baseFilename = baseFilename.substr(0, baseFilename.size() - 4);
                 }
             } else {
                 baseFilename = tempFile();
             }
             if (baseName(baseFilename) == "/" || baseName(baseFilename) == ".") {
                 baseFilename = tempFile();
             }
             std::string baseIdentifier = identifier(simpleName(baseFilename));
             std::string sourceFilename = baseFilename + ".cpp";
             bool withSharedLibrary;
             const bool emitToStdOut = Global::config().has("generate", "-");
             if (emitToStdOut)
                 synthesiser->generateCode(std::cout, baseIdentifier, withSharedLibrary);
             else {
                 std::ofstream os{sourceFilename};
                 synthesiser->generateCode(os, baseIdentifier, withSharedLibrary);
             }
             if (withSharedLibrary) {
                 if (!Global::config().has("libraries")) {
                     Global::config().set("libraries", "functors");
                 }
                 if (!Global::config().has("library-dir")) {
                     Global::config().set("library-dir", ".");
                 }
             }
             auto findCompileCmd = [&] {
                 auto cmd = ::findTool("souffle-compile", souffleExecutable, ".");
                 /* Fail if a souffle-compile executable is not found */
                 if (!isExecutable(cmd)) {
                     throw std::runtime_error("failed to locate souffle-compile");
                 }
                 return cmd;
             };
             if (Global::config().has("swig")) {
                 auto compileCmd = findCompileCmd() + " -s " + Global::config().get("swig") + " ";
                 compileToBinary(compileCmd, sourceFilename);
             } else if (Global::config().has("compile")) {
                 auto start = std::chrono::high_resolution_clock::now();
                 compileToBinary(findCompileCmd(), sourceFilename);
                 /* Report overall run-time in verbose mode */
                 if (Global::config().has("verbose")) {
                     auto end = std::chrono::high_resolution_clock::now();
                     std::cout << "Compilation Time: " << std::chrono::duration<double>(end - start).count()
                               << "sec\n";
                 }
                 // run compiled C++ program if requested.
                 if (!Global::config().has("dl-program") && !Global::config().has("swig")) {
                     executeBinary(baseFilename);
                 }
             }
         }
     } catch (std::exception& e) {
         std::cerr << e.what() << std::endl;
         std::exit(1);
     }
     /* Report overall run-time in verbose mode */
     if (Global::config().has("verbose")) {
         auto souffle_end = std::chrono::high_resolution_clock::now();
         std::cout << "Total Time: " << std::chrono::duration<double>(souffle_end - souffle_start).count()
                   << "sec\n";
     }
     return 0;
 }
make_range()
template<typename Iter > range<Iter> souffle::make_range (const Iter & a, const Iter & b)
A utility function enabling the construction of ranges without explicitly specifying the iterator type.
Template Parameters
Iter .. the iterator type
Parameters
a .. the lower boundary
b .. the upper boundary
Definition at line 456 of file Util.h.
References souffle::range< Iter >::a, and souffle::range< Iter >::b.
Referenced by souffle::EquivalenceRelation< t_tuple< 2 > >::getBoundaries(), souffle::Trie< Arity >::getBoundaries(), souffle::Trie< 1u >::getBoundaries(), souffle::EquivalenceRelation< t_tuple< 2 > >::partition(), souffle::Trie< Arity >::partition(), and souffle::Trie< 1u >::partition().
{
     return range<Iter>(a, b);
 }
makeInfoRelation()
std::unique_ptr<AstRelation> souffle::makeInfoRelation (AstClause & originalClause, size_t originalClauseNum, AstTranslationUnit & translationUnit)
Definition at line 65 of file ProvenanceTransformer.cpp.
References souffle::AstProgram::addClause(), souffle::AstAtom::getArguments(), souffle::AstClause::getBodyLiterals(), souffle::AstClause::getHead(), souffle::AstTranslationUnit::getProgram(), souffle::AstAtom::getQualifiedName(), i, identifierToString(), INFO, join(), makeRelationName(), souffle::AstClause::setHead(), souffle::profile::ss, and toBinaryConstraintSymbol().
Referenced by souffle::ProvenanceTransformer::transformMaxHeight(), and souffle::ProvenanceTransformer::transformSubtreeHeights().
{
     AstQualifiedName name =
             makeRelationName(originalClause.getHead()->getQualifiedName(), "@info", originalClauseNum);
     // initialise info relation
     auto infoRelation = new AstRelation();
     infoRelation->setQualifiedName(name);
     // set qualifier to INFO_RELATION
     infoRelation->setRepresentation(RelationRepresentation::INFO);
     // create new clause containing a single fact
     auto infoClause = new AstClause();
     auto infoClauseHead = new AstAtom();
     infoClauseHead->setQualifiedName(name);
     // (darth_tytus): Can this be unsigned?
     infoRelation->addAttribute(std::make_unique<AstAttribute>("clause_num", AstQualifiedName("number")));
     infoClauseHead->addArgument(std::make_unique<AstNumericConstant>(originalClauseNum));
     // add head relation as meta info
     std::vector<std::string> headVariables;
     // a method to stringify an AstArgument, translating functors and aggregates
     // keep a global counter of functor and aggregate numbers, which increment for each unique
     // functor/aggregate
     int functorNumber = 0;
     int aggregateNumber = 0;
     auto getArgInfo = [&](AstArgument* arg) -> std::string {
         if (auto* var = dynamic_cast<AstVariable*>(arg)) {
             std::stringstream varName;
             varName << *var;
             return varName.str();
         } else if (auto* constant = dynamic_cast<AstConstant*>(arg)) {
             std::stringstream constName;
             constName << *constant;
             return constName.str();
         } else if (nullptr != dynamic_cast<AstUnnamedVariable*>(arg)) {
             return "_";
         } else if (nullptr != dynamic_cast<AstFunctor*>(arg)) {
             auto functorName = "functor_" + std::to_string(functorNumber);
             functorNumber++;
             return functorName;
         } else if (nullptr != dynamic_cast<AstAggregator*>(arg)) {
             auto aggregateName = "agg_" + std::to_string(aggregateNumber);
             aggregateNumber++;
             return aggregateName;
         }
         assert(false && "Unhandled argument type");
     };
     // add head arguments
     for (auto& arg : originalClause.getHead()->getArguments()) {
         headVariables.push_back(getArgInfo(arg));
     }
     // join variables in the head with commas
     std::stringstream headVariableString;
     headVariableString << join(headVariables, ",");
     // add an attribute to infoRelation for the head of clause
     infoRelation->addAttribute(
             std::make_unique<AstAttribute>(std::string("head_vars"), AstQualifiedName("symbol")));
     infoClauseHead->addArgument(std::make_unique<AstStringConstant>(headVariableString.str()));
     // visit all body literals and add to info clause head
     for (size_t i = 0; i < originalClause.getBodyLiterals().size(); i++) {
         auto lit = originalClause.getBodyLiterals()[i];
         const AstAtom* atom = nullptr;
         if (dynamic_cast<AstAtom*>(lit) != nullptr) {
             atom = static_cast<AstAtom*>(lit);
         } else if (dynamic_cast<AstNegation*>(lit) != nullptr) {
             atom = static_cast<AstNegation*>(lit)->getAtom();
         } else if (dynamic_cast<AstProvenanceNegation*>(lit) != nullptr) {
             atom = static_cast<AstProvenanceNegation*>(lit)->getAtom();
         }
         // add an attribute for atoms and binary constraints
         if (atom != nullptr || dynamic_cast<AstBinaryConstraint*>(lit) != nullptr) {
             infoRelation->addAttribute(std::make_unique<AstAttribute>(
                     std::string("rel_") + std::to_string(i), AstQualifiedName("symbol")));
         }
         if (atom != nullptr) {
             std::string relName = identifierToString(atom->getQualifiedName());
             // for an atom, add its name and variables (converting aggregates to variables)
             if (dynamic_cast<AstAtom*>(lit) != nullptr) {
                 std::string atomDescription = relName;
                 for (auto& arg : atom->getArguments()) {
                     atomDescription.append("," + getArgInfo(arg));
                 }
                 infoClauseHead->addArgument(std::make_unique<AstStringConstant>(atomDescription));
                 // for a negation, add a marker with the relation name
             } else if (dynamic_cast<AstNegation*>(lit) != nullptr) {
                 infoClauseHead->addArgument(std::make_unique<AstStringConstant>("!" + relName));
             }
             // for a constraint, add the constraint symbol and LHS and RHS
         } else if (auto con = dynamic_cast<AstBinaryConstraint*>(lit)) {
             std::string constraintDescription = toBinaryConstraintSymbol(con->getOperator());
             constraintDescription.append("," + getArgInfo(con->getLHS()));
             constraintDescription.append("," + getArgInfo(con->getRHS()));
             infoClauseHead->addArgument(std::make_unique<AstStringConstant>(constraintDescription));
         }
     }
     // generate and add clause representation
     std::stringstream ss;
     ss << originalClause;
     infoRelation->addAttribute(std::make_unique<AstAttribute>("clause_repr", AstQualifiedName("symbol")));
     infoClauseHead->addArgument(std::make_unique<AstStringConstant>(ss.str()));
     // set clause head and add clause to info relation
     infoClause->setHead(std::unique_ptr<AstAtom>(infoClauseHead));
     translationUnit.getProgram()->addClause(std::unique_ptr<AstClause>(infoClause));
     return std::unique_ptr<AstRelation>(infoRelation);
 }
makeLambdaAstMapper()
template<typename Lambda > detail::LambdaNodeMapper<Lambda> souffle::makeLambdaAstMapper (const Lambda & lambda)
Creates a node mapper based on a corresponding lambda expression.
Definition at line 155 of file AstNode.h.
Referenced by souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), and souffle::ProvenanceTransformer::transformSubtreeHeights().
{
     return detail::LambdaNodeMapper<Lambda>(lambda);
 }
makeLambdaRamMapper()
template<typename Lambda > LambdaRamNodeMapper<Lambda> souffle::makeLambdaRamMapper (const Lambda & lambda)
Creates a node mapper based on a corresponding lambda expression.
Definition at line 87 of file RamNode.h.
Referenced by souffle::RamProgram::clone(), souffle::CollapseFiltersTransformer::collapseFilters(), souffle::IfConversionTransformer::convertIndexScans(), souffle::ChoiceConversionTransformer::convertScans(), souffle::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::ExpandFilterTransformer::expandFilters(), souffle::HoistAggregateTransformer::hoistAggregate(), souffle::HoistConditionsTransformer::hoistConditions(), souffle::MakeIndexTransformer::makeIndex(), souffle::ParallelTransformer::parallelizeOperations(), souffle::ReorderConditionsTransformer::reorderConditions(), souffle::ReorderFilterBreak::reorderFilterBreak(), souffle::TupleIdTransformer::reorderOperations(), and souffle::RamNode::rewrite().
{
     return LambdaRamNodeMapper<Lambda>(lambda);
 }
makeRelationName()
AstQualifiedName souffle::makeRelationName (const AstQualifiedName & orig, const std::string & type, int num = -1) inline
Definition at line 54 of file ProvenanceTransformer.cpp.
References souffle::AstQualifiedName::append(), and identifierToString().
Referenced by makeInfoRelation().
{
     AstQualifiedName newName(identifierToString(orig));
     newName.append(type);
     if (num != -1) {
         newName.append((const std::string&)std::to_string(num));
     }
     return newName;
 }
nameInlinedUnderscores()
void souffle::nameInlinedUnderscores (AstProgram & program)
Removes all underscores in all atoms of inlined relations.
Definition at line 124 of file InlineRelationsTransformer.cpp.
References souffle::AstProgram::apply(), souffle::AstProgram::getRelations(), INLINE, and replaceUnderscores().
Referenced by souffle::InlineRelationsTransformer::transform().
{
     struct M : public AstNodeMapper {
         const std::set<AstQualifiedName> inlinedRelations;
         bool replaceUnderscores;
         M(std::set<AstQualifiedName> inlinedRelations, bool replaceUnderscores)
                 : inlinedRelations(std::move(inlinedRelations)), replaceUnderscores(replaceUnderscores) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             static int underscoreCount = 0;
             if (!replaceUnderscores) {
                 // Check if we should start replacing underscores for this node's subnodes
                 if (auto* atom = dynamic_cast<AstAtom*>(node.get())) {
                     if (inlinedRelations.find(atom->getQualifiedName()) != inlinedRelations.end()) {
                         // Atom associated with an inlined relation, so replace the underscores
                         // in all of its subnodes with named variables.
                         M replace(inlinedRelations, true);
                         node->apply(replace);
                         return node;
                     }
                 }
             } else if (dynamic_cast<AstUnnamedVariable*>(node.get()) != nullptr) {
                 // Give a unique name to the underscored variable
                 // TODO (azreika): need a more consistent way of handling internally generated variables in
                 // general
                 std::stringstream newVarName;
                 newVarName << "<underscore_" << underscoreCount++ << ">";
                 return std::make_unique<AstVariable>(newVarName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     // Store the names of all relations to be inlined
     std::set<AstQualifiedName> inlinedRelations;
     for (AstRelation* rel : program.getRelations()) {
         if (rel->hasQualifier(RelationQualifier::INLINE)) {
             inlinedRelations.insert(rel->getQualifiedName());
         }
     }
     // Apply the renaming procedure to the entire program
     M update(inlinedRelations, false);
     program.apply(update);
 }
negateConstraint()
void souffle::negateConstraint (AstConstraint * constraint)
Negate an ast constraint.
Parameters
constraint constraint that will be negated
Definition at line 222 of file AstUtils.cpp.
References negatedConstraintOp().
Referenced by getBodyLiterals(), negateLiteral(), and souffle::RuleBody::toClauseBodies().
{
     assert(nullptr != dynamic_cast<AstConstraint*>(constraint) && "not a constraint object");
     if (auto* bcstr = dynamic_cast<AstBooleanConstraint*>(constraint)) {
         bcstr->set(!bcstr->isTrue());
     } else if (auto* cstr = dynamic_cast<AstBinaryConstraint*>(constraint)) {
         cstr->setOperator(souffle::negatedConstraintOp(cstr->getOperator()));
     } else {
         assert(false && "Unknown ast-constraint type");
     }
 }
negatedConstraintOp()
BinaryConstraintOp souffle::negatedConstraintOp (const BinaryConstraintOp op) inline
Negated Constraint Operator Each operator requires a negated operator which is necessary for the expansion of complex rule bodies with disjunction and negation.
Definition at line 149 of file BinaryConstraintOps.h.
References CONTAINS, EQ, FEQ, FGE, FGT, FLE, FLT, FNE, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, SGE, SGT, SLE, SLT, UGE, UGT, ULE, and ULT.
Referenced by souffle::FoldAnonymousRecords::isValidRecordConstraint(), and negateConstraint().
{
     switch (op) {
         case BinaryConstraintOp::EQ:
             return BinaryConstraintOp::NE;
         case BinaryConstraintOp::FEQ:
             return BinaryConstraintOp::FNE;
         case BinaryConstraintOp::NE:
             return BinaryConstraintOp::EQ;
         case BinaryConstraintOp::FNE:
             return BinaryConstraintOp::FEQ;
         case BinaryConstraintOp::LT:
             return BinaryConstraintOp::GE;
         case BinaryConstraintOp::ULT:
             return BinaryConstraintOp::UGE;
         case BinaryConstraintOp::FLT:
             return BinaryConstraintOp::FGE;
         case BinaryConstraintOp::SLT:
             return BinaryConstraintOp::SGE;
         case BinaryConstraintOp::LE:
             return BinaryConstraintOp::GT;
         case BinaryConstraintOp::ULE:
             return BinaryConstraintOp::UGT;
         case BinaryConstraintOp::FLE:
             return BinaryConstraintOp::FGT;
         case BinaryConstraintOp::SLE:
             return BinaryConstraintOp::SGT;
         case BinaryConstraintOp::GE:
             return BinaryConstraintOp::LT;
         case BinaryConstraintOp::UGE:
             return BinaryConstraintOp::ULT;
         case BinaryConstraintOp::FGE:
             return BinaryConstraintOp::FLT;
         case BinaryConstraintOp::SGE:
             return BinaryConstraintOp::SLT;
         case BinaryConstraintOp::GT:
             return BinaryConstraintOp::LE;
         case BinaryConstraintOp::UGT:
             return BinaryConstraintOp::ULE;
         case BinaryConstraintOp::FGT:
             return BinaryConstraintOp::FLE;
         case BinaryConstraintOp::SGT:
             return BinaryConstraintOp::SLE;
         case BinaryConstraintOp::MATCH:
             return BinaryConstraintOp::NOT_MATCH;
         case BinaryConstraintOp::NOT_MATCH:
             return BinaryConstraintOp::MATCH;
         case BinaryConstraintOp::CONTAINS:
             return BinaryConstraintOp::NOT_CONTAINS;
         case BinaryConstraintOp::NOT_CONTAINS:
             return BinaryConstraintOp::CONTAINS;
     }
     assert(false && "Unsupported Operator!");
     exit(EXIT_FAILURE);
 }
negateLiteral()
AstLiteral* souffle::negateLiteral (AstLiteral * lit)
Returns the negated version of a given literal.
Definition at line 345 of file InlineRelationsTransformer.cpp.
References souffle::AstConstraint::clone(), souffle::AstAtom::clone(), and negateConstraint().
Referenced by combineNegatedLiterals().
{
     if (auto* atom = dynamic_cast<AstAtom*>(lit)) {
         auto* neg = new AstNegation(std::unique_ptr<AstAtom>(atom->clone()));
         return neg;
     } else if (auto* neg = dynamic_cast<AstNegation*>(lit)) {
         AstAtom* atom = neg->getAtom()->clone();
         return atom;
     } else if (auto* cons = dynamic_cast<AstConstraint*>(lit)) {
         AstConstraint* newCons = cons->clone();
         negateConstraint(newCons);
         return newCons;
     } else {
         assert(false && "Unsupported literal type!");
         return nullptr;
     }
 }
nextSrcLoc()
SrcLocation souffle::nextSrcLoc (SrcLocation orig)
Definition at line 176 of file MagicSet.cpp.
References souffle::SrcLocation::Point::column, souffle::SrcLocation::end, souffle::SrcLocation::filenames, souffle::SrcLocation::Point::line, and souffle::SrcLocation::start.
Referenced by createNewRelation(), separateDBs(), and souffle::MagicSetTransformer::transform().
{
     static int pos = 0;
     pos += 1;
     SrcLocation newLoc;
     newLoc.filenames = orig.filenames;
     if (orig.filenames.empty()) {
         newLoc.filenames.emplace_back("[MAGIC_FILE]");
     } else {
         newLoc.filenames.back() = orig.filenames.back() + "[MAGIC_FILE]";
     }
     newLoc.start.line = pos;
     newLoc.end.line = pos;
     newLoc.start.column = 0;
     newLoc.end.column = 1;
     return newLoc;
 }
none_of()
template<typename Container , typename UnaryPredicate > bool souffle::none_of (const Container & c, UnaryPredicate p)
A generic test checking whether all elements within a container satisfy a certain predicate.
Parameters
c the container
p the predicate
Returns
true if for all elements x in c the predicate p(x) is true, false otherwise; for empty containers the result is always true
Definition at line 1024 of file Util.h.
{
     return std::none_of(c.begin(), c.end(), p);
 }
normaliseInlinedHeads()
void souffle::normaliseInlinedHeads (AstProgram & program)
Replace constants in the head of inlined clauses with (constrained) variables.
Definition at line 68 of file InlineRelationsTransformer.cpp.
References souffle::AstProgram::addClause(), EQ, FEQ, souffle::AstNumericConstant::Float, getClauses(), souffle::AstProgram::getRelations(), INLINE, and souffle::AstProgram::removeClause().
Referenced by souffle::InlineRelationsTransformer::transform().
{
     static int newVarCount = 0;
     // Go through the clauses of all inlined relations
     for (AstRelation* rel : program.getRelations()) {
         if (!rel->hasQualifier(RelationQualifier::INLINE)) {
             continue;
         }
         for (AstClause* clause : getClauses(program, *rel)) {
             // Set up the new clause with an empty body and no arguments in the head
             auto newClause = std::make_unique<AstClause>();
             newClause->setSrcLoc(clause->getSrcLoc());
             auto clauseHead = std::make_unique<AstAtom>(clause->getHead()->getQualifiedName());
             // Add in everything in the original body
             for (AstLiteral* lit : clause->getBodyLiterals()) {
                 newClause->addToBody(std::unique_ptr<AstLiteral>(lit->clone()));
             }
             // Set up the head arguments in the new clause
             for (AstArgument* arg : clause->getHead()->getArguments()) {
                 if (auto* constant = dynamic_cast<AstConstant*>(arg)) {
                     // Found a constant in the head, so replace it with a variable
                     std::stringstream newVar;
                     newVar << "<new_var_" << newVarCount++ << ">";
                     clauseHead->addArgument(std::make_unique<AstVariable>(newVar.str()));
                     auto* const c_num = dynamic_cast<const AstNumericConstant*>(constant);
                     assert((!c_num || c_num->getType()) && "numeric constant wasn't bound to a type");
                     auto opEq = c_num && *c_num->getType() == AstNumericConstant::Type::Float
                                         ? BinaryConstraintOp::FEQ
                                         : BinaryConstraintOp::EQ;
                     // Add a body constraint to set the variable's value to be the original constant
                     newClause->addToBody(std::make_unique<AstBinaryConstraint>(opEq,
                             std::make_unique<AstVariable>(newVar.str()),
                             std::unique_ptr<AstArgument>(constant->clone())));
                 } else {
                     // Already a variable
                     clauseHead->addArgument(std::unique_ptr<AstArgument>(arg->clone()));
                 }
             }
             newClause->setHead(std::move(clauseHead));
             // Replace the old clause with this one
             program.addClause(std::move(newClause));
             program.removeClause(clause);
         }
     }
 }
now()
time_point souffle::now () inline
Definition at line 1037 of file Util.h.
Referenced by souffle::RamTransformer::apply(), souffle::MetaTransformer::applySubtransformer(), main(), souffle::ProfileEventSingleton::makeTimeEvent(), souffle::ProfileEventSingleton::makeUtilisationEvent(), souffle::ExplainProvenanceImpl::measureRelation(), souffle::profile::Reader::processFile(), souffle::DebugReporter::transform(), souffle::AstTranslator::translateUnit(), souffle::profile::Tui::Tui(), and souffle::Logger::~Logger().
{
     return std::chrono::high_resolution_clock::now();
 }
numBoundArguments()
unsigned int souffle::numBoundArguments (const AstAtom * atom, const std::set< std::string > & boundVariables)
Counts the number of bound arguments in a given atom.
Definition at line 49 of file ReorderLiteralsTransformer.cpp.
References souffle::AstAtom::getArguments(), souffle::AstVariable::getName(), and visitDepthFirst().
Referenced by getSipsFunction(), and souffle::ReorderLiteralsTransformer::transform().
{
     int count = 0;
     for (const AstArgument* arg : atom->getArguments()) {
         // argument is bound iff all contained variables are bound
         bool isBound = true;
         visitDepthFirst(*arg, [&](const AstVariable& var) {
             if (boundVariables.find(var.getName()) == boundVariables.end()) {
                 // found an unbound variable, so argument is unbound
                 isBound = false;
             }
         });
         if (isBound) {
             count++;
         }
     }
     return count;
 }
operator+()
AstQualifiedName souffle::operator+ (const std::string & name, const AstQualifiedName & id) inline
Definition at line 100 of file AstQualifiedName.h.
References souffle::AstQualifiedName::prepend().
{
     AstQualifiedName res = id;
     res.prepend(name);
     return res;
 }
operator<<() [1/7]
std::ostream& souffle::operator<< (std::ostream & out, TupleRef ref)
Definition at line 26 of file InterpreterIndex.cpp.
References i, and souffle::TupleRef::size().
{
     out << "[";
     for (std::size_t i = 0; i < ref.size(); i++) {
         if (i > 0) {
             out << ',';
         }
         out << ref[i];
     }
     return out << "]";
 }
operator<<() [2/7]
std::ostream& souffle::operator<< (std::ostream & os, TypeAttribute T) inline
Definition at line 38 of file RamTypes.h.
References Float, Record, Signed, Symbol, and Unsigned.
{
     switch (T) {
         case TypeAttribute::Symbol:
             os << "TypeAttribute::Symbol";
             break;
         case TypeAttribute::Signed:
             os << "TypeAttribute::Signed";
             break;
         case TypeAttribute::Float:
             os << "TypeAttribute::Float";
             break;
         case TypeAttribute::Unsigned:
             os << "TypeAttribute::Unsigned";
             break;
         case TypeAttribute::Record:
             os << "TypeAttribute::Record";
     }
     return os;
 }
operator<<() [3/7]
std::ostream& souffle::operator<< (std::ostream & out, const Order & order)
Definition at line 80 of file InterpreterIndex.cpp.
References join(), and souffle::Order::order.
{
     return out << "[" << join(order.order) << "]";
 }
operator<<() [4/7]
std::ostream& souffle::operator<< (std::ostream & os, RelationQualifier qualifier) inline
Definition at line 122 of file RelationTag.h.
References INLINE, INPUT, OUTPUT, OVERRIDABLE, PRINTSIZE, and SUPPRESSED.
{
     switch (qualifier) {
         case RelationQualifier::INPUT:
             os << "input";
             break;
         case RelationQualifier::OUTPUT:
             os << "output";
             break;
         case RelationQualifier::PRINTSIZE:
             os << "printsize";
             break;
         case RelationQualifier::OVERRIDABLE:
             os << "overridable";
             break;
         case RelationQualifier::INLINE:
             os << "inline";
             break;
         case RelationQualifier::SUPPRESSED:
             os << "suppressed";
             break;
         default:
             assert(false && "unhandled relation qualifier");
     }
     return os;
 }
operator<<() [5/7]
std::ostream& souffle::operator<< (std::ostream & out, const RuleBody & body)
Definition at line 137 of file AstParserUtils.cpp.
References souffle::RuleBody::dnf, and join().
Referenced by souffle::Order::getOrder(), and souffle::TupleRef::operator==().
{
     return out << join(body.dnf, ";", [](std::ostream& out, const RuleBody::clause& cur) {
         out << join(cur, ",", [](std::ostream& out, const RuleBody::literal& l) {
             if (l.negated) {
                 out << "!";
             }
             out << *l.atom;
         });
     });
 }
operator<<() [6/7]
std::ostream& souffle::operator<< (std::ostream & os, RelationRepresentation representation) inline
Definition at line 149 of file RelationTag.h.
References BRIE, BTREE, DEFAULT, EQREL, and INFO.
{
     switch (representation) {
         case RelationRepresentation::BTREE:
             os << "btree";
             break;
         case RelationRepresentation::BRIE:
             os << "brie";
             break;
         case RelationRepresentation::EQREL:
             os << "eqrel";
             break;
         case RelationRepresentation::INFO:
             os << "info";
             break;
         case RelationRepresentation::DEFAULT:
         default:
             break;
     }
     return os;
 }
operator<<() [7/7]
template<typename T , unsigned size> std::ostream& souffle::operator<< (std::ostream & out, const LRUCache< T, size > & cache)
Definition at line 1502 of file Util.h.
{
     bool first = true;
     cache.forEachInOrder([&](const T& val) {
         if (!first) {
             out << ",";
         }
         first = false;
         out << val;
         return false;
     });
     return out;
 }
pack()
template<std::size_t Arity> RamDomain souffle::pack (RecordTable & recordTab, Tuple< RamDomain, Arity > tuple) inline
helper to convert tuple to record reference for the synthesiser
Definition at line 143 of file RecordTable.h.
References souffle::Tuple< Domain, _arity >::data, and souffle::RecordTable::pack().
Referenced by souffle::Synthesiser::emitCode(), and souffle::RamLevelAnalysis::getLevel().
{
     return recordTab.pack(static_cast<RamDomain*>(tuple.data), Arity);
 }
pathJoin()
std::string souffle::pathJoin (const std::string & first, const std::string & second) inline
Join two paths together; note that this does not resolve overlaps or relative paths.
Definition at line 1148 of file Util.h.
{
     unsigned firstPos = static_cast<unsigned>(first.size()) - 1;
     while (first.at(firstPos) == '/') {
         firstPos--;
     }
     unsigned secondPos = 0;
     while (second.at(secondPos) == '/') {
         secondPos++;
     }
     return first.substr(0, firstPos + 1) + '/' + second.substr(secondPos);
 }
ramBitCast()
template<typename To = RamDomain, typename From > To souffle::ramBitCast (From source)
In C++20 there will be a new way to cast between types by reinterpreting bits (std::bit_cast), but as of January 2020 it is not yet supported.
Cast a type by reinterpreting its bits. Domain is restricted to Ram Types only. Template takes two types (second type is never necessary because it can be deduced from the argument) The following always holds For type T and a : T ramBitCast<T>(ramBitCast<RamDomain>(a)) == a
Definition at line 123 of file RamTypes.h.
Referenced by souffle::ExplainProvenance::argsToNums(), souffle::InterpreterEngine::execute(), souffle::InterpreterEngine::executeAggregate(), souffle::ExplainProvenanceImpl::findTuple(), souffle::ExplainProvenanceImpl::measureRelation(), souffle::tuple::operator<<(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStreamCSV::readNextTuple(), and souffle::ReadStream::readRecord().
{
     static_assert(isRamType<From> && isRamType<To>, "Bit casting should only be used on Ram Types.");
     static_assert(sizeof(To) == sizeof(From), "Can't bit cast types with different size.");
     To destination;
     memcpy(&destination, &source, sizeof(destination));
     return destination;
 }
RamFloatFromString()
RamFloat souffle::RamFloatFromString (const std::string & str, std::size_t * position = nullptr) inline
Converts a string to a RamFloat.
Definition at line 163 of file Util.h.
Referenced by souffle::ExplainProvenance::argsToNums(), canBeParsedAsRamFloat(), souffle::AstTranslator::getConstantRamRepresentation(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStreamCSV::readNextTuple(), souffle::ReadStream::readRecord(), and souffle::AstTranslator::translateValue().
{
     RamFloat val;
 #if RAM_DOMAIN_SIZE == 64
     val = std::stod(str, position);
 #else
     val = std::stof(str, position);
 #endif
     return static_cast<RamFloat>(val);
 }
RamSignedFromString()
RamSigned souffle::RamSignedFromString (const std::string & str, std::size_t * position = nullptr, const int base = 10) inline
Converts a string to a RamSigned.
This procedure has similar behaviour to std::stoi/stoll.
The procedure accepts prefixes 0b (if base = 2) and 0x (if base = 16) If base = 0, the procedure will try to infer the base from the prefix, if present.
Definition at line 121 of file Util.h.
References base, isPrefix(), and str.
Referenced by souffle::ExplainProvenance::argsToNums(), canBeParsedAsRamSigned(), souffle::InterpreterEngine::execute(), souffle::AstTranslator::getConstantRamRepresentation(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStreamSQLite::readNextTuple(), souffle::ReadStreamCSV::readNextTuple(), souffle::ReadStream::readRecord(), and souffle::AstTranslator::translateValue().
{
     RamSigned val;
     if (base == 0) {
         if (isPrefix("-0b", str) || isPrefix("0b", str)) {
             return RamSignedFromString(str, position, 2);
         } else if (isPrefix("-0x", str) || isPrefix("0x", str)) {
             return RamSignedFromString(str, position, 16);
         } else {
             return RamSignedFromString(str, position);
         }
     }
     std::string binaryNumber;
     bool parsingBinary = base == 2;
     // stoi/stoll can't handle base 2 prefix by default.
     if (parsingBinary) {
         if (isPrefix("-0b", str)) {
             binaryNumber = "-" + str.substr(3);
         } else if (isPrefix("0b", str)) {
             binaryNumber = str.substr(2);
         }
     }
     const std::string& tmp = parsingBinary ? binaryNumber : str;
 #if RAM_DOMAIN_SIZE == 64
     val = std::stoll(tmp, position, base);
 #else
     val = std::stoi(tmp, position, base);
 #endif
     if (parsingBinary && position != nullptr) {
         *position += 2;
     }
     return val;
 }
RamUnsignedFromString()
RamUnsigned souffle::RamUnsignedFromString (const std::string & str, std::size_t * position = nullptr, const int base = 10) inline
Converts a string to a RamUnsigned.
This procedure has similar behaviour to std::stoul/stoull.
The procedure accepts prefixes 0b (if base = 2) and 0x (if base = 16) If base = 0, the procedure will try to infer the base from the prefix, if present.
Definition at line 180 of file Util.h.
References base, isPrefix(), and str.
Referenced by souffle::ExplainProvenance::argsToNums(), canBeParsedAsRamUnsigned(), souffle::AstTranslator::getConstantRamRepresentation(), souffle::ExplainProvenanceImpl::queryProcess(), souffle::ReadStreamCSV::readRamUnsigned(), souffle::ReadStream::readRecord(), and souffle::AstTranslator::translateValue().
{
     // Be default C++ (stoul) allows unsigned numbers starting with "-".
     if (isPrefix("-", str)) {
         throw std::invalid_argument("Unsigned number can't start with minus.");
     }
     if (base == 0) {
         if (isPrefix("0b", str)) {
             return RamUnsignedFromString(str, position, 2);
         } else if (isPrefix("0x", str)) {
             return RamUnsignedFromString(str, position, 16);
         } else {
             return RamUnsignedFromString(str, position);
         }
     }
     // stoul/stoull can't handle binary prefix by default.
     std::string binaryNumber;
     bool parsingBinary = false;
     if (base == 2 && isPrefix("0b", str)) {
         binaryNumber = str.substr(2);
         parsingBinary = true;
     }
     const std::string& tmp = parsingBinary ? binaryNumber : str;
     RamUnsigned val;
 #if RAM_DOMAIN_SIZE == 64
     val = std::stoull(tmp, position, base);
 #else
     val = std::stoul(tmp, position, base);
 #endif
     if (parsingBinary && position != nullptr) {
         *position += 2;
     }
     // check if it's safe to cast (stoul returns unsigned long)
     if (val > std::numeric_limits<RamUnsigned>::max()) {
         throw std::invalid_argument("Unsigned number of of bounds");
     }
     return static_cast<RamUnsigned>(val);
 }
reduceLocallyEquivalentClauses()
bool souffle::reduceLocallyEquivalentClauses (AstTranslationUnit & translationUnit)
Reduces locally-redundant clauses.
A clause is locally-redundant if there is another clause within the same relation that computes the same set of tuples.
Returns
true iff the program was changed
Definition at line 324 of file MinimiseProgramTransformer.cpp.
References areBijectivelyEquivalent(), getClauses(), souffle::AstTranslationUnit::getProgram(), souffle::AstProgram::getRelations(), and souffle::AstProgram::removeClause().
Referenced by souffle::MinimiseProgramTransformer::transform().
{
     AstProgram& program = *translationUnit.getProgram();
     std::vector<AstClause*> clausesToDelete;
     // split up each relation's rules into equivalence classes
     // TODO (azreika): consider turning this into an ast analysis instead
     for (AstRelation* rel : program.getRelations()) {
         std::vector<std::vector<AstClause*>> equivalenceClasses;
         for (AstClause* clause : getClauses(program, *rel)) {
             bool added = false;
             for (std::vector<AstClause*>& eqClass : equivalenceClasses) {
                 AstClause* rep = eqClass[0];
                 if (areBijectivelyEquivalent(rep, clause)) {
                     // clause belongs to an existing equivalence class, so delete it
                     eqClass.push_back(clause);
                     clausesToDelete.push_back(clause);
                     added = true;
                     break;
                 }
             }
             if (!added) {
                 // clause does not belong to any existing equivalence class, so keep it
                 std::vector<AstClause*> clauseToAdd = {clause};
                 equivalenceClasses.push_back(clauseToAdd);
             }
         }
     }
     // remove non-representative clauses
     for (auto clause : clausesToDelete) {
         program.removeClause(clause);
     }
     // changed iff any clauses were deleted
     return !clausesToDelete.empty();
 }
reduceSingletonRelations()
bool souffle::reduceSingletonRelations (AstTranslationUnit & translationUnit)
Removes redundant singleton relations.
Singleton relations are relations with a single clause. A singleton relation is redundant if there exists another singleton relation that computes the same set of tuples.
Returns
true iff the program was changed
Definition at line 372 of file MinimiseProgramTransformer.cpp.
References souffle::AstProgram::apply(), areBijectivelyEquivalent(), souffle::AstTranslationUnit::getAnalysis(), getClauses(), souffle::AstClause::getHead(), souffle::AstTranslationUnit::getProgram(), souffle::AstAtom::getQualifiedName(), getRelation(), souffle::AstProgram::getRelations(), i, j, souffle::AstProgram::removeClause(), and souffle::AstProgram::removeRelation().
Referenced by souffle::MinimiseProgramTransformer::transform().
{
     // Note: This reduction is particularly useful in conjunction with the
     // body-partitioning transformation
     AstProgram& program = *translationUnit.getProgram();
     auto* ioTypes = translationUnit.getAnalysis<IOType>();
     // Find all singleton relations to consider
     std::vector<AstClause*> singletonRelationClauses;
     for (AstRelation* rel : program.getRelations()) {
         if (!ioTypes->isIO(rel) && getClauses(program, *rel).size() == 1) {
             AstClause* clause = getClauses(program, *rel)[0];
             singletonRelationClauses.push_back(clause);
         }
     }
     // Keep track of clauses found to be redundant
     std::set<AstClause*> redundantClauses;
     // Keep track of canonical relation name for each redundant clause
     std::map<AstQualifiedName, AstQualifiedName> canonicalName;
     // Check pairwise equivalence of each singleton relation
     for (size_t i = 0; i < singletonRelationClauses.size(); i++) {
         AstClause* first = singletonRelationClauses[i];
         if (redundantClauses.find(first) != redundantClauses.end()) {
             // Already found to be redundant, no need to check
             continue;
         }
         for (size_t j = i + 1; j < singletonRelationClauses.size(); j++) {
             AstClause* second = singletonRelationClauses[j];
             // Note: Bijective-equivalence check does not care about the head relation name
             if (areBijectivelyEquivalent(first, second)) {
                 AstQualifiedName firstName = first->getHead()->getQualifiedName();
                 AstQualifiedName secondName = second->getHead()->getQualifiedName();
                 redundantClauses.insert(second);
                 canonicalName.insert(std::pair(secondName, firstName));
             }
         }
     }
     // Remove redundant relation definitions
     for (AstClause* clause : redundantClauses) {
         auto relName = clause->getHead()->getQualifiedName();
         AstRelation* rel = getRelation(program, relName);
         assert(rel != nullptr && "relation does not exist in program");
         program.removeClause(clause);
         program.removeRelation(relName);
     }
     // Replace each redundant relation appearance with its canonical name
     struct replaceRedundantRelations : public AstNodeMapper {
         const std::map<AstQualifiedName, AstQualifiedName>& canonicalName;
         replaceRedundantRelations(const std::map<AstQualifiedName, AstQualifiedName>& canonicalName)
                 : canonicalName(canonicalName) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             // Remove appearances from children nodes
             node->apply(*this);
             if (auto* atom = dynamic_cast<AstAtom*>(node.get())) {
                 auto pos = canonicalName.find(atom->getQualifiedName());
                 if (pos != canonicalName.end()) {
                     auto newAtom = std::unique_ptr<AstAtom>(atom->clone());
                     newAtom->setQualifiedName(pos->second);
                     return newAtom;
                 }
             }
             return node;
         }
     };
     replaceRedundantRelations update(canonicalName);
     program.apply(update);
     // Program was changed iff a relation was replaced
     return !canonicalName.empty();
 }
reduceSubstitution()
bool souffle::reduceSubstitution (std::vector< std::pair< AstArgument *, AstArgument *>> & sub)
Reduces a vector of substitutions.
Returns false only if matched argument pairs are found to be incompatible.
Definition at line 193 of file InlineRelationsTransformer.cpp.
References i, lhs, rhs, and sub().
Referenced by unifyAtoms().
{
     // Type-Checking functions
     auto isConstant = [&](AstArgument* arg) { return dynamic_cast<AstConstant*>(arg) != nullptr; };
     auto isRecord = [&](AstArgument* arg) { return dynamic_cast<AstRecordInit*>(arg) != nullptr; };
     // Keep trying to reduce the substitutions until we reach a fixed point.
     // Note that at this point no underscores ('_') or counters ('$') should appear.
     bool done = false;
     while (!done) {
         done = true;
         // Try reducing each pair by one step
         for (size_t i = 0; i < sub.size(); i++) {
             auto currPair = sub[i];
             AstArgument* lhs = currPair.first;
             AstArgument* rhs = currPair.second;
             // Start trying to reduce the substitution
             // Note: Can probably go further with this substitution reduction
             if (*lhs == *rhs) {
                 // Get rid of redundant `x = x`
                 sub.erase(sub.begin() + i);
                 done = false;
             } else if (isConstant(lhs) && isConstant(rhs)) {
                 // Both are constants but not equal (prev case => !=)
                 // Failed to unify!
                 return false;
             } else if (isRecord(lhs) && isRecord(rhs)) {
                 // Note: we will not deal with the case where only one side is
                 // a record and the other is a variable, as variables can be records
                 // on a deeper level.
                 std::vector<AstArgument*> lhsArgs = static_cast<AstRecordInit*>(lhs)->getArguments();
                 std::vector<AstArgument*> rhsArgs = static_cast<AstRecordInit*>(rhs)->getArguments();
                 if (lhsArgs.size() != rhsArgs.size()) {
                     // Records of unequal size can't be equated
                     return false;
                 }
                 // Equate all corresponding arguments
                 for (size_t i = 0; i < lhsArgs.size(); i++) {
                     sub.push_back(std::make_pair(lhsArgs[i], rhsArgs[i]));
                 }
                 // Get rid of the record equality
                 sub.erase(sub.begin() + i);
                 done = false;
             } else if ((isRecord(lhs) && isConstant(rhs)) || (isConstant(lhs) && isRecord(rhs))) {
                 // A record =/= a constant
                 return false;
             }
         }
     }
     return true;
 }
removeRelationClauses()
void souffle::removeRelationClauses (AstProgram & program, const AstQualifiedName & name)
Removes the set of clauses with the given relation name.
Parameters
program the program
name the name of the relation to search for
Definition at line 69 of file AstUtils.cpp.
References getClauses(), and souffle::AstProgram::removeClause().
Referenced by getBodyLiterals(), and souffle::AstProgram::removeRelation().
{
     for (const auto* clause : getClauses(program, name)) {
         program.removeClause(clause);
     }
 }
renameVariables()
void souffle::renameVariables (AstArgument * arg)
Renames all variables in a given argument uniquely.
Definition at line 477 of file InlineRelationsTransformer.cpp.
References souffle::AstNode::apply().
Referenced by combineAggregators().
{
     static int varCount = 0;
     varCount++;
     struct M : public AstNodeMapper {
         int varnum;
         M(int varnum) : varnum(varnum) {}
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* var = dynamic_cast<AstVariable*>(node.get())) {
                 auto newVar = std::unique_ptr<AstVariable>(var->clone());
                 std::stringstream newName;
                 newName << var->getName() << "-v" << varnum;
                 newVar->setName(newName.str());
                 return newVar;
             }
             node->apply(*this);
             return node;
         }
     };
     M update(varCount);
     arg->apply(update);
 }
reorderAdornment()
std::vector<std::string> souffle::reorderAdornment (std::vector< std::string > adornment, std::vector< unsigned int > order)
Definition at line 431 of file MagicSet.cpp.
References i.
Referenced by souffle::MagicSetTransformer::transform().
{
     // order[i] denotes where labels[i] should move
     // [a, b, c] with order [1, 2, 0] -> [c, a, b]
     std::vector<std::string> result(adornment.size());
     for (size_t i = 0; i < adornment.size(); i++) {
         result[order[i]] = adornment[i];
     }
     return result;
 }
reorderAtoms()
AstClause * souffle::reorderAtoms (const AstClause * clause, const std::vector< unsigned int > & newOrder)
Reorders the atoms of a clause to be in the given order.
Remaining body literals remain in the same order.
E.g. if atoms are [a,b,c] and given order is [1,2,0], then the final atom order will be [b,c,a].
Parameters
clause clause to reorder atoms in
newOrder new order of atoms; atoms[i] = atoms[newOrder[i]]
Definition at line 189 of file AstUtils.cpp.
References souffle::AstClause::addToBody(), souffle::AstLiteral::clone(), cloneHead(), souffle::AstClause::getBodyLiterals(), and i.
Referenced by getBodyLiterals(), souffle::AstTranslator::ClauseTranslator::getReorderedClause(), isValidPermutation(), reorderClauseWithSips(), and souffle::MagicSetTransformer::transform().
{
     // Find all atom positions
     std::vector<unsigned int> atomPositions;
     std::vector<AstLiteral*> bodyLiterals = clause->getBodyLiterals();
     for (unsigned int i = 0; i < bodyLiterals.size(); i++) {
         if (dynamic_cast<AstAtom*>(bodyLiterals[i]) != nullptr) {
             atomPositions.push_back(i);
         }
     }
     // Validate given order
     assert(newOrder.size() == atomPositions.size());
     std::vector<unsigned int> nopOrder;
     for (unsigned int i = 0; i < atomPositions.size(); i++) {
         nopOrder.push_back(i);
     }
     assert(std::is_permutation(nopOrder.begin(), nopOrder.end(), newOrder.begin()));
     // Create a new clause with the given atom order, leaving the rest unchanged
     AstClause* newClause = cloneHead(clause);
     unsigned int currentAtom = 0;
     for (unsigned int currentLiteral = 0; currentLiteral < bodyLiterals.size(); currentLiteral++) {
         AstLiteral* literalToAdd = bodyLiterals[currentLiteral];
         if (dynamic_cast<AstAtom*>(literalToAdd) != nullptr) {
             // Atoms should be reordered
             literalToAdd = bodyLiterals[atomPositions[newOrder[currentAtom++]]];
         }
         newClause->addToBody(std::unique_ptr<AstLiteral>(literalToAdd->clone()));
     }
     return newClause;
 }
reorderClauseWithSips()
AstClause* souffle::reorderClauseWithSips (sips_t sipsFunction, AstClause * clause)
Definition at line 334 of file ReorderLiteralsTransformer.cpp.
References applySips(), souffle::AstClause::getExecutionPlan(), i, and reorderAtoms().
Referenced by souffle::ReorderLiteralsTransformer::transform().
{
     // ignore clauses with fixed execution plans
     if (clause->getExecutionPlan() != nullptr) {
         return nullptr;
     }
     // get the ordering corresponding to the SIPS
     std::vector<unsigned int> newOrdering = applySips(sipsFunction, getBodyLiterals<AstAtom>(*clause));
     // check if we need a change
     bool changeNeeded = false;
     for (unsigned int i = 0; i < newOrdering.size(); i++) {
         if (newOrdering[i] != i) {
             changeNeeded = true;
         }
     }
     // reorder if needed
     return changeNeeded ? reorderAtoms(clause, newOrdering) : nullptr;
 }
reorderOrdering()
std::vector<unsigned int> souffle::reorderOrdering (std::vector< unsigned int > order)
Definition at line 410 of file MagicSet.cpp.
References i.
Referenced by souffle::MagicSetTransformer::transform().
{
     // when the adornment is computed, the atoms are numbered based on
     // which was chosen by the SIPS first - this is the 'order' vector.
     // want to reorder clause atoms so that the atom labelled 0 is first, and so on.
     // i.e. order[i] denotes where labels[i] should move
     // e.g.: [a, b, c] with label [1, 2, 0] should become [c, a, b]
     // the atom reordering function for clauses, however, moves it as follows:
     // [a, b, c] with label [1, 2, 0] becomes [b, c, a]
     // i.e. labels[i] goes to the position of i in the order vector
     // this function reorders the ordering scheme to match the second type
     std::vector<unsigned int> neworder(order.size());
     for (size_t i = 0; i < order.size(); i++) {
         // this took embarrassingly long to figure out
         neworder[order[i]] = i;
     }
     return neworder;
 }
replaceUnderscores()
void souffle::replaceUnderscores (AstProgram * program)
Definition at line 1017 of file MagicSet.cpp.
References getClauses(), souffle::AstProgram::getRelations(), and hasPrefix().
Referenced by nameInlinedUnderscores(), and souffle::MagicSetTransformer::transform().
{
     struct M : public AstNodeMapper {
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             if (auto* var = dynamic_cast<AstVariable*>(node.get())) {
                 if (hasPrefix(var->getName(), "+underscore")) {
                     return std::make_unique<AstUnnamedVariable>();
                 }
             }
             node->apply(*this);
             return node;
         }
     };
     M update;
     for (AstRelation* rel : program->getRelations()) {
         for (AstClause* clause : getClauses(*program, *rel)) {
             clause->apply(update);
         }
     }
 }
separateDBs()
void souffle::separateDBs (AstProgram * program)
Definition at line 899 of file MagicSet.cpp.
References souffle::AstProgram::addClause(), souffle::AstProgram::addRelation(), souffle::AstClause::clone(), createNewRelation(), getClauses(), souffle::AstClause::getHead(), getNextEdbName(), souffle::AstProgram::getRelations(), isFact(), j, nextSrcLoc(), relation, and souffle::AstAtom::setQualifiedName().
Referenced by souffle::MagicSetTransformer::transform().
{
     for (AstRelation* relation : program->getRelations()) {
         AstQualifiedName relName = relation->getQualifiedName();
         // determine whether the relation fits into the EDB, IDB, or both
         bool is_edb = false;
         bool is_idb = false;
         for (AstClause* clause : getClauses(*program, *relation)) {
             if (isFact(*clause)) {
                 is_edb = true;
             } else {
                 is_idb = true;
             }
             if (is_edb && is_idb) {
                 break;
             }
         }
         if (is_edb && is_idb) {
             // relation is part of EDB and IDB
             // move all the relation's facts to a new relation with a unique name
             std::string newEdbName = getNextEdbName(program);
             AstRelation* newEdbRel = createNewRelation(relation, newEdbName);
             program->addRelation(std::unique_ptr<AstRelation>(newEdbRel));
             // find all facts for the relation
             for (AstClause* clause : getClauses(*program, *relation)) {
                 if (isFact(*clause)) {
                     // clause is fact - add it to the new EDB relation
                     AstClause* newEdbClause = clause->clone();
                     newEdbClause->getHead()->setQualifiedName(newEdbName);
                     program->addClause(std::unique_ptr<AstClause>(newEdbClause));
                 }
             }
             // add a rule to the old relation that relates it to the new relation
             auto* newIdbClause = new AstClause();
             newIdbClause->setSrcLoc(nextSrcLoc(relation->getSrcLoc()));
             // oldname(arg1...argn) :- newname(arg1...argn)
             auto* headAtom = new AstAtom(relName);
             auto* bodyAtom = new AstAtom(newEdbName);
             size_t numargs = relation->getArity();
             for (size_t j = 0; j < numargs; j++) {
                 std::stringstream argName;
                 argName.str("");
                 argName << "arg" << j;
                 headAtom->addArgument(std::make_unique<AstVariable>(argName.str()));
                 bodyAtom->addArgument(std::make_unique<AstVariable>(argName.str()));
             }
             newIdbClause->setHead(std::unique_ptr<AstAtom>(headAtom));
             newIdbClause->addToBody(std::unique_ptr<AstAtom>(bodyAtom));
             program->addClause(std::unique_ptr<AstClause>(newIdbClause));
         }
     }
 }
simpleName()
std::string souffle::simpleName (const std::string & path) inline
File name, with extension removed.
Definition at line 1202 of file Util.h.
Referenced by main().
{
     std::string name = baseName(path);
     const size_t lastDot = name.find_last_of('.');
     // file has no extension
     if (lastDot == std::string::npos) {
         return name;
     }
     const size_t lastSlash = name.find_last_of('/');
     // last slash occurs after last dot, so no extension
     if (lastSlash != std::string::npos && lastSlash > lastDot) {
         return name;
     }
     // last dot after last slash, or no slash
     return name.substr(0, lastDot);
 }
split()
std::vector<std::string> souffle::split (const std::string & s, char delim, int times = -1) inline
utility function to split a string
Definition at line 130 of file ExplainProvenance.h.
References souffle::profile::ss, and times().
Referenced by souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::getSplitPoint(), souffle::Explain::processCommand(), souffle::detail::btree< Key, Comparator, Allocator, blockSize, SearchStrategy, isSet, WeakComparator, Updater >::node::rebalance_or_split(), and souffle::profile::EventProcessorSingleton::splitSignature().
{
     std::vector<std::string> v;
     std::stringstream ss(s);
     std::string item;
     while ((times > 0 || times <= -1) && std::getline(ss, item, delim)) {
         v.push_back(item);
         times--;
     }
     if (ss.peek() != EOF) {
         std::string remainder;
         std::getline(ss, remainder);
         v.push_back(remainder);
     }
     return v;
 }
splitString()
std::vector<std::string> souffle::splitString (const std::string & str, char delimiter) inline
Splits a string given a delimiter.
Definition at line 908 of file Util.h.
Referenced by addIgnoredRelations(), souffle::AstSemanticChecker::checkProgram(), compileToBinary(), executeBinary(), souffle::ExplainProvenanceImpl::explain(), souffle::ExplainProvenanceImpl::explainNegation(), souffle::ExplainProvenanceImpl::explainNegationGetVariables(), souffle::InterpreterEngine::loadDLL(), and main().
{
     std::vector<std::string> parts;
     std::stringstream strstr(str);
     std::string token;
     while (std::getline(strstr, token, delimiter)) {
         parts.push_back(token);
     }
     return parts;
 }
stringify()
std::string souffle::stringify (const std::string & input) inline
Stringify a string using escapes for newline, tab, double-quotes and semicolons.
Definition at line 1260 of file Util.h.
Referenced by souffle::RamLogRelationTimer::print(), souffle::RamLogTimer::print(), souffle::RamDebugInfo::print(), souffle::RamLogSize::print(), souffle::InnerNode::printJSON(), souffle::LeafNode::printJSON(), souffle::ExplainProvenanceImpl::printRulesJSON(), souffle::AstTranslator::ClauseTranslator::translateClause(), souffle::AstTranslator::translateNonRecursiveRelation(), and souffle::AstTranslator::translateRecursiveRelation().
{
     std::string str(input);
     // replace semicolons returns by escape sequence
     size_t start_pos = 0;
     while ((start_pos = str.find(';', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\;");
         start_pos += 2;
     }
     // replace double-quotes returns by escape sequence
     start_pos = 0;
     while ((start_pos = str.find('"', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\\"");
         start_pos += 2;
     }
     // replace newline returns by escape sequence
     start_pos = 0;
     while ((start_pos = str.find('\n', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\n");
         start_pos += 2;
     }
     // replace tab returns by escape sequence
     start_pos = 0;
     while ((start_pos = str.find('\t', start_pos)) != std::string::npos) {
         str.replace(start_pos, 1, "\\t");
         start_pos += 2;
     }
     return str;
 }
sub() [1/2]
template<typename Var > std::shared_ptr<Constraint<Var> > souffle::sub (const Var & a, const Var & b, const std::string & symbol = "")
A generic factory for constraints of the form.
a b
where a and b are variables and is the order relation induced by their associated property space.
Definition at line 221 of file Constraints.h.
References b.
Referenced by souffle::RamProgram::apply(), souffle::AstSemanticChecker::checkUnionType(), souffle::RamProgram::clone(), souffle::Synthesiser::generateCode(), souffle::RamProgram::getChildNodes(), souffle::RamProgram::getSubroutines(), souffle::detail::fix_lower_bound< Pos, Dim >::operator()(), souffle::detail::fix_upper_bound< Pos, Dim >::operator()(), souffle::RamProgram::print(), souffle::RamProgram::RamProgram(), and reduceSubstitution().
{
     struct Sub : public Constraint<Var> {
         Var a, b;
         std::string symbol;
         Sub(Var a, Var b, std::string symbol) : a(std::move(a)), b(std::move(b)), symbol(std::move(symbol)) {}
         bool update(Assignment<Var>& ass) const override {
             typename Var::property_space::meet_assign_op_type meet_assign;
             return meet_assign(ass[b], ass[a]);
         }
         void print(std::ostream& out) const override {
             out << a << " " << symbol << " " << b;
         }
     };
     return std::make_shared<Sub>(a, b, symbol);
 }
sub() [2/2]
template<typename Var , typename Val = typename Var::property_space::value_type> std::shared_ptr<Constraint<Var> > souffle::sub (const Val & a, const Var & b, const std::string & symbol = "")
A generic factory for constraints of the form.
a b
where b is a variables, a is a value of b's property space, and is the order relation induced by b's property space.
Definition at line 250 of file Constraints.h.
References b.
{
     struct Sub : public Constraint<Var> {
         Val a;
         Var b;
         std::string symbol;
         Sub(Val a, Var b, std::string symbol) : a(std::move(a)), b(std::move(b)), symbol(std::move(symbol)) {}
         bool update(Assignment<Var>& ass) const override {
             typename Var::property_space::meet_assign_op_type meet_assign;
             return meet_assign(ass[b], a);
         }
         void print(std::ostream& out) const override {
             out << a << " " << symbol << " " << b;
         }
     };
     return std::make_shared<Sub>(a, b, symbol);
 }
tempFile()
std::string souffle::tempFile () inline
Generate temporary file.
Definition at line 1240 of file Util.h.
Referenced by main().
{
 #ifdef _WIN32
     std::string templ;
     std::FILE* f = nullptr;
     while (f == nullptr) {
         templ = std::tmpnam(nullptr);
         f = fopen(templ.c_str(), "wx");
     }
     fclose(f);
     return templ;
 #else
     char templ[40] = "./souffleXXXXXX";
     close(mkstemp(templ));
     return std::string(templ);
 #endif
 }
times()
template<typename T > detail::multiplying_printer<T> souffle::times (const T & value, unsigned num)
A utility printing a given value multiple times.
Definition at line 868 of file Util.h.
Referenced by souffle::SparseArray< value_t, BITS, merge_op >::dump(), souffle::RamIO::print(), souffle::RamClear::print(), souffle::RamScan::print(), souffle::RamExtend::print(), souffle::RamParallelScan::print(), souffle::RamSwap::print(), souffle::RamQuery::print(), souffle::RamIndexScan::print(), souffle::RamParallelIndexScan::print(), souffle::RamParallel::print(), souffle::RamChoice::print(), souffle::RamLoop::print(), souffle::RamParallelChoice::print(), souffle::RamExit::print(), souffle::RamIndexChoice::print(), souffle::RamParallelIndexChoice::print(), souffle::RamLogRelationTimer::print(), souffle::RamLogTimer::print(), souffle::RamDebugInfo::print(), souffle::RamLogSize::print(), souffle::RamAggregate::print(), souffle::RamIndexAggregate::print(), souffle::RamFilter::print(), souffle::RamBreak::print(), souffle::RamProject::print(), souffle::RamSubroutineReturnValue::print(), and split().
{
     return detail::multiplying_printer<T>(value, num);
 }
toBinaryConstraintOp()
BinaryConstraintOp souffle::toBinaryConstraintOp (const std::string & symbol) inline
Converts symbolic representation of an operator to the operator.
Note that this won't tell you which polymorphic overload is actually used.
Definition at line 257 of file BinaryConstraintOps.h.
References CONTAINS, EQ, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, and NOT_MATCH.
Referenced by souffle::ExplainProvenanceImpl::explain().
{
     if (symbol == "=") return BinaryConstraintOp::EQ;
     if (symbol == "!=") return BinaryConstraintOp::NE;
     if (symbol == "<") return BinaryConstraintOp::LT;
     if (symbol == "<=") return BinaryConstraintOp::LE;
     if (symbol == ">=") return BinaryConstraintOp::GE;
     if (symbol == ">") return BinaryConstraintOp::GT;
     if (symbol == "match") return BinaryConstraintOp::MATCH;
     if (symbol == "contains") return BinaryConstraintOp::CONTAINS;
     if (symbol == "not_match") return BinaryConstraintOp::NOT_MATCH;
     if (symbol == "not_contains") return BinaryConstraintOp::NOT_CONTAINS;
     std::cout << "Unrecognised operator: " << symbol << "\n";
     assert(false && "Unsupported Operator!");
     exit(EXIT_FAILURE);
 }
toBinaryConstraintSymbol()
std::string souffle::toBinaryConstraintSymbol (const BinaryConstraintOp op) inline
Converts operator to its symbolic representation.
Definition at line 212 of file BinaryConstraintOps.h.
References CONTAINS, EQ, FEQ, FGE, FGT, FLE, FLT, FNE, GE, GT, LE, LT, MATCH, NE, NOT_CONTAINS, NOT_MATCH, SGE, SGT, SLE, SLT, UGE, UGT, ULE, and ULT.
Referenced by makeInfoRelation(), souffle::RamConstraint::print(), and souffle::AstBinaryConstraint::print().
{
     switch (op) {
         case BinaryConstraintOp::FEQ:
         case BinaryConstraintOp::EQ:
             return "=";
         case BinaryConstraintOp::FNE:
         case BinaryConstraintOp::NE:
             return "!=";
         case BinaryConstraintOp::SLT:
         case BinaryConstraintOp::ULT:
         case BinaryConstraintOp::FLT:
         case BinaryConstraintOp::LT:
             return "<";
         case BinaryConstraintOp::SLE:
         case BinaryConstraintOp::ULE:
         case BinaryConstraintOp::FLE:
         case BinaryConstraintOp::LE:
             return "<=";
         case BinaryConstraintOp::SGT:
         case BinaryConstraintOp::UGT:
         case BinaryConstraintOp::FGT:
         case BinaryConstraintOp::GT:
             return ">";
         case BinaryConstraintOp::SGE:
         case BinaryConstraintOp::UGE:
         case BinaryConstraintOp::FGE:
         case BinaryConstraintOp::GE:
             return ">=";
         case BinaryConstraintOp::MATCH:
             return "match";
         case BinaryConstraintOp::CONTAINS:
             return "contains";
         case BinaryConstraintOp::NOT_MATCH:
             return "not_match";
         case BinaryConstraintOp::NOT_CONTAINS:
             return "not_contains";
     }
     assert(false && "Unsupported Operator!");
     exit(EXIT_FAILURE);
 }
toCondition()
std::unique_ptr<RamCondition> souffle::toCondition (const std::vector< std::unique_ptr< RamCondition >> & conds) inline
Convert list of conditions to a conjunction.
Parameters
A list of RAM conditions
A RAM condition
Convert a list {C1, C2, ..., Cn} to a condition of the format C1 /\ C2 /\ ... /\ Cn.
Definition at line 71 of file RamUtils.h.
Referenced by souffle::CollapseFiltersTransformer::collapseFilters(), souffle::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::Synthesiser::emitCode(), and souffle::ReorderConditionsTransformer::reorderConditions().
{
     std::unique_ptr<RamCondition> result;
     for (auto const& cur : conds) {
         if (result == nullptr) {
             result = std::unique_ptr<RamCondition>(cur->clone());
         } else {
             result = std::make_unique<RamConjunction>(
                     std::move(result), std::unique_ptr<RamCondition>(cur->clone()));
         }
     }
     return result;
 }
toConjunctionList()
std::vector<std::unique_ptr<RamCondition> > souffle::toConjunctionList (const RamCondition * condition) inline
Convert terms of a conjunction to a list.
Parameters
conds A RAM condition
Returns
A list of RAM conditions
Convert a condition of the format C1 /\ C2 /\ ... /\ Cn to a list {C1, C2, ..., Cn}.
Definition at line 44 of file RamUtils.h.
References souffle::RamCondition::clone().
Referenced by souffle::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::Synthesiser::emitCode(), souffle::ExpandFilterTransformer::expandFilters(), souffle::ReorderConditionsTransformer::reorderConditions(), souffle::MakeIndexTransformer::rewriteAggregate(), souffle::MakeIndexTransformer::rewriteIndexScan(), and souffle::MakeIndexTransformer::rewriteScan().
{
     std::vector<std::unique_ptr<RamCondition>> conditionList;
     std::queue<const RamCondition*> conditionsToProcess;
     if (condition != nullptr) {
         conditionsToProcess.push(condition);
         while (!conditionsToProcess.empty()) {
             condition = conditionsToProcess.front();
             conditionsToProcess.pop();
             if (const auto* ramConj = dynamic_cast<const RamConjunction*>(condition)) {
                 conditionsToProcess.push(&ramConj->getLHS());
                 conditionsToProcess.push(&ramConj->getRHS());
             } else {
                 conditionList.emplace_back(condition->clone());
             }
         }
     }
     return conditionList;
 }
toPtrVector()
template<typename T > std::vector<T*> souffle::toPtrVector (const std::vector< std::unique_ptr< T >> & v)
A utility function enabling the creation of a vector of pointers.
Definition at line 363 of file Util.h.
References e.
Referenced by souffle::RamAbstractOperator::getArguments(), souffle::AstAtom::getArguments(), souffle::AstTerm::getArguments(), souffle::RamPackRecord::getArguments(), souffle::AstRelation::getAttributes(), souffle::AstComponent::getBaseComponents(), souffle::AstClause::getBodyLiterals(), souffle::AstAggregator::getBodyLiterals(), souffle::AstProgram::getClauses(), souffle::AstComponent::getClauses(), souffle::AstProgram::getComponentInstantiations(), souffle::AstProgram::getComponents(), souffle::AstComponent::getComponents(), souffle::AstProgram::getFunctorDeclarations(), souffle::AstComponent::getInstantiations(), souffle::AstProgram::getIOs(), souffle::AstComponent::getIOs(), souffle::RamIndexOperation::getRangePattern(), souffle::AstProgram::getRelations(), souffle::RamProgram::getRelations(), souffle::AstComponent::getRelations(), souffle::RamListStatement::getStatements(), souffle::AstProgram::getTypes(), souffle::AstComponent::getTypes(), souffle::RamAbstractExistenceCheck::getValues(), souffle::RamProject::getValues(), and souffle::RamSubroutineReturnValue::getValues().
{
     std::vector<T*> res;
     for (auto& e : v) {
         res.push_back(e.get());
     }
     return res;
 }
toString() [1/3]
const std::string& souffle::toString (const std::string & str) inline
A generic function converting strings into strings (trivial case).
Definition at line 793 of file Util.h.
References str.
Referenced by souffle::ParserDriver::addFunctorDeclaration(), souffle::ParserDriver::addIO(), souffle::ParserDriver::addRelation(), souffle::ParserDriver::addType(), souffle::AstSemanticChecker::checkAtom(), souffle::AstComponentChecker::checkComponentNamespaces(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkIO(), souffle::AstSemanticChecker::checkNamespaces(), souffle::AstSemanticChecker::checkProgram(), souffle::AstSemanticChecker::checkRecordType(), souffle::AstSemanticChecker::checkRecursiveUnionTypes(), souffle::AstSemanticChecker::checkRelation(), souffle::AstSemanticChecker::checkRelationDeclaration(), souffle::AstSemanticChecker::checkUnionType(), souffle::Synthesiser::emitCode(), genJsonAtoms(), souffle::profile::Tui::genJsonRelations(), genJsonRules(), souffle::ComponentLookup::getComponent(), souffle::AstTranslator::getOutputDirectives(), souffle::AstTranslator::getRelationName(), getTypeQualifier(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::AstTranslator::nameUnnamedVariables(), souffle::ResolveAliasesTransformer::removeComplexTermsInAtoms(), souffle::UniqueAggregationVariablesTransformer::transform(), souffle::AstTranslator::ClauseTranslator::translateClause(), souffle::AstTranslator::translateNonRecursiveRelation(), souffle::AstTranslator::translateProgram(), and souffle::AstTranslator::translateRecursiveRelation().
{
     return str;
 }
toString() [2/3]
template<typename T > std::enable_if<detail::is_printable<T>::value, std::string>::type souffle::toString (const T & value)
A generic function converting arbitrary objects to strings by utilizing their print capability.
This function is mainly intended for implementing test cases and debugging operations.
Definition at line 824 of file Util.h.
{
     // write value into stream and return result
     std::stringstream ss;
     ss << value;
     return ss.str();
 }
toString() [3/3]
template<typename T > std::enable_if<!detail::is_printable<T>::value, std::string>::type souffle::toString (const T &)
A fallback for the to-string function in case an unprintable object is supposed to be printed.
Definition at line 836 of file Util.h.
{
     std::stringstream ss;
     ss << "(print for type ";
     ss << typeid(T).name();
     ss << " not supported)";
     return ss.str();
 }
toVector() [1/2]
template<typename T > std::vector<T> souffle::toVector ()
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
This is the base case covering empty vectors.
Definition at line 345 of file Util.h.
{
     return std::vector<T>();
 }
toVector() [2/2]
template<typename T , typename... R> std::vector<T> souffle::toVector (const T & first, const R &... rest)
A utility function enabling the creation of a vector with a fixed set of elements within a single expression.
This is the step case covering vectors of arbitrary length.
Definition at line 355 of file Util.h.
{
     return {first, rest...};
 }
transformEqrelRelation()
void souffle::transformEqrelRelation (AstProgram & program, AstRelation & rel)
Transform eqrel relations to explicitly define equivalence relations.
Definition at line 191 of file ProvenanceTransformer.cpp.
References souffle::AstAtom::addArgument(), souffle::AstProgram::addClause(), BTREE, EQREL, souffle::AstRelation::getArity(), souffle::AstRelation::getQualifiedName(), souffle::AstRelation::getRepresentation(), and souffle::AstRelation::setRepresentation().
Referenced by souffle::ProvenanceTransformer::transformMaxHeight(), and souffle::ProvenanceTransformer::transformSubtreeHeights().
{
     assert(rel.getRepresentation() == RelationRepresentation::EQREL &&
             "attempting to transform non-eqrel relation");
     assert(rel.getArity() == 2 && "eqrel relation not binary");
     rel.setRepresentation(RelationRepresentation::BTREE);
     // transitivity
     // transitive clause: A(x, z) :- A(x, y), A(y, z).
     auto transitiveClause = new AstClause();
     auto transitiveClauseHead = new AstAtom(rel.getQualifiedName());
     transitiveClauseHead->addArgument(std::make_unique<AstVariable>("x"));
     transitiveClauseHead->addArgument(std::make_unique<AstVariable>("z"));
     auto transitiveClauseBody = new AstAtom(rel.getQualifiedName());
     transitiveClauseBody->addArgument(std::make_unique<AstVariable>("x"));
     transitiveClauseBody->addArgument(std::make_unique<AstVariable>("y"));
     auto transitiveClauseBody2 = new AstAtom(rel.getQualifiedName());
     transitiveClauseBody2->addArgument(std::make_unique<AstVariable>("y"));
     transitiveClauseBody2->addArgument(std::make_unique<AstVariable>("z"));
     transitiveClause->setHead(std::unique_ptr<AstAtom>(transitiveClauseHead));
     transitiveClause->addToBody(std::unique_ptr<AstLiteral>(transitiveClauseBody));
     transitiveClause->addToBody(std::unique_ptr<AstLiteral>(transitiveClauseBody2));
     program.addClause(std::unique_ptr<AstClause>(transitiveClause));
     // symmetric
     // symmetric clause: A(x, y) :- A(y, x).
     auto symClause = new AstClause();
     auto symClauseHead = new AstAtom(rel.getQualifiedName());
     symClauseHead->addArgument(std::make_unique<AstVariable>("x"));
     symClauseHead->addArgument(std::make_unique<AstVariable>("y"));
     auto symClauseBody = new AstAtom(rel.getQualifiedName());
     symClauseBody->addArgument(std::make_unique<AstVariable>("y"));
     symClauseBody->addArgument(std::make_unique<AstVariable>("x"));
     symClause->setHead(std::unique_ptr<AstAtom>(symClauseHead));
     symClause->addToBody(std::unique_ptr<AstLiteral>(symClauseBody));
     program.addClause(std::unique_ptr<AstClause>(symClause));
     // reflexivity
     // reflexive clause: A(x, x) :- A(x, _).
     auto reflexiveClause = new AstClause();
     auto reflexiveClauseHead = new AstAtom(rel.getQualifiedName());
     reflexiveClauseHead->addArgument(std::make_unique<AstVariable>("x"));
     reflexiveClauseHead->addArgument(std::make_unique<AstVariable>("x"));
     auto reflexiveClauseBody = new AstAtom(rel.getQualifiedName());
     reflexiveClauseBody->addArgument(std::make_unique<AstVariable>("x"));
     reflexiveClauseBody->addArgument(std::make_unique<AstUnnamedVariable>());
     reflexiveClause->setHead(std::unique_ptr<AstAtom>(reflexiveClauseHead));
     reflexiveClause->addToBody(std::unique_ptr<AstLiteral>(reflexiveClauseBody));
     program.addClause(std::unique_ptr<AstClause>(reflexiveClause));
 }
unescape() [1/2]
std::string souffle::unescape (const std::string & inputString, const std::string & needle, const std::string & replacement) inline
Definition at line 1318 of file Util.h.
Referenced by souffle::AstTranslator::getInputDirectives(), and souffle::AstTranslator::getOutputDirectives().
{
     std::string result = inputString;
     size_t pos = 0;
     while ((pos = result.find(needle, pos)) != std::string::npos) {
         result = result.replace(pos, needle.length(), replacement);
         pos += replacement.length();
     }
     return result;
 }
unescape() [2/2]
std::string souffle::unescape (const std::string & inputString) inline
Definition at line 1329 of file Util.h.
{
     std::string unescaped = unescape(inputString, "\\\"", "\"");
     unescaped = unescape(unescaped, "\\t", "\t");
     unescaped = unescape(unescaped, "\\r", "\r");
     unescaped = unescape(unescaped, "\\n", "\n");
     return unescaped;
 }
unifyAtoms()
NullableVector<std::pair<AstArgument*, AstArgument*> > souffle::unifyAtoms (AstAtom * first, AstAtom * second)
Returns the nullable vector of substitutions needed to unify the two given atoms.
If unification is not successful, the returned vector is marked as invalid. Assumes that the atoms are both of the same relation.
Definition at line 255 of file InlineRelationsTransformer.cpp.
References souffle::AstAtom::getArguments(), i, and reduceSubstitution().
Referenced by inlineBodyLiterals().
{
     std::vector<std::pair<AstArgument*, AstArgument*>> substitution;
     std::vector<AstArgument*> firstArgs = first->getArguments();
     std::vector<AstArgument*> secondArgs = second->getArguments();
     // Create the initial unification equalities
     for (size_t i = 0; i < firstArgs.size(); i++) {
         substitution.push_back(std::make_pair(firstArgs[i], secondArgs[i]));
     }
     // Reduce the substitutions
     bool success = reduceSubstitution(substitution);
     if (success) {
         return NullableVector<std::pair<AstArgument*, AstArgument*>>(substitution);
     } else {
         // Failed to unify the two atoms
         return NullableVector<std::pair<AstArgument*, AstArgument*>>();
     }
 }
usesInvalidWitness()
static const std::vector<SrcLocation> souffle::usesInvalidWitness (const std::vector< AstLiteral *> & literals, const std::set< std::unique_ptr< AstArgument >> & groundedArguments) static
Definition at line 985 of file AstSemanticChecker.cpp.
References souffle::AstAggregator::getBodyLiterals(), getGroundedTerms(), i, str, and visitDepthFirst().
Referenced by souffle::AstSemanticChecker::checkWitnessProblem().
{
     // Node-mapper that replaces aggregators with new (unique) variables
     struct M : public AstNodeMapper {
         // Variables introduced to replace aggregators
         mutable std::set<std::string> aggregatorVariables;
         const std::set<std::string>& getAggregatorVariables() {
             return aggregatorVariables;
         }
         std::unique_ptr<AstNode> operator()(std::unique_ptr<AstNode> node) const override {
             static int numReplaced = 0;
             if (dynamic_cast<AstAggregator*>(node.get()) != nullptr) {
                 // Replace the aggregator with a variable
                 std::stringstream newVariableName;
                 newVariableName << "+aggr_var_" << numReplaced++;
                 // Keep track of which variables are bound to aggregators
                 aggregatorVariables.insert(newVariableName.str());
                 return std::make_unique<AstVariable>(newVariableName.str());
             }
             node->apply(*this);
             return node;
         }
     };
     std::vector<SrcLocation> result;
     // Create two versions of the original clause
     // Clause 1 - will remain equivalent to the original clause in terms of variable groundedness
     auto originalClause = std::make_unique<AstClause>();
     originalClause->setHead(std::make_unique<AstAtom>("*"));
     // Clause 2 - will have aggregators replaced with intrinsically grounded variables
     auto aggregatorlessClause = std::make_unique<AstClause>();
     aggregatorlessClause->setHead(std::make_unique<AstAtom>("*"));
     // Construct both clauses in the same manner to match the original clause
     // Must keep track of the subnode in Clause 1 that each subnode in Clause 2 matches to
     std::map<const AstArgument*, const AstArgument*> identicalSubnodeMap;
     for (const AstLiteral* lit : literals) {
         auto firstClone = std::unique_ptr<AstLiteral>(lit->clone());
         auto secondClone = std::unique_ptr<AstLiteral>(lit->clone());
         // Construct the mapping between equivalent literal subnodes
         std::vector<const AstArgument*> firstCloneArguments;
         visitDepthFirst(*firstClone, [&](const AstArgument& arg) { firstCloneArguments.push_back(&arg); });
         std::vector<const AstArgument*> secondCloneArguments;
         visitDepthFirst(*secondClone, [&](const AstArgument& arg) { secondCloneArguments.push_back(&arg); });
         for (size_t i = 0; i < firstCloneArguments.size(); i++) {
             identicalSubnodeMap[secondCloneArguments[i]] = firstCloneArguments[i];
         }
         // Actually add the literal clones to each clause
         originalClause->addToBody(std::move(firstClone));
         aggregatorlessClause->addToBody(std::move(secondClone));
     }
     // Replace the aggregators in Clause 2 with variables
     M update;
     aggregatorlessClause->apply(update);
     // Create a dummy atom to force certain arguments to be grounded in the aggregatorlessClause
     auto groundingAtomAggregatorless = std::make_unique<AstAtom>("grounding_atom");
     auto groundingAtomOriginal = std::make_unique<AstAtom>("grounding_atom");
     // Force the new aggregator variables to be grounded in the aggregatorless clause
     const std::set<std::string>& aggregatorVariables = update.getAggregatorVariables();
     for (const std::string& str : aggregatorVariables) {
         groundingAtomAggregatorless->addArgument(std::make_unique<AstVariable>(str));
     }
     // Force the given grounded arguments to be grounded in both clauses
     for (const std::unique_ptr<AstArgument>& arg : groundedArguments) {
         groundingAtomAggregatorless->addArgument(std::unique_ptr<AstArgument>(arg->clone()));
         groundingAtomOriginal->addArgument(std::unique_ptr<AstArgument>(arg->clone()));
     }
     aggregatorlessClause->addToBody(std::move(groundingAtomAggregatorless));
     originalClause->addToBody(std::move(groundingAtomOriginal));
     // Compare the grounded analysis of both generated clauses
     // All added arguments in Clause 2 were forced to be grounded, so if an ungrounded argument
     // appears in Clause 2, it must also appear in Clause 1. Consequently, have two cases:
     //   - The argument is also ungrounded in Clause 1 - handled by another check
     //   - The argument is grounded in Clause 1 => the argument was grounded in the
     //     first clause somewhere along the line by an aggregator-body - not allowed!
     std::set<std::unique_ptr<AstArgument>> newlyGroundedArguments;
     std::map<const AstArgument*, bool> originalGrounded = getGroundedTerms(*originalClause);
     std::map<const AstArgument*, bool> aggregatorlessGrounded = getGroundedTerms(*aggregatorlessClause);
     for (auto pair : aggregatorlessGrounded) {
         if (!pair.second && originalGrounded[identicalSubnodeMap[pair.first]]) {
             result.push_back(pair.first->getSrcLoc());
         }
         // Otherwise, it can now be considered grounded
         newlyGroundedArguments.insert(std::unique_ptr<AstArgument>(pair.first->clone()));
     }
     // All previously grounded are still grounded
     for (const std::unique_ptr<AstArgument>& arg : groundedArguments) {
         newlyGroundedArguments.insert(std::unique_ptr<AstArgument>(arg->clone()));
     }
     // Everything on this level is fine, check subaggregators of each literal
     for (const AstLiteral* lit : literals) {
         visitDepthFirst(*lit, [&](const AstAggregator& aggr) {
             // Check recursively if an invalid witness is used
             std::vector<AstLiteral*> aggrBodyLiterals = aggr.getBodyLiterals();
             std::vector<SrcLocation> subresult = usesInvalidWitness(aggrBodyLiterals, newlyGroundedArguments);
             for (SrcLocation argloc : subresult) {
                 result.push_back(argloc);
             }
         });
     }
     return result;
 }
visitDepthFirst() [1/8]
template<typename R , typename... Ps, typename... Args> void souffle::visitDepthFirst (const AstNode & root, AstVisitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the AST to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 233 of file AstVisitor.h.
References visitDepthFirstPreOrder().
Referenced by addAggregators(), addBackwardDependencies(), souffle::BindingStore::addBinding(), addForwardDependencies(), areBijectivelyEquivalent(), souffle::AstSemanticChecker::checkAggregator(), souffle::AstSemanticChecker::checkClause(), souffle::AstSemanticChecker::checkInlining(), souffle::AstSemanticChecker::checkProgram(), souffle::AstSemanticChecker::checkRecursiveUnionTypes(), souffle::AstSemanticChecker::checkWitnessProblem(), souffle::CollapseFiltersTransformer::collapseFilters(), containsAggregators(), containsInlinedAtom(), souffle::FoldAnonymousRecords::containsValidRecordConstraint(), souffle::IfConversionTransformer::convertIndexScans(), souffle::ChoiceConversionTransformer::convertScans(), createAnnotatedClause(), souffle::AstTranslator::ClauseTranslator::createOperation(), souffle::EliminateDuplicatesTransformer::eliminateDuplicates(), souffle::Synthesiser::emitCode(), souffle::InterpreterEngine::executeMain(), souffle::ExpandFilterTransformer::expandFilters(), souffle::NodeGenerator::findAllViews(), souffle::Synthesiser::generateCode(), souffle::NodeGenerator::generateTree(), getBodyRelations(), getRecords(), souffle::Synthesiser::getReferencedRelations(), getSipsFunction(), getVariables(), hasClauseWithAggregatedRelation(), souffle::HoistAggregateTransformer::hoistAggregate(), souffle::HoistConditionsTransformer::hoistConditions(), souffle::InterpreterProgInterface::InterpreterProgInterface(), souffle::AstSemanticChecker::isDependent(), isFact(), isRecursiveClause(), isValidPermutation(), souffle::MakeIndexTransformer::makeIndex(), souffle::AstTranslator::makeNegationSubproofSubroutine(), souffle::MaterializeAggregationQueriesTransformer::materializeAggregationQueries(), souffle::MaterializeAggregationQueriesTransformer::needsMaterializedRelation(), numBoundArguments(), souffle::ParallelTransformer::parallelizeOperations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelations(), souffle::RemoveEmptyRelationsTransformer::removeEmptyRelationUses(), souffle::RemoveRelationCopiesTransformer::removeRelationCopies(), souffle::ReorderConditionsTransformer::reorderConditions(), souffle::ReorderFilterBreak::reorderFilterBreak(), souffle::TupleIdTransformer::reorderOperations(), souffle::ResolveAliasesTransformer::resolveAliases(), souffle::IfConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteIndexScan(), souffle::ChoiceConversionTransformer::rewriteScan(), souffle::IOType::run(), souffle::ComponentLookup::run(), souffle::RecursiveClauses::run(), souffle::Adornment::run(), souffle::RamIndexAnalysis::run(), souffle::AstPragmaChecker::transform(), souffle::ResolveAliasesTransformer::transform(), souffle::UniqueAggregationVariablesTransformer::transform(), souffle::RemoveBooleanConstraintsTransformer::transform(), souffle::PartitionBodyLiteralsTransformer::transform(), souffle::ReduceExistentialsTransformer::transform(), souffle::ReplaceSingletonVariablesTransformer::transform(), souffle::MagicSetTransformer::transform(), souffle::AstTranslator::translateProgram(), usesInvalidWitness(), visitDepthFirst(), and souffle::NodeGenerator::visitQuery().
{
     visitDepthFirstPreOrder(root, visitor, args...);
 }
visitDepthFirst() [2/8]
template<typename R , typename... Ps, typename... Args> void souffle::visitDepthFirst (const RamNode & root, RamVisitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the RAM fragments rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the RAM fragments to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 281 of file RamVisitor.h.
References visitDepthFirstPreOrder().
{
     visitDepthFirstPreOrder(root, visitor, args...);
 }
visitDepthFirst() [3/8]
template<typename R , typename N > void souffle::visitDepthFirst (const AstNode & root, const std::function< R(const N &)> & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 287 of file AstVisitor.h.
References souffle::detail::makeLambdaAstVisitor().
{
     auto visitor = detail::makeLambdaAstVisitor(fun);
     visitDepthFirst<void>(root, visitor);
 }
visitDepthFirst() [4/8]
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type> std::enable_if<!detail::is_ast_visitor<Lambda>::value, void>::type souffle::visitDepthFirst (const AstNode & root, const Lambda & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 303 of file AstVisitor.h.
References visitDepthFirst().
{
     visitDepthFirst(root, std::function<R(const N&)>(fun));
 }
visitDepthFirst() [5/8]
template<typename T , typename Lambda > void souffle::visitDepthFirst (const std::vector< T *> & list, const Lambda & fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
list the list of roots of the ASTs to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 318 of file AstVisitor.h.
References visitDepthFirst().
{
     for (const auto& cur : list) {
         visitDepthFirst(*cur, fun);
     }
 }
visitDepthFirst() [6/8]
template<typename T , typename Lambda > void souffle::visitDepthFirst (const std::vector< std::unique_ptr< T >> & list, const Lambda & fun)
A utility function visiting all nodes within a given list of AST root nodes recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
list the list of roots of the ASTs to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 334 of file AstVisitor.h.
References visitDepthFirst().
{
     for (const auto& cur : list) {
         visitDepthFirst(*cur, fun);
     }
 }
visitDepthFirst() [7/8]
template<typename R , typename N > void souffle::visitDepthFirst (const RamNode & root, const std::function< R(const N &)> & fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the RAM fragment to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 335 of file RamVisitor.h.
References souffle::detail::makeLambdaRamVisitor().
{
     auto visitor = detail::makeLambdaRamVisitor(fun);
     visitDepthFirst<void>(root, visitor);
 }
visitDepthFirst() [8/8]
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type> std::enable_if<!detail::is_ram_visitor<Lambda>::value, void>::type souffle::visitDepthFirst (const RamNode & root, const Lambda & fun)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given function to each encountered node.
Parameters
root the root of the RAM fragment to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 351 of file RamVisitor.h.
References visitDepthFirst().
{
     visitDepthFirst(root, std::function<R(const N&)>(fun));
 }
visitDepthFirstPostOrder() [1/3]
template<typename R , typename... Ps, typename... Args> void souffle::visitDepthFirstPostOrder (const AstNode & root, AstVisitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the AST to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 214 of file AstVisitor.h.
References souffle::AstNode::getChildNodes().
Referenced by souffle::AstTranslator::ClauseTranslator::createValueIndex(), souffle::UniqueAggregationVariablesTransformer::transform(), and visitDepthFirstPostOrder().
{
     for (const AstNode* cur : root.getChildNodes()) {
         if (cur != nullptr) {
             visitDepthFirstPostOrder(*cur, visitor, args...);
         }
     }
     visitor(root, args...);
 }
visitDepthFirstPostOrder() [2/3]
template<typename R , typename N > void souffle::visitDepthFirstPostOrder (const AstNode & root, const std::function< R(const N &)> & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 350 of file AstVisitor.h.
References souffle::detail::makeLambdaAstVisitor().
{
     auto visitor = detail::makeLambdaAstVisitor(fun);
     visitDepthFirstPostOrder<void>(root, visitor);
 }
visitDepthFirstPostOrder() [3/3]
template<typename Lambda , typename R = typename lambda_traits<Lambda>::result_type, typename N = typename lambda_traits<Lambda>::arg0_type> std::enable_if<!detail::is_ast_visitor<Lambda>::value, void>::type souffle::visitDepthFirstPostOrder (const AstNode & root, const Lambda & fun)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first post-order fashion applying the given function to each encountered node.
Parameters
root the root of the AST to be visited
fun the function to be applied
args a list of extra parameters to be forwarded to the visitor
Definition at line 366 of file AstVisitor.h.
References visitDepthFirstPostOrder().
{
     visitDepthFirstPostOrder(root, std::function<R(const N&)>(fun));
 }
visitDepthFirstPreOrder() [1/2]
template<typename R , typename... Ps, typename... Args> void souffle::visitDepthFirstPreOrder (const AstNode & root, AstVisitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the ast rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the AST to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 195 of file AstVisitor.h.
References souffle::AstNode::getChildNodes().
Referenced by visitDepthFirst(), and visitDepthFirstPreOrder().
{
     visitor(root, args...);
     for (const AstNode* cur : root.getChildNodes()) {
         if (cur != nullptr) {
             visitDepthFirstPreOrder(*cur, visitor, args...);
         }
     }
 }
visitDepthFirstPreOrder() [2/2]
template<typename R , typename... Ps, typename... Args> void souffle::visitDepthFirstPreOrder (const RamNode & root, RamVisitor< R, Ps... > & visitor, Args &... args)
A utility function visiting all nodes within the RAM fragment rooted by the given node recursively in a depth-first pre-order fashion applying the given visitor to each encountered node.
Parameters
root the root of the RAM fragment to be visited
visitor the visitor to be applied on each node
args a list of extra parameters to be forwarded to the visitor
Definition at line 262 of file RamVisitor.h.
References souffle::RamNode::getChildNodes(), and visitDepthFirstPreOrder().
{
     visitor(root, args...);
     for (const RamNode* cur : root.getChildNodes()) {
         if (cur != nullptr) {
             visitDepthFirstPreOrder(*cur, visitor, args...);
         }
     }
 }
which()
std::string souffle::which (const std::string & name) inline
Simple implementation of a which tool.
Definition at line 1091 of file Util.h.
Referenced by main().
{
     char buf[PATH_MAX];
     if ((::realpath(name.c_str(), buf) != nullptr) && isExecutable(buf)) {
         return buf;
     }
     const char* syspath = ::getenv("PATH");
     if (syspath == nullptr) {
         return "";
     }
     std::stringstream sstr;
     sstr << syspath;
     std::string sub;
     while (std::getline(sstr, sub, ':')) {
         std::string path = sub + "/" + name;
         if (isExecutable(path) && (realpath(path.c_str(), buf) != nullptr)) {
             return buf;
         }
     }
     return "";
 }
Variable Documentation
else
souffle::else
Initial value:
{
            std::string str
Definition at line 468 of file Tui.h.
getName
ss<< R"_("usage": [)_"; bool firstRow = true; Usage previousUsage = *usages.begin(); previousUsage.time = beginTime; for (auto usage : usages) { comma(firstRow); ss << '['; ss << (usage.time - beginTime).count() / 1000000.0 << ", "; ss << 100.0 * (usage.usertime - previousUsage.usertime) / (usage.time - previousUsage.time) << ", "; ss << 100.0 * (usage.systemtime - previousUsage.systemtime) / (usage.time - previousUsage.time) << ", "; ss << usage.maxRSS * 1024 << ", "; ss << '"'; bool firstCol = true; for (auto& cur : out.getProgramRun()->getRelationsAtTime(previousUsage.time, usage.time)) { comma(firstCol); ss << cur-> souffle::getName()
Definition at line 501 of file Tui.h.
Referenced by isValidPermutation(), and souffle::AstTranslator::translateRecursiveRelation().
isRamType
template<typename T > constexpr bool souffle::isRamType
Initial value:
= (std::is_same<T, RamDomain>::value || std::is_same<T, RamSigned>::value ||
                            std::is_same<T, RamUnsigned>::value || std::is_same<T, RamFloat>::value)
Definition at line 108 of file RamTypes.h.
MAX_RAM_FLOAT
constexpr RamFloat souffle::MAX_RAM_FLOAT = std::numeric_limits<RamFloat>::max()
Definition at line 139 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
MAX_RAM_SIGNED
constexpr RamSigned souffle::MAX_RAM_SIGNED = std::numeric_limits<RamSigned>::max()
Definition at line 133 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::execute(), and souffle::InterpreterEngine::executeAggregate().
MAX_RAM_UNSIGNED
constexpr RamUnsigned souffle::MAX_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::max()
Definition at line 136 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
MIN_RAM_FLOAT
constexpr RamFloat souffle::MIN_RAM_FLOAT = std::numeric_limits<RamFloat>::min()
Definition at line 138 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
MIN_RAM_SIGNED
constexpr RamSigned souffle::MIN_RAM_SIGNED = std::numeric_limits<RamSigned>::min()
lower and upper boundaries for the ram types
Definition at line 132 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::execute(), souffle::InterpreterEngine::executeAggregate(), and souffle::EquivalenceRelation< t_tuple< 2 > >::lower_bound().
MIN_RAM_UNSIGNED
constexpr RamUnsigned souffle::MIN_RAM_UNSIGNED = std::numeric_limits<RamUnsigned>::min()
Definition at line 135 of file RamTypes.h.
Referenced by souffle::InterpreterEngine::executeAggregate().
rank_mask
constexpr block_t souffle::rank_mask = (1ul << split_size) - 1
Definition at line 47 of file UnionFind.h.
Referenced by souffle::DisjointSet::b2r().
split_size
constexpr uint8_t souffle::split_size = 8u
Definition at line 42 of file UnionFind.h.
Referenced by souffle::DisjointSet::b2p().