souffle: souffle::RecordType Struct Reference
souffle::RecordType Struct Reference
A record type combining a list of fields into a new, aggregated type.
#include <TypeSystem.h>
Data Structures
struct Field
The type to model fields.
Public Member Functions
void add (const std::string &name, const Type &type)
The list of contained fields.
const std::vector< Field > & getFields () const
void print (std::ostream &out) const override
Public Member Functions inherited from souffle::Type
const AstQualifiedName & getName () const
const TypeEnvironment & getTypeEnvironment () const
bool operator!= (const Type &other) const
bool operator< (const Type &other) const
bool operator== (const Type &other) const
Type (const TypeEnvironment &environment, AstQualifiedName name)
Type (const Type &other)=delete
virtual ~Type ()=default
Private Member Functions
RecordType (const TypeEnvironment &environment, const AstQualifiedName &name)
Private Attributes
std::vector< Field > fields
Friends
class TypeEnvironment
Additional Inherited Members
Protected Attributes inherited from souffle::Type
const TypeEnvironment & environment
A reference to the type environment this type is associated to.
Detailed Description
A record type combining a list of fields into a new, aggregated type.
Definition at line 147 of file TypeSystem.h.
Constructor & Destructor Documentation
RecordType()
souffle::RecordType::RecordType (const TypeEnvironment & environment, const AstQualifiedName & name) inline private
Definition at line 170 of file TypeSystem.h.
 : Type(environment, name) {}
Member Function Documentation
add()
void souffle::RecordType::add (const std::string & name, const Type & type)
The list of contained fields.
Definition at line 38 of file TypeSystem.cpp.
References souffle::Type::environment, souffle::TypeEnvironment::isType(), and souffle::Type::name.
Referenced by souffle::TypeEnvironmentAnalysis::updateTypeEnvironment().
{
     assert(environment.isType(type));
     fields.push_back(Field({name, type}));
 }
getFields()
const std::vector<Field>& souffle::RecordType::getFields () const inline
Definition at line 158 of file TypeSystem.h.
References souffle::Type::print().
Referenced by souffle::AstSemanticChecker::checkProgram(), souffle::getTypeQualifier(), and souffle::isRecursiveType().
{
         return fields;
     }
print()
void souffle::RecordType::print (std::ostream & out) const override virtual
Reimplemented from souffle::Type.
Definition at line 43 of file TypeSystem.cpp.
References souffle::Type::getName(), souffle::join(), souffle::RecordType::Field::name, and souffle::RecordType::Field::type.
{
     out << getName() << " = ";
     if (fields.empty()) {
         out << "()";
         return;
     }
     out << "( " << join(fields, " , ", [](std::ostream& out, const RecordType::Field& f) {
         out << f.name << " : " << f.type.getName();
     }) << " )";
 }
Friends And Related Function Documentation
TypeEnvironment
friend class TypeEnvironment friend
Definition at line 166 of file TypeSystem.h.
Field Documentation
fields
std::vector<Field> souffle::RecordType::fields private
Definition at line 168 of file TypeSystem.h.
The documentation for this struct was generated from the following files:
TypeSystem.h
TypeSystem.cpp