souffle: souffle::range< Iter > Struct Template Reference
souffle::range< Iter > Struct Template Reference
A utility class enabling representation of ranges by pairing two iterator instances marking lower and upper boundaries.
#include <Util.h>
Public Member Functions
Iter & begin ()
const Iter & begin () const
bool empty () const
Iter & end ()
const Iter & end () const
range & operator= (const range &)=default
std::vector< range > partition (int np=100)
range (Iter a, Iter b)
range (const range &)=default
range (range &&)=default
Data Fields
Iter a
Iter b
Detailed Description
template<typename Iter>
struct souffle::range< Iter >
A utility class enabling representation of ranges by pairing two iterator instances marking lower and upper boundaries.
Definition at line 380 of file Util.h.
Constructor & Destructor Documentation
range() [1/3]
template<typename Iter> souffle::range< Iter >::range (Iter a, Iter b) inline
Definition at line 385 of file Util.h.
Referenced by souffle::range< iterator >::range().
 : a(std::move(a)), b(std::move(b)) {}
range() [2/3]
template<typename Iter> souffle::range< Iter >::range (const range< Iter > &) default
range() [3/3]
template<typename Iter> souffle::range< Iter >::range (range< Iter > &&) default
Member Function Documentation
begin() [1/2]
template<typename Iter> Iter& souffle::range< Iter >::begin () inline
Definition at line 393 of file Util.h.
Referenced by souffle::Trie< Arity >::find(), and souffle::GenericIndex< Structure >::GenericIndexView::range().
                   {
         return a;
     }
begin() [2/2]
template<typename Iter> const Iter& souffle::range< Iter >::begin () const inline
Definition at line 396 of file Util.h.
{
         return a;
     }
empty()
template<typename Iter> bool souffle::range< Iter >::empty () const inline
Definition at line 409 of file Util.h.
Referenced by souffle::Trie< Arity >::find().
{
         return a == b;
     }
end() [1/2]
template<typename Iter> Iter& souffle::range< Iter >::end () inline
Definition at line 401 of file Util.h.
Referenced by souffle::GenericIndex< Structure >::GenericIndexView::range().
                 {
         return b;
     }
end() [2/2]
template<typename Iter> const Iter& souffle::range< Iter >::end () const inline
Definition at line 404 of file Util.h.
{
         return b;
     }
operator=()
template<typename Iter> range& souffle::range< Iter >::operator= (const range< Iter > &) default
Referenced by souffle::range< iterator >::range().
partition()
template<typename Iter> std::vector<range> souffle::range< Iter >::partition (int np = 100) inline
Definition at line 414 of file Util.h.
Referenced by souffle::GenericIndex< btree_set< t_tuple< Arity >, comparator< Arity >, std::allocator< t_tuple< Arity > >, 256, detail::default_strategy< t_tuple< Arity > >::type, comparator< Arity - 2 >, InterpreterProvenanceUpdater< Arity > > >::partitionRange().
{
         // obtain the size
         int n = 0;
         for (auto i = a; i != b; ++i) {
             n++;
         }
         // split it up
         auto s = n / np;
         auto r = n % np;
         std::vector<range> res;
         res.reserve(np);
         auto cur = a;
         auto last = cur;
         int i = 0;
         int p = 0;
         while (cur != b) {
             ++cur;
             i++;
             if (i >= (s + (p < r ? 1 : 0))) {
                 res.push_back({last, cur});
                 last = cur;
                 p++;
                 i = 0;
             }
         }
         if (cur != last) {
             res.push_back({last, cur});
         }
         return res;
     }
Field Documentation
a
template<typename Iter> Iter souffle::range< Iter >::a
Definition at line 382 of file Util.h.
Referenced by souffle::range< iterator >::begin(), souffle::equal_targets(), souffle::join(), souffle::make_range(), and souffle::range< iterator >::partition().
b
template<typename Iter> Iter souffle::range< Iter >::b
Definition at line 382 of file Util.h.
Referenced by souffle::range< iterator >::empty(), souffle::range< iterator >::end(), souffle::equal_ptr(), souffle::equal_targets(), souffle::join(), souffle::make_range(), souffle::comp_deref< T >::operator()(), and souffle::range< iterator >::partition().
The documentation for this struct was generated from the following file:
Util.h